### ISSUE TITLE
Add the new slime creature

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#100]
As freshly baked by @Danimal696 here:
http://forum.freegamedev.net/viewtopic.php?f=38&t=5664&p=58883#p58883

CC-BY 3.0 or CC-BY-SA 3.0 or GPL 3.0 or GPL 2.0
Model by Grefuntor and animated by D3dm

For reference, the interesting line in the creatures.def is this one:
`Slime    WeakFighter Slime.mesh  Bed 1   1   0.15    0.15    0.15    6   6   180 180 15  0   0   0.6 walkableTile`

**Comment by Bertram25** [comment]
The N° #100 !! Woohoo :D

**Comment by akien-mga** [comment]
> The N° #100 !! Woohoo :D

I thought about opening a troll issue like this one: https://bugs.mageia.org/show_bug.cgi?id=10000 :-D
But the latter was already too good, I couldn't come up with something really original ;-)
