### ISSUE TITLE
Make all issue numbers 4 digits long

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#1000]
I think that's a must have for a project such as ours. I'll handle it.

**Comment by hwoarangmy** [comment]
lol

**Comment by akien-mga** [comment]
I've been lurking in the dark to fetch this one :P

**Comment by Bertram25** [comment]
XD omg 1000 issues

**Comment by hwoarangmy** [comment]
> XD omg 1000 issues

That includes PRs ^^
