### ISSUE TITLE
Gold seems not to decrease when being the host of a game

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#1007]
just start any type of game, it seems building rooms doesn't cost gold anymore for the host.

Tested on Linux.

**Comment by Bertram25** [comment]
Just had a full game, woah, the creature behaviour has changed a lot.
+Kudos for the new spells :D 
(I'll stop hi-jacking this issue now)

**Comment by hwoarangmy** [comment]
my mistake. I will fix that now
