### ISSUE TITLE
Prison icon

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#1019]
the current one is not explicit at all, i propose to change it to this:
http://game-icons.net/delapouite/originals/prisoner.html

and jailed creature to this one:
http://game-icons.net/lorc/originals/manacles.html

**Comment by hwoarangmy** [comment]
I agree the room icon is not very explicit. However, what about using the same icon (prisoner) for both the creatures and the room ? That would be pretty straight forward, no ?
