### ISSUE TITLE
Gold on the floor

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1020]
When the treasury room is full, dug gold is left on the floor. We could allow creatures to sneak that gold and take it.
That would make more important to have enough treasuries for the dug gold

@OpenDungeons/developers WDYT ?

**Comment by Danimal696** [comment]
i wouldnt be agaisnt them taking a bit, but not all. But would that also apply to gold dropped from killing rival creatures? i see myself slapping my creatures to death when rough times come, Casino room migth be the best addition after this would be implemented

**Comment by Bertram25** [comment]
It could be interesting, but I would make them stop sneaking for a while when you've slapped a creature. So that slapping has also a new purpose. ;>

**Comment by hwoarangmy** [comment]
not a bad idea ^^
