### ISSUE TITLE
Allow to play a battleroyal in the arena

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1022]
According to:
http://forum.freegamedev.net/viewtopic.php?f=45&t=4765&start=600#p66535

@Danimal696 wants to be allowed to drop more than 2 creatures in the arena.
For my part, Ive no strong opinion about that.

@OpenDungeons/developers WDYT ?

**Comment by Bertram25** [comment]
Fine by me. one on one is supported if you drop only two of them, and the more the merrier, right? ;)

**Comment by hwoarangmy** [comment]
Fixed in #1072
