### ISSUE TITLE
Make at least one new multiplayer level

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#1033]
We need to add some diversity to the game, currently we have only:
- one 2 player level (The Bridge)
- one 3 player level (Greed or Might)
- one 4 players level, but it's hard :p (#1032) (Ruins of the Confluent)
- one 5 players level (Scream in the Dark)

We could use at least one other 3+ players level, and maybe even a 6 players level.

**Comment by Bertram25** [comment]
I guess the user map support is even more urgent? :)

**Comment by Bertram25** [comment]
@hwoarangmy Didn't you handle this one already?

**Comment by hwoarangmy** [comment]
yes
