### ISSUE TITLE
Segfault while playing multiplayer games

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#1034]
While playing the current dev branch yesterday we had two segfaults after ~20-30 minutes of game:
- one while I was hosting on Linux, no meaningful stacktrace: http://hastebin.com/bepojakodu.scala
- one in the server while hwoarangmy was hosting on Windows, he had a stacktrace IIRC (could you post it here?)

It could be that the two segfaults have the same cause but the Windows stacktrace code was cleverer.

@oyvindln also had a segfault when joining the lobby, but that's likely a driver issue: http://hastebin.com/ipedasedux.coffee

**Comment by oyvindln** [comment]
My segfault could also have something to do with trying to join after failing to connect on the first attempt.

**Comment by hwoarangmy** [comment]
The segfault I got is related to a bug with hatcheries. I forgot to test if there is room available before allowing a creature to go to the hatchery. Because of that, they used to go there even if they couldn't be added (because at room level, there is a check on availability). Thus, if there is a room absorbtion, the creature is not notified (because not in the creatures using the room list) and do not update its hatchery. This is fixed in the PR I will open right now.

**Comment by hwoarangmy** [comment]
Done in #1036

**Comment by hwoarangmy** [comment]
Note that @oyvindln segfault looks like #610
I thought it was fixed by a nasty workaround of loading all entities at game start (for some unknown reason, it solved a similar problem I had on windows) but it looks like it doesn't on linux.
Maybe upgrading Ogre might help for that...

**Comment by Bertram25** [comment]
Maybe we should also have Ogre 1.10 as a submodule or something?

**Comment by akien-mga** [comment]
I think that as long as we aren't explicitly using Ogre 1.10 features or we know that it fixes bugs we are having, it's better to stay with the latest stable. It could be that Ogre 1.10 ends up never to be released once too much work has been put in 2.0 and 2.1 and "whatever comes next and has no stable release yet", if Ogre developers finally have no interest in releasing a new version in 1.x.

But it could be worth making a linux64 dev snapshot with Ogre 1.10-dev bundled yes, to see if it's better.

**Comment by Bertram25** [comment]
sounds fair to me. :)

**Comment by hwoarangmy** [comment]
Well, Ogre 1.10 do not exists, it is the dev branch. That means that if all of us try it, we will have different versions (and possibly different bugs). I wouldn't be against using a non stable version but IMHO, we need at least something that doesn't change (ie a RC or a beta version). Too bad they don't do that from time to time (creating a tag for pre releases).

**Comment by akien-mga** [comment]
The second segfault mentioned was fixed in #1036, and the first one might have been the same issue but with a poorer stacktrace, so I'll close this issue. We'll open a new one if we get further segfaults.
