### ISSUE TITLE
New elements for casino room

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#1054]
i have these two ready for conversion, but im out of ideas for others; help?

http://opengameart.org/content/poker-table-fantasy-cards
http://opengameart.org/content/beer-barrel-decoration-for-walls

Also, when should dance animation be used? if it goes unused ill stop adding it to models.

**Comment by hwoarangmy** [comment]
Note that I've already added a model for the casino in #1053 

> Also, when should dance animation be used?

Well, when we will have decided to use it. So far, I've no idea when to do it. The only way I can see is to use a gift box/spell that will make every creature dance ^^

**Comment by Danimal696** [comment]
Closed with #1065
