### ISSUE TITLE
Add support to run either custom maps or official ones through command line.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#1055]
Once support for user maps will be added, running a game through command line should permit to differenciate games made with official maps and user ones.

See @hwoarangmy comment:

> to do that, the simplest, IMHO, would be to split the "server" option into "serverOfficial" and "serverCustom".

**Comment by hwoarangmy** [comment]
Also note that it might be a good idea, if someone goes for this one, to allow to play a saved game the same way. That would allow to run unit tests on a saved game
