### ISSUE TITLE
Wrong handling of carryable entities

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1061]
Crash seen by @Danimal696 

```
(16:26:41) (CreatureActionCarryEntity) [NORMAL] creature=DefaultWorker1 is carrying Dwarf97 to tile=[44,25]
(16:26:41) (CreatureActionCarryEntity) [NORMAL] creature=DefaultWorker24 is carrying Dwarf97 to tile=[46,25]
```

As we can see, 2 creatures try to carry the same dead body.

**Comment by hwoarangmy** [comment]
@Danimal696 I confirm I could reproduce the crash with the mistake I've seen. However, in my case, the creature causing the crash is the one carried. I will assume the log you have sent corresponds to another similar crash as the snapshot or that you had some slightly different but related bug.

**Comment by Danimal696** [comment]
i hope so :) , ill try out in the next exe

**Comment by hwoarangmy** [comment]
Could you reproduce it several times ?

**Comment by Danimal696** [comment]
It really seemed like the bug came when the kobold put the body in the corresponding room (jail, cript), lets hope it wasnt that

**Comment by hwoarangmy** [comment]
yes, that's the problem I've fixed. The crash happened when the creature was released in the crypt.
