### ISSUE TITLE
Display a scene in the menus background instead of an image

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1064]
I'm almost done with this. The scene will be simple but it will be a good occasion to display @Danimal696 animations dancing ^^

**Comment by akien-mga** [comment]
Woooooot! :D

**Comment by Danimal696** [comment]
Have any of you seen the game menus of Heroes 5? i love them and would like to try some of them:
https://www.youtube.com/watch?v=ZclSn5tYKDE

**Comment by hwoarangmy** [comment]
Well, once we have a scene, we can do what we want (or at least, whatour models can do ^^)

**Comment by Bertram25** [comment]
Yeah, I love that scene, too. ;)

**Comment by Bertram25** [comment]
@hwoarangmy Ah, btw. Should we remove that image now?
https://github.com/OpenDungeons/OpenDungeons/blob/development/gui/ODMainMenuBackground.png

**Comment by hwoarangmy** [comment]
well, if you all agree on keeping the main screen like it is for now, yes

**Comment by Bertram25** [comment]
I personally love it :) Even if I'm an old bear with many improvement ideas in mind. ;)

**Comment by hwoarangmy** [comment]
No problem. It only was a first step to get a scene working ^^
Feel free to let the artist in you play with it. However, if we want a more complex scene, it might be a good idea to use some scripting (and an occasion to have a look at AS or lua or something else)

**Comment by akien-mga** [comment]
Since we closed this one as being the "make it possible to display a scene" issue, should we open a new one to discuss how to improve the scene and what we're aiming for? (for "Later" likely, though we can already start adding enhancements for 0.7.0).

**Comment by hwoarangmy** [comment]
ok

**Comment by Bertram25** [comment]
yep :)
