### ISSUE TITLE
Trap balancing

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1067]
Recently, we balanced creatures so that, basically:
- each creature is specialized into 1 attack skill and better than another creature of its tier
- at level 10, a creature is more or less equivalent to its level 1 tier+1
- At level 1, a tier 1 can hurt (a little bit) a tier 4 creature

However, we din't balance traps at all. I'm not talking about how many damages each trap should do but a more general vision of traps.
For each trap, we should decide:
- which tier should loose against it (in 1 vs 1)
- How much hurt a given tier creature should be after fighting each trap
- Do we give some "skill" advantage for traps as we did for creatures (that would make some traps more interesting depending on which kind of creatures the enemy has). Note that we can also find some way to upgrade traps in a way or another (for example increasing physical damages OR magical damages)

The offensive traps we currently have:
- Cannon
- Spike
- Boulder

@OpenDungeons/developers WDYT ?

**Comment by akien-mga** [comment]
Balancing-wise, I think that moving/firing traps (boulder and especially cannon) should do less damage than static traps (spike), as they are likely to hit way more creatures/more times before they are destroyed.

Our 3 current traps are all kind of "physical" I guess, so I would expect them to damage more creatures with a low physical defence. We might then add a few new traps that do magical damage. 

I guess we could try to take inspiration from the characteristics of the traps: the cannon could do mostly physical (if you have a plate armor you get less shattered ribs from a blow ;)), while the boulder could do physical + absolute (armor or not, if a boulder rolls on you, it should hurt pretty badly). The spike trap could do mostly physical damage but also cause bleeding over time for a while. Just throwing some ideas :)

Regarding tiers, I guess traps should definitely win in 1v1 against tier 1 creatures. At any rate it takes time to research traps, so most players won't have many tier 1 creatures left when traps start being crafted and placed. Maybe traps should win in 1v1 against tier 2 (apart maybe highly armored tier 2), but not against tier 3 and 4?

**Comment by Bertram25** [comment]
Would each trap be a creature, what tiers and levels would those be in your opinions?

**Comment by hwoarangmy** [comment]
Well, we don't have much traps but I would say no tier 1 because of @akien-mga already said. IMHO, Cannon would be tier2, spike tier 3 and boulder tier 4.

**Comment by Bertram25** [comment]
Sounds fair. The skill tree might need tweaking, but I'm fine with this logic, combined with @akien-mga damage computation. The evil keeper in me loves that. :>
