### ISSUE TITLE
Runelord dwarf holds shield in the wrong direction

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#1071]
![lutris-weird1](https://cloud.githubusercontent.com/assets/4701338/12184467/b1d7baca-b595-11e5-9fb9-7cc0fef14b28.png)

**Comment by hwoarangmy** [comment]
i had never seen this one ^^
note that it may also be because it is in the wrong hand (right instead of left). Have you tried ?

**Comment by Danimal696** [comment]
Its because its in the wrong hand, happened to me a few times when messing with creatures

**Comment by hwoarangmy** [comment]
FYI, I've tried and confirm it is because the wrong hand is used. I can't remember which one is used ATM, but if you change to the other, it works well.

I will fix the level
