### ISSUE TITLE
Main scene "easy" improvements?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#1074]
Hey guys, I'm opening this issue because atm the main screen scene displays monsters aligned orthognally (AFAIK).

Let's take this example:
http://pre02.deviantart.net/b8aa/th/pre/f/2014/364/9/e/lara_croft_and_the_temple_of_osiris___wallpaper_by_allenrgamer-d8bxj2r.png

If you look at this image, you can see the view is slightly placed down to the characters, turn slightly up and left, ad tilted to the right. The characters are also placed a bit more on the right.
Also, the characters are placed in a staggered way, making them feel more heroic or something like that.
Adding fog on the ground, lighting, ... can also be added, but WDYT about it already?

**Comment by Danimal696** [comment]
when will you post a screen of what you are secretly cooking?

**Comment by akien-mga** [comment]
![screen1](https://cloud.githubusercontent.com/assets/4701338/12219031/d6838bb8-b731-11e5-8551-79c16237df56.jpg)
;)

**Comment by Danimal696** [comment]
I need to upload the hair fix for elf later; thats some interesting scene start :)

**Comment by Danimal696** [comment]
I wonder why the elf skin looks that bad, its a really nice texture, i think the problem is in the materials, doesnt it look a bit emissive?

**Comment by hwoarangmy** [comment]
It would also be good to use a config file to define the scene. That would allow the artists to easily test a new model with its animation without having to launch a game and wait for the wanted creature to spawn ^^
