### ISSUE TITLE
Copyright issues?

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#1076]
After looking at this, im left wondering if its usable at all:
Model:
https://sketchfab.com/models/f87f491c5c7b4160bf925f2466f2c8c6

Model its based off:
http://2.bp.blogspot.com/-lVmQsUzgO-c/VQCkrAr0BKI/AAAAAAAAlk8/FZdGHkPbuak/s1600/basepanthcompare.jpg

If not because the author says its a reimagination/inspired fanart off from a LOL character there is nothing that links to it except being a guy using the armor of that age. Could this be usable?

**Comment by akien-mga** [comment]
That's a good question... It was apparently made for a LOL fanart contest, so there's definitely a link. 
It does not seem to reuse or try to imitate too much the textures of Pantheon in LOL, and I'm not sure to which extent Riot Games can say that this "character" is copyrighted.

What makes it probably LOL-specific compared to a normal warrior of Ancient Greece is the ridiculous idea to go around almost naked but with a heavy iron helmet. Real Greek warriors had some more protections: http://www.ancient.eu/uploads/images/152.jpg?v=1431030817 :)

So all in all, I have no clue :)

**Comment by Danimal696** [comment]
can they claim ownership over the author just by entering the contest?

**Comment by akien-mga** [comment]
Probably not, but in the area of works "inspired by" a copyrighted work, the rugulations are quite unknown to me. If the model was a clear reference to a jedi with slightly different shape for the lightsaber and robe, I'm not sure it would prevent the author from being annoyed by Disney :)

**Comment by akien-mga** [comment]
In the end it's the question of whether this was "fair use" of the copyrighted material as inspiration, or a copyright infringement: http://www.howdesign.com/featured/graphic-design-copyright-laws-inspiration-vs-infringement/
As those concepts vary a lot depending on the country, I'd say we better avoid such things if we're not sure ourselves. Also an Ancient Greek character does not really fit our medieval fantasy setting I guess - though it did not prevent Riot Games from using it in a similar setting.

**Comment by Danimal696** [comment]
Sadly, this other one is under the same circunstances:
https://sketchfab.com/models/95233e2a8c0e4fe891301b9d673dadc3

**Comment by Bertram25** [comment]
The actual question is: Will it be difficult to prove it is closed-source work, or will it be difficult to prove it is not?
In the latter case, we are to get rid of the model as soon as possible. As we are a spare-time project with no lawyer at hand, we should avoid such problematic items as soon as we know about them. (The usual patent dilemma).
And it's not an example of "fair use", IMHO. AFAIK Fair use only exist in US for education purpose and such. Here, our work, even open source, is considered professional.

**Comment by akien-mga** [comment]
So I think the conclusion is: stay clear :)

**Comment by Danimal696** [comment]
Pity, such good models.

**Comment by Bertram25** [comment]
I'm closing since the answer was given.
