### ISSUE TITLE
Freeze at skrimish startup

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#1079]
Hi all! I'm back :)
I've tried to run latest two releases, but both freeze at skrimish map startup (select map- select players-push button-button rolls back-freeze). No errors risen. Zone Alarm warning sucessfully dismissed.
log:
[Ogre.log.zip](https://github.com/OpenDungeons/OpenDungeons/files/87388/Ogre.log.zip)
The OD binary loads a single core at ~100% and just does nothing.
![untitled](https://cloud.githubusercontent.com/assets/10726162/12265574/73a5da66-b946-11e5-99a0-e620655de8fb.png)
Win7 64 bits.
8-core AMD processor
Radeon HD5400 (512Mb)

**Comment by hwoarangmy** [comment]
Hi. Nice to see you back ^^

Could you please post your opendungeons.log ? It should be somewhere around:
C:\Users\eugeneloza\AppData\Roaming\opendungeons

Moreover, if you have no crash, I would guess at some firewall blocking the port opendungeons uses. Did you install zonealarm after trying previous releases ? Have you installed another firewall ?
Could you please try to start the game after disabling zonealarm to be sure ?

**Comment by Danimal696** [comment]
Wassup Eugeneloza :) , long time no see

**Comment by eugeneloza** [comment]
@Danimal696, I'm back from winter children camp. We've had a wonderful time in Carpathian mountains :)

@hwoarangmy, Oh... there it is... I was searching in ProgramData\AppData... And that damn new Win7 search skips system folders... I should always remember to use TC or something like that instead.

[od.zip](https://github.com/OpenDungeons/OpenDungeons/files/90276/od.zip)

**Comment by hwoarangmy** [comment]
@eugeneloza I've had a look at your logs but I could see no error. Communications between the server and the client sem ok. However, you have launched the legacy test map which is pretty long to load. Are you sure you have waited long enough ?

Could you please try to load another level and check if it can be loaded ?

If you really have issues loading maps, I will build a version with more logs.

**Comment by eugeneloza** [comment]
I've tried 'Failing keeper' and legacy test map (maybe, two of them) - I've included a few logs in the archive for different maps and versions.
I've forgotten to specify: I've reinstalled Win7-64 before the New Year (my sound recording started glitching) and it may have stopped working because of 'all new environment'. While I've kept all the programs the same, their 'story' (maybe, some settings) has changed, including Zone Alarm Free firewall & AVG antivirus. I've allowed OD 'everything' in program control settings in firewall.
I've waited for ~1 minute, but no result (on previous Win installation it took at max 5-10 seconds to prepare a map). It just loads a single processor core at 100% (maybe two of them, because 1 core is 13% and OD consumes 19%).

**Comment by hwoarangmy** [comment]
In this case, I would guess at a utf8 problem. Are you using some non standard characters in your user name ?
IIRC, you already had errors due to that in your previous environment. Could you try after setting appdata ? Something like:
OpenDungeons.exe --appData c:\temp\od

**Comment by eugeneloza** [comment]
No, Win7 is English, everything possible is also English. (good habit from MSDOS :D)
Username is User :)
No non-english characters in path. No spaces if I'm not mistaking (however, something like "Application Data" might contain spaces).
OD is at V: root subfolder (named by the downloaded archive name).
Everything is exactly as it was in previous installation.
I should try it at some PC at work...

**Comment by eugeneloza** [comment]
I've tried the new version with the same result... Game menu animation plays well, but skrimish won't start. I've also tried different run modes, including run as administrator, compatibility with WinXP...Win7 modes, etc. Still no result.
Strange, but... no music. Maybe there is some problem with music/sound output?
New logs attached.
Plus, maybe, I should try an older version to see if that one'll work as it did before.
[opendungeons.zip](https://github.com/OpenDungeons/OpenDungeons/files/104627/opendungeons.zip)

**Comment by hwoarangmy** [comment]
I will try to build you a version with much more logs to see where it freezes asap

**Comment by Bertram25** [comment]
> Plus, maybe, I should try an older version to see if that one'll work as it did before.

Yeah, this would definitely help. Thanks!

**Comment by hwoarangmy** [comment]
@eugeneloza I've uploaded new binaries:
http://download.tuxfamily.org/opendungeons/WIP/OpenDungeons-git20160124-Win32-MSVS2013.zip

Could you launch it with:
OpenDungeons.exe --loglevel 0
=> That will enable more logs. Could you please post the log file ?

**Comment by eugeneloza** [comment]
Well... DON'T ASK ME WHY I DID THAT! I have absolutely no idea. Just some programmer's intuition...
I've replaced the following DLLs from Castle Game Engine in the game folder (OGRE's DLLs) and everything started working. 
[dlls.zip](https://github.com/OpenDungeons/OpenDungeons/files/106219/dlls.zip)
Maybe some AL bug... or something.

**Comment by eugeneloza** [comment]
Now... let's just put everything in order.
1. I've downloaded 0.6.0 release yesterday and got the following error:
![160127_ogre_error](https://cloud.githubusercontent.com/assets/10726162/12607594/d9be9ef2-c4de-11e5-9f98-01ae66006070.jpg)
By trial-and-error I've understood that this one appeared due to my previous 'playing' with game configuration. None of the installed versions ever worked since (including the snapshot - the error message was similar but not identical) until I've fixed the configuration file in .../roaming/OpenDungeons/config (fixed pipeline item) folder.
2. After changing the configuration 0.6.0 started running (latest development snapshot still didn't let me start skrimish&no music). However, 0.6.0 had a high gamma value and stated blinking with 'mirror' image:
![160127_blinking window](https://cloud.githubusercontent.com/assets/10726162/12607649/45f6a222-c4df-11e5-978a-ac42db4138c1.jpg)
I've deleted the complete .../roaming/OpenDungeons folder and 0.6.0 started working ok without any glitches. Latest snapshot still wouldn't launch Skrimish and no sound.
3. I've replaced the DLLs above in the game folder and heard sound&music instantly. And the skrimish started normally.
P.S. I seem to overwritten only OpenAL32.dll, but in Castle Game Engine to get the OGG music to work I also have to include the attached DLLs (Vorbis-specific stuff and ZLib).
I've seen no such files in 0.6.0, but the music&sound worked fine.
OpenAL32.dll in 0.6.0 is ~400Kb compared to ~100Kb in the snapshot. I didn't try replacing the new dll with the 0.6.0 one, it might also do the trick.

**Comment by hwoarangmy** [comment]
Interesting. We are supposed to embed the openal dll shipped with SFML. I may have something in my environment making it choose some other library (I've already seen I have more than 1 in my computer). I will have a look tonight and build a new snapshot if the one embedded is not the SFML one.

**Comment by hwoarangmy** [comment]
@eugeneloza As we had guessed, there was a problem with my cmake file. For some reason, it had detected the openal dll on my computer (shipped with windows) rather than the one from sfml. I've fixed it and it should use the good one for next releases. I've uploaded binaries (same sources) but the openal is the correct one (at least the expected one):
http://download.tuxfamily.org/opendungeons/WIP/OpenDungeons-git20160127-Win32-MSVS2013.zip

Could you please confirm if it works well with this one ?

**Comment by eugeneloza** [comment]
Downloaded. I'll test it asap.

**Comment by eugeneloza** [comment]
Works flawlessly :D
Issue solved. Closing.
