### ISSUE TITLE
Add support to destroy a room using a new button.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#108]
Destroying a room gives back half the tile price.

The icon is ready (The wrecking ball)
Should we add this to 0.4.9 or later?

**Comment by hwoarangmy** [comment]
I think this will be usefull for debug purposes and it is not very hard to implement so we should add this for 0.4.9

**Comment by Bertram25** [comment]
Should be easier now that auto-addition of gold has been added with #92 & #117

**Comment by hwoarangmy** [comment]
I've done the patch. Currently, it is possible to sell the dungeon temple and the portal (even if it costs 0). IMHO, I don't care. But if someone thinks we should not, that's the right time to say it :)

**Comment by Bertram25** [comment]
No, we should not be able to sell the portal and the dungeon temple!! It's a game breaker! You will add a suicide option to the game. XD

**Comment by hwoarangmy** [comment]
yep ^^

**Comment by hwoarangmy** [comment]
now that we talk about it, if we want to avoid players selling some rooms, we should decide how we do. I mean Portals and Dungeon temples will be in the list but we will probably want to do the same for some other rooms. Probably in tutorial maps or in the campaign.
Even if we can do that later. For now, it can even help to be able to kill the portal/dungeon temple for debug purposes...

**Comment by Danimal696** [comment]
yes, some other buildings should be un-sellable, they are still on planning phase but "gem mine", "relics" and "mana well" come to mind

**Comment by hwoarangmy** [comment]
ok. Then I guess it will be better to think about it when we will have a better vision of what we wanna do :)

**Comment by Bertram25** [comment]
The room config (price and whether it is destroyable) will have to be part of the global config file, indeed.
For now, you can go ahead. I'll happily commit suicide to test it. ;)
