### ISSUE TITLE
Segmentation fault in MovableGameEntity::clearDestinations

### ISSUE THREAD

**Issue by johndh** [OpenDungeons/OpenDungeons#1084]
http://pastebin.com/22dwPMUK

64-bit Linux, current git version

Last few lines:

```
AL lib: FreeContext: (0xb78370) Deleting 109 Source(s)
signal 11 (Segmentation fault), address is 0x7f2f2dcdec90 from 0x7f2f2dcdec90

[bt]: (1) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : +0x696c90 [0x7f2f2dcdec90]
[bt]: (2) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : +0x696c90 [0x7f2f2dcdec90]
```

**Comment by akien-mga** [comment]
Thanks for the report. Looking at the log, the actual relevant part seems to be more:

```
(18:32:12) (Room) [NORMAL] SERVER - Room=Hatchery_10 is absorbing room=Hatchery_5
signal 11 (Segmentation fault), address is 0x8 from 0x4fbaf0

[bt]: (1) ./opendungeons : MovableGameEntity::clearDestinations(std::string const&, bool, bool)+0x60 [0x4fbaf0]
[bt]: (2) ./opendungeons : MovableGameEntity::clearDestinations(std::string const&, bool, bool)+0x60 [0x4fbaf0]
[bt]: (3) ./opendungeons : RoomHatchery::handleCreatureUsingAbsorbedRoom(Creature&)+0x1f [0x5fd2af]
[bt]: (4) ./opendungeons : Room::absorbRoom(Room*)+0x324 [0x5e2494]
[bt]: (5) ./opendungeons : Room::checkForRoomAbsorbtion()+0xbb [0x5e2c3b]
[bt]: (6) ./opendungeons : RoomFactory::buildRoomDefault(GameMap*, Room*, Seat*, std::vector<Tile*, std::allocator<Tile*> > const&) const+0x373 [0x6079d3]
[bt]: (7) ./opendungeons() [0x5fcfa9]
[bt]: (8) ./opendungeons : RoomManager::buildRoom(GameMap*, RoomType, Player*, ODPacket&)+0x203 [0x602f13]
[bt]: (9) ./opendungeons : ODServer::processClientNotifications(ODSocketClient*)+0x3e5d [0x5b583d]
[bt]: (10) ./opendungeons : ODServer::notifyClientMessage(ODSocketClient*)+0x21 [0x5bbe91]
[bt]: (11) ./opendungeons : ODSocketServer::doTask(int)+0x10c [0x5c8b4c]
[bt]: (12) ./opendungeons : ODServer::serverThread()+0x70 [0x5b11e0]
[bt]: (13) /usr/lib/x86_64-linux-gnu/libsfml-system.so.2 : +0x5fb8 [0x7f2f2b75afb8]
[bt]: (14) /lib/x86_64-linux-gnu/libpthread.so.0 : +0x8182 [0x7f2f2d018182]
[bt]: (15) /lib/x86_64-linux-gnu/libc.so.6 : clone+0x6d [0x7f2f2aa5047d]
```

**Comment by hwoarangmy** [comment]
Thanks for the report. Could you please upload the full log ? In the part you uploaded, we cannot see which creatures are currently using the room.

**Comment by johndh** [comment]
Sure thing!

[opendungeons.log (copy).1.txt](https://github.com/OpenDungeons/OpenDungeons/files/95132/opendungeons.log.copy.1.txt)

**Comment by akien-mga** [comment]
Wow, how did you manage to embed a text file in GH? Did they finally alllow this most basic feature after their nonsensical support for MS Office documents? :D

**Comment by hwoarangmy** [comment]
> Wow, how did you manage to embed a text file in GH?

Magicians never give their tricks...

**Comment by akien-mga** [comment]
It does work :-O [test.txt](https://github.com/OpenDungeons/OpenDungeons/files/95584/test.txt)
At last! :D

And there's support for zip files too: [test.zip](https://github.com/OpenDungeons/OpenDungeons/files/95588/test.zip)

Ok I'm done hijacking this issue, sorry :D

**Comment by hwoarangmy** [comment]
Note that this issue can be easily reproduced:
- drop 3 creatures in the training room
- while creatures are training, add a tile to the training room to absorb it
- slap to death the creatures training
- wait until they disapear
- add a new tile again to the training room

=> The game should crash
