### ISSUE TITLE
Lizardman loves lava???

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#1088]
(just a note)
The a few days ago downloaded snapshot shows Lizardman has 1.08 speed over lava. This sounds not very logical... :) Flying creatures - yes, maybe some fire-driven creatures... but walking lizardman... 
![lizardman_lava](https://cloud.githubusercontent.com/assets/10726162/12614984/af63e022-c50b-11e5-8af2-b23853fc608b.jpg)

**Comment by akien-mga** [comment]
I guess we forgot to adapt the stats of the lizardman when we made him replace the flying wyvern XD
