### ISSUE TITLE
Many goals use Client gamemap to check if they are reached

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#110]
They should use the server gamemap (at least for those in the server gamemap)

**Comment by Bertram25** [comment]
Hi,

Also, shouldn't the goals be told by the server, and the clients only display what they're told to? IMHO, it would simpler to handle.
Hence remote clients wouldn't handle goals update at all by themselves, except if it means a lot of useless traffic, though.

**Comment by hwoarangmy** [comment]
It is the case. The goals are updated on the server gamemap and the result is sent to the clients as a string. But I had did not remember that some goals used the client gamemap :
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/GoalProtectCreature.cpp#L35

**Comment by Bertram25** [comment]
k :)
