### ISSUE TITLE
Using own linux package repository

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1103]
ATM, travis CI compilation fails because the libogre1.9 package has been removed from the repo we used to install it from.

IMHO, to not rely on repos that may change, we have 2 options:
1 - Get our own repo with all required packages (for example using launchpad)
2 - Compile what we need to, build a tarball with what is needed to install and download the tarball

@OpenDungeons/developers WDYT ?

**Comment by Bertram25** [comment]
> 1 - Get our own repo with all required packages (for example using launchpad)
> 2 - Compile what we need to, build a tarball with what is needed to install and download the tarball

Solution 1 is the best practice. I'm all for it.

**Comment by hwoarangmy** [comment]
I guess so. But I don't know how to do it. I will have a quick look.

@akien-mga I guess we are in your speciality field. Do you have some clues ?

**Comment by akien-mga** [comment]
I think that would be overkill, I'm pretty sure we can find existing PPAs with the dependencies we need; our dependencies are not so custom, we just need to update our travis-ci config. For example we're still building on Ubuntu 12.04 IIRC, while we could use Ubuntu 14.04 and then likely not need to build boost ourselves for example. Or we could use a docker image.

I just need to find some time to look into it. I'm actually fighting with travis-ci right now for Godot, but it's arguably more complex than what we need for OD: https://github.com/akien-mga/godot-deploy/blob/2.0/.travis.yml :)

**Comment by Bertram25** [comment]
> I think that would be overkill, I'm pretty sure we can find existing PPAs with the dependencies we need; our dependencies are not so custom, we just need to update our travis-ci config

That's pretty much what I did for VT, so I'm ok with it. The thing is, with a custom PPA, even if we retake packages from elsewhere, we could reliabily count on those. Note that even doing a wget on some url is fine as well, right?

**Comment by hwoarangmy** [comment]
I didn't knew we could force a distro when building with travis. Indeed, using ubuntu 14 would help much as Ogre is already there IIRC. I will have a look.

**Comment by akien-mga** [comment]
They support either Ubuntu 12.04 (legacy), 14.04 (trusty) and containers.
To use 14.04, you have to define:

```
sudo: required
dist: trusty
```

**Comment by hwoarangmy** [comment]
yes, I had seen in your travis file, thanks

**Comment by Bertram25** [comment]
Isn't this fixed?

**Comment by hwoarangmy** [comment]
ok
