### ISSUE TITLE
Settings menu button is not visible

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1109]
As stated by bark in the forum:
http://forum.freegamedev.net/viewtopic.php?f=36&t=6791&p=67931#p67931

We might want to add a button next to the other ones for settings especially now that we have more interesting stuff than only video settings.

@OpenDungeons/developers WDYT ?

**Comment by Bertram25** [comment]
Fine by me. This was the first plan afaik. :)
