### ISSUE TITLE
Change chicken spawning logic in the hatchery

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#112]
I've been thinking about how to display the chicken coops in the hatchery. I think it could be nice to have one per active spot to know how many chickens are generated even if they are all eaten.
The problem is that for 3x3 rooms, we could have 5 activespots. With the chickens, it will be 10 room objects for 9 tiles.
We could add support to have several room objects on the same tile (at least 2).

@Bertram25 What do you think ?

**Comment by Bertram25** [comment]
Hi @hwoarangmy :)
Here is how I see hacheries, feel free to coorect as you see fit:
As an exception, hatcheries should only have chicken coops on their center active spot, Imho. I do think it wouldn't look good otherwise.
I also do think a chicken should be spawned per room tile, except where the chicken coops are. (Spawned little by little, like now).
What do you think?

**Comment by hwoarangmy** [comment]
I agree, 10 room objects on a 3x3 tiles room seems a lot. But I would prefer to be able to see at a glance how many chickens can be spawn in a hatchery (as some can have been eaten). And actually, there is one per active spot.
Spawning 1 per tile seems too much to me. There would be too many chickens. Moreover, if we do so, there will be no benefit of claiming walls in the hatchery (and I think the additionals actives spots when caliming walls are a good idea). Even if we can forget this bonus for hatcheries.

**Comment by Bertram25** [comment]
> Spawning 1 per tile seems too much to me. There would be too many chickens. Moreover, if we do so, there will be no benefit of claiming walls in the hatchery (and I think the additionals actives spots when caliming walls are a good idea). Even if we can forget this bonus for hatcheries.

You're right. Let's keep one chicken per active spot.

> I agree, 10 room objects on a 3x3 tiles room seems a lot. But I would prefer to be able to see at a glance how many chickens can be spawn in a hatchery (as some can have been eaten). And actually, there is one per active spot.

What about a central chicken coop, which has a different size and/or shape depending on how much active spots are around?
I know it's demanding as for the modeling, but this would look nice, wouldn't it?
This solution would require 5 different chicken coop model though. (Or maybe we can play with it's scaling?)
What do you think guys?

Another solution would be to create another model adapted for claimed walls. What do you think @Danimal696 ?

**Comment by hwoarangmy** [comment]
> different size and/or shape

That's also what I had in mind as a "simple" solution (playing with size/color). I had also thought about changing the time respawning with the increased number of active spots (even if we have to find a logic for bigger rooms). In this case, the hatchery could spawn 3 chickens per central active spots and the time respawn would change accordingly to the number of wall active spots per central active spot.

> This solution would require 5 different chicken coop model though.

I think this is too much work for the artists. Maybe a simple model like a patio heater or something like that on the walls active spots could do.

**Comment by Bertram25** [comment]
> That's also what I had in mind as a "simple" solution (playing with size/color). I had also thought about changing the time respawning with the increased number of active spots (even if we have to find a logic for bigger rooms). In this case, the hatchery could spawn 3 chickens per central active spots and the time respawn would change accordingly to the number of wall active spots per central active spot.

I like that proposal, too. :)

> Maybe a simple model like a patio heater or something like that on the walls active spots could do.

Yep, that's a good idea as well. I think you can go ahead for the central active spot, and maybe @Danimal696 will agree to help us for wall hatchery models?

**Comment by hwoarangmy** [comment]
> I like that proposal, too. :)

Ok, I will do that.

**Comment by hwoarangmy** [comment]
I've made a try and after all, I think the old logic was better (and it's less complicated to change). I mean spawning 1 chicken per active spot because on the training room or the library, central or wall active spots are equivalent. In the hatchery, I think we should keep the same logic. That's why, now, there will be 1 chicken coop on central tiles and 1 chicken will be spawned per activespot.
The only difference with before is that the chickens will be randomly linked to one of the room tiles (except those with chicken coops). This way, we can have chicken coops and the same behaviour :)

**Comment by Danimal696** [comment]
I like the more simple way proposed by hwoarangmy, i always saw the chicken coop just as some fancy decoration for the room, not an active object. I would just add it at room centers witouth any other change to code. That said if something else is decided i can made some new models as needed

**Comment by Bertram25** [comment]
Np for that change. I do think it doesn't change anything in game and if it's more simple... :)
@Danimal696 I sincerely still would like to see small pond on wall active spots. This would visually help understand why claimed walls make a difference, IMHO.

**Comment by hwoarangmy** [comment]
> This would visually help understand why claimed walls make a difference, IMHO.

That's also my point. Currently, the more active spots, the more chickens. But if there are creatures eating, it is not that obvious how many chickens are there. Well, that said, it can be done later. Shall we create an issue ?

@Danimal696 
Concerning the chickens, I've just realized that they do not have a "Walk" animation state (at least, they seem static when I set them to this state). Do they have ? If not, which state do they have ?
Bonus question : is there a way to list the available states ?

**Comment by Danimal696** [comment]
> "@Danimal696 I sincerely still would like to see small pond on wall active spots. This would visually help understand why claimed walls make a difference, IMHO."

Yes, i can make some kind of model to pretty up the room; but this takes me to something i have been thinking, Could the wall textures be changed when a room is build next to it? and could the wall mesh be changed? that could open a lot of posibilities to make the rooms and graphics stand up by a lot.

> Concerning the chickens, I've just realized that they do not have a "Walk" animation state (at least, they seem static when I set them to this state). Do they have ? If not, which state do they have ?
> Bonus question : is there a way to list the available states ?

the only way i know is to look at the unimported blender model animation tracks, sometimes a capital or "Death" instead of "Die" can ruin the animation;

Edit: they seems to be walking normally on the exe bertram released last week, maybe you cant see it because of how fast they walk around, "Walk" is also listed as an animation

**Comment by hwoarangmy** [comment]
ok. I will keep Idle animation for chickens even when they move as it's the only one I'm sure of. We can change that later.

**Comment by Bertram25** [comment]
@hwoarangmy It seems there is a getAllAnimationStates() function in Ogre:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/RenderManager.cpp#L1170

I hope it will help you.

**Comment by Bertram25** [comment]
> Yes, i can make some kind of model to pretty up the room; but this takes me to something i have been thinking, Could the wall textures be changed when a room is build next to it? and could the wall mesh be changed? that could open a lot of possibilities to make the rooms and graphics stand up by a lot.

@Danimal696 The good news is that it is possible. :) But the bad one is that things are already very complicated and hard-coded when it comes to the tileset handling.
I'd rather we have a clean and tested way to configure how the tileset should behave before we enter in complicating it. (One of my oh so neat tasks assigned. ;])
Let's take this point when we're more or less done with tileset handling dehardcoding, and why not add special claimed wall tiles making the room stand out more. :)

**Comment by hwoarangmy** [comment]
> It seems there is a getAllAnimationStates() function in Ogre:

It works; And chickens have a Pick animation :)
There is also a Walk animation after all. It is a little bit static so I thought it was buggy. But if it is the intended animation, I will use it.
