### ISSUE TITLE
Try to display the callstack in the logs when a crash occurs

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1120]
I cannot reproduce so far but @bark10 reported it:
http://forum.freegamedev.net/viewtopic.php?f=36&t=6791#p67957

**Comment by Bertram25** [comment]
Let's see if @bark10 still has the issue with the setting button being different (?)

**Comment by bark10** [comment]
Will check this as soon as the next snapshot/version is out :D 

Edit: tried deleting .config/opendungeons and .local/share/opendungeons. did not work

**Comment by hwoarangmy** [comment]
@bark10 Relevant test. We will see once the new binaries are out

**Comment by akien-mga** [comment]
I can reproduce the bug too actually using my Linux64 snapshot, so it's a library problem on my buildsystem most likely. I'll investigate.

**Comment by akien-mga** [comment]
I'll try to build against the new CEGUI 0.8.5, and revert OIS back to the old release (I had installed a git snapshot to see if it improved input issues at a time).

**Comment by hwoarangmy** [comment]
CEGUI 0.8.5 ? IMHO, we should use the same version as they might introduce different bugs/behaviours. Have you tested it ? If not, I think we should stick on 0.8.4 for the RC1

**Comment by akien-mga** [comment]
I'm using 0.8.5 locally, it works ok. The binaries I've just built against cegui 0.8.5 and the older OIS seem to work fine, I'm currently uploading them.

**Comment by akien-mga** [comment]
CEGUI 0.8.5 just has some minor bugfixes: http://cegui.org.uk/download/cegui-085

**Comment by akien-mga** [comment]
@bark10 Could you try http://download.tuxfamily.org/opendungeons/WIP/OpenDungeons-git20160318-Linux64.tar.xz ?

@hwoarangmy I've got to go, I'll let you link my snapshot when you announce your new windows binaries. My snapshot does not contain your very latest PR, but since it only affects unit tests it's not really an issue IMO.

**Comment by hwoarangmy** [comment]
yep, I agree. Ok, i will add the link

**Comment by Bertram25** [comment]
@akien-mga @hwoarangmy There are interesting fixes relative to tooltip. Might be worth testing whether they fixed the empty tooltip behavior. When is the lan scheduled ? :)

**Comment by bark10** [comment]
@akien-mga Yay, the settings menu works now. But the game crashes whenever I try to start a new game! I get this error message:

`GLSL compiled: 
Vertex Program:3ede7ef0-466e-4636-87cf-acfedb1c8df0_VS Fragment Program:cc639481-98a1-525f-5f8a-428d02db2597_FS GLSL link result : 
CEGUI::UnknownObjectException in function 'CEGUI::NamedElement* CEGUI::NamedElement::getChildElement(const CEGUI::String&) const' (/home/cegui/BUILD/cegui-0.8.5/cegui/src/NamedElement.cpp:150) : The Element object referenced by '__auto_titlebar__' is not attached to Element at 'SettingsWindow'.
terminate called after throwing an instance of 'CEGUI::UnknownObjectException'
  what():  CEGUI::UnknownObjectException in function 'CEGUI::NamedElement* CEGUI::NamedElement::getChildElement(const CEGUI::String&) const' (/home/cegui/BUILD/cegui-0.8.5/cegui/src/NamedElement.cpp:150) : The Element object referenced by '__auto_titlebar__' is not attached to Element at 'SettingsWindow'.
Aborted`

**Comment by hwoarangmy** [comment]
Then I guess we should stay on CEGUI 0.8.4. I remember someone tried to compile using CEGUI dev branch (before 0.8.5 was out) and had similar problem. I guess they somehow changed how windows are built.

**Comment by akien-mga** [comment]
I've done another build using CEGUI 0.8.4, and it indeed fixes the issue.

@bark10 I've upload new binaries at http://download.tuxfamily.org/opendungeons/WIP/OpenDungeons-git20160318-Linux64-fixed.tar.xz that should fix the above issue. To save bandwidth I only uploaded the new `opendungeons.x86_64` binary and `lib64` folder, as the rest of the data is unchanged; so just remove your binary and lib64 with the new ones, and it should work fine.

**Comment by bark10** [comment]
Excellent! I can start games now. The game crashed after 30 minutes. Here's the log found in .local/share/opendungeons: https://paste.perldancer.org/2LfTpqltfazla

**Comment by akien-mga** [comment]
Thanks! Was there by any chance a stacktrace in the terminal?

(@hwoarangmy @Bertram25: Would we have a way to ensure that the stacktrace is written in the log too, or is the application killed already so we can't manage the log file at that time?)

**Comment by bark10** [comment]
I usually run the game in the terminal, but I forgot it this time (just double-clicked the executable). Therefore I had to rely on the log in .local/share. Could you explain what "stacktrace" means?

edit:  I read this http://stackoverflow.com/questions/3988788/what-is-a-stack-trace-and-how-can-i-use-it-to-debug-my-application-errors

How do I recognize a/the stacktrace?

**Comment by akien-mga** [comment]
It will look typically like the last part of this log: https://github.com/OpenDungeons/OpenDungeons/issues/763#issue-77431335 (everything after "Program received signal SIGABRT, Aborted."). Basically it gives the list of the function calls that led to the crash, starting from the function that crashes and going up the stack. Depending on whether you have debug informations including in the binary, it will be more or less verbose.

**Comment by hwoarangmy** [comment]
I've had a look at the log but couldn't see the reason why it crashed. It is not an easy task without the call stack.

Concerning displaying the call stack in the log, it is not straight forward because the log file may not be initialized when the crash occurs. Thus, it is always better to use the console or a dedicated log. However, I guess it is worth the trouble to have a look.

**Comment by akien-mga** [comment]
Using a different file would be fine if that's easier, something like crash.log.

**Comment by hwoarangmy** [comment]
the freezing issue is fixed as it was a packaging issue.
Since it has been discussed here, we can change this issue to try to display the callstack in the logs when a crash occurs

**Comment by hwoarangmy** [comment]
fixed by #1155
