### ISSUE TITLE
Faction not correctly set in the lobby when hosting

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1122]
in the lobby (masterserver game), we can see the faction is set but the game complains it is not when I click launch. I had to open the combo and choose the values to make them work

**Comment by hwoarangmy** [comment]
Note that it has been tested on "the bridge" level. After hosting another game ("greed or might", game launched in a row without closing/launching), the game could be launched without having to manually set factions. I don't know if it is because of different level settings or something else. In any case, when a multiplayer level is launched, we would expect unselectable settings only to be set. Other combos should be empty.

**Comment by Bertram25** [comment]
Fixed with https://github.com/OpenDungeons/OpenDungeons/pull/1124/commits/ad754f12c034e18d37e3fdd3227655cd4ad7b13c
