### ISSUE TITLE
Crash-to-destop log

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#1131]
@hwoarangmy, I've found the crash report log I was talking about:
[crash.zip](https://github.com/OpenDungeons/OpenDungeons/files/187648/crash.zip)
P.S. I was also recording the gameplay video by OBS.

**Comment by hwoarangmy** [comment]
@eugeneloza Thanks for the log. It is much easier to understand what happened with it. You forgot to say that you were exiting the game when it crashed ;-)

I will fix that tonight. Fix should be pretty easy

**Comment by eugeneloza** [comment]
Ooops... I don't remember I was exiting the game :) But, maybe... Or perhaps I was just trying to make a pause...? Anyway, I'm glad it was easy to fix :)
Thanks!
