### ISSUE TITLE
Keyboard input to jump to dungeon heart

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1133]
I would like to be able to press the 'H' key on my keyboard and have the screen jump to my dungeon heart.
This helps immensely with dungeon management to go back to your main dungeon after spending time exploring or fighting away from it.
For now it is also a very welcome workaround while issue #955 is not solved and you can get lost completely.

Follow up features would be to also have (configurable) keybindings to jump to other rooms and/or player configurable slots (Press Ctrl+1 to store, press 1 to go back to that location.)

**Comment by Bertram25** [comment]
Hi @Loobinex and welcome! :)

Actually, the T key can already do exaclty that.

**Comment by akien-mga** [comment]
Welcome :)

For the part about configuring keybindings, it's tracked in this issue: #910. We haven't really started working on it, though it should be relatively easy to integrate in the existing game settings.

**Comment by Bertram25** [comment]
Ah, also when you are attacked, pressing Space will bring you to the location of the fight. Might be handy. :)

**Comment by Loobinex** [comment]
Thanks for the welcome, and sorry for the duplicate. I had tried a few buttons already, T was not one of them but it should do the trick.

**Comment by Bertram25** [comment]
> Thanks for the welcome, and sorry for the duplicate. I had tried a few buttons already, T was not one of them but it should do the trick.

Don't be sorry :) Feed-back is always welcome! Btw, your comment about the right click make sense and may induce some control changes. Let's see how it turns.
