### ISSUE TITLE
Crash-to-destop #2

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#1148]
In the latest snapshot (http://download.tuxfamily.org/opendungeons/WIP/OpenDungeons-git20160326-Win32-MSVS2013.zip) I still get crash-to-desktop at closing the game window. Log:
[crash.zip](https://github.com/OpenDungeons/OpenDungeons/files/195102/crash.zip)
Previous issue here:
https://github.com/OpenDungeons/OpenDungeons/issues/1131

**Comment by hwoarangmy** [comment]
strange. Could you post your log ?

**Comment by eugeneloza** [comment]
You mean OpenDungeons.log from 'roaming' folder? I'll get it tonight. But it contains no messages I could detect as crash-related.
It happens when I click on cross (close) in the window titlebar.

**Comment by hwoarangmy** [comment]
> You mean OpenDungeons.log from 'roaming' folder?

yes.

> But it contains no messages I could detect as crash-related.

Well, here the crash.log is not very explicit so I was hoping the log would be better. Do you see this crash often ? Do you have a way to reproduce it ? I never experienced similar crash so it might not be straight forward. Depending on crash frequency, it might be worth or not to fix it before 0.7.0.

**Comment by eugeneloza** [comment]
Tested it thoroughly today morning. I always get CTD when closing the OD window at Model's Fair. I remember I got a crash at some other map, but I can be wrong.
Maybe that's the prison/torture room? I see the skulls at the walls, but no active spots, neither particles when I imprison the creature (I'm not sure if they are implemented in latest snapshot?). And I'm almost sure I got the torture room before the crash at another map (I don't remember exactly which one I've played).
[opendungeons.zip](https://github.com/OpenDungeons/OpenDungeons/files/199097/opendungeons.zip)

**Comment by hwoarangmy** [comment]
I've seen what's going on. Stupid me ^^

**Comment by hwoarangmy** [comment]
@eugeneloza I've uploaded new binaries with a version that should fix the bug you have seen. Could you please confirm that it is ok ?

**Comment by eugeneloza** [comment]
I've downloaded the binaries. I will try it today evening. 
Yeah... that normal skrimish map I've played also had a door :)

**Comment by eugeneloza** [comment]
Works flawlessly! Thanks!
