### ISSUE TITLE
Battle music @ imprisoned/tortured creature

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#1149]
When I put my own creature into prison I get "we're under attack" message, the music starts "battle theme" and persists...
(got it at Model's Fair + latest release when imprisoned a kretaur).

**Comment by hwoarangmy** [comment]
Yes. ATM, torture room and prison trigger the attacked message/sound

**Comment by hwoarangmy** [comment]
fixed by #1155
