### ISSUE TITLE
Spells and traps need to have counter-play

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1150]
In Dungeon Keeper the spells and traps were poorly designed from a game play perspective. This was especially so in the first game, but OpenDungeons should not repeat the same mistake. That they add so little to these games is because they don't have any counter-play.
###### On spells:

---

For players the spells and traps of DK have always felt both overpowered and useless at the same time. For example take the lightning spell of DK1: If you have very little gold you won't cast it on your rival army because it will hardly make an impact, but if your on a map with gems you can effectively lightning down the entire army and there's nothing that can be done about it. And conversely, when you know the enemy keeper has lightning, it means nothing to you as a player, you won't change your play style because there's nothing to do, you'll just accept a few hits and ignore it. So when you play with this spell _or when you play against it_, it provides no fun.
Compare this to for example the Psionic Storm spell in starcraft, which does have counter-play and how this actually adds something to the game both for people playing protoss and those playing against them. To cast the spell you'll need to get a slow and weak templar unit close to the location you wish to storm and than you can cast a fixed amount of times before you are vulnerable. When you manage to get good hits you can devastate the rival army or economy and it feels exhilarating, because you've actually accomplished something. However, playing against the protoss does not mean you're simply at the mercy of this spell, you can see the templar coming and kill him before he can cast the spell, you can cast a counter spell to take away his mana, you can spread out your units or move them out of the way so that there's no effective location to be hit and finally even when a storm hits you can reduce the effect by quickly getting out from under it. Doing so is also fun, and you can blame yourself and the skill of your rival when you actually get hit by it. This counter-play does not make the spell useless against a good player however, as by casting it you can force your rival to move his army away and as such try to get a tactical advantage in positioning, providing several levels of engagement and fun.

In OpenDungeons the spells can also be designed with counter-play in mind making them more fun overall. For example instead of an instant hit lightning spell, make it a lightning cloud that builds up before lightning comes out giving the enemy time to get out from under it doing massive damage when it hits. Or make it an earthquake spell that does damage over time in a large area, which only adds up when you stay in the area too long.
For each spell to be put in the game keep in mind not only when to cast it, but also what can be done to counter it or what it counters.
###### On traps:

---

Traps are to be treated the same way. In especially DK1 there's very little dept to them, and maps with a lot of them on it are simply no fun because they are tedious to go up against. For example the Word of Power trap in DK1, when there's one on the map you'll only find out when you lose your first imp against it and you are just annoyed but know there's nothing you could have done to prevent it. Now the only way to proceed is to just have it triggered by a creature you don't mind getting hit a few times until the trap is spent, because otherwise you're just going to lose some more creatures as there's nothing to do to stop the trap.
Likewise on many maps there is little strategy in using them; if heroes come from a specific direction just place damaging traps in the way and that's it. You don't exactly feel clever when you manage to damage some heroes a bit by having them walk over a trap in the only pathway to your dungeon.

To make these fun, you'll need to come up with some way to require strategy to use them effectively. For example make invading heroes dodge them when they can so you'll have to place them in a way to box them in or run into another trap. Or make it so traps need to be primed right before the heroes arrive for them to go off. More ideas required.

**Comment by Bertram25** [comment]
@Loobinex I must say I wholeheartedly agree with your point of view, but as you said, we first need precise examples of how we'll improve each spell and traps.

For instance, that's why we thought about the fear trap which makes the creature flee carelessly away, and adds some strategy upon how you place them, or a trap that makes the creature run while getting zone damages, making them dangerous to anyone and forcing you place them carefully.
I must say I like the feat behind that but I would ask to keep design and conceptual discussion in the forums if possible and add more precise tasks in issues so that the issue list doesn't get crowded with "vague" issues as it doesn't help people go forth.

Could you open something on the forums instead?

**Comment by Loobinex** [comment]
Ok, I'll sign up for the forums.

**Comment by Bertram25** [comment]
Thanks! I'd suggest there: http://forum.freegamedev.net/viewforum.php?f=37 Feel free to point out anything. (Closing as it belongs to forums, but I hope precise tasks will come up out of this. :])

**Comment by Loobinex** [comment]
@Bertram25: I've opened a topic yesterday: http://forum.freegamedev.net/viewtopic.php?f=37&t=6858

**Comment by Bertram25** [comment]
@Loobinex You should be accepted quite soon. It's cool to have you on board. :)
