### ISSUE TITLE
Suggestion regarding dying and death of minions

### ISSUE THREAD

**Issue by sverre123** [OpenDungeons/OpenDungeons#1162]
Very cool game! I have a suggestion regarding the dying and death of friendly minions, basically what they did in DK2. 
1. When health bar goes down to zero (faction tag turns dark), the minion is "dying", but not immediately dead.
2. The faction tag starts blinking signalising the minion is now dying, and will stay so for about 20 seconds. (you can of course not pick them up or use healing spells in this state)
3. Available workers may collect the dying minion and drag them to their beds in the lair so that they can recover. (if the minion is hostile it will be dragged to jail and be ready for torturing or starvation).
4. However if the minion is not collected within the 20 seconds the minion dies permanently and the faction tag disappears. 
5. The body will stay there for 20 seconds before dissolving.
6. Available workers may collect the dead minion and drag them to the crypt. 

I think this would be a very good thing to implement for several reasons:
- Gaining territory during a fight and positioning of the fight is more important, because you can drop workers only in your own tiles to save your own minions and capture your opponents. It adds another layer of strategic consideration to the game, rewards tactical and patient plays and punishes over-extension.
- Easier to get overview of the fight! With blinking tags you can easily spot how many of yours and your opponent's minions are down, and get a feeling of how the fight is going. You will easily see the difference between minions who are down and who are not. Right now the color of dead and living minions faction tag is very similar and hard to spot when the battlefield is chaotic.
- It will be a rewarding experience to save your most beloved high level minions that you put in so much time training and feeding.

**Comment by hwoarangmy** [comment]
It is already implemented that way. What you describe is KOing creatures instead of killing. IIRC, it was an option in the DK games and it is also the case here. You can activate it in the menu you can open by pressing the hammer button near the minimap.
However, the option is disabled by default. And if it is disabled, the creatures will fight to death.

**Comment by Bertram25** [comment]
@hwoarangmy I guess we can close then?

**Comment by hwoarangmy** [comment]
ok
