### ISSUE TITLE
Enemy workers escape prison

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1163]
I played a map in version git20160402 where enemy workers entered my dungeon. I had enabled the checkbox to stun rivals and a prison to bring those workers to. However, when they were carried towards prison they immediately walked out and started fighting with my creatures again. They were recaptured and escaped indefinitely until I disabled the config for them to be captured.

To see this behavior in progress, load the attached save:

[2016-04-06_004712-SK-FallingKeeper.zip](https://github.com/OpenDungeons/OpenDungeons/files/205478/2016-04-06_004712-SK-FallingKeeper.zip)

**Comment by hwoarangmy** [comment]
I had not seen this one. I've always thought about fighters regarding prison but not workers ^^
I guess it is worth fixing.

**Comment by Loobinex** [comment]
And what is the intended behavior in this case?

**Comment by hwoarangmy** [comment]
Good question ^^
I was thinking about letting workers be in prison/torture room. That would make possible to have more than what mana would possibly allow.

**Comment by Loobinex** [comment]
For the capturing player, sure,... What about for the player who has his workers captured, while they are in prison can he have fewer workers available? So can I defeat a player by capturing all his workers and keeping them alive?

**Comment by hwoarangmy** [comment]
Indeed, as long as they are alive, they will count as owned by the player they used to belong to before getting captured.
IMHO, that's not a big problem. After all, if you can manage to get all my workers, I will accept the handicap it will be for me. However, implementing this behaviour might be a game breaker before a release as for now, we always stated that fighters only could use rooms (including prison or torture room). Allowing workers to use this might have fallbacks on the other rooms if we are careless.

**Comment by Loobinex** [comment]
In that case the easiest way forward for now is to make it that workers always die, not get stunned.

**Comment by hwoarangmy** [comment]
yep, I guess it is wiser ^^
