### ISSUE TITLE
Wizards kill whole armies in a single shot

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1164]
I like wizards as much as the next guy, but they seem a bit overpowered. I have yet to be able to win a single fight as whenever a wizard shows up they manage to kill every creature I have with a single shot.

To see this in action load the attached saved game, complete the bridge in to the northwest that allows the heroes access to your dungeon and use all 15 creatures to attack the wizards that come. Notice the entire army just melts right away.

[2016-04-06_004712-SK-FallingKeeper.zip](https://github.com/OpenDungeons/OpenDungeons/files/205490/2016-04-06_004712-SK-FallingKeeper.zip)

**Comment by Danimal696** [comment]
He is very weak to archers, but its true, its in need of heavy balance .

**Comment by hwoarangmy** [comment]
I've tried your save game and he is far from being alone. There are quite a lot of knights/wizards coming to your dungeon. I'm not sure this level can still be won since the last balancing

**Comment by Loobinex** [comment]
yeah, I know there's more than enough there to kill me. Let the others heroes walk by, focus on the wizards because they are truly impossible.

**Comment by Danimal696** [comment]
i tried the new level, just two unguarded wizards destroyed my 15 man army. Im so nerfing them...

**Comment by Loobinex** [comment]
Yeah, I would go so far as claim levels with wizards in them are unplayable now. And I haven't found a level without them yet.

**Comment by hwoarangmy** [comment]
I've just had a look and they have same stats as other tier 3 units. Since they have magical attack, you should take care of using creatures that are not weak against it.

I will try to edit a level to add a few wizards and check how hard it is.

**Comment by Bertram25** [comment]
IMHO, needs a good check before release.

**Comment by Danimal696** [comment]
he shots too fast and gives lots of damage, two lv7 wizards ended my mixed 15 man army of rats/spiders/roaches/goblins/lizardman, and i had dropped all of them on their heads... my poor creeps didnt stand a chance...

**Comment by akien-mga** [comment]
Well, I think it OK that two lvl 7 wizards can defeat 10-12 tier 1-2 creatures (at least if there was more tier 1 than tier 2). But maybe they should be nerfed a bit still so that it's not such a huge defeat, you should have been able to kill one of them and still lose the battle IMO :D

**Comment by hwoarangmy** [comment]
I've had a look at the creature definition file. Indeed, there is a problem with wizard (the cooldown/warmup is 2/1 where is should be 3/2 like the other ranged creatures). And after a few tests, I confirm it makes a pretty huge difference.

I've tried to let 2 level 7 wizards with a pack of 3 roaches + 3 spiders + 3 rats + 2 lizard mans + 2 goblins.

With the original stats, they use to kill everything sometimes without loosing even 1 of them. With the supposed stats, they both die and there are more or less 5 remaining creatures.

I have also seen problems with Dragon (opposite as the wizard error) and kreatur (cooldown/warmup correct 3/2 but attack lower than its hero equivalent - the wizard)

I will fix that ASAP
@Loobinex well spoted

**Comment by Loobinex** [comment]
If the current problem is with the cooldown, it would be very interesting to see (after the fix) if there is any army composition of 15 or more creatures that can take down an army of 9 mid-level wizards.
It appears to me they do area of effect damage, and if a group can kill an army of any size in a single shot the cooldown becomes irrelevant.

**Comment by hwoarangmy** [comment]
No, they have no area effect. So far, only the boulder trap and explosion spell have area effect. They just shoot once per creature (but most are one shooted so it goes pretty fast). And, even if they aim at the same creature, the missile will hurt the first enemy creature on its path so, if there is a pack of creatures, they will always hit.

however, a cooldown from 3 to 2 means 33% more hits. And when shooting at one shooted creatures, it makes a huge difference...

Note that if you want to make some tries, you can have a look there:
https://github.com/OpenDungeons/OpenDungeons/blob/development/config/creatures.cfg#L2058

And change the 2 first data in the MissileLaunch skill from "2" and "1" to "3" and "2" or anything you wanna try

For the record, the cooldown (first number) is the number of turns the skill won't be usable after being used (but the creature might use another available skill or move).
The warmup (second number) is the number of turns the creature will not move nor do anything after using the skill (basically, the time needed to display the skill animation)

**Comment by akien-mga** [comment]
> however, a cooldown from 3 to 2 means 33% more hits. 

50% actually :p

**Comment by hwoarangmy** [comment]
> 50% actually :p

Yep, it's 33% less cooldown for 50% more hits ^^

**Comment by Loobinex** [comment]
I've played a level with the intended stats, and now I've managed to beat a level. Wizards are still strong, but not overly so.

I think ALL creatures do too much damage though, reducing damage across the board might not be a bad idea, but I think this issue can be considered fixed when the stats are updated.

**Comment by hwoarangmy** [comment]
ok, thanks for your feedback. IIRC, we set up HP/Damages so that in 1v1 level 1, 2 similar creatures will kill each other after 4 hits.

**Comment by Loobinex** [comment]
How many hits will it take for a lvl 1 rat to kill a lvl 10 pit demon?

**Comment by hwoarangmy** [comment]
Level1 Rat hits = 8 magical damages
Level 10 PitDemon magical defense = 4.4 + 9 \* 0.41 = 8.09

The rat cannot hit the pit demon at this levels.
Note that it would be true even earlier for Troll (good defense against magical). Against it, a level 1 rat will not hurt a level 3 Troll.

For leveling, we just stated that a Tier 1 level 1 unit should be able to hurt (not much) a Tier 4 level 1 good against its attack. But if it levels up, it won't hurt it at all...

**Comment by Loobinex** [comment]
Ok, that sounds ok. I thought I saw my pit lord get seriously hurt in 1 hit by a lvl 1 little green man, but I'm not sure, so I'll pay some attention to this in the future.
