### ISSUE TITLE
Creatures should use the closest room

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1172]
I frequently see creatures walk past a room they need to go to another room of the same time. Often they turn angry in the process. They should always use the closest room, especially when they walk through it.

See this screenshot from the 20160402 build and see I dropped all my creatures next to a treasure room on payday only for them to walk through it to another treasure room:
![bettergoldelsewhere](https://cloud.githubusercontent.com/assets/13840686/14764523/1864cdea-09bb-11e6-86a5-41e8aeaebe81.jpg)

**Comment by hwoarangmy** [comment]
Strange, they should go to the nearest. Is it systematic ?

**Comment by Loobinex** [comment]
Perhaps, looks totally random though like they just do whatever they want. When I see a pattern I'll let you know.

**Comment by Loobinex** [comment]
It almost looks like the go to the furthest room there is. On payday the creatures walk all the way to the treasure rooms I build closest to the gold I'm mining, ignoring the filled treasure rooms inside my dungeon. On the way there they walk straight through other filled treasure rooms.

**Comment by hwoarangmy** [comment]
Oops, I had a look and the treasury is chosen randomly. And it seems like you are not very lucky ;-)
I guess I never noticed because I usually don't build that many treasuries ^^
I will fix that for the release.
Nice catch.

**Comment by hwoarangmy** [comment]
@Loobinex I've checked the code and you are right, even for choosing job room, the creature chooses randomly between all usable rooms. I will fix that too
