### ISSUE TITLE
Voice acting

### ISSUE THREAD

**Issue by tomluchowski** [OpenDungeons/OpenDungeons#1193]
Who is currently voice acting the Keeper ? 
Current version is far from perfect; I don't like especially the synthesized "bassed" version of it.
When we have all sayings scripted we could take a professional actor for free ... ( however wird it sounds one can look for volunteers there ) : 
Before we start, could someone start scripting.txt file with ALL possible Keeper sayings ?
Mines are :

"Keeper , our treasury is shrinking, better do something , King of Germania refuses bail-out ! "
"You need more gold to do this !"
"Your mana is going to explode !"
"Another creature is leaving your dungeon..... Hey, the last monster turns the lights off ! " 

If everyone of us come up with a few funny phrases, then we could have an orginal script of our own. 

[http://voiceactingalliance.com/board/forum.php/]

**Comment by Danimal696** [comment]
Eugeneloza already did a long time ago, its just a matter of deciding exactly what we want and he will get to work, no need to look for anyone else. What do you dislike the most of the current voice version?

**Comment by eugeneloza** [comment]
link to #1165

**Comment by hwoarangmy** [comment]
Let's use the other thread for voice acting requests until it is closed
