### ISSUE TITLE
Portals: Add parameters to trigger interesting effects

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#12]
- [x] Permit wave of new creatures at once instead of only one at a time. Used for heroes teams.
- [x] Add support to specify the room(s) needed to spawn the creature and how big is the biggest of each room type must be. See also #11 
- Add support for new per faction parameters:
  - [x] `max-creature-for-first-portal`: Tells the max number of creature the first player can have with his first portal.
  - [x] `max-creature-for-next-portals`: When a player has got more than one portal, the next one will add X creature to the max number of creatures he can get.
  - [x] `max-overall-creature-limit.`: Set an absolute maximum limit a player can get, for scenario, engine or lag handling purpose.

**Comment by hwoarangmy** [comment]
This should be part of #239

**Comment by Bertram25** [comment]
I'm not sure. Those parameters are for specific instances of portals. Or maybe were you speaking of default values?

**Comment by hwoarangmy** [comment]
Yes, I'm talking of default values (do we really want them to be overridable ?)

**Comment by Bertram25** [comment]
> Yes, I'm talking of default values (do we really want them to be overridable ?)

Yes, or specially guarded portals would have no special values, for instance. And Hero spawning portals wouldn't be interesting to put in place, IMHO.

**Comment by Bertram25** [comment]
See also #323

**Comment by hwoarangmy** [comment]
oops, I had forgotten this. That's not exctly what I did to set max creatures. But I guess that this will only apply when we will be able to claim portals...

**Comment by Bertram25** [comment]
Also, while we're on all this, note that this will have to a per-portal config. Or a portal won't be more interesting than another for the given level.

**Comment by hwoarangmy** [comment]
I was having a look at older issues and now that we have a clearer vision of where OD is, what do we want to do about portals ?
- Are they all claimable ?
- What about hero portals ? Do we consider them as special portals or not (fighting and spawning) ? ATM, rooms can handle per type level parameters so we can choose to use the same portals or not. The choice is more about using the same mesh than hero faction portals.

**Comment by Bertram25** [comment]
@Danimal696 @oyvindln @akien-mga <-- For updates.

> I was having a look at older issues and now that we have a clearer vision of where OD is, what do we want to do about portals ?

It's good to start getting rid of oldies. :)

Let's speak about what a player would expect, IMO, then you'll tell me what you think about it:
- In multiplayer games (or standard singleplayer ones), I would expect that portals and temples meshes are different depending from the faction, even with similar roles. Just a visual nicety.

I would also expect to be able to claim a full opponent portal, or even better, why not be able to destroy it and be able to reconstruct my own there. (It would explain more the creatures spawned from the portal). After all, the mesh is a decoration around what matters: A portal to another realm. ;)
I even wondered whether we could make the Keepers portal whirl red and the hero one blue.
- I would also like to see "feral portals" or spawn points, that make feral enemies appear, and I have to destroy this "portal" to get free of the threat. This will be useful in multiplayer but also a very basic need for the campaign. This "portal" mesh (I guess a better name is needed) should be different so that the player knows it only has to be destroyed.

Those "portals" should have a specific spawn pool, be able to spawn creature only after some time and optionally in waves. And to make them interesting, we should first make sure to have creatures capable to dig dirt and seek opponents to kill.

All that may be two or three separate features, in fact. Maybe some of those things could be done differently, through scripting or another AI, like in #88 

WDYT?

**Comment by Danimal696** [comment]
Answers from the art(dark) side:
Hero portal -> Model located in OGA, needs texturing but OK, easy to do
Evil portal red vortex -> really easy to do
Feral portals -> Models located in OGA, only heroes though, no beasts ones(needs searching), needs texturing, big work since there are many

> portals and temples meshes are different depending from the faction

+1 , i would even say to make them different depending on biome, but lets stick to the basic for now

> I would also expect to be able to claim a full opponent portal, or even better, why not be able to destroy it and be able to reconstruct my own there

+1, hero portal could become evil portal and vice-verse, we could do it by making them going from solid(old conquered portal)->transparent->solid(new portal) by a fading off taking a few seconds. This makes me realize how basic current evil portal is, needs a way to show owner.

> we should first make sure to have creatures capable to dig dirt and seek opponents to kill.

You know thats easy, the bad is the models not being ready yet. Miner Dwarf for heroes and molewolves for monsters?

I would make feral portals only destructible by claiming all surrounding tiles just like normal portal, that way its more difficult to get rid of it.

**Comment by Bertram25** [comment]
> Feral portals -> Models located in OGA, only heroes though, no beasts ones(needs searching), needs texturing, big work since there are many

I would go for only one feral portal model for now. Adding other could be done later, lil by lil, IMO.
I really hope we can get better temple meshes as well for 0.6.0 but no pressure, we have time.

> +1, hero portal could become evil portal and vice-verse, we could do it by making them going from solid(old conquered portal)->transparent->solid(new portal) by a fading off taking a few seconds. This makes me realize how basic current evil portal is, needs a way to show owner.

About this, this could be done by workers automatically, with some mana + gold cost maybe?

> You know thats easy, the bad is the models not being ready yet. Miner Dwarf for heroes and molewolves for monsters?

The hero faction already has dwarf workers, btw.

> I would make feral portals only destructible by claiming all surrounding tiles just like normal portal, that way its more difficult to get rid of it.

Agreed.

**Comment by hwoarangmy** [comment]
ok. Lets summarize:
- Portals (all of them) cannot be attacked. They have to be claimed by kobolds.
- There are 2 types of portal. 1 - Normal: Associated with a seat (what we currently have, spawns creatures depending on certain conditions). 2 - Wave portal: spanws creatures per waves. The list of spawnable creatures have to be defined in the level as well as time between 2 waves.
- We should define a number of allowable creatures per seat (for example 10 - can be overriden for each seat). Then, for each portal, we can define the number of creatures it allows (for example 5 - mandatory for each portal). That means a player with 1 portal can have up to 15 creatures. If he manages to get control of another portal, he will be able to have 20. Note that it is possible to have more creatures than the maximum if you loose a portal when maxed.
- When a normal portal is claimed, it becomes of the claimer seat. When a wave portal is claimed, it is destroyed.
- Concerning claiming, do we want to claim  the tiles one after the other or only on 1 tile (like done in DK ?) Note that if we choose the first solution, we will need to have something visual to know which tile is claimed or not.

Concerning wave portals, I think they should define in the level map:
- several sets of creatures. They will randomly spawn
- Time between 2 waves
  It will be needed to be able to have stronger creatures with time. We can do that by defining conditions for wave spawning or by using AS.

WDYT ?

**Comment by Bertram25** [comment]
Looks good. :)

As for your questions:

> Concerning claiming, do we want to claim the tiles one after the other or only on 1 tile (like done in DK ?) Note that if we choose the first solution, we will need to have something visual to know which tile is claimed or not.

Since we will claim our first room since long, I'd rather have it claimed as a whole or not at all. It would look more logical IMHO, but:
That said, I'll happily take the solution which is the simplest technically between the two.

> - several sets of creatures. They will randomly spawn

I like the Wave portal name. :)
The only thing I'd like to point out is that in many single player and campaign levels, there isn't a endless spawning of enemy monsters, but rather a predetermined serie of waves.
Also, being endless or not, the waves shouldn't be random but rather starting small and raising in strength. EDIT: As you already pointed out, in fact. :)
Another question is: Do we want to support endless waves, predetermined ones or both? Do we want support for random waves as well as predetermined ones?

This issue is also starting to be big. I guess this will have to be done step by step.

**Comment by Bertram25** [comment]
> Time between 2 waves It will be needed to be able to have stronger creatures with time. We can do that by defining conditions for wave spawning or by using AS.

Yeah, I do also wonder whether a lot of this couldn't be scripted instead. Note also that in campaigns, we'll likely want to spawn enemies out of nowhere, which is basically the same, minus testing a wave portal existence.
Can't tell much until we have better scripting support, though.

**Comment by hwoarangmy** [comment]
Yep, that's exactly what I wanted to define: what do we want to be scriptable and what do we want to be defined in the level.
In reality, we could even have everything about spawning (including spawn list) scripted but it may be a bit difficult for someone who just wants to do a single map to have to mess with AS (even if we could have the editor generate automatically corresponding scripts based on some visual editor input).
But we have to decide something ^^

**Comment by hwoarangmy** [comment]
> Since we will claim our first room since long, I'd rather have it claimed as a whole or not at all. It would look more logical

That's also what I think and is probably easier so I guess we should go for that

**Comment by Bertram25** [comment]
> In reality, we could even have everything about spawning (including spawn list) scripted but it may be a bit difficult for someone who just wants to do a single map to have to mess with AS (even if we could have the editor generate automatically corresponding scripts based on some visual editor input).
> But we have to decide something ^^

Arf, you're right. Let's have this as an hardcoded feature, at least for now. This is so much a basic need for level events anyway.
Later on, we'll emulate more advanced behaviour through scripting.

**Comment by hwoarangmy** [comment]
I've done the claiming portal + bonus max creature number per owned portals. Concerning portal waves, I propose that it handles itself to mark tiles between itself and the closest enemy dungeon and, when it is reachable, it would cast a "go to war" spell.

WDYT?

**Comment by Bertram25** [comment]
> I've done the claiming portal + bonus max creature number per owned portals. Concerning portal waves, I propose that it handles itself to mark tiles between itself and the closest enemy dungeon and, when it is reachable, it would cast a "go to war" spell.

A portal AI, sooo evil... I love it! You would need fighter capable to dig, for a maximal effect, IMHO. But I like the use of the existing pieces. :)

**Comment by hwoarangmy** [comment]
> You would need fighter capable to dig

Well, that's up to whom defines the waves ^^ After all, you may also want to spawn fighters non worker in a corridor to one's dungeon

**Comment by Bertram25** [comment]
@hwoarangmy Btw, need an icon to be able to add waveportals in the editor?
