### ISSUE TITLE
Culling should not be processed when camera doesn't move

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#1215]
Following the PR #1198 and according to discussion in the PR.

@tomluchowski wanna take this one ?

**Comment by tomluchowski** [comment]
Err ... what we discussed was to slow down the refresh rate of minimap camera.
Are you sure you want to disable culling totally , when the camera is not moving ? First it's only one simple and short loop , second I don't know if we would be able to start culling properly after it is stopped : we need some frames to see that the camera is moving ; at the same time at those frames our algorithm should already process  show and hide tiles , you dig what I mean ? Even one frame left might make a diffrence and introduce blunder. Could you answer my forum posts ? All those threads which end up with paul424 as last post.

**Comment by hwoarangmy** [comment]
> Are you sure you want to disable culling totally , when the camera is not moving ?

No, I'm just talking about not computing culling if the camera did not move. I'm not talking about stopping/starting.

However, as I told you, I'm working on some code to allow the player to choose between the old and the camera minimap. I've made quick tries and, as expected, we have a crash when using the old minimap.
I think I will have to split culling between minimap and main map to avoid current dependencies.
I might also have a look at refreshing culling while I'm at it unless you say you really want to take this

**Comment by tomluchowski** [comment]
Maybe I could make it as a parameter whether to do the culling only for main camera or both of them ?
Could you give me access to the branch with that minimap prototype ?

**Comment by hwoarangmy** [comment]
I've already tried and it seems splitting the culling is not that hard. BTW, I've played with the zoom value to see how it behaves and it seems to work pretty well. Is the algorithm from you ?

**Comment by tomluchowski** [comment]
Yes.
