### ISSUE TITLE
Dropping the unused AngelScript?

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#1218]
Hi there,

We still have a quite old version of AngelScript bundled in our source tree, and lots of commented out references to AS in the CMake buildsystem, as well as a couple scripts in `scripts/` and a wrapper in `source/scripting/`.

I'd propose to just dump it, as most likely this code does not work anymore with the current branch and when we want to implement scripting, we'll want to start with something recent and not with old code IMO. And I think most of us tend more towards Lua than AS, though the discussion is still open.

WDYT? If you agree I'll dump all references to AS.

**Comment by hwoarangmy** [comment]
Back when we disabled AS (IIRC, @oyvindln did it), we decided to comment the use and makefile scripts to remember how to integrate it.
However, I don't know if we will really use scripting at all one day and if we will use AS (rather than LUA or whatever).

I guess we should first decide if we use a scripting tool and what for ?

**Comment by Bertram25** [comment]
Hey there, (Yes, I'm still around, even if pretty much a ghost those times)
I do think some scripting will be very useful, if only for event based maps. I'm starting to have a bit of experience in Lua, and I can tell it made my day several times (even without the use of luabind).

So I agree we can remove the as source code, and that we can discuss again how to add event in maps and so on later, but I do think that adding scripting support in maps would be awesome.

**Comment by hwoarangmy** [comment]
ok for removing AS code and to move to LUA (all the open source games I know of use LUA so I guess it is not a bad choice).
But it would be nice to open an issue and to list what we want to allow from the scripts to make sure at least the most basic features are available.
Note that the script will be played on server side.

As a first thought, I will add:
- Allow to ask the client to display some text in a modal popup (the client should send a message back to the server when the popup is closed)
- Allow to listen to tile events such as "seat that got vision on the tile", "Creature walked on the tile"
- Allow to register a callback for time based events (something equivalent to the update animations for Ogre)
- Allow to play with the camera
- Allow to add camera restrictions

We should also decide if we want to move some stuff declared on the level file to scripting. For example, we can move goals (which are not very well supported as for now anyway), maybe seats and tiles, creatures, ...

**Comment by akien-mga** [comment]
Let's maybe fork the discussion about the scope of scripting to another issue, so that I can close this one when removing AS?

**Comment by hwoarangmy** [comment]
ok

**Comment by akien-mga** [comment]
Will handle this asap.
