### ISSUE TITLE
Crash when double-click on a creature (and maybe drop it.)

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#122]
Seems like the pickup message is sent twice. On server side, we should do nothing if asked to pickup a creature already in hand.

**Comment by Bertram25** [comment]
Nice catch!

**Comment by akien-mga** [comment]
I did not try but if the logic is implemented in a similar way, I guess there would also be a crash when you have a creature in hand and you double-click to drop it.

**Comment by hwoarangmy** [comment]
Yes, you may be right. In any case, I will add some checks for both cases.

**Comment by Bertram25** [comment]
I confirm the bug. It happened to me several times in game. I guess this is when click several times within a turn on the client side.
