### ISSUE TITLE
Money amount doesn't fit in GUI

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1223]
When you have a few treasure rooms, the gold amount you have might not fit in the GUI, see the screenshots. As the font is not fixed-width, it depends on the exact number. Even with low amounts with 'wide' numbers it won't fit, sometimes the left most figure completely disappears.

When you get over 100k Gold, it surely no longer fits.

![moneymoneymoney](https://cloud.githubusercontent.com/assets/13840686/16541661/1091c172-4089-11e6-86e6-f41b70777855.png)
![itssofunny](https://cloud.githubusercontent.com/assets/13840686/16541662/1133127a-4089-11e6-9da5-77ac054d4a4f.png)

**Comment by hwoarangmy** [comment]
I guess 1 more digit should be enough

**Comment by Loobinex** [comment]
No, you need two. Now the problem already occurs in the 10k-99k range, with a digit more you'll run into it above 100k gold.

**Comment by akien-mga** [comment]
I'll fix that asap.
