### ISSUE TITLE
Creatures unhappy on payday

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1224]
I played a game today (git20160624) and on payday suddenly a lot of my creatures became unhappy. I had plenty of money and a filled treasure room right were my creatures were. This should not happen.
See the screenshot, or try the replay.

I've had this happen before(long time ago I last played, don't remember how exactly) My guess is that I missed the previous payday and creatures just went along with it, then did not get gold once I got some.

What should happen is that creatures will try to get gold every few minutes when they are unpaid, and become unhappy each time they arrive at an empty treasure room.(not on payday) This way as a player you'll lose efficiency when you fail to get enough gold, but don't run into the situation mentioned above where creatures turn angry for no good reason.

[replay_20160702_173059.zip](https://github.com/OpenDungeons/OpenDungeons/files/344725/replay_20160702_173059.zip)
![pleasebehappy](https://cloud.githubusercontent.com/assets/13840686/16542424/18d811fa-40a8-11e6-9725-447c6cf6f27a.jpg)

**Comment by hwoarangmy** [comment]
The logic for angriness concerning pay day is that the creature becomes negatively affected when its fee is more than 1 pay day. So, as you guessed, that means that your creatures could not get their fee on the previous pay day (unless there is a bug).

From the games I've played, I agree there is a problem. When the dungeon becomes a bit big, the creatures are unable to go the the treasury room in time and get angry very easily (which is even worth when there are ennemies and you drop them to help). We should think about a way to fix that.

**Comment by Loobinex** [comment]
Like I said, I think the solution revolves around getting creatures to get their gold in between paydays as well if they missed a payday.

**Comment by hwoarangmy** [comment]
> I think the solution revolves around getting creatures to get their gold in between paydays as well if they missed a payday.

That's what they do. But if the dungeon is big, they will probably not reach any treasury room before you pick them up if there is a fight.

**Comment by Loobinex** [comment]
That was not the behavior in the game I played. As you can see on the screenshot, there was a treasure room right next to the training room and as very little has happened on this map until this point, I doubt I picked up all these creatures.
I had a compact and small dungeon.

**Comment by hwoarangmy** [comment]
That's strange. I will have a look at the replay. BTW, when you post a replay please also post the log file as the replay only shows what happens on client side but we don't see what happened on server side (even if in this case, the log file will probably not be very verbose)

**Comment by Loobinex** [comment]
Will do. Here's the one that matches this replay:
[opendungeons.log.zip](https://github.com/OpenDungeons/OpenDungeons/files/346482/opendungeons.log.zip)

**Comment by hwoarangmy** [comment]
I've had a look. The only issue I've seen is that creatures working in a room do not stop working even if their fee > 0. Each time they have nothing to do, they have a 50% chance of looking for their fee.

I guess you were not lucky with the PitDemon and it just choose to work somewhere instead of getting its fee (which took many time). And then, it got angry at the next payday.

To fix that, I will increase the rate of looking for gold when idle and make creature stop working for their fee.

**Comment by Loobinex** [comment]
As you see on the screenshot, it's not just the pit demon but a whole lot of creatures that instantly turn angry. But when you've implemented this change I'll see if the same problematic behavior still occurs or not.

**Comment by hwoarangmy** [comment]
The thing is that 50% chances is pretty high and most of the times, creatures will choose to work somewhere if they don't go for their fee.
And if they are awake and not hungry, they can spend some time there (I've checked the code and they don't stop working for getting paid).

Moreover, if the creature is already working, it won't stop for the payday. Then, once it is hungry/tired, it will go to eat/sleep (again, it won't check for its fee). That can take some time. And, for high level creatures, not being paid for 1 pay day is enough to get them angry.
In any case, the simplest is to make creatures look more often for pay day and see if the bug if fixed or not. If not, I will add some more logging to understand what is happening.

**Comment by hwoarangmy** [comment]
@Loobinex I've uploaded binaries with the fixes. Could you please try if you reproduce the bug ?

**Comment by Loobinex** [comment]
Sure.

**Comment by Loobinex** [comment]
@hwoarangmy: I can confirm this issue fixed.

**Comment by hwoarangmy** [comment]
Thanks for the confirmation ^^
