### ISSUE TITLE
Gems are mined too quickly

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1225]
When you have access to gems, you'll get gold far too quickly. Workers seem to mine gems as quickly as they mine gold, with an additional benefit that you can build your treasure room really close. Even a single gem face can support an entire dungeon very easily, allowing you to do whatever you want.

This is completely unbalanced: Gold should always provide a faster income than gems, to motivate players to still go for gold on maps that have both.
A mapmaker should also be able to have a choice on how much steady income he provides the player by tweaking the number of gem faces available - with 1 being nowhere near enough to support an army of 15 creatures.

**Comment by hwoarangmy** [comment]
Yep, I had alsio seen that. With only 1 gem tile you have no need to anything else. As you say, we should greatly decrease the gold rate so that it is better to go for gold rather than digging 1 gem tile.

As a side note, the number of available faces doesn't change anything. Only 2 workers can work on the same tile no matter the faces.

**Comment by Loobinex** [comment]
Then that should also change! I assume not just for gems, but for any or all blocks.
If x amount of workers can work it, it should be per face, not per block. For a player it makes no sense if you have a gem block with 4 available faces and you can't get your workers to mine them.

**Comment by hwoarangmy** [comment]
Yes but it's easier to say than to do ;-)
Although feasible if someone wants to take it.

**Comment by hwoarangmy** [comment]
I've had a look at this one and their is a bug. The gem mining rate is the same as gold. I will fix that.
