### ISSUE TITLE
Gem blocks (and others) should be mined from all sides

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1227]
This issue is a split from issue #1225, where hwoarangmy shares that gems blocks are only mined by 2 workers no matter how many faces are available.

This is not the proper behavior. The game should limit how many workers can work each side of a block, not limit the workers per block in general.
As a result a gem block where workers can reach 4 sides should provide 4 times the gold compared to a block where workers can only reach one side. It should also make digging dirt look a bit more natural.

**Comment by hwoarangmy** [comment]
While looking at the gem/gold issue, I will have a look at this one too
