### ISSUE TITLE
Unclear where/what/who is under the effect of CTA spell

### ISSUE THREAD

**Issue by Loobinex** [OpenDungeons/OpenDungeons#1236]
The player does not get enough feedback when using the Call to Arms spell. Using it is currently trial and error.

When I cast it and when it's active I do not see the range. Furthermore creatures do not show if they are effected either.
I think it would be very helpful if the area where the spell can be heard is visualized and that a mood icon is introduced for creatures affected.

**Comment by akien-mga** [comment]
More than yet another mood icon, I think it might be nice to have a visual effect like a red glow on affected creatures, like they were subject to a kind of "frenzy" spell.

**Comment by hwoarangmy** [comment]
ATM, all creatures that can reach the call to arm and that are not busy should go. But if the spell is cast far from the creatures, it can be tricky to know what's going on. I guess something to see affected creatures would not be a waste.
