### ISSUE TITLE
libpcre.so.1 is missing in Linux 64-bit binary package

### ISSUE THREAD

**Issue by roman-yagodin** [OpenDungeons/OpenDungeons#1256]
So the subject, `libpcre.so.1` library is missing in Linux 64-bit binary package for v0.7.1 release. Adding one from v0.7.0 fixed the issue.

**Comment by akien-mga** [comment]
Thanks, I'll have a look.

**Comment by hwoarangmy** [comment]
@akien-mga BTW, is there a reason why you don't build 32 bit versions ?
It would work on more systems than 64 bit, no ?

**Comment by akien-mga** [comment]
There aren't many 32-bit Linux users, it's a privilege left to the Windows ecosystem to stay so behind technology :p More seriously, it's just a bit more work and so far nobody complained, so I guess all users were happy with the 64-bit binaries. If there's demand, I'll do 32-bit binaries too.

**Comment by hwoarangmy** [comment]
I'm asking because I've been asked on ufo ai forum:
http://ufoai.org/forum/index.php/topic,9071.0.html

Since you are the one baking linux binaries, it is your call to decide if you want to build 32 bit binaries or not.

**Comment by akien-mga** [comment]
I uploaded an hopefully fixed tarball, can you test? http://download.tuxfamily.org/opendungeons/0.7/OpenDungeons-0.7.1-Linux64.tar.bz2

**Comment by roman-yagodin** [comment]
Unpacked and running OK.

**Comment by akien-mga** [comment]
Awesome :)
