### ISSUE TITLE
Traps are invisible after load

### ISSUE THREAD

**Issue by abenkovskii** [OpenDungeons/OpenDungeons#1265]
Version: 0.7.1
Steps to reproduce:
1. Start skirmish
2. Research, designate and build traps
3. Save
4. Close the game, reboot computer (not sure if this is necessary, but that's what I did)
5. Load skirmish

Expected:
Traps are visible
Got:
Traps, both the ones already built and the ones just designated, but not built are invisible, but appear to be there (can't designate other traps on this squares).
Edit: Doors stay visible despite being "traps" too.

**Comment by hwoarangmy** [comment]
Is it systematic ? If not, could you please upload the log file and the saved game that shows this bug ?
I will try that when I can.

**Comment by abenkovskii** [comment]
It it happens often, though not always. Where to find the log file? I only found OpenDungeons/build/Ogre.log. Is this the one?

**Comment by abenkovskii** [comment]
Sorry can't find the saves. Where are they stored on linux?

**Comment by abenkovskii** [comment]
NVM I found them in ~/.local/share/opendungeons

**Comment by abenkovskii** [comment]
Here is a save file where it happened. 
[2016-12-01_175801-SK-DuelToDeath.level.zip](https://github.com/OpenDungeons/OpenDungeons/files/625333/2016-12-01_175801-SK-DuelToDeath.level.zip)
Here is a replay showing a worker carrying a trap to a seemingly empty square
[replay_20161201_180200.odr.zip](https://github.com/OpenDungeons/OpenDungeons/files/625336/replay_20161201_180200.odr.zip)
Here are the log files I found. One of them must be the one.
[CEGUI.log.txt](https://github.com/OpenDungeons/OpenDungeons/files/625140/CEGUI.log.txt)
[opendungeons.log.txt](https://github.com/OpenDungeons/OpenDungeons/files/625199/opendungeons.log.txt)
[opendungeons.log.1.txt](https://github.com/OpenDungeons/OpenDungeons/files/625141/opendungeons.log.1.txt)
[opendungeons.log.2.txt](https://github.com/OpenDungeons/OpenDungeons/files/625139/opendungeons.log.2.txt)
[opendungeons.log.3.txt.zip](https://github.com/OpenDungeons/OpenDungeons/files/625267/opendungeons.log.3.txt.zip)

**Comment by hwoarangmy** [comment]
It seems traps are not displayed, even in standard games. A big bug we missed ^^
