### ISSUE TITLE
Doors don't work

### ISSUE THREAD

**Issue by abenkovskii** [OpenDungeons/OpenDungeons#1266]
Version: 0.7.1
Enemies walk through closed doors.
Alternatively:
Doors destroyed by dragons and nature monsters look like they are still there when in fact they are "disarmed".

**Comment by oyvindln** [comment]
This only happens with some types of monsters?

**Comment by abenkovskii** [comment]
@oyvindln Do doors only "work" on allays? Because all enemies seam to be able to pass through them.

**Comment by oyvindln** [comment]
No they're supposed to work on all creatures, so if enemies can pass through them that's a bug.

**Comment by hwoarangmy** [comment]
It is strange for enemy creatures to go through doors. They should attack it. My guess is that the door is only placed, not built (no door trap has been brought from the workhop).
If it is not the case, could you upload a replay showing this bug ?

**Comment by abenkovskii** [comment]
I definitely saw a worker carry a door to the designated location and it definitely was closed. I even checked: allies weren't able to go through it. Sadly, I didn't save the replay (very foolish of me). I'll try playing it again.

**Comment by abenkovskii** [comment]
Here is the replay. I didn't watch it, but the door definitely was built and it looked intact when enemies were walking right through it.
[replay_20161201_174327.odr.zip](https://github.com/OpenDungeons/OpenDungeons/files/625302/replay_20161201_174327.odr.zip)
Here are the log files I found. One of them must be the one.
[CEGUI.log.txt](https://github.com/OpenDungeons/OpenDungeons/files/625140/CEGUI.log.txt)
[opendungeons.log.txt](https://github.com/OpenDungeons/OpenDungeons/files/625199/opendungeons.log.txt)
[opendungeons.log.1.txt](https://github.com/OpenDungeons/OpenDungeons/files/625141/opendungeons.log.1.txt)
[opendungeons.log.2.txt](https://github.com/OpenDungeons/OpenDungeons/files/625139/opendungeons.log.2.txt)
[opendungeons.log.3.txt.zip](https://github.com/OpenDungeons/OpenDungeons/files/625267/opendungeons.log.3.txt.zip)

**Comment by hwoarangmy** [comment]
Thanks for the report. If you want to report another bug, opendungeons.log is the last game log. Each time you launch the game, log files are renamed in case you accidentally launch another game before getting the log (that's the files .log.1, .log.2, ...).
Back to the topic, I've had a quick look and, indeed, there is a problem. It seems like rogue creatures ignore doors (unlike your creatures or enemy creatures)

**Comment by abenkovskii** [comment]
Are heroes from the "Falling keeper" considered rogue? They have their own player (blue) assigned to them and they can go rogue (white) sometimes. I think I saw them pass through doors too.

**Comment by hwoarangmy** [comment]
Then, the bug is worst than expected.

**Comment by hwoarangmy** [comment]
I've had a look and it is indeed related to trap vision management (like the other bug you spotted on traps not being visible) #1265 
Thanks for reporting, I will fix it ASAP
