### ISSUE TITLE
added the Private variable names section in the Naming, comments and documentation

### ISSUE THREAD

**Issue by Hokbras** [OpenDungeons/OpenDungeons#1267]
Hi,

In the code guidelines, I added the "Private variable names" section in the "Naming, comments and documentation". [here](https://github.com/OpenDungeons/OpenDungeons/wiki/Code-Guidelines/_compare/a33831b6cf8ec8bfc9f6f478161989bf40a53bf0...a46416a935154dbf927047d45f7cfc9f445fcb59)

Hope it's good for you ;-)

**Comment by hwoarangmy** [comment]
Looks good, thanks
