### ISSUE TITLE
Update bundled dependencies

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#132]
I've seen that we bundle angelscript 2.23.0 [0], when the latest upstream version is 2.29.1 [5]. Maybe we could update the bundled files to the newer version, and it might fix #40 if done with proper file encoding and line endings.

We could take the opportunity to update all bundled dependencies, i.e.:
- [x] **dropped** tinygettext old version (history doesn't go before 2011 on our copy) -> recent commits in August 2014 after 3 years of silence [1]. Do we actually use tinygettext btw?
- [x] **To drop in favour of boost::filesystem** dirent old version from March 2011 -> there seems to be a version 1.20.1 from April 2014 if I found the correct upstream [2]
- [x] **To drop in favour of boost::thread or std::thread** pthreads-win32 2.8.0 -> 2.9.1 or newer [3]
- [x] **To drop** tinyxml2 pre-release development snapshot from Sep 2012 -> 2.1.0 or newer [4]
- [x] angelscript 2.23.0 -> 2.29.1 or newer [5] - Handled in #268 

[0] https://github.com/OpenDungeons/OpenDungeons/tree/development/dependencies/angelscript/add_on/autowrapper/generator

[1] https://github.com/Grumbel/tinygettext
[2] http://www.softagalleria.net/dirent.php
[3] http://sourceforge.net/projects/pthreads4w/
[4] https://github.com/leethomason/tinyxml2
[5] http://www.angelcode.com/angelscript/

**Comment by hwoarangmy** [comment]
There is also another issue related #2

**Comment by Bertram25** [comment]
This is part of #24

**Comment by Bertram25** [comment]
Please, drop tinyxml and tinygettext instead if possible. :) We aren't using them atm.
Plus, we might want more complete solution when we add support for either.

**Comment by akien-mga** [comment]
@Bertram25, @hwoarangmy, @tomluchowski: Does any of you know whether tinyxml and tinygettext are used at all in the current code base? If not, let's nuke them :-)

**Comment by Bertram25** [comment]
Neither of them are used, you can drop them. If there are ghost include, feel free to remove. :)

**Comment by oyvindln** [comment]
dirent.h is really not needed since we are using boost::filesystem, which is much simpler, through Ogre anyway. I can have a look at doing that once my previous changes are merged.

**Comment by oyvindln** [comment]
Pthreads can also be dropped, we should use boost or std::thread instead.

**Comment by Bertram25** [comment]
for the record, I'm also in favour of dropping pthreads if using boost replacement isn't hurting. :)
EDIT: Replace dirent by boost::filesystem is a good thing IMO, too.

**Comment by akien-mga** [comment]
Dirent dropped with #186, updated the first comment.

**Comment by akien-mga** [comment]
Only pthreads-win32 is left to be dropped and replaced by boost.

**Comment by Bertram25** [comment]
pthreads and other thread reference were dropped as we're now using sf::Thread() for the server part.
This issue can be closed.
