### ISSUE TITLE
How to run game?!??

### ISSUE THREAD

**Issue by MegaBaconator** [OpenDungeons/OpenDungeons#1325]
I downloaded the release files, and none of them contain an exe file or a clear way to start the game. How do you run the game?
None of the tutorials detail this.

I'm on a Windows 11.

**Comment by akien-mga** [comment]
You should download the binary release from the website, here: http://opendungeons.github.io/downloads.html

On GitHub it's only the source code.

I'll edit the release on GitHub to point at the binary downloads too.
