### ISSUE TITLE
Some dirt wall tiles get a golden colouring

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#133]
It's been around for some time already, but now that @hwoarangmy has tackled bug #51, fixing this bug could be a nice further enhancement before the 0.4.9 release.

See the screenshot:
![od-bug-golden-dirt-walls](https://cloud.githubusercontent.com/assets/4701338/4220434/5e762d1a-3901-11e4-8b90-4118aeebf60d.jpg)

Some dirt wall tiles get a funny colouring. From the screenshot, it seems to be:
- Around a newly claimed wall (though not always)
- At the ends of a wall with a width of 1 tile

**Comment by Bertram25** [comment]
This comes from the appliance of a normal on the first instance of dirt wall. I'll handle this.

**Comment by akien-mga** [comment]
Fix confirmed, thanks :-)
