### ISSUE TITLE
Create an equipment catalog support

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#138]
This file will tell what mesh file to use (from the entity catalog file), the given attack/defense and range given by the equipment name.

Then, other files will be able to reference only the equipment name and get the rest through that.
The entity catalog file is a prerequisite to this issue: #60

**Comment by hwoarangmy** [comment]
BTW, how many files are you going to create ?
I've been thinking that when we will have a good architecture for creature behaviour (needed active spots / gold / friendly creatures / unfriendly creatures ...), it may be pretty messy if everything is in one file...

**Comment by Bertram25** [comment]
> it may be pretty messy if everything is in one file...

True, I understand your concern and I have the same one, but this is something for another time, I guess.

For now, I'd like to add what's strictly necessary:
An entity catalog file, which will greatly help to configure models by calling only the model reference name, and getting all what's linked to models through that.
And a equipment file described above. Those will be reference files and thus placed into the config/ folder.

As for the creature's mood, spawn conditions, and so on. We have yet to see how best to describe it in a file or several ones.
My first semi-educated guess is that creatures stats will later have to be described between specific tags and no more on the same line, like this for instance:

```
[Creatures]
...
[Creature]
[Stats]
hpPerLevel 12
maxHP 100
...
[/Stats]
[/Creature]
...
[/Creatures]
```

Once we have this format, we can more easily add other tags with other info. We could even think about splitting those data per creature, or not. It's more a matter of point of view, IMHO.

In level files, we will have to gather the needed data so that a level can be loaded/saved in a given state. Will it be different? I guess so, but how, I don't know yet. :)

**Comment by hwoarangmy** [comment]
If you want, I can do the weapon configuration file so you don't have to do all the configuration files by yourself...

**Comment by Bertram25** [comment]
> If you want, I can do the weapon configuration file so you don't have to do all the configuration files by yourself...

I'd be glad :) Yet I wonder if it wouldn't be best to first create the config manager and link the file to it, so we can access the values from anywhere in the code.
Wanna put your claws on that one?

**Comment by Bertram25** [comment]
Unassigned myself. I'll only keep assignment where I'm actual working on stuff. It's saner IMHO.

**Comment by hwoarangmy** [comment]
> Yet I wonder if it wouldn't be best to first create the config manager and link the file to it, so we can access the values from anywhere in the code.
> Wanna put your claws on that one?

Ok, I will have a look.

**Comment by Danimal696** [comment]
tell once this is done, i keep a really nice weapon cache on check just for this.

**Comment by hwoarangmy** [comment]
I will try to do that tonight or tomorrow.
@Bertram25 I've thought to add Weapon tags to define usable weapons. What do you think about adding that into config/creatures.cfg ?
Or shall I use another file ?

**Comment by Bertram25** [comment]
> @Bertram25 I've thought to add Weapon tags to define usable weapons.

Something like ?

```
[Creature]
    [Equipment]
    RoundShield
    Sabber
    LongSword
    [/Equipment]
[/Creature]
```

**Comment by hwoarangmy** [comment]
> Something like ?

This will be good when the forge will be ready. For now, I wasn't planning on implementing that already.

I was talking about defining weapons :
[Creatures]
...
[/Creatures]
[Weapons]
[Weapon]
Name Longsword
Damage 10
Defense 0
Range 1
[/Weapon]
...
[/Weapons]

**Comment by Bertram25** [comment]
Ah in that case, I'd rather have a true equipment file, something like:
config/equipment.cfg:

[Equipment]
name
mesh
physicaldamage
magicaldamage
physicalDefense
magicalDefense
range
[/Equipment]

Plus, weapons doesn't fit since it's also listing protections. I'd propose accessories instead.

**Comment by Bertram25** [comment]
You can add a new loader function in the mapLoader if you don't feel like creating the configuration manager now.

**Comment by hwoarangmy** [comment]
> Ah in that case, I'd rather have a true equipment file

Ok

> You can add a new loader function in the mapLoader if you don't feel like creating the configuration manager now.

I had forgotten about the configuration manager :$
As you have worked on most configuration files, how do you see that ?
So far, configuration files are embedded into the level file. Shall we remove them from there ? How do you think the manager should be called from within code ?

**Comment by hwoarangmy** [comment]
@Bertram25 Could you tell me your point of view about this ?
So far, what I'm planning to do:
- Remove the class + equipment files from the level files

Then, each time a level is launched
- Load config/creatures.cfg + config/equipment.cfg
- Check for tags in the config file (same format as in the config files) to check if the default creatures/equipments shall be overriden if so, override them.

Is it ok for you ?

**Comment by akien-mga** [comment]
+1

**Comment by Bertram25** [comment]
> Remove the class + equipment files from the level files

class + equipment files ?? I can't get it. Are you planning to remove the creature className and equipment parameters from level creatures definition? Or are you speaking about removing the config/creatures.cfg link given in the level files?

> Then, each time a level is launched
> ...
> Check for tags in the config file (same format as in the config files) to check if the default creatures/equipments shall be overriden if so, override them.

Sorry, I'm not sure I fully get it. I'll need a minimal example. Could you provide one? :)

**Comment by akien-mga** [comment]
From what I understood (at least of the overall logic, not the practical implementation):
- Creatures are defined in config/creatures.cfg with some default equipment, which is defined in config/equipment.cfg
- The level contains lists of creatures without having to redefine their characteristics + equipment. Tags can be used in the level files to override default values and further customise creatures (level, equipment, etc.), thus also enabling to save the game state in a level file.

**Comment by Bertram25** [comment]
> The level contains lists of creatures without having to redefine their characteristics + equipment. Tags can be used in the level files to override default values and further customise creatures (level, equipment, etc.), thus also enabling to save the game state in a level file.

AFAIK, level creatures necessary stats are all stored in the level file now and the already stored level parameter makes it possible to compute the rest. (was #252)
If we wants to add other growth values for one creature, we should define a brand new creature class, even one sharing its model, but not store something like 30 parameters more per overridden creatures in the level file.
I do not think a creature should be that customizable, other than maybe using status effects, but IMHO, that's not for now.
Maybe @hwoarangmy  was speaking about upgrading the level creature's format to use lines as in config files?

> Creatures are defined in config/creatures.cfg with some default equipment, which is defined in config/equipment.cfg

Yeah, if think that's also what @hwoarangmy meant, but let's wait for his data example. :)

**Comment by hwoarangmy** [comment]
Yes, that's exactly what @akien-mga said :
In the level file, there will no more be the path to the config file because it will be automatically loaded (before the level).
Then, during level parsing, if a parameter is overriden, it will be used. For example :
config/creatures.cfg

```
[CreatureDefinitions]
[Creature]
Name Wyvern
[Stats]
CreatureJob Fighter
MeshName Wyvern.mesh
...
MinHP 2
...
[/Stats]
...
[/Creature]
[/CreatureDefinitions]
```

And in the level file (optional) :

```
[CreatureDefinitions]
[Creature]
Name Wyvern
[Stats]
MinHP 5
[/Stats]
[/Creature]
[/CreatureDefinitions]
```

In this case, all the default Wyvern parameters will be used except MinHP that will be set to 5

**Comment by hwoarangmy** [comment]
> I do not think a creature should be that customizable, other than maybe using status effects, but IMHO, that's not for now.

Well, I'm not against that (it is simpler) but if so, why having added the config file into the level file ? I did that to try to stick to your code.

**Comment by Bertram25** [comment]
> Well, I'm not against that (it is simpler) but if so, why having added the config file into the level file ? I did that to try to stick to your code.

Eh eh. In my defense, the creatures.cfg link was first here to permit easier modding of creatures class per models at the time. In practice, I do also think it's not relevant to do it that way anymore, especially as more config is appearing, whatever the files they are in. :)

The fact that overridden parameters are optional per level creature is cool, though. Meaning that you only describe what you change and not everything.

As for status effects, we can later add that as an optional level creature stats parameters. We're not there, though. :)

I'm ok with the concept but not sure of the tag names chosen in the level file, how do plan to declare the regular and mandatory parameters for level files, such as level, currentXP, currentHP, position, ... ?

**Comment by Bertram25** [comment]
Btw, I missed that one:

> As you have worked on most configuration files, how do you see that ?
> So far, configuration files are embedded into the level file. Shall we remove them from there ? How do you think the manager should be called from within code ?

As discussed above, you're right, config files links should be removed from level files. We'll deal with true modding support as a whole, by (re)loading a different set of config files if needed.

I was at the very first thinking about a singleton, or a component of a manager such as the resource manager maybe, and invoked in the corresponding way?
Something like?
ConfigManager::getSingleton().getEquipmentConfig()
or 
ConfigManager& config = ResourceManager::getSingleton().getConfigManager();
equip = config.getEquipmentConfig();
equip.get...

Depending on the use case, we may have some shortcuts, such as:
config.getDefaultEquipmentForCreature(x);

It's all wild examples but hopefully will give you ideas or things to react against. ;)

**Comment by hwoarangmy** [comment]
> Eh eh. In my defense, the creatures.cfg link was first here to permit easier modding of creatures class per models at the time

No need for defense, you are not being attacked ;-)
I was just saying that because I saw the config file there, I thought you were planning on allowing to customize it. I want this reason to be clear so that if it is a misunderstood, I don't end up allowing this customization for a wrong reason. If we decide to do it, I will do it. But don't think it is my wish and that I would be offended if you are against it.

We should decide if we allow this customization or not. So far, Spawning pool allows to decide which creature can spawn per level file.

We should define what we want and then choose the best solution. IMHO, here is what we might want to customize per level file (please feel free to add/discuss what will be there) :
- Allowing a creature to spawn or not (done with spawning pool)
- Add unique creatures with different stats (A stronger Troll for example)
- Set a maximum level per creature class
- Disable a room (to make it non constructible even if the requirements are made)
- Disable a trap
- Disable a weapon
- Disable a search
- Disable a spell

**Comment by Bertram25** [comment]
> No need for defense, you are not being attacked ;-)

Aww, /me removes a reason to crush @hwoarangmy on the next lan in his list.

> But don't think it is my wish and that I would be offended if you are against it.

I must say that I didn't think about it the way you did, but IMHO, your solution is better, as permitting much more twisted things :>, especially for single-player maps.
On the other hand, it may make map saving more difficult/complicated. I wouldn't add option to setup custom stats for now as well in the editor. We have time for that.

That said, i'm fine with the overall list of options you've just given.

**Comment by hwoarangmy** [comment]
ok. But do we want to change everything else (xp table, physical damage, magical damage per level, ...).
IMHO, we need to decide if we want to decide what is configurable and what is not.
1 - allowing only the things in my previous message + whatever we want
2 - allow to change everything in the level (by overriding the config files with the data in the level file).

1 would be easier to configure (in the editor when we will choose to). 2 would allow to setup everything but would be more complicated to handle (and maybe messy to configure).
@Bertram25 @Danimal696 @akien-mga @oyvindln What do you think ?

**Comment by Danimal696** [comment]
Some degree of freedom in the editor would be good.

**Comment by hwoarangmy** [comment]
Ok, so, let's go for enabling to tune everything ^^

**Comment by Bertram25** [comment]
> Ok, so, let's go for enabling to tune everything ^^

Yeah, have default values taken from the cfg file, and potentially overridden by level ones is the way to go. It is representing some work, though so feel free to tell if something seems too big.
Later, a way to reset to default (no override) will also be a good thing.

Good luck on that one, you're carving the road at this very moment. :)

**Comment by Danimal696** [comment]
but im not happy about creature modification tru editor, if you see a lv10 knigth it should have his corresponding stats, not the stats of a demi-god, for that a new creature should be created in .def and even make a skin variation (Knigth->black-knigth). But i would like to be able to set how much of its hp it has remaining, weapon equipped, lv, xp... to resume, all within the limits of his class.

**Comment by hwoarangmy** [comment]
@Danimal696 Then, you will be happy with my next PR ^^
Now, a creature in a level file looks like :

```
SeatId  ClassName   Name    Level   CurrentXP   CurrenHP    CurrentAwakeness    CurrentHunger   GoldToDeposit   PosX    PosY    PosZ    LeftWeaponName RightWeaponName
```

If CurrenHP > maximum Hp for the creature level, it is set to the max (not from my PR - I think it comes from @Bertram25 PR about creature class configuration).

If you want to add a demi-god knight, you will have to create it in the creature config file or to define its class in the level (same way as in the creature config file). I will upload an example of creature class modification and creation in the skirmish 2v2 test map as well as a weapon modification and creation.

But you won't be able anymore to edit a creature and increase its HP/Attack/defense without changing its class :)

**Comment by Danimal696** [comment]
good additions!
