### ISSUE TITLE
The rooms active spots aren't always complete

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#141]
In the screenshot below, the there is no active spot and this no models on the right wall of the left training room:
![room active spot](https://cloud.githubusercontent.com/assets/4701338/4240746/d70eff44-39ed-11e4-9e90-c330884d6314.jpg)

This case and similar should be fixed.

**Comment by hwoarangmy** [comment]
If someone takes this issue before I do, the problem probably relies where activespots are computed (I've not checked, it's just a guess) :
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Room.cpp#L883
