### ISSUE TITLE
Misc sounds fixes to do

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#147]
- [x] Review the claim/dig/rock falling/fighting sounds and ensure they are mono and normalized.
- [x] Fix creature spatial sounds use through culling.
- [x] Trigger the fighting music when a own-team cannon is firing.
- [x] Trigger battle music when one of your ally is attacked. Internally, this means the creature seat team_id needs to be checked instead of the concerned player only.
- [x] The deposit gold spatial sound server message should be turned into a more generic one.

**Comment by hwoarangmy** [comment]
That makes me think of something. When multiplayer will be supported, we should ensure fighting music is triggered when allied units are attacked/attacking...

**Comment by Bertram25** [comment]
True. If you don't do it, I'll handle it afterwards if you want. :)

**Comment by Bertram25** [comment]
Ok, I think I know why the digging sound isn't heard that much.
In fact, even if played at random, those sounds are played many times by many creatures.
As the sounds have been made spatial, they will be placed at the last creature calling position and heard there. This is making the sound near or far (but rather far) at random.

Same thing for every sounds that can be played often, such as sounds used in battles, and so on.
The actual fix to this will be to add sound culling based on the listener current distance from given position. I'll add this sometime soon and improve a bit how sounds are positioned by the creature sound class.

**Comment by hwoarangmy** [comment]
That sounds good (but maybe not that easy :) )

**Comment by Danimal696** [comment]
arent the digging sounds too bland? i would like to know if im the only one to think that, if im not, i can split this track to have some varity and replace the old ones:

https://www.freesound.org/people/cameronmusic/sounds/138412/

**Comment by Bertram25** [comment]
Heya Danimal,

We can always replace the digging sounds, but I'm quite sure the current ones are very close to the ones you're proposing. I'd propose we take a decision about this once I've fixed the spatial sound culling. Would this be ok for you?

**Comment by Danimal696** [comment]
yes, it  would be a pity for you to prepare a lot of sounds just to be discarded, that would really annoy me if it happened to me.

**Comment by Bertram25** [comment]
Don't worry. :) I understand your quest for better sounds. My point is that we won't hear a difference in game, for now at least. Once you'll be able to hear clearly while playing, you'll tell me. :)

**Comment by akien-mga** [comment]
Another small sound bug: the battle music is triggered directly when you load the oldTest level, but there is no battle unless I'm mistaken. It then switches back to the calm music after ~10 sec.

**Comment by Bertram25** [comment]
> Another small sound bug: the battle music is triggered directly when you load the oldTest level, but there is no battle unless I'm mistaken. It then switches back to the calm music after ~10 sec.

I've checked that one. It's not a bug. An orc is almost immediately attacked by your dragons at map start now the creature fighting behaviour has been fixed. Once the Orc is dead, everything is back to the usual evilish normal. ;)

**Comment by akien-mga** [comment]
> > Another small sound bug: the battle music is triggered directly when you load the oldTest level, but there is no battle unless I'm mistaken. It then switches back to the calm music after ~10 sec.
> 
> I've checked that one. It's not a bug. An orc is almost immediately attacked by your dragons at map start now the creature fighting behaviour has been fixed. Once the Orc is dead, everything is back to the usual evilish normal. ;)

Ah good to know :-) I couldn't find it after a quick search, but this makes sense.

**Comment by Bertram25** [comment]
From @hwoarangmy The deposit gold spatial sound server message should be turned into a more generic one.

**Comment by Bertram25** [comment]
All done :)
