### ISSUE TITLE
Small refinement concerning win/lose and objectives

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#148]
Now the game is much more stable, players can beat it or lose without encountering a single crash. ^^

I'll thus add those few things to help the user understand what's going on:
- [x] When all objectives are completed, a text tells it but at the end of the list. The text telling all objectives are completed should be added on top of the objective text. https://github.com/OpenDungeons/OpenDungeons/commit/402488a8b7b4c74c500d5408ff5795177675a000
- [x] Some chat text should be printed the same way when a player wins. https://github.com/OpenDungeons/OpenDungeons/commit/402488a8b7b4c74c500d5408ff5795177675a000
- [x] Some chat text should be sent to the players to tell one of them has lost his temple when it is the case. The concerned player should get a "You have lost your temple" text instead.
- [x] Some chat text should be sent to the player's team to tell them they have lost when it is the case. 
- [x] A player who has lost his temple should no longer see his mana increase.

**Comment by hwoarangmy** [comment]
Good, I have been thinking about goals lately and this is the occasion to talk about :)
I have opened a thread in the forum because I think other people might have an interesting point of view :)
http://forum.freegamedev.net/viewtopic.php?f=35&t=5830

**Comment by Bertram25** [comment]
So true. :)

I've answered there but I would gladly like to get every point of view. :)

**Comment by Bertram25** [comment]
Points 1 and 3 are done with https://github.com/Bertram25/OpenDungeons/commit/402488a8b7b4c74c500d5408ff5795177675a000

Yet, failed objectives (currently meaning a losing player) aren't handled the same way that a winning player. I thus rather have primary/secondary objectives implemented first before finishing that one.

**Comment by hwoarangmy** [comment]
Seems wise

**Comment by Bertram25** [comment]
If you don't mind, I'll thus add a message about losing only when one's temple is destroyed and consider this issue done. Ok with it?

**Comment by hwoarangmy** [comment]
Well, considering the fact we don't even have a beta version, I'm not so sure it is a top priority to have such advanced goal handling. When we will talk about campaign, I may not say the same but until then...

**Comment by Bertram25** [comment]
> Well, considering the fact we don't even have a beta version, I'm not so sure it is a top priority to have such advanced goal handling. When we will talk about campaign, I may not say the same but until then...

I'm also not fond adding premature stuff. That's why I'm just for adding a message when destroyed for now, and we'll see later on. Are you ok with this?

**Comment by hwoarangmy** [comment]
ok for me

**Comment by hwoarangmy** [comment]
> If you don't mind, I'll thus add a message about losing only when one's temple is destroyed and consider this issue done. Ok with it?

I would just add we should consider loosing when every dungeon temple from a team are destroyed to make sure we cannot have a looser player in a winning team :)

**Comment by Bertram25** [comment]
> I would just add we should consider loosing when every dungeon temple from a team are destroyed to make sure we cannot have a looser player in a winning team :)

True. :)
By checking the code in goals and seats, I also noticed that some code was prepared to trigger an action when meeting an objective but not enabled AFAIK.
While on it, I'll make it so corresponding functions are triggered when meeting/failing at an objective,
and I'll use this to check team winning/losing.

Anyway, I do think that when a player has lost his last temple, a message should tell him about it unless the whole team has lost and then the you have lost message should be sent. Are you ok with this?

**Comment by hwoarangmy** [comment]
Yes. Having a message is always good if you are not looking at this moment :)
But while the team has not lost, I would let the player continue to handle his creatures and do whatever he wishes. But if he still has a portal, I would disable it and I would also disable all the spells (or at least stop increasing his mana).

**Comment by Bertram25** [comment]
> But if he still has a portal, I would disable it and I would also disable all the spells (or at least stop increasing his mana).

True. I'll do that as well, then. I'm in favour of stopping the mana increase as we are more in the "let entropy do its job" mode when with no temple, IMHO.

**Comment by hwoarangmy** [comment]
Yes. And I think it can be understandable.

**Comment by Bertram25** [comment]
Unassigning myself for now. I'll come back at it when the creatures stats and AI are both in.
