### ISSUE TITLE
Addition of a configuration manager

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#150]
This one is somehow the mother or all configuration/catalog files issues and a prerequisite to them.

This issue is about adding support of a configuration manager that will parse reference configuration files for the game, except for the per-level files which should remain under the hood of the game map.

The concerned files are:
- A global game configuration file, described below.
- The entities catalog file: #60 
- The equipment catalog file: #138 
- Other files that will come in time...

I'd propose that the global configuration file comes first, as a test before further support with other files.

This file should add support for all the values that should be configurable game-wide and may be of interest of advanced users and modders, such as @Danimal696 ;)
Note that I'm not yet speaking of user options, such as video/audio ones, but rather global default metrics, such as:
- Creature standard heal rate per turn.
- Awakeness decrease per turn.
- Hunger growth per turn.
- Default creatures.def filename.
- Server/client network default port.
- Default maximum sound & music volume value.

And many other things I surely have missed.

**Comment by Bertram25** [comment]
@Danimal696 @hwoarangmy @akien-mga Please tell me if this suits you, especially as for the global configuration file. I wouldn't like to add undesired things. :)

**Comment by akien-mga** [comment]
This looks good. About your global configuration file, I wonder if part of those points should not be addressed in level configuration files? Or do you plan to have default values in this configuration file, and let levels override some of these values, to have e.g. a different creatures.def?

**Comment by hwoarangmy** [comment]
> Or do you plan to have default values in this configuration file, and let levels override some of these values, to have e.g. a different creatures.def?

That's what was planed if I remember well :)

I know this can be done later but should heal rate/awakness/hunger growth per turn be global or per creature ?

**Comment by akien-mga** [comment]
> I know this can be done later but should heal rate/awakness/hunger growth per turn be global or per creature ?

Good question. I don't know how interesting it can be for the gameplay to have the possibility to define it per creature. A relatively easy implementation could be to have a global parameter for those, and a creature stat to override them.

Since those parameters concern only the creatures, maybe the default stats can be defined in creatures.def instead of a global configuration file? i.e. creatures.def would have a first section with global default creature parameters, before the section with per-creature definitions.

**Comment by Bertram25** [comment]
> About your global configuration file, I wonder if part of those points should not be addressed in level configuration files? Or do you plan to have default values in this configuration file, and let levels override some of these values, to have e.g. a different creatures.def?

Without specifically speaking about creatures, as hwoarangmy said, the global file would be for default values only. All of those should be overrideable if a file/thing is more specific for any reason.

> Since those parameters concern only the creatures, maybe the default stats can be defined in creatures.def instead of a global configuration file?

In that case, the heal rates should indeed be in the creatures.def file, per creature, and no more in the global file, indeed, from what you both said.

**Comment by Danimal696** [comment]
> I know this can be done later but should heal rate/awakness/hunger growth per turn be global or per creature ?

A per creature value would be really interesting, we could made never sleeping skeletons and gluton orcs, i want my vile demon equivalent :D. I thrust you guys will do a nice job with the coding, so its all in your hands.

**Comment by hwoarangmy** [comment]
> i want my vile demon equivalent

I think we all had him in mind when saying that ;)

**Comment by Bertram25** [comment]
Unassigned myself. I'll only keep assignment where I'm actual working on stuff. It's saner IMHO.

**Comment by hwoarangmy** [comment]
I've almost finished the configuration manager but I've been wondering about what we should do if a configuration parameter is missing ? For example the creature definition file or the equipement file ?
Shall we try to continue or to exit application ?
In any case, a log will be added.

**Comment by Bertram25** [comment]
>  For example the creature definition file or the equipement file ?
> Shall we try to continue or to exit application ?

If a mandatory file is missing, we should exit, or not load the level, and log why,  IMHO.
If a non-mandatory file is missing, I guess we can apply defaults and keep on.

The creatures.cfg and equipment.cfg files are mandatory IMHO.

And it's cool to know you're on it. :)

**Comment by Bertram25** [comment]
Just set milestone to 0.4.9 since it seems @hwoarangmy has almost done it. :)
