### ISSUE TITLE
Creature stats format upgrade

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#151]
As discussed here: http://forum.freegamedev.net/viewtopic.php?p=59460#p59460

At the moment, the creatures stats per class, defined in the levels/creatures.def file, as set within the same line.
This is very unreadable and very limiting.

Thus, as first upgrade, and to make it look much more like structured data, and more extensible, the creatures data will have to be set within  [Creature] [/Creature] tags.

Their stats should be within [Stats] [/Stats] tags if it's helping for readability and code.
The file should be auto-documented using #comments.
See Github issue #11 for an example.

**Comment by Bertram25** [comment]
@hwoarangmy @akien-mga @Danimal696 @oyvindln Here is a (unfinished but yet with complete examples) snapshot of the next config/creatures.cfg file, replacing levels/creatures.def:
https://www.dropbox.com/s/6swdo6io5lp2oem/creatures.cfg?dl=0

What do you think as a 1:1 replacement? (I'm not yet speaking about missing/changing stats)

**Comment by Danimal696** [comment]
yes, by the end i was thinking it was the same old .def; what are the changes?

**Comment by hwoarangmy** [comment]
In the file, the advanced worker has a bed. Is it wanted ? Do we want workers that sleep ?

**Comment by Danimal696** [comment]
No, the only advanced worker will be the robo-miner, which will be a kind of drilling tank, and not obtained from portals, rather by sacrifices and found on map. No sleeping or eating for it. Nope.

This unless we decide something different, but advanced worker is a nasty topic, they would take valuable warrior creatures spots if spawned normally, having it only when you need it its better. And it allows to make it special in many senses.

Kobolds also dont deserve the luxury of sleep.

**Comment by Bertram25** [comment]
> In the file, the advanced worker has a bed. Is it wanted ? Do we want workers that sleep ?

Nope, indeed. But this doesn't hurt to have common parameters for every creatures, IMHO, at least for now.

> what are the changes?

There are no changes in the values, only in the format. The end of the file doesn't count, it's WIP.

**Comment by Bertram25** [comment]
I'm in the process of finishing to update the future creature definition file.

I've got a few proposals:
- IMHO, the Gnome and Wizard are good creatures. Thus, I'd placed them in the hero team. What do you think? (We'd later need to name a creature for the wizard replacement for the evil side in that case.)
- The Pitdemon has a lava speed of 0.1. I'd propose to put it to 0.4 at least, since it makes it useless when crossing lava atm.

What do you think?

**Comment by Bertram25** [comment]
I finished the new file:
https://www.dropbox.com/s/6swdo6io5lp2oem/creatures.cfg?dl=0

I'll use it for implementation if you're all ok with it.

**Comment by akien-mga** [comment]
Agreed. I guess the evil Wizard can be named Sorcerer (and/or Warlock depending on the skillset).

**Comment by hwoarangmy** [comment]
> IMHO, the Gnome and Wizard are good creatures

In DK1, wizard was on evil side. But we can have something like a witch or vampire that does the same :)

> The Pitdemon has a lava speed of 0.1. I'd propose to put it to 0.4

I just put 0.1 to allow testing the PR. Now that it is tested, we can even set it to 1 if you prefer.

**Comment by Bertram25** [comment]
> I just put 0.1 to allow testing the PR. Now that it is tested, we can even set it to 1 if you prefer.

Fine by me, while I know this all about balancing and can be done anytime after the implementation of the new format.

> In DK1, wizard was on evil side. But we can have something like a witch or vampire that does the same :)

I clearly didn't think about following DK1 about this point, I must say. And yes, I'd rather have some frightening Warlocks for the evil side instead. This would be more fun, IMHO. ;)
@Danimal696 ?

**Comment by akien-mga** [comment]
IMO it alls depends on the model. Our current Wizard model looks like a friendly wizard and fits the Hero side better. If we want the name "Wizard" for the evil side, then we would need a frightening dark wizard model, but I think it's not worth dropping our current good model :-)
We could name it "Enchanter" if we want something that sounds even more Happily Ever After™ :-)

**Comment by Danimal696** [comment]
yes, a warlock would be more fitting for evil side, you can change wizard and gnomes to the heroes side. I would make demon faster on lava, since hes supposed to be a super creature.

**Comment by Bertram25** [comment]
Ok, :)

And what do you think about the new file format?

**Comment by Danimal696** [comment]
its very easy to read, it will do until we get the upgraded one ;)

**Comment by hwoarangmy** [comment]
Seems good :)

**Comment by Bertram25** [comment]
Cool, I've got almost working code. The "almost" part is somehow taking time to resolve. ;)

**Comment by hwoarangmy** [comment]
> The "almost" part is somehow taking time to resolve. ;)

Most of the time, it is the case ;)

**Comment by oyvindln** [comment]
Shouldn't we be using some standardised data format for this, to make it easy to parse?

**Comment by Bertram25** [comment]
> Shouldn't we be using some standardised data format for this, to make it easy to parse?

@oyvindln Good question. The current format we're using is looking like a midway between plain config files, and xml.
For the coming release, I think we shouldn't waste too much time on this and focus on releasing, even with some non-standard stuff about parsing.

Then, I guess we'll have to decide whether we create our own parser, streamlining the current code, or whether we switch to a data language, such as xml.
A **generic** (let me insist on the reusability of the component) config parser class could be created to ease all that in any case. :) 

What do you guys think?

**Comment by Bertram25** [comment]
An example I (among others) worked on several years ago:
https://github.com/mana/mana/blob/master/src/utils/xml.cpp
https://github.com/mana/mana/blob/master/src/utils/xml.h

(Was improved on manaplus since then)
https://github.com/ManaPlus/ManaPlus/blob/master/src/utils/xml.cpp
https://github.com/ManaPlus/ManaPlus/blob/master/src/utils/xml.h

**Comment by oyvindln** [comment]
I agree. I mean that if we are planning on changing the format, we should attempt to use a standardised format, but if we have something working right now, we should of course focus on releasing first. Also, looking at how other games do this is probably a good idea. This is FOSS after all :)

**Comment by hwoarangmy** [comment]
Using XML with an external tool will make more complex the way objects are written in the file. In such a case, I usually think of the pros and cons. In the cons, I see adding the tool and adapting the code. In the pros, I would say that it may be interesting if it allows us to use a tool that can modify XML easily. But I don't know such a tool...

**Comment by oyvindln** [comment]
I think it makes more sense to use a standardised format than spending a lot of time maintaining our own parser which will probably be slow and buggy. There are more human-readable formats than XML, such as YAML or JSON that could be used.

**Comment by Bertram25** [comment]
> Using XML with an external tool will make more complex the way objects are written in the file. In such a case, I usually think of the pros and cons. In the cons, I see adding the tool and adapting the code. In the pros, I would say that it may be interesting if it allows us to use a tool that can modify XML easily. But I don't know such a tool...

That's a very personal opinion so I'd understand if anybody has got another one on XML, but IMHO, XML is a pure data formatting language and has got a few nice things, such as being well known or famous, has validators, XML handling apps, and can probably be imported/exported using certain tools.

And IMHO, it's a common XML trap to think about editing it with an external or advanced tool right from the start. (I didn't say you told it ;]) I think we don't need validators, and such other niceties in the first place if we can define a simple and readable data format that fits the game. (It's just text after all).
Once the base is done, we can talk of what's next.
One mistake @tomluchowski did, was to try implementing a parser that was using a bunch of advanced XML features without even asking himself on whether the raw data was readable/maintainable. And I'm not speaking of the proposed code, containing yet other new, heavy and useless dependencies.

> I think it makes more sense to use a standardised format than spending a lot of time maintaining our own parser which will probably be slow and buggy. There are more human-readable formats than XML, such as YAML or JSON that could be used.

It's a decision to take, but I will keep begging for a simple parsing API resulting from the use of one of them. :) I, for one, have a preference for either JSON or XML.

What about you guys?

**Comment by oyvindln** [comment]
I think YAML looks nice, the structure is similar your file suggestion, but with a slightly different syntax. Using it looks very straight forward as well: https://code.google.com/p/yaml-cpp/wiki/Tutorial .

**Comment by Bertram25** [comment]
Ok, @hwoarangmy @Danimal696 @akien-mga ?

**Comment by hwoarangmy** [comment]
I don't know YAML. Between JSON and XML, I would prefer JSON as it is more readable IMHO. That's just a feeling and I am not aware (and interested) enough on the available APIs to help deciding. So, you can choose the one you like.

> which will probably be slow and buggy

I am curious to compare the speed when we will have implemented something else as we read it in a straightforward way. IMO, the advantage of using such a tool is not the speed but the format error handling. So, I agree with "buggy" but not with "slow" ;-)

**Comment by Danimal696** [comment]
how is that an improvement over the more simple text we are using atm? i only see a lot of added complextity to something that can be explained just commenting some lines.

**Comment by Bertram25** [comment]
@Danimal696 

> how is that an improvement over the more simple text we are using atm? i only see a lot of added complextity to something that can be explained just commenting some lines.

Well, two days ago you said:

> its very easy to read, it will do until we get the upgraded one ;)

But anyway, why did I change that?
As the game is becoming more mature, our data is becoming more complex and needs structure to stay readable. At the moment, we only have stats based data for creatures mostly, but soon, we'll finally have spawn conditions and later even mood modifier conditions, skills, preferred job, ..., all added in their own sub-tags.

Defining a creature in a single line of parameters separated by tabs makes it unreadable (hence your need of a spreadsheet tool), and thus rather inextensible anyway. It makes things more prone to errors and doesn't help for a future transition to a standardized structured data format.

If you see improvements, feel free to tell, but I'm strongly sure it's the way to go and I won't go back without valid points. :P 

EDIT: Or were you speaking the choice of a standardized structured data format?
In that case, creating our own parser is also an option. The consensus, pros/cons still need to be fully examined, IMHO.

Best regards,

**Comment by hwoarangmy** [comment]
> If you see improvements, feel free to tell, but I'm strongly sure it's the way to go and I won't go back without valid points. :P

I don't want to speak for @Danimal696 but I believe he is talking about using XML/YAML/JSON, not about your PR ;)

**Comment by Bertram25** [comment]
> I don't want to speak for @Danimal696 but I believe he is talking about using XML/YAML/JSON, not about your PR ;)

Yeah, dumb me, I just realized that:

> EDIT: Or were you speaking the choice of a standardized structured data format?
> In that case, creating our own parser is also an option. The consensus, pros/cons still need to be fully examined, IMHO.

**Comment by Bertram25** [comment]
Btw, if we're to choose those options, I'd request we gather pros/cons for each ones. In the pros and cons, try not to forget whether there is a popular lib permitting us to parse/write in that format, whether it is mature enough and so on. And using our own parser is also an option as pointed out by @Danimal696 

I know that libxml2 is more than fine for xml, but I don't know yet how widespread yaml-cpp, or json are, for cpp projects yet, for instance.

**Comment by akien-mga** [comment]
I don't know much about all those data formats and the correspond parsing libraries. I can give some input though about which projects use each one in Mageia, to give some context about how widespread they are (though Mageia is not a reference of all existing projects ;-).

The `urpmq --whatrequires <libname>` command that I use here lists the packages in the database that depend on the given argument.

```
$ urpmq --whatrequires lib64yaml-cpp0.5
lib64OpenColorIO1
lib64yaml-cpp-devel
openxcom
```

```
$ urpmq --whatrequires lib64xml++2.6_2
bombono-dvd
ffado
galois
glom
gobby
lib64ffado2
lib64glom1.26_0
lib64gstreamermm0.10_2
lib64lightspark0
lib64synfig0
lib64synfigapp0
lib64xml++2.6-devel
me-tv
pinot
repsnapper
subtitleeditor
synfig
textroom
```

```
$ urpmq --whatrequires lib64jsoncpp0
lib64jsoncpp-devel
minetest
paraview
sysdig
```

Keep in mind that it only finds packages that are built against the system wide version of those libraries, if they bundle their own version of the library, they are not found. And given the low number of results, I find it hardly relevant, but thought I'd share nevertheless :-)

**Comment by Bertram25** [comment]
@akien-mga Thanks! It already indicates that the three options can used as system wide libs, and that they doesn't seem that heavy to install (seems there is no too much sub-dependencies AFAIK). :)
I'm already somehow relieved about that.

**Comment by Danimal696** [comment]
im out of my deep on here, so i wont talk and about it and leave all of the coding stuff to you guys :)
just remember not to need to know rocket science for the final product

**Comment by Bertram25** [comment]
> just remember not to need to know rocket science for the final product 

Understood and completely agreed.
