### ISSUE TITLE
Create a creature sheet with all the stats so we can start balancing creatures as a whole.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#153]
As discussed here: http://forum.freegamedev.net/viewtopic.php?p=59460#p59460

Part of #152 for the XP table.

**Comment by Bertram25** [comment]
Made spreadsheet model file for that while on the whole creature/entity/equipment config thing: https://www.dropbox.com/s/0j7qiyxesv0uoh4/OD%20-%20stats.xls?dl=0

Feel free to open it, play with the values and tell me what to improve. :)

**Comment by Danimal696** [comment]
Thats amazing Bertram, pretty complete; i can tell how much effort you put on it ;)

**Comment by Bertram25** [comment]
Thanks :)

**Comment by hwoarangmy** [comment]
Seems very good. I think we should use it as it is. If needed, we will add/remove stuff.
My 2 cents : Ranking for current creatures IMHO (can help to define file content) :
Slime
Tentacle1
Tentacle2
CaveHornet
Gnome
Spider
Dwarf1
Dwarf2
Dwarf3
Goblin
Wyvern
Wizard
Kreatur
LizardMan
Adventurer
Knight
Orc
Dragon
BigKnight
PitDemon
Scarab
Troll

**Comment by Danimal696** [comment]
Why do you use that order? its based on supposed power levels?
With the inclusion of physical and magical defence some creatures will be strong on one point but weak on others; imo pit demon will be strongest along with "King, Emperor, Avatar" or how we decide to call the strongest hero side troop

**Comment by hwoarangmy** [comment]
Yes, it is based on physical stats in my opinion. As skills are not yet implemented, we will see later. I think that now that @Bertram25 did a nice job on defining creatures, it would be a shame to not take the oportunity to give a first try to balance. And I believe the easiest way is to rank every available creature and give them stats in consequence. But feel free to change this order if you think it is not suited. It was just a first draft :)

**Comment by Bertram25** [comment]
The values I've put in the next creatures.cfg file are blunt copy/paste atm. But hopefully, the file will help making tests. :)

**Comment by hwoarangmy** [comment]
> The values I've put in the next creatures.cfg file are blunt copy/paste atm. But hopefully, the file will help making tests

Yes, that's what I've seen. And why I try to help finding values, as it is not an easy task :)

**Comment by Danimal696** [comment]
Well, in my opinion i would make 4 creatures tiers: weak, medium, strong, elite, each tier having some tanks, damage dealers... and somewhat similar max stats.
Then, i would only use small integers for the values since they are more explicit and easier to handle.

**Comment by hwoarangmy** [comment]
Thanks for the forum thread :)

**Comment by Bertram25** [comment]
The sheet being made, once #152 will be more or less, I'll consider this one done as well.

Yet, should I push the file somewhere in the data repository?
While on it, can the old faction system be dropped there?

**Comment by hwoarangmy** [comment]
This has been fixed with #256 . The only missing stuff is about mood but it will not be done now so I close it

**Comment by Bertram25** [comment]
@Danimal696 @hwoarangmy @akien-mga I've got a very last question about this one:
Shall I add the file to the data repository? (And maybe drop the former faction system doc there?)

**Comment by akien-mga** [comment]
Sure, it's better than Dropbox IMO :-)

**Comment by Bertram25** [comment]
@akien-mga Btw, @hwoarangmy just disappeared from github. Is this the same for you??

**Comment by akien-mga** [comment]
@Bertram25 Yes, and his pull request and issues disappeared too... ?! That doesn't look good..

**Comment by Bertram25** [comment]
Oh my. I hope everything is fine for him. I opened a request on github support to know whether this is an error and a topic on the forums to know what happened. I hope we didn't offend him by whatever stuff we said ??

**Comment by Bertram25** [comment]
> Sure, it's better than Dropbox IMO :-)

Ok, I'll do that. Hopefully, he'll be back soon :four_leaf_clover:

**Comment by Bertram25** [comment]
TODO: Move the sheet to the data repository (and remove the old faction doc.)

**Comment by Bertram25** [comment]
Done in https://github.com/OpenDungeons/OpenDungeons-media-source/pull/1

**Comment by Bertram25** [comment]
Now that file is merged, I'm considering this issue done.
