### ISSUE TITLE
Add spells support

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#16]
Keeper's kobold workers shouldn't spawn through the temple automatically.

Instead, the Keeper should have a Spawn kobold spell functional when he's still got his temple.
- The spell should then cost mana. The mana cost would be set according to the number of Kobolds the Keeper has already got.
- The first three Kobold workers would be free of charge.
- The kobold should be spawned where the Keeper trigger the spell, but only on claimed tiles.

**Comment by hwoarangmy** [comment]
This issue is closed by #477
