### ISSUE TITLE
Crash when loading a map

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#161]
When selecting TestSingleplayerSmallEmpty.level:

[bt]: (1) ./OpenDungeons.bin : Seat::isAlliedSeat(Seat_)+0 [0x5e48b0]
[bt]: (2) ./OpenDungeons.bin : Seat::isAlliedSeat(Seat_)+0 [0x5e48b0]
[bt]: (3) ./OpenDungeons.bin : GameMap::getVisibleForce(std::vector<Tile*, std::allocator<Tile*> >, Seat_, bool)+0x9f [0x55866f]
[bt]: (4) ./OpenDungeons.bin : Creature::getVisibleForce(Seat_, bool)+0xc1 [0x532a81]
[bt]: (5) ./OpenDungeons.bin : Creature::doTurn()+0x14e [0x53f45e]
[bt]: (6) ./OpenDungeons.bin : GameMap::doCreatureTurns()+0x4a [0x5514da]
[bt]: (7) ./OpenDungeons.bin : GameMap::doTurn()+0x43 [0x559853]
[bt]: (8) ./OpenDungeons.bin : ODServer::startNewTurn(double)+0x474 [0x5b3344]
[bt]: (9) ./OpenDungeons.bin : ODServer::serverThread()+0x15d [0x5bbbed]
[bt]: (10) /usr/lib/x86_64-linux-gnu/libsfml-system.so.2 : +0x6508 [0x7fc319918508]
[bt]: (11) /lib/x86_64-linux-gnu/libpthread.so.0 : +0x80a4 [0x7fc319d360a4]
[bt]: (12) /lib/x86_64-linux-gnu/libc.so.6 : clone+0x6d [0x7fc318c12c2d]

**Comment by hwoarangmy** [comment]
If I remember well, I might have not added the Seat for the ennemy creature in this map (which is the way we should use when adding neutral creatures). I will check that.

**Comment by hwoarangmy** [comment]
I confirm I can reproduce and it comes from the creature in the map not having associated seat

**Comment by akien-mga** [comment]
I can confirm the issue too.

Which means that my "I can't start a game" issue is solved btw \o/. I'm at my parents' with an ethernet connection, so I guess the issue came from the wireless connection at my place and/or to the network settings for this particular connection.
