### ISSUE TITLE
Warnings should be turned on

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#167]
@akien-mga has done a great work on cmake files to (among else) enable warnings. He had to turn them off by default because there was much too many. I've had a look to  see if some could be turned off because produced by additional libraries. Here is what I've found :
-Wno-unused-local-typedefs : There was so much of these that compilation time went from 10 to 50 minutes. As the name implies, it comes from Boost not using local typedefs and it is triggered when compiling with c++11. See https://ogre3d.atlassian.net/browse/OGRE-303
-Wno-format : CEGUI produces loads of them because they use c-style *printf in a way MinGW do not like. As we are not supposed to use c-style functions within OD, we can safely remove them.
-Wno-reorder : It seems c++11 do not like when class parameters are declared within a class and initialised in a constructor in a different order. This could be turned on but there are loads of them and it doesn't sound a top priority warning.

From what I've tested with MinGW, adding them to the CXX flags should be enough to not crush compilation time but to keep relevant warnings on.

Could you please test other configurations to try to find the fewest warnings we have to remove to keep a not too annoying amount ?

**Comment by Bertram25** [comment]
@hwoarangmy Ok, so to summarize, you'd propose the following default warnings?
`-Wall -Wno-unused-local-typedefs -Wno-format -Wno-reorder`

If so, I would be fine, but we should then open an issue about reordering stuff in initialization asap. This isn't a warning that should be ignored for performance purpose, usually, and IMO.

Best regards,

**Comment by hwoarangmy** [comment]
> This isn't a warning that should be ignored for performance purpose, usually, and IMO

I agree. But it will require to change almost all initialisations. IMHO, it can be done later.

**Comment by Bertram25** [comment]
> I agree. But it will require to change almost all initialisations. IMHO, it can be done later.

Sure. Thus my proposal of opening another issue tagged for Later.

**Comment by Bertram25** [comment]
I added #176 Thus, the reorder warnings can be enabled once the such warnings are fixed, and aren't concerning this issue anymore.

**Comment by hwoarangmy** [comment]
ok, I will try to do that tonight

**Comment by Bertram25** [comment]
thanks :)
