### ISSUE TITLE
Editor: Fix cursor behaviour when moving a creature around.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#17]
Currently, moving a creature around makes the tile selector duplicate itself from the dragging start to the dragging end.
While this is correct when selecting tiles to add or placing rooms, this is not when doing something else.

The bug was somehow introduced with this commit: https://github.com/OpenDungeons/OpenDungeons/commit/eb7806ed2b1c70109cf9a67a61a279979565de78

**Comment by hwoarangmy** [comment]
@Bertram25 Are you working on the editor ? If not, I can have a look :)

**Comment by Bertram25** [comment]
@hwoarangmy Nope. You can go ahead. :)
