### ISSUE TITLE
Prettify screenshot names

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#171]
At the moment and thanks to latest @oyvindln's patch, screenshot names gets a serial number based on the time value added as a suffix on their filenames.

This permits to prevent making them overwritten between two sessions of OD.

Since this serial number is based on time, we should prettify the time given and make it human readable, such as:
OD_screenshot_YYMMDD_HHMMSS.png instead of OD_screenshot_NNNNNNNN.png

Nothing urgent, of course. :)

**Comment by Bertram25** [comment]
I've done it.

**Comment by hwoarangmy** [comment]
I've added a comment to your commit about using a more c++ way to get time
