### ISSUE TITLE
Remove the (Skirmish) or (Multiplayer) part of map names.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#172]
Now the gui has been improved a bit, and that map info is displayed when clicking on a map, this info is redundant and is wasting space.

**Comment by Bertram25** [comment]
@hwoarangmy I'll do that something like tonight if you don't before me. :)

I'll take the opportunity to try to refresh the map titles and description a bit.

**Comment by hwoarangmy** [comment]
ok, I was going to do it but I have not started yet so no problem :)

**Comment by Bertram25** [comment]
Ok, I'll try not getting in the way. :)
