### ISSUE TITLE
Addition of the newest forge objects.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#187]
As prepared by @Danimal696 here:
http://forum.freegamedev.net/viewtopic.php?p=59775#p59775

Also, the former forge material and texture can die after the addition of those.

**Comment by Bertram25** [comment]
Ok, I added them with: https://github.com/Bertram25/OpenDungeons/commit/353fe6a0660cc2ecc97a566bbea0e9d8981e9c6b

A proof, it rocks!! :D
![odscreenshot_1411857846](https://cloud.githubusercontent.com/assets/765917/4432518/949e0cb0-4698-11e4-8aba-8f75779d98d9.png)

But I've got several requests:
- Isn't it Chim**n**ey instead of Chimmey? Could the model and used material be renamed accordingly?
- The chimmey models aren't made to be put against walls making them weird looking in such cases:
  ![odscreenshot_1411857855](https://cloud.githubusercontent.com/assets/765917/4432520/a045d39a-4698-11e4-9633-0adccd1e4e12.png)
- Also that model hasn't got a back side, and this could show glitches in certain viewpoints:
  ![odscreenshot_1411857859](https://cloud.githubusercontent.com/assets/765917/4432523/c46ec966-4698-11e4-9319-1b2235c86f8d.png)

@Danimal696 Could you fix the model for the three bugs noticed?

Thanks a lot! :)

**Comment by Danimal696** [comment]
sure, btw the new font looks great!

**Comment by Bertram25** [comment]
> sure, btw the new font looks great!

Thanks a lot!! :)

**Comment by Danimal696** [comment]
updated and tested, look on forum you grammar nazi ;)

**Comment by Bertram25** [comment]
>  you grammar nazi ;)

Mwahahaha...
