### ISSUE TITLE
Editor: Fix moving map lights

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#19]
At the moment, moving map lights is weird on the editor. Moving lights should be functional but also easier to grab.

**Comment by Bertram25** [comment]
@Danimal696 Just a small reminder (just in case you've forgotten about it as there is a lot happening those times :]).
We'll need some kind of torch model to permit moving the lights around more easily as the current panel is taking too much space on screen IMHO.
(Why not a wall torch so we can reuse that one on walls when claiming tiles?)

**Comment by Danimal696** [comment]
ok, its almost ready from a previous model of mine; ill finish it between today and tomorrow; i have two in fact, a metal and a wooden one; which one is prefered?

**Comment by Bertram25** [comment]
>  i have two in fact, a metal and a wooden one; which one is prefered?

Without pictures, I'd say wooden one, IMHO. :)

**Comment by akien-mga** [comment]
Maybe wooden for dirt walls, and metal for claimed walls? ;-)

**Comment by Danimal696** [comment]
look on forum for a little preview

**Comment by Danimal696** [comment]
Lamp ready on forum

**Comment by Bertram25** [comment]
Cool update :)

**Comment by Bertram25** [comment]
We'll want to help moving them but that's for another issue now. :)
