### ISSUE TITLE
Add bridges

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#191]
I just realized we have no means to cross water/lava and claim tiles. ;)
- Two sort of bridges need to be added: Wood and stone ones.

Both can be built over water and lava but wooden bridges will break after a dozen seconds over lava.
One cannot build something over bridges.

**Comment by Danimal696** [comment]
there is a stone one on repo, ill convert tomorrow

**Comment by Bertram25** [comment]
Stone bride icon proposal:
http://game-icons.net/lorc/originals/bridge.html

Wooden one:
An adapted version based on that one: http://game-icons.net/delapouite/originals/planks.html

What do you think?

**Comment by akien-mga** [comment]
I'm not sure how the planks could be adapted to look like a wooden bridge.

As for the stone bridge, it could work, though my first impression is that it represents an archway more than a bridge. I think we need two similar icons for the two bridges, i.e. with the same perspective. It should just be the "texture" of the bridge that changes and makes it clear that one is made of planks, while the other is made of stone/bricks.

**Comment by Danimal696** [comment]
they dont really fit as they are; akien has a point. Bertram do you think you can do it? Vector graphics are not my strong

**Comment by Bertram25** [comment]
Yeah, quite understandable. Based on those, I should manage to make something:
I'd base the actual icon on them, recreating the tribal-tattoo-like effect of other icons:
http://opengameart.org/content/wooden-bridge
http://opengameart.org/content/stone-bridge-alt

What do you think as a base?

**Comment by Bertram25** [comment]
A picture is worth 1'000 words; a quick try on the wooden bridge icon based on OGA ref (actual game size):
![woodenbridge_try1](https://cloud.githubusercontent.com/assets/765917/4441509/d46fface-47d3-11e4-858a-38eba2b9894a.png)

**Comment by Danimal696** [comment]
Good, explicit enougth

**Comment by Bertram25** [comment]
Cool, here is the stone one (I managed to make it look good on a somewhat higher scale):
![stonebridge](https://cloud.githubusercontent.com/assets/765917/4443497/c5aeb736-47e8-11e4-8a65-19ac160883ac.png)

**Comment by akien-mga** [comment]
Looks nice! I think it would be slightly better if the point where the bridge wall changes angle to go down would be visible on the right-hand side too. My point might be clearer with this:

![bridge](https://cloud.githubusercontent.com/assets/4701338/4443709/78214658-47ea-11e4-98dd-252a5f8cd23c.png)

The current perspective looks a little bit off, editing the red part on my pic (or a subset of it) to show the bridge wall going down would make it clearer IMO that this is a bridge.

**Comment by Bertram25** [comment]
ok :)

**Comment by Bertram25** [comment]
And now?
![stonebridge2](https://cloud.githubusercontent.com/assets/765917/4557361/e229f592-4ed2-11e4-8fef-2fb9d86a0dda.png)

**Comment by Danimal696** [comment]
still not very explixct, maybe adding some water ripples below?

**Comment by Bertram25** [comment]
Ok. :)

**Comment by Bertram25** [comment]
Like this?
![stonebridge3](https://cloud.githubusercontent.com/assets/765917/4561039/a4374272-4ef9-11e4-9def-ead6fb46ab81.png)

**Comment by Danimal696** [comment]
you forgot the other side, also, you should spread the ripples more and paint a black line on the upper/far side of the bridge

**Comment by Bertram25** [comment]
> paint a black line on the upper/far side of the bridge 

You mean like an horizon?

**Comment by Bertram25** [comment]
@Danimal696 Without willing to bother you too much, could you make a quick and dirty mock up of what you have in mind? I'll redo it based on your input. :)

**Comment by Danimal696** [comment]
![a4374272-4ef9-11e4-9def-ead6fb46ab81](https://cloud.githubusercontent.com/assets/8299756/4627384/b9bf4cc6-538a-11e4-9605-ee008af5a6fc.png)
Like this, by the way, is the bridge already converted? we need a wood one as well, rigth?

**Comment by Bertram25** [comment]
Here is the updated icon:

![stonebridge2](https://cloud.githubusercontent.com/assets/765917/4809566/d233988e-5eac-11e4-8bfd-a7cbbb8c6716.png)

> by the way, is the bridge already converted? we need a wood one as well, rigth?
> The bridge "room" model(s) aren't part of the data files atm. Also, yes, we'll need a wooden one as well. :)

If you can come up with models that tile well with other bridges tiles, and water/lava borders, it would be perfect. :)

**Comment by akien-mga** [comment]
Nice :-D

**Comment by Danimal696** [comment]
Is still required a wood one and a stone one?

**Comment by akien-mga** [comment]
I don't remember the discussions but I guess the idea would be to have the wooden one for water (that you could reach early in the game in the research tree) and a stone one for lava (that would take more time to research, so level creators could hide lots of gold behind lava :-)

**Comment by Bertram25** [comment]
Yes, plus the wooden one wouldn't last over lava and break over time. At least it is DK concept. Maybe we even don't want to permit wooden bridges over lava?

**Comment by hwoarangmy** [comment]
I wouldn't allow, at least as a first step. Otherwise, we would have to deal with what happens to creature that goes on the bridge while it breaks and saving its state.

**Comment by Danimal696** [comment]
you know, ill try that just for kicks, build bridge -> put creature on top -> sell it , look at creature stuck on its place because it has 0 speed over lava. Is is posible for them to be damaged it they are over lava and speed = 0? in the original dk, you could make any creature walk over lava (by posession, never by own will) but they took a lot of damage

**Comment by Danimal696** [comment]
more problems, there is already a stone bridge in the repo, it has 3 pieces:
http://forum.freegamedev.net/viewtopic.php?f=38&t=3958&p=40254&hilit=bridge#p40229

I think only using the real bridge model is the best option ignoring the shore piece and making it the same heigh as the rest of floor tiles; some questions:
- how to know its owner?
- is it destructible? (i suggest not)
- Claimable? (i say yes)

**Comment by Bertram25** [comment]
I'd say the owner is the one adding it at first. But then, bridges could be claimed by enemies tile per tile. It should also permit to keep claiming tile on the other shore if the tile next to the shore is of the same team color.

**Comment by Danimal696** [comment]
Then the player knows the bridge owner by minimap colour, thats fine by me

**Comment by hwoarangmy** [comment]
> Then the player knows the bridge owner by minimap colour, thats fine by me

Or by coloring like claimed tiles

**Comment by Bertram25** [comment]
> I wouldn't allow, at least as a first step. Otherwise, we would have to deal with what happens to creature that goes on the bridge while it breaks and saving its state.

Sure, let's not add some hellish twist while dealing with new features. 

> you know, ill try that just for kicks, build bridge -> put creature on top -> sell it , look at creature stuck on its place because it has 0 speed over lava. Is is posible for them to be damaged it they are over lava and speed = 0? in the original dk, you could make any creature walk over lava (by posession, never by own will) but they took a lot of damage

IMHO, this will have to be done as a second step. Honestly, I'd even kill creatures in the middle of a full tile when we will be at this stage.

> > Then the player knows the bridge owner by minimap colour, thats fine by me
> > Or by coloring like claimed tiles

Would be better, yes.

**Comment by Danimal696** [comment]
First try, i can see some troubles, like its clear it will have a defined orientation and need to be rotated depending on where its build, also, how to see owner colour, sugestions? I could make it a single square instead of 3 steps but it will look uglier
![woodbridgedemo](https://cloud.githubusercontent.com/assets/8299756/6759797/48bad4ac-cf43-11e4-934e-a0f25445678c.png)

![woodbridgedemo2](https://cloud.githubusercontent.com/assets/8299756/6759848/b34953a2-cf43-11e4-9be5-2763f76320e1.png)

**Comment by akien-mga** [comment]
It looks great :-O

If you want to have a complete tileset that handles orientation and rotation, I guess those shapes would be needed:
![bridge-tileset](https://cloud.githubusercontent.com/assets/4701338/6760382/361ecd94-cf48-11e4-827d-09f5e8b61d9e.png)

But actually, thinking about it again I guess we could do with just the simple square, and just use rotations to build complex shapes, e.g.:
![bridge-example](https://cloud.githubusercontent.com/assets/4701338/6760486/510382f2-cf49-11e4-8fed-48d985e400dd.png)

I don't think the algorithm to determine the optimal orientation would be too complicated :)

**Comment by akien-mga** [comment]
As for the owner colour, we could maybe reuse the star from claimed tiles?

**Comment by Danimal696** [comment]
im an advocate of simplicity ;-P ; ok ill put a small star in the middle

**Comment by Bertram25** [comment]
Note to self: tweak the texture and material to add the owner star.

Is there a will to see bridges in 0.6.0 or do you guys think there is already enough for now?

**Comment by Danimal696** [comment]
stone one shouldnt take more than a day to finish, if you are adding them i can prioritize it

**Comment by akien-mga** [comment]
The wood and stone bridges models are now available since #571 and #853, so what's left is integrating them in the gameplay. I guess this can be done for 0.7.0.
