### ISSUE TITLE
Add the portal and temple rooms as available rooms for the editor

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#192]
New icons are also needed.

**Comment by Bertram25** [comment]
@Danimal696 @hwoarangmy @akien-mga please, tell me which ones to make :)
Icons proposal
- Portal: 
  http://game-icons.net/lorc/originals/orbital.html
  http://game-icons.net/lorc/originals/magic-portal.html
  http://game-icons.net/lorc/originals/reticule.html
- Dungeon Temple:
  http://game-icons.net/lorc/originals/caged-ball.html
  ![caged-ball](https://cloud.githubusercontent.com/assets/765917/4440300/6ad61ae0-47c3-11e4-8f7c-156a7db9901f.png)

What do you think?

**Comment by akien-mga** [comment]
I like both the orbital and magic-portal icons for the Portal. The reticule one doesn't fit IMO. Maybe the magic-portal is best?

As for the Dungeon Temple, the proposal looks nice :-)

**Comment by Bertram25** [comment]
Added the reworked dungeon temple icon. I'll wait for the others before doing more.
Ping @Danimal696 @hwoarangmy

**Comment by Danimal696** [comment]
I like the magical portal icon, and the temple one fits for now

**Comment by Bertram25** [comment]
Here it is, still hot from the newest foundry model: ;)
![magic-portal](https://cloud.githubusercontent.com/assets/765917/4441265/a28327dc-47d0-11e4-8248-fe536e77c24a.png)

**Comment by hwoarangmy** [comment]
I also prefer the magic portal. The dungeon heart seems clear enough IMO.
