### ISSUE TITLE
Editor - Crash when adding a room for a factionless seat.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#196]
To reproduce the crash, search a level which has a seat slot with a faction parameter equal to 'none'

Then, load this level with the editor, select corresponding the team id with 'Y',
Click on Treasury for instance and try placing the room on map.

The editor crashes.
(I'll add the bt asap.)

**Comment by hwoarangmy** [comment]
Strange, I had tested this. Maybe some weird side effect

**Comment by Bertram25** [comment]
Yeah, maybe, hopefully the bt will help. :)

**Comment by hwoarangmy** [comment]
I can reproduce. Not something very tricky, I will handle that in my next PR :)

**Comment by Bertram25** [comment]
Cool :)
