### ISSUE TITLE
Add the boulder trap.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#197]
Prerequisite: #194 

@Danimal696 @hwoarangmy @akien-mga Feel free to correct those little specs as I might have missed something. :)

The trap boulder is triggered when an enemy is within the 5 nearest tiles.
A boulder appears and rolls slowy (movement speed to define) toward the unit.
When reaching a wall, the boulder change its direction randomly (making it more hazardous)
After two or three bounces, it breaks and disappears.

The trap is out of order after being triggered.

Model: http://forum.freegamedev.net/viewtopic.php?p=59832#p59832
Icon: http://game-icons.net/lorc/originals/stone-sphere.html
![stone-sphere](https://cloud.githubusercontent.com/assets/765917/4439971/0e9158f2-47bf-11e4-9b73-5da5fc391043.png)

**Comment by hwoarangmy** [comment]
I think the idea is good but it should trigger when a creature is closer. This trap will be a powerfull one and if it triggers too early, it would be too easy to pickup the creature before it is hurt.

**Comment by Danimal696** [comment]
closer trigger +1

**Comment by Bertram25** [comment]
Np. I guess it's something we'll have to fine-tune anyway.

**Comment by hwoarangmy** [comment]
In the actual code, boulder trap is supposed to be directional. For now, I've set it to trigger only when a creature is on its left as there is currently no way of setting it. Do we want to keep that way (if no, more generally, do we want to keep traps that can trigger in only one direction) ?
If yes, does someone have an idea how to represent that ? A popup ? Some visual artefact ?

**Comment by Bertram25** [comment]
I think we don't want limited traps. The boulder trap should ideally trigger on the straight tile the victim is, IMHO. @hwoarangmy How do you see it, as a player?

**Comment by hwoarangmy** [comment]
As a player, I could understand both. But if you prefer not being a directional map at all, I will change that and add it in the PR :-)

**Comment by Bertram25** [comment]
Hmm, let's vote! @Danimal696 @akien-mga @oyvindln ?

**Comment by Danimal696** [comment]
i would prefer it detects the enemy and triggers in the direction it is.
