### ISSUE TITLE
Wrong attack behaviour for ranged fighters when attacking rooms

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#199]
Ranged fighters always try to go at the maximum range before attacking. The problem with room is that when they try to spot a tile, they might end up somewhere where another tile is closer. That will make them move and possibly move indefinitly.

**Comment by Bertram25** [comment]
Setting to later until you or someone else has got the time and nerve to take it. Creature behaviour stuff are tricky and the game is smooth enough already.

**Comment by hwoarangmy** [comment]
Actually, fighters will attack in priority creatures. If none is in sight, they will go on rooms. I think the easiest way is, for rooms, to check if a tile is in range (as it was done before) and, if so, attack.

**Comment by Bertram25** [comment]
And if not, get closer. (But you will tell me they already do that. ;])

**Comment by hwoarangmy** [comment]
> But you will tell me they already do that. ;]

;)
