### ISSUE TITLE
Dependencies: Add a CMake option to search for system-wide angelscript + drop tinygettext and tinyxml

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#2]
#### Edit by Akien & Bertram

To reflect the change of scope of this issue, the tasks that it covers are now :
- ~~Add a CMake script and option to search for system-wide angelscript~~ (Won't be done until the lib as a system shared object is more commonly existing in distros).
- [x] Drop tinygettext - Part of #132 - Done in #173
- [x] Drop tinyxml - Part of #132 - Done in #190 
#### Previous comment

At the moment, OD has got several dependencies bundled with the code in the `dependencies/` folder.

A cmake option for each one should be added so that their system counter-part is seeked instead of the code there, if possible.
`angelscript/` `tinygettext/` and `tinyXML/` are good examples.

**Comment by akien-mga** [comment]
I'll be working on this now, actually on making it possible to use system-wide angelscript. I think we should drop the other two if they are not used.

It's importing for me to do this quickly, because I want to package OD for Mageia 5, and should do it in the coming month at the latest. It's not particularly an issue if we haven't released version 0.4.9 by then, I'll just package a stable development snapshot, that can already give visibility to OD and bring us players and contributors.

Since Linux distributions tend to have quite static repositories, it's not that straight-forward to provide updates to stable releases (though I'll probably manage it for OD since I'm both active in Mageia's QA team and in OD's upstream :-p), so I want my package bereft of bundled dependencies that can have security issues.

Just FYI :-D

**Comment by akien-mga** [comment]
Updated according to #132.

**Comment by Bertram25** [comment]
> so I want my package bereft of bundled dependencies that can have security issues.

I can understand that. Thanks!! :)

**Comment by oyvindln** [comment]
I remember there being issues with using angelscript as a shared library, not sure if it's even possible. From what I remember, it's not really designed for it so it might not work. I think we may want to consider a different scripting language in general, at least if we want to use it as a console language. Angelscript is c++-like and not really suited for use in a console.

**Comment by hwoarangmy** [comment]
Since you seem to know how it works, could you please explain in a few words how it does ? Is it compiled ? How can it interact with the code ? I've looked AS website but could not find an easy to understand explanation...

**Comment by oyvindln** [comment]
I don't know it all that well. I wasn't the one that implemented it. It's an interpreted language, but it lets you export C++ classes and interact with them directly so it probably involves lots obscure and complex compiler interaction to make it work.

**Comment by Bertram25** [comment]
>  it probably involves lots obscure and complex compiler interaction to make it work. 

Yeah, there must some kind of meta programming at some point. But it seems to me the latest version hides it rather well, according to the doc:
http://www.angelcode.com/angelscript/sdk/docs/manual/doc_hello_world.html

The doc also says it's possible to use it as dynamic shared lib, btw:
http://www.angelcode.com/angelscript/sdk/docs/manual/doc_compile_lib.html §3

>  Angelscript is c++-like and not really suited for use in a console.

Here I'd like you to elaborate a bit on your experience. Angel Script is effectively c-ish/cpp-ish but I've seen Lua used as a console language (and for many other stuff) in many projects, and it went rather well. The guys usually made it so the statement is interpreted as a console command after checking against a list of keywords, just as it is done more or less atm, so I don't see where it won't do it.

**Comment by Bertram25** [comment]
Ah, I just realized: Even if we are using AS as a static library, we don't forcefully need to import the source into our repo, btw. So it's a false problem, IMHO. Just two cents.

**Comment by oyvindln** [comment]
Maybe they have fixed the use as a lib since we used it last, so if that works, great!

I thought the point of using a scripting language in the console would be to be able to run code from the console, I think a language like Lua would be simpler for that purpose, though I suppose angelscript could work too. If you are just using it to implement console commands as in was in OD earlier, I don't see much point in it, then you could as well do that in C++ instead.

**Comment by oyvindln** [comment]
When I think about it AS is probably okay.

**Comment by hwoarangmy** [comment]
IMHO, the good point with a scripting language will be more for campaign/map purpose to trigger stuff and to allow to add custom effects while playing. For me, console is for debug purposes. I'm not sure using AS for this will allow much more than using code...

**Comment by Bertram25** [comment]
> IMHO, the good point with a scripting language will be more for campaign/map purpose to trigger stuff and to allow to add custom effects while playing. For me, console is for debug purposes. I'm not sure using AS for this will allow much more than using code...

And I think you're completely right. The main use I've seen when using direct script statement in the console was more to set values for scripts and so on. (To force triggering events, make a script start, ...)

**Comment by oyvindln** [comment]
Yeah, map scripts is the important bit, so the focus should be on what's best for that.

**Comment by akien-mga** [comment]
Edited the first comment to better reflect the new scope of this issue (partly resolved already).

**Comment by Bertram25** [comment]
Thanks :)

**Comment by akien-mga** [comment]
Ok I'll package Angelscript for Mageia as a prerequisite to adding a CMake option to use the system package :-)

**Comment by akien-mga** [comment]
AngelScript is not that packaging-friendly as far as I can tell, and it's shared library versioning seems a bit fishy. I think for now it's not particularly relevant to add CMake instructions to find a system-wide version of AngelScript and use it to build OD. WDYT?

If you agree I'll add a mention that the AngelScript part of this issue is "WONTFIX", and close the issue since the two other points have been fixed.

**Comment by Bertram25** [comment]
I'll be honest. I don't agree. ;)

Don't misunderstand me, though. I'm not meaning you should package AS, the issue isn't about packaging AS anyway.
But I do think you should add the option to find a system-wide AS lib while setting it to false per default.
This way packagers of other distribution can optionally use it (and maintain it for us if doesn't work for their distro for any reason.)

Feel free to tell if there a more problems linked to that point. :)

**Comment by akien-mga** [comment]
I agree with you, but what I mean is that no distribution ships angelscript (apart from the OpenSUSE Games repository and the unofficial Fedora RPM Fusion), and both had to patch a broken makefile to fix the shared library soname, so I can't be 100% sure where the lib will be located on Linux systems, so at first I thought it was not worth the bother.

Now that I think about it a bit more, I guess I can do a minimalistic FindAngelscript.cmake script that would look for angelscript.h in /usr(/local)/include and for libangelscript.so in /usr(/local)/lib(64). I'll give it a try.

**Comment by akien-mga** [comment]
What about the AngelScript addons? Do we use those?

**Comment by Bertram25** [comment]
> Now that I think about it a bit more, I guess I can do a minimalistic FindAngelscript.cmake script that would look for angelscript.h in /usr(/local)/include and for libangelscript.so in /usr(/local)/lib(64). I'll give it a try.

Fear not. :) We might even be in the process of paving the road here. ;)

> What about the AngelScript addons? Do we use those?

??? I don't know. @oyvindln Help!

**Comment by Bertram25** [comment]
@akien-mga  Taken from the code in ASWrapper.cpp:
#include "scriptarray.h"
#include "scripthelper.h"
#include "scriptstdstring.h"
#include "scriptbuilder.h"

So, I'd say yes, we are.

**Comment by Bertram25** [comment]
@akien-mga 

> Now that I think about it a bit more, I guess I can do a minimalistic FindAngelscript.cmake script that would look for angelscript.h in /usr(/local)/include and for libangelscript.so in /usr(/local)/lib(64). I'll give it a try.

I know adding a find angelscript module is uneasy. Still wanna do it? If not, we might want wider acceptance of AS as a system lib before moving on with this. Your call.

**Comment by akien-mga** [comment]
It shouldn't be that hard, the main problem is just that last time I had a look at it, angelscript was not well-defined as a system library. This may have been improved in the last release, I'll have another look at it. Basically (for Linux) we just have to search for the main header in its normal installation location, provided it's something reliable such as $(prefix)/include/angelscript, and to search for the main lib in $(prefix)/{lib,lib64}/libangelscript.so

For now I set it to the Later milestone, because we don't need this at all costs for 0.4.9. No distro will complain about the bundled static library for now since it has not been packaged officially yet: http://pkgs.org/search/angelscript

As for whether we want to go on with AS, that's still open to discussion, and if it makes this issue obsolete while I'm working on it, I'll just forward my FindAngelscript.cmake upstream :-)

**Comment by Bertram25** [comment]
ok. But feel free to report here, I'll be happy to add that in the corresponding AS forums. :)

**Comment by akien-mga** [comment]
Basically the main issue is that when you build AS as a shared library, it creates a libAngelscript.so library (with its SONAME being simply libAngelscript.so). I'm not a library guru, but "normally" libraries have a versioned suffix after .so, which is often the API major.

I don't know about the AS versioning model, but most likely the SONAME should be something like libAngelscript.so.2 or libAngelscript.so.2.29 (or even libAngelscript.so.2.29.2, depending on whether there are API changes between the versions). I just speak from what I've seen in the libraries I packaged or installed, Internet has plenty of better-documented information about this:
http://unix.stackexchange.com/questions/134801/library-version-api-version-and-soname-how-should-it-be-done
http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

Then of course the libAngelscript.so file should exist, but it should be a symbolic link to the one with the above-mentioned SONAME (e.g. libAngelscript.so.2).

Most libraries also use lower-case names, but that's no big deal :-)

EDIT: Above comment were about the output of the CMake buildsystem.

**Comment by akien-mga** [comment]
With the gnuc buildsystem, it's already better: you can build AS with `make SHARED=1 VERSION=2.29.2` and it produces a library named `libangelscript-2.29.2.so`.

That's already better, but that's probably overkill: such a name means that programs using libangelscript-2.29.1.so won't run with libangelscript-2.29.2.so. Such a naming scheme is used when there are heavy API changes from one version to another, for example between libSDL-1.2.so and libSDL2-2.0.so (though in this case, they also changed the base name for more clarity).

Once again I don't know much about AS, but if its version follows the MAJOR.MINOR.PATCH numbering scheme, I guess it should be named libangelscript.so.MAJOR (with a symlink to libangelscript.so) or libangelscript.so.MAJOR.MINOR (with symlinks to both libangelscript.so.MAJOR and libangelscript.so).

EDIT: For the reference, the SONAME can be observed with:

```
$ objdump -x libangelscript-2.29.2.so | grep SONAME
  SONAME               libangelscript-2.29.2.so
```

**Comment by Bertram25** [comment]
I've put a few questions on AS forums about this and linked back here. Hopefully, this will be interesting for both him and us. :)

**Comment by Bertram25** [comment]
@akien-mga The author answered: http://www.gamedev.net/topic/662413-compiler-warnings-with-latest-stable-version/#entry5190921

I think all three version number have to be included according to what he says. And I'm sure he would be more than happy to see a CMake module in action. :)

**Comment by akien-mga** [comment]
I wrote a simple CMake module to find AngelScript on Linux systems:

```
# - Try to find AngelScript
# This module aims at finding AngelScript if it is installed and determines where
# the library and header files are. This code sets the following variables:
#
#  ANGELSCRIPT_FOUND - System has AngelScript
#  ANGELSCRIPT_INCLUDE_DIRS - The AngelScript include directories
#  ANGELSCRIPT_LIBRARIES - The libraries needed to use AngelScript
#  ANGELSCRIPT_DEFINITIONS - Compiler switches required for using AngelScript
#
# Based on http://www.cmake.org/Wiki/CMake:How_To_Find_Libraries#Writing_find_modules

find_package(PkgConfig)
pkg_check_modules(PC_ANGELSCRIPT angelscript)

find_path(ANGELSCRIPT_INCLUDE_DIR angelscript.h
          HINTS ${PC_ANGELSCRIPT_INCLUDEDIR}
          PATH_SUFFIXES include
          PATHS /usr /usr/local)

find_library(ANGELSCRIPT_LIBRARY angelscript
             HINTS ${PC_ANGELSCRIPT_LIBDIR}
             PATH_SUFFIXES lib64 lib
             PATHS /usr /usr/local)

set(ANGELSCRIPT_LIBRARIES ${ANGELSCRIPT_LIBRARY})
set(ANGELSCRIPT_INCLUDE_DIRS ${ANGELSCRIPT_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(AngelScript DEFAULT_MSG
                                  ANGELSCRIPT_LIBRARY ANGELSCRIPT_INCLUDE_DIR)
mark_as_advanced(ANGELSCRIPT_INCLUDE_DIR ANGELSCRIPT_LIBRARY)
```

It works fine, but the problem I have now is with the addons. The addons directory contains source code but no evident way to turn it into a shared library + headers, so I wonder if using a system-wide AS (with addons) is even possible?

**Comment by Bertram25** [comment]
Thanks Akien :)

I did the proxy once again about your question. We'll see what are the author's advice here. Maybe it's possible or maybe not yet. After all, I have the impression we are still digging a new road here.

**Comment by Bertram25** [comment]
The author has answered. The add-ons are meant to be directly integrated into the application code.
http://www.gamedev.net/topic/662413-compiler-warnings-with-latest-stable-version/#entry5191391

Thus, I'd say that we should provide the findAS cmake module to him, and keep the code within OD anyway. When there will be real packages of AS in distros, we'll check what we can drop and keep.

Would you be ok with that?

**Comment by Bertram25** [comment]
@akien-mga Hey :)

It seems my latest comment slipped through other things. IMHO, this issue can be closed as there is no viable ways to get rid of the angelscript source for now. Things may change in the future, we'll open a new issue if it happens. I'll give the module to the author as it may help, though.
Ok about this?

**Comment by akien-mga** [comment]
Fine by me :-)
