### ISSUE TITLE
Editor: Add support to add light sources

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#20]
When opening a map with the editor, the possibility to add lights, creatures, and rooms are missing.
The possibility to remove them using specific buttons should be added also.

**Comment by Bertram25** [comment]
The possibility to add rooms has been added + team selection support in #157 #158 
Lights and creatures are left. Maybe there are icons needed here?

**Comment by hwoarangmy** [comment]
Yes, we need icons. When creature menu will be there, we should use CEGUI LayoutImport tag in the CEGUI layout file to share the menu within editor and gamemode (as it is done for rooms and traps).

**Comment by Bertram25** [comment]
Ok, this means I'll start seeking for creature icons and "torch" one.
While on it, I'll add a creature and light removal icon for the editor. (The one for rooms is already done.)

**Comment by hwoarangmy** [comment]
Adding creature in editor is possible since #259

**Comment by Bertram25** [comment]
Adding light sources is left. I'll rename the issue.

**Comment by Bertram25** [comment]
#19 is done, btw.

**Comment by Bertram25** [comment]
Note to self: Find a torch icon asap.

**Comment by Bertram25** [comment]
Which one do you prefer?
http://game-icons.net/lorc/originals/lantern-flame.html
or
http://game-icons.net/lorc/originals/light-bulb.html

**Comment by hwoarangmy** [comment]
The first one. It fits better for a game like OD ^^

**Comment by Bertram25** [comment]
Deal. I'll add the prepared resource in my next PR.

**Comment by akien-mga** [comment]
+1 for the first icon

**Comment by Bertram25** [comment]
![lantern-flame](https://cloud.githubusercontent.com/assets/765917/6147222/6340529a-b1f5-11e4-9ea0-934971d267ea.png)
Here is the prepared icon.
