### ISSUE TITLE
Random crash when room/traps/missiles/roomobjects are destroyed

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#200]
Active objects are handled here :
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/GameMap.cpp#L685

We can see in the code that the active objects list is not supposed to be changed outside this function (at least, not during its execution).
But in almost every entity (room/traps/missiles/roomobjects), we can see that it is removed. For example, for rooms :
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Room.cpp#L591
Then
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/GameMap.cpp#L1451

The consequence is that if the destroyed active object is the last from the list => crash.
If not, we will not make the upkeep for the next in the list.

The functions are not the same but the behaviour is identical for creatures.

**Comment by Bertram25** [comment]
Now you tell it. It explains a few glitches I've seen in game today, especially when destroying an enemy hatchery tile with chicken above it.

**Comment by oyvindln** [comment]
I think the entity classes are doing a lot of things they shouldn't in general, not sure if they should really manipulate anything other than themselves.
