### ISSUE TITLE
Adapt GUI to lower resolutions

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#203]
As seen on #201, the GUI is particularly out of scale when running the lowest windowed resolutions that are 640x480 and 800x600. The game in itself runs fine, so if CEGUI permits it, it would be nice to downscale the whole GUI (both the main menu and the in-game UI) to fit those lower resolutions.

**Comment by Bertram25** [comment]
I'll adapt down to 640x480. :)

**Comment by Bertram25** [comment]
Note to self: The main menu might concerned.
