### ISSUE TITLE
Warnings when loading the chicken model + similar warnings for other models?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#213]
WARNING: the mesh 'Chicken.mesh' includes vertices without bone assignments. Those vertices will transform to wrong position when skeletal animation enabled. To eliminate this, assign at least one bone assignment per vertex on your mesh.

**Comment by Danimal696** [comment]
its simple, in the converter, after you do export-> realextend-tundra, roll down lower left corner; you need to make "trim weigths" to something like 0.16, rise the number if it doesnt work

**Comment by Danimal696** [comment]
i just saw the other thread, please make a list of all faulty models, ill reconvert them as needed

**Comment by Bertram25** [comment]
I'll be on making the list.

**Comment by akien-mga** [comment]
I snatch it from @Bertram25, he has enough on his plate :-)

**Comment by Bertram25** [comment]
I'm fine with being relieved :) Thanks @akien-mga  :)

**Comment by akien-mga** [comment]
##### Meshes with vertices with more than 4 bone assignments

`WARNING: the mesh 'Wizard.mesh' includes vertices with more than 4 bone assignments. The lowest weighted assignments beyond this limit have been removed, so your animation may look slightly different. To eliminate this, reduce the number of bone assignments per vertex on your mesh to 4.`
- [x] Dragon.mesh
- [x] Dwarf3.mesh
- [x] Knight.mesh
- [x] Lizardman.mesh
- [x] Orc.mesh
- [x] Wizard.mesh

##### Meshes with vertices without bone assignments

`WARNING: the mesh 'Dwarf3.mesh' includes vertices without bone assignments. Those vertices will transform to wrong position when skeletal animation enabled. To eliminate this, assign at least one bone assignment per vertex on your mesh.`
- [x] Chicken.mesh
- [x] Dwarf3.mesh
- [x] Spider.mesh

##### Old format

`WARNING: Spiderbed.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.`
- [ ] Boulder.mesh
- [ ] DragonBed.mesh
- [ ] ImpBed.mesh
- [ ] LizardmanBed.mesh
- [ ] OrcBed.mesh
- [ ] Spider.mesh
- [ ] Spiderbed.mesh
- [ ] TentacleBed.mesh
- [ ] TrainingDummy4.mesh

**Comment by Danimal696** [comment]
so this all is a result of an upgrade on the mesh exporter? i need help here as well, all the xxxxxBed were done recently so they shouldnt fail except in that case, what version is being used now to check agaisnt mine?

**Comment by Bertram25** [comment]
About old format:
I'll check my version of the mesh exporter and have a try at upgrading the files. IIRC, @oyvindln did have to export them to XML and turn those into mesh files for it to work. We should define a how-to if we can find how to fix this.

**Comment by Danimal696** [comment]
yes please, or else all models i export will have the same error

**Comment by Bertram25** [comment]
@Danimal696 @akien-mga : I try upgrading the models using this method and it seems to work:
I install the `ogre-tools` package

```
OgreXMLConverter models/DragonBed.mesh
-> models/DragonBed.mesh.xml is created
OgreXMLConverter models/DragonBed.mesh.xml models/DragonBed.mesh
-> models/DragonBed.mesh is upgraded
rm models/DragonBed.mesh.xml
```

When playing the game, the warning about the mesh format is gone. I didn't speak about meshes with bone assignment problems, of course.

Can you test this @akien-mga ?

**Comment by Danimal696** [comment]
ill check if my ogre tools are outdated

**Comment by akien-mga** [comment]
Updated the list: TrainingDummy4.mesh and Spider.mesh are also in an "old format" (as discussed previously, it's no big deal). The Spider also has vertices with no bone assignment.

**Comment by Danimal696** [comment]
dont worry about the spider, it has some useless bones, so it wont affect the model animation

**Comment by Danimal696** [comment]
my tools seems to be to the day (ironically they stopped giving support to the exporter years ago) then, since its an easy (even if boring task) can i delegate this task to someone else? i prefer to be creating new content instead, but it can also be left for later, before the official release

**Comment by Bertram25** [comment]
> my tools seems to be to the day (ironically they stopped giving support to the exporter years ago) then, since its an easy (even if boring task) can i delegate this task to someone else? i prefer to be creating new content instead, but it can also be left for later, before the official release

I'll happily upgrade the models if nobody else does. What should we do about the other bone assignment warnings, like more than 4, or vertices without bone assignment?

**Comment by Danimal696** [comment]
by my experience with the exporter most of those will have to be left like that, some of them may be fixed tho

**Comment by Bertram25** [comment]
> by my experience with the exporter most of those will have to be left like that, some of them may be fixed tho

Ok, just tell us what kind of warnings we can ignore, so we'll be able to know which we can report in the future. :)

**Comment by Danimal696** [comment]
truthfully all of them can be ignored, i have exported models and seen how the exporter twisted and forgot bones among many other stuff, the model works perfectly like in the spider case, but i had to reexport over 20 times and each time i had a different result with the same settting.
Upgrading meshes has no problem , but lets let the bones issue aside for now.

**Comment by Bertram25** [comment]
> Upgrading meshes has no problem , but lets let the bones issue aside for now.

Ok, let's forget about the bones, I'll take care of the rest. :)

**Comment by Danimal696** [comment]
Thanks, i cant believe how poorly supported blender to ogre is

**Comment by Bertram25** [comment]
> Thanks, i cant believe how poorly supported blender to ogre is

Actually, the commit log of the exporter shows relatively recent activity, but well, no new release so far:
https://bitbucket.org/MindCalamity/blender2ogre/commits/all

I've opened a new topic on Ogre to get some news from the exporter team. Let's see how it turns:
http://www.ogre3d.org/forums/viewtopic.php?f=1&t=82002
