### ISSUE TITLE
Deletion of a room should not unclaim the tile.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#221]
I've noticed that some time after merging.
Nothing hurting, though...

**Comment by hwoarangmy** [comment]
That's the same behaviour as when the room is attacked. IMHO, we should keep the same behaviour when a room is sold or attacked (being letting the tile claimed or setting it to dirt).
What do you prefer ?

**Comment by Bertram25** [comment]
I sincerely think it is more logical to let the tile claimed when selling/destroying a room/trap.
Because it is what I was expecting ;) and because it is preventing from being able to drop a worker in the middle of a destroyed room, even if now, workers are far less Chick Norris than before. ;)

But since we might want later to add a claim skill to workers, this doesn't fit in the long term, IMHO.
To me, room are a layer upon tiles, simply put.

But what do you guys think?

**Comment by Danimal696** [comment]
yes, let the tile still claimed

**Comment by akien-mga** [comment]
Agreed :-)

**Comment by hwoarangmy** [comment]
ok. I will do that :)
