### ISSUE TITLE
Change rooms/traps definition in the level file.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#224]
While I see and think about it:

Rooms/traps are still defined the old way:
Room/trapName
Number of tile
The tiles
...
...

We should use tag couples as we do for everything else:
[Room]
[/Room]

The trick is to implement it at save time, load and save every level (and check they're ok),
and then only implement the new loading algorithm.

**Comment by Bertram25** [comment]
@hwoarangmy For info, since we're speaking about it.

**Comment by hwoarangmy** [comment]
ok, i agree. It should not be very difficult. If someone wants to do this before I do, saving is here :
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Trap.cpp#L410
Loading here :
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Trap.cpp#L435

**Comment by hwoarangmy** [comment]
Now that I think about it, I've done that in PR #232
