### ISSUE TITLE
Remove void* pointer when Traps are created and do the same for rooms

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#228]
As discussed with @Bertram25 :

We should handle Trap like RoomObjects are handled here to avoid the need of using void\* pointers in the Trap creation :
- Allow the Trap static function that creates Traps to use the stream to allow specialized Traps to get the information it needs
- Do not use a generic function on server side when creating a trap. Create the good trap instead with a new (since it is the place where we have all the information)
- On client side, use a generic function with the ODPacket to create the correct trap like when reading the level file.

See PR #227 to see how RoomObjects are used

**Comment by Bertram25** [comment]
0.4.9? Wanna do it?

**Comment by hwoarangmy** [comment]
Yes, I will if nobody does before
