### ISSUE TITLE
Add support for default spawn pools and support to optionally override them in levels per seat.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#230]
Prerequisite: #150 

The default spawn pools will be defined per faction in a config/factions.cfg file:

Example:

```
[Factions]
    [Faction]
        Name Keeper
        [Spawn]
        Dragon
        Wyvern
       ...
        [/Spawn]
    [/Faction]
    [Faction]
        Name Hero
        [Spawn]
        Gnome
        Adventurer
       ...
        [/Spawn]
    [/Faction]
[/Factions]
```

~~This will permit to define default spawn pools per faction, that can still optionally be overridden in the level file within SpawnPool tags.~~
=> We will see later if we want to open an issue for allowing editing spawn pools and how.

Thus, the current Faction in the level files will have to be split into two: AI type (can be human) and Faction.

Also, it would be nice when choosing a level to optionally have the right to define one's faction. This could lead to interesting replayability. Later also, it could be cool to let the server define the human/AI slots also. :)

Feel free to comment. :)

**Comment by hwoarangmy** [comment]
> it would be nice when choosing a level to optionally have the right to define one's faction

In the seat definition, we could have "Keeper", "Hero", "Choice". And, for now, if it is "Choice", we assume it is Keeper. This way, when we will have the GUI that allows to choose, it would be easy ^^

> it could be cool to let the server define the human/AI slots also

Right ^^ Again, it is just a mater of GUI :)

**Comment by hwoarangmy** [comment]
While doing the faction stuff, I'm trying to set up the menu to configure seats (to associate seats to players). But I'm loosing patience while trying to set up cegui combo boxes. has anyone ever tried it ? The list is empty no matter what I've tried...

@Bertram25 an idea ?

In the layout I've added a "OD/Combobox" and in code, I used the addItem function to add items...

**Comment by Bertram25** [comment]
> In the layout I've added a "OD/Combobox" and in code, I used the addItem function to add items...

IMHO, you doing nothing wrong so far. The combo boxes might be broken without anyone aware of it.
That's a bummer really. What I've found so far but without any actual clues:
http://delta3d.org/forum/viewtopic.php?showtopic=19760
For self reference: http://cegui.org.uk/wiki/Sample_code_for_all_Widgets#Combobox

I don't know what code you've used to create the combo box maybe but have a go at using the one in the second link, just in case.
If that doesn't work, maybe we can use a ListBox in the meanwhile. I know it's not ideal but I won't be able to say more before making my own tries, sorry. :S

**Comment by hwoarangmy** [comment]
I will test tonight if I can find something. Thanks for your help anyway.

**Comment by hwoarangmy** [comment]
OK. I've had a look and it is nin CEGUI FAQ. The combobox height should include its list and not only the combo itself. That's why I had an empty list. Not an expected behaviour...

**Comment by Bertram25** [comment]
Indeed. Does it mean it is fixed ??? :) If so, I'll gladly improve the skin afterwards. :D

**Comment by hwoarangmy** [comment]
It is fixed but there is a scroll bar...

**Comment by Bertram25** [comment]
IIRC, there is an horizontal/vertical scrollbar policy option you should be able to set. I'll check the doc asap. :)

**Comment by hwoarangmy** [comment]
IMHO, it is ok the way it works. I've made some tests by adding several items to see how it behaves and it is not bad. When wanted, we might want to improve the look and feel buit even the style fits pretty well with the rest of the menu

**Comment by Bertram25** [comment]
> When wanted, we might want to improve the look and feel buit even the style fits pretty well with the rest of the menu

Cool. This means I've got a bit more time to port those controls to our gui style. :) And thanks for this feature, it will be soo cool! :)
