### ISSUE TITLE
Rename RoomObject

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#231]
As they are not used by rooms only, they should have a more suited name.
RenderedEntity is the best so far.

@Bertram25 @oyvindln , what do you think of RenderedMovableEntity or RenderedAnimableEntity ?

**Comment by Bertram25** [comment]
> what do you think of RenderedMovableEntity or RenderedAnimableEntity ?

As children of RenderedEntity or as a possible replacement? In the latter, I think it's useless as I thought such entities could already move and animate. Am I wrong?

**Comment by hwoarangmy** [comment]
As a replacement. It's just because RenderedEntity reminds GameEntity (which cannot move). To be animated/able to move, you have to extend MovableGameEntity.
That's why I think RenderedMovableEntity or RenderedAnimableEntity would fit better. But it's a bit long...

**Comment by Bertram25** [comment]
I haven't looked a the code, but IMHO:
If you have to extend Movable\* you should rather keep that name part for the children.
That said, if we're always using those objects in game, a shorter name may be better.

Thus, IMHO, either RenderedEntity or RenderedMovableEntity. Your choice. :)

**Comment by hwoarangmy** [comment]
OK. Let's go for RenderedMovableEntity ^^
