### ISSUE TITLE
Rooms.cfg - rooms configuration file

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#239]
This file should gather per room, configurable component, permitting to fine-tune the game without recompiling.

So far we have:
- **Hatchery**
  - How much hunger decreases per eaten chicken
  - How many hp recovered per eaten chicken
  - Chicken spawn rate (at the moment, it doesn't depend on active spots - only max number chickens depends on active spots)
  - min & max turns to wait before next chicken eating.
- **Training Hall**
  - XP per attack
  - min & max turns to wait before next attack.
  - min & max turns before changing dummies

We should also do the same for traps: traps.cfg
With reload time, min damage, maxdamage... for each trap

**Comment by hwoarangmy** [comment]
I would add training hall : how many experience is given per attack.
And maybe : minimum and maximum turns to recover after an attack in training room (and maybe same for hatchery)

**Comment by Bertram25** [comment]
Agreed, I'll add that in the summary.

**Comment by Danimal696** [comment]
yes, its good.

**Comment by Bertram25** [comment]
Is chicken HP healing desired, or should it only touch hunger?

**Comment by Danimal696** [comment]
i do want it, but should it recover a % or some set value (say, 5 hp)

**Comment by hwoarangmy** [comment]
I would say a defined value or it would be too powerfull (especially since it would allow to recover hp for creatures in the arena). But I remember you said you didn't want to end up in a game where previously to a battle, you took all creatures to feed them like babies. If they get healed when they eat, that's a risk...
Anyway, we can prepare for that. We will always have the choice to set this value to 0 if we see it is not that good after all...

**Comment by Danimal696** [comment]
> Anyway, we can prepare for that. We will always have the choice to set this value to 0 if we see it is not that good after all...

Yes, let them heal a bit for now, if it can be abused, we remove the hp healing later

**Comment by akien-mga** [comment]
Maybe we could have the creatures regenerate health slowly when well-fed, e.g. more than 85% satiated? Then the chicken would not be "health potions", but would permit to reach a hunger status that lets the creature heal slowly.

**Comment by Bertram25** [comment]
OMG, @akien-mga is back!! Take cover! ;)

**Comment by akien-mga** [comment]
Let's spot some of the regressions that you let through while I was away :-p

**Comment by Bertram25** [comment]
> Let's spot some of the regressions that you let through while I was away :-p

Self-reported regressions don't count! ;P

**Comment by hwoarangmy** [comment]
Concerning hatchery, I would propose to spawn 1 chicken per chicken coop (per central active spot) and to have a configurable spawn rate.
Max chickens would still be equal to the total number of activespots.

@akien-mga Welcome back :)

**Comment by Danimal696** [comment]
> Max chickens would still be equal to the total number of activespots.

Wouldnt that be too few? maybe its better to make the max chicken number equal to total farm tiles?

**Comment by hwoarangmy** [comment]
Actually, it is the spawning rate that is too low. And the fact that only 1 chicken spawns at a time makes it better to have several small hatcheries than 1 big, which is not what we would expect. Concerning the number of chickens, using active spots makes it usefull to choose a good place where active spots are maxed...

**Comment by Bertram25** [comment]
> Actually, it is the spawning rate that is too low. And the fact that only 1 chicken spawns at a time makes it better to have several small hatcheries than 1 big, which is not what we would expect. Concerning the number of chickens, using active spots makes it usefull to choose a good place where active spots are maxed...

You have a point. Should this be another issue?

**Comment by hwoarangmy** [comment]
yes, it doesn't hurt to have another issue since it is not directly related to room configuration. And IMHO, spawning 1 chicken per coop makes sense and is good as long as we have the hunger decrease per eaten chicken that can be configured through the config file.
