### ISSUE TITLE
Empty corners on the inner-side of dirt wall tiles

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#240]
As shown on the following screenshots, there are empty corners in the inner-part of some wall tiles. It seems the mesh used for a dirt wall tiles (i.e. a dirt tile with tile fullness 100% and next to a non-dirt tile or tile with tile fullness 0%) has smooth corners (since it looks better), but might not be placed correctly in some cases (here a "north-south" wall relative to the original position of the camera).

![od-wall-tiles](https://cloud.githubusercontent.com/assets/4701338/4661164/4ca0f2ec-5520-11e4-9fa5-4ef67311a3a2.jpg)
![od-wall-tiles1](https://cloud.githubusercontent.com/assets/4701338/4661165/4e35ae86-5520-11e4-9f22-25b29d236792.jpg)

This also raises another question (not directly linked to this issue): should we use "smoothed dirt wall" tiles next to claimed walls? Wouldn't it make more sense (and look better) to use normal "inner wall" tiles, i.e. with no empty space between the dirt wall and the claimed wall?

**Comment by Bertram25** [comment]
This bug is coming from the hard-coded way to select and rotate a tile not handling every cases properly.
It is feasible but will require some tests as breaking something else will be easy here. :)

**Comment by Danimal696** [comment]
Yes, a replacement for walls and its code is on the todo list for the future
