### ISSUE TITLE
Some beds are misplaced

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#243]
The Orc and Lizard beds are placed south of where they should be.
It might comes from two things. The bed has got either a wrong default orientation, or isn't centered on the 2 tiles:
![odscreenshot_1413704495](https://cloud.githubusercontent.com/assets/765917/4692463/efdf543a-5764-11e4-83cf-55fd70b321b7.png)

~~The two beds models should be checked against the Bed.mesh one and get same alignment and default rotation value.~~
~~Could you do it, @Danimal696 ?~~
EDIT: The models are ok, the bug must be in the code.

**Comment by Danimal696** [comment]
they were, i used the values of bed to center them

**Comment by Danimal696** [comment]
did you  set their values to be "BedDim 1/2" 1x2 on creature.def? this is how i see them in my game
![new beds](https://cloud.githubusercontent.com/assets/8299756/4689529/fcd320be-56be-11e4-8cfc-1e0296778c69.png)

**Comment by Bertram25** [comment]
Ah ok. :) Then it seems the error doesn't come from the models. My apologies. :S 

I'll give a screen shot asap.

**Comment by Bertram25** [comment]
Here is an example of what is happening on my end:
![odscreenshot_1413704495](https://cloud.githubusercontent.com/assets/765917/4692463/efdf543a-5764-11e4-83cf-55fd70b321b7.png)

**Comment by Danimal696** [comment]
wierd ill upload my .def and you tell me

**Comment by Danimal696** [comment]
i want a second opinion! could someone else besides Bertram confirm the same error?

http://forum.freegamedev.net/viewtopic.php?f=45&t=4765&p=60315#p60315

**Comment by Bertram25** [comment]
This might also be a regression due to the new creature definition format. I'll have a look. :)

**Comment by Bertram25** [comment]
@Danimal696 With the new rolling release out, could you tell me how beds do behave now? Thanks!

**Comment by Danimal696** [comment]
they are still misplaced,
1x1 bed OK 
1x2 bed the center in the same place as a 1x1
2x2 the center is in the same place as a 1x1 would be

**Comment by Danimal696** [comment]
![opendungeons 2014-11-03 18-21-32-038](https://cloud.githubusercontent.com/assets/8299756/4886633/ff9ab6ba-637d-11e4-84de-1a7d34bd9f05.png)

**Comment by Bertram25** [comment]
Thanks! This simple example really helps! :)

**Comment by hwoarangmy** [comment]
I had seen that in the good way. Previously, creatures used to go at bottom left to sleep. Now, they go at center. I thought it was an improvement but it seems like it is a bug. I don't know when we introduced that (maybe while playing with the renderer ?) but I would say it comes from the beds being centered now.

**Comment by akien-mga** [comment]
> I would say it comes from the beds being centered now.

Judging from the screenshot, it seems the beds are centered on one tile, independently of the number of tiles that they are supposed to cover. Is it because they are placed on active spots?

**Comment by hwoarangmy** [comment]
No, dormitory is a special room and active spots were never used there. Beds are on empty tiles. But when I look at the screenshot, I would say they are centered on the bottom left tile (where the creature used to sleep) instead of the center of their place.

**Comment by Danimal696** [comment]
that the creature sleep at his center is good and something i would request on the future, but not in this way...

**Comment by Bertram25** [comment]
What I have seen so far is that creatures getting a bed location are usually taking the most left-bottom one available, while the code is correcting the mesh location as if the tile chosen was forcefully the top-right one.
