### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#246]
I've checked if there were memory leaks on GameEntity and I've fixed the only one I've seen.
But I've not checked for non-GameEntity.
I propose to do an instrumentation that would check memory management (a little bit like it is done for angel script) by adding the filename and file line when a memory block is allocated. To use it, it would be needed to use a macro to allocate memory instead of the new operator (something like OD_NEW).
The good point is that we would be sure to not have memory leaks and we could even add a signature at begin/end of blocks to check for memory corruption.
@Bertram25 , @oyvindln Do you want to use that or shall we use some kind of external tool ?

**Comment by Bertram25** [comment]
Hey, :)

I'll be honest, before putting out the rotary gun to kill memleak or corruption, I'd request some more standard measures before touching something very sensitive, and making it harder to read to any other standard c++ projects. I say that fully knowing the new operator is a general filler and can't be best one for everyone. But I'm just asking to take a special amount of care when touching global operators.

Out of curiosity, what are the reasons making you wonder about this?
Have you tried run the game through valgrind first?

**Comment by oyvindln** [comment]
I think it would be a better idea to try to use smart pointers (or stack objects where appropriate) if we want to make sure memory is released properly, rather than messing with an OD_NEW construct. C++11 has Unique_ptr and move constructors which makes it possible to be quite explicit about ownership.

**Comment by Bertram25** [comment]
> if we want to make sure memory is released properly, rather than messing with an OD_NEW construct. C++11 has Unique_ptr and move constructors which makes it possible to be quite explicit about ownership.

Yep, that is true as well. If something has got a weird life cycle, we can either try to simplify it (the best option), or use smart pointers if it's hard to do, IMHO.

**Comment by hwoarangmy** [comment]
> Out of curiosity, what are the reasons making you wonder about this?

It"s just that I've seen a memory leak and I wondered if we wanted to go further

> Have you tried run the game through valgrind first?

valgring only works on linux AFAIK and I don't have a linux machine that can run OD.

> I think it would be a better idea to try to use smart pointers

I'll be honest, I don't like smart pointers very much (which can be pretty strange from someone who comes from the java world). When coding with C++, I prefer to handle that myself.

But NVM, if you don't want to do that (which I understand), I will close this issue.

**Comment by Bertram25** [comment]
> I'll be honest, I don't like smart pointers very much (which can be pretty strange from someone who comes from the java world). When coding with C++, I prefer to handle that myself.

I'll be honest as well, I like your reasoning and prefer people to use the simplest tools as long as they suffice.

> valgring only works on linux AFAIK and I don't have a linux machine that can run OD.

I wondered whether you could try out free tools for windows, such as Dr. Memory or VLD: http://drmemory.org/
http://vld.codeplex.com/

A lot of tools are listed here also: http://stackoverflow.com/questions/413477/is-there-a-good-valgrind-substitute-for-windows

Hopefully, those tools will help were the language fails.

**Comment by hwoarangmy** [comment]
FYI, I've also tried to use a profiler for curiosity (I wanted to see if it worked with C::B) and I've seen that we spend much time refreshing the minimap. It's just a remainder as until we have no problem, I think there is no need to optimize too much (even if I wasn't expecting minimap to be the most CPU time consumming).
I talked about this memory instrumentation because I was playing with those kind of tools ^^

**Comment by Bertram25** [comment]
> FYI, I've also tried to use a profiler for curiosity (I wanted to see if it worked with C::B) and I've seen that we spend much time refreshing the minimap. It's just a remainder as until we have no problem, I think there is no need to optimize too much (even if I wasn't expecting minimap to be the most CPU time consumming).

Funny, indeed. valgrinding and profiling will be something we'll have to consider eventually from time to time, so it's cool you already played with those tools. :) I guess it was gprof under C::B ?

**Comment by hwoarangmy** [comment]
BTW, since @oyvindln is in this discussion and we have already talked about that, I've started to look at entities memory management because I changed the way they are deleted on client side. Now, they are handled like on server side (not deleted by the render manager anymore). So I wanted to make sure I had not broken too many things ^^

> I guess it was gprof under C::B ?

yes

**Comment by Bertram25** [comment]
> Now, they are handled like on server side (not deleted by the render manager anymore). So I wanted to make sure I had not broken too many things ^^

Ah, this is cool :) I guess it's linked to future simplification in the render manager we talked earlier?

**Comment by hwoarangmy** [comment]
> I guess it's linked to future simplification in the render manager we talked earlier?

Your guess is good ^^

**Comment by hwoarangmy** [comment]
As said, we will use external tools to check memory. No need for an implementation. I close the issue
