### ISSUE TITLE
Made OD follow paths policies on Windows, Mac and Linux.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#25]
At the moment, the game app is writing log files and shader debug data in the same place that it is running.

While this is useful when debugging, this should not happen on release mode and follow system standard data paths instead.
User saved games should also do the same.

**Comment by akien-mga** [comment]
Some details about the paths to use on Linux (and Mac?): http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
Basically config files should go in XDG_CONFIG_HOME/OpenDungeons (or lower case name, depending on what we decide for the linux binary in #57) i.e. ~/.config/OpenDungeons, and user data (saves and custom maps or custom tilesets, etc.) should go to XDG_DATA_HOME/OpenDungeons i.e. ~/.local/share/OpenDungeons.

**Comment by Bertram25** [comment]
As told in a743cb2:

The ogre.cfg and other cfg files should be in: ~/.config/OpenDungeons
Later, the saves should be in: ~/.local/share/OpenDungeons

Such paths shouldn't be hardcoded but rather taken through XDG\* variables using getenv() when possible.
I'll deal with this issue while I'm on such things anyway.

**Comment by Bertram25** [comment]
Ah, to be clear about it, I'll let the code setting paths for Mac as is. I can't test that one since I don't own a mac. I'll deal with windows and linux, though.

**Comment by Bertram25** [comment]
@oyvindln On developer builds, when the data path is overriden to "./". Do you think I should also make it so the ShaderCache should be written there, too? Or should I let it written to: ~/.local/share/opendungeons/ShaderDataCache/ instead?

**Comment by akien-mga** [comment]
IMO, everything should be in the source tree for developers builds.

But then the question would be, what about end-users who compile the game themselves and run it in the source tree? I think we can expect them to run a "sudo make install" and make their build a "non-developer" build. If not, well let them have the save games and everything in the build tree, it's probably simpler that way (and then we developers can do as many builds and saves and caches as we want without wreaking havoc in our ~/.local/share/opendungeons folder where we have our on-going playthrough of Danimal's latest awesome campaign :-P

**Comment by Bertram25** [comment]
You have a point. :) Ok, I'll do that.

**Comment by akien-mga** [comment]
Actually it's not that bad to have the settings in ~/.local/share/opendungeons on developer builds (it is the current behaviour IINM). I like that I don't have anymore to set fullscreen to no and the resolution to a smaller one each time I run a clean build :-P

**Comment by akien-mga** [comment]
As far as I can tell, the only file that gets written to the runtime directory now is CEGUI.log. It should be written in ~/.local/share/opendungeons.

**Comment by Bertram25** [comment]
True, and opendungeons.log, too.

**Comment by Bertram25** [comment]
> Actually it's not that bad to have the settings in ~/.local/share/opendungeons on developer builds (it is the current behaviour IINM). I like that I don't have anymore to set fullscreen to no and the resolution to a smaller one each time I run a clean build :-P

So, the resource.cfg and ogre.cfg plugin files should be put there. But maybe with a fallback to "./" then?

**Comment by akien-mga** [comment]
If I think in terms of end user, I want to use the config files in the XDG path, and overwrite them if I change a parameter.

As a developer, I don't want to override them each time I test something new. But I might like it to have a default config in the XDG path that can be applied to new builds.

Thus I would propose to put the cfg files in the XDG path, but in the case of developer builds, it should:
- Check whether the required file exists in ./
- If it does, use it (and modify it if need be)
- If it doesn't but it exists in the XDG path, copy the latter to ./, and then use and modify the copy
- If it doesn't and is not in the XDG path, create it in ./

WDYT? Is it too far-fetched maybe?

**Comment by Bertram25** [comment]
Hey. :)

What cfg files are you talking about precisely talking about?
- ogre.cfg?
- plugins.cfg plugins_d.cfg?
- resources.cfg resources_d.cfg?
- Other ones?

Secondly, I'd drop this line:

> If it doesn't but it exists in the XDG path, copy the latter to ./, and then use and modify the copy

We are developers after all, so the file can be created locally if it doesn't exist but I'm not fond fiddling with user files. To me, developer builds and installed build should if possible not mingle too much. Especially when you'll later have 0.4.9 installed while already working on 0.5.1 for instance, since a lot might have changed in configuration due to a number of reasons. (Ogre version change, new settings system, ...)

So my proposal would then remain: To use game data in ./ if files exist there and if not, use standard game data path.
For cfg files, do the same.
For user custom map, use home data path (so we can test the standard behaviour in a user point of view).

Feel free to correct me where you think I may be wrong, of course. :)

**Comment by akien-mga** [comment]
> What cfg files are you talking about precisely talking about?

Good question :-) I guess I'm speaking about all config files + logs (e.g. CEGUI.log and opendungeons.log).

BTW while we're talking about config files, what is resources.zip.cfg used for?

> We are developers after all, so the file can be created locally if it doesn't exist but I'm not fond fiddling with user files. To me, developer builds and installed build should if possible not mingle too much.

I agree with your point, but then:

> So my proposal would then remain: To use game data in ./ if files exist there and if not, use standard game data path.

This doesn't sound right. As you said it, the developer build might be 0.5.1 when the system version (the one making use of the ~/.local/share/opendungeons path) might be 0.4.9. So let's settle for:
- Developer builds _always_ use their own config files: they should be created anew if they are not in ./

Agreed for user custom map. What about saved games?

**Comment by Bertram25** [comment]
> Developer builds always use their own config files: they should be created anew if they are not in ./

You have a point. I agree.

> What about saved games?

Good question also. :) Technically, I'd like to have save game being level files with the necessary info to load a game "state". The only missing part AFAIK atm, being some creature stats I guess and script variables states. Now you've discovered all the evil plan, I'll need to make you forget about all this in a way involving ropes and whips. >;)
Anyway, I think save games should have a game version parameter, just like levels have, and thus be handled just as custom levels also. (If the game version isn't supported, we don't show/use it.)

Feel free to complete me, it's cool to be able to improve things by sharing ideas and constraints. :)
