### ISSUE TITLE
Creature spawning conditions support

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#257]
Split out of #11 

One of the most needed feature to make 0.4.9 feel more complete, the creatures shouldn't come out of the portal at random but rather based on conditions, such as room size or gold, and later why not weapon ability or a keeper skill.

This would also add a purpose to build a forge and a library, btw. :)

Spawning conditions should be parsed in the config/creatures.cfg file with a format such as this one:

```
[SpawnConditions]
# Room: <RoomName> <Active spots needed to consider spawning>
Room Library 3
Room TrainingHall 1

# Gold <minimum gold to attract>
Gold 2000

# Later: Skill needed to consider spawning
# Skill CraftLv2

# Later: Weapon forged
# Weapon LongSword 1
[/SpawnConditions]
```

**Comment by Danimal696** [comment]
While everything looks pretty good, isnt it a bit weird being attracted to a weapon? The up side of that is that its a reason to put the forge to work at making new weapons

**Comment by Bertram25** [comment]
It's as you wish, I just copy-pasted what was earlier discussed. The scope of this issue is to add room conditions, I even wonder whether adding a gold condition is relevant. What do you think?

**Comment by hwoarangmy** [comment]
> While everything looks pretty good, isnt it a bit weird being attracted to a weapon?

Well, that's also what I thought at first but after all, why not ? I think all the reasons to not use the weapons will work for gold...

> the up side of that is that its a reason to put the forge to work at making new weapons

the down side is that it is not implemented at all ;)
And if you ask the code guys to do that, we will ask for corresponding animations ^^

> I even wonder whether adding a gold condition is relevant

If we remove gold and weapon conditions, there will be not much conditions left. But to be honest, I don't really care so if you feel like removing them, do so ^^ Anyway, we can add them later if needed so if you think it will be time consuming, just skip it.

An idea :
We could use a system with points that would allow or not spawning. Something like for the mood system :

```
[SpawnConditions]
#Room: <RoomName> <minimum active spots needed to consider spawning> <points per activespots>
Room Library 3 5
Room TrainingHall 0 5

#Gold: <Minimum gold to attract> <Points per 100 gold>
Gold 5000 2

#Creatures: <class> <Minimum to attract> <points per creature>
Dragon 2 2
Troll 0 -5
[/SpawnConditions]
```

If the spawn conditions have more than for example 20 points, we consider spawning. That would allow to have non fatal negative modifiers.
What do you think ?

**Comment by Danimal696** [comment]
thats actually not bad, it means we can still get weak creatures even with a few rooms already built.
The issue with the weapons is that they will most likely be used by creatures once created, will it still count if a creature equips it? and what happens to the equiped weapon if the creature dies? gamer sense tells me it should just disappear

**Comment by hwoarangmy** [comment]
> The issue with the weapons is that they will most likely be used by creatures once created

Logic tells me to not consider used weapons. Because :
- It's the same for gold : once used, it will not be considered
- If a creature comes because there is a weapon, it is because she wants to use it. If it is already used, I don't see why it would be attracted

If the creature dies, we can consider the weapons are used and can be destroyed

**Comment by Danimal696** [comment]
good points

**Comment by Bertram25** [comment]
Right, let's remove weapon and gold then. :)

The spawning point system is something interesting, but I'd like to ask a few details on what we want first:
- What we agree: Based on the conditions, a creature can spawn if the minimal conditions are met and the creature is in the player's spawn pool.
  Once the conditions are met, how should handle spawning:
- At random between the permitted creatures?
- Based on points, but how?
  - At random but pondered by creatures' points?
  - Something else ?

**Comment by Bertram25** [comment]
I like the fact spawned creatures change the attraction, but I'll need more details on the how we handle that. :)

**Comment by hwoarangmy** [comment]
> At random between the permitted creatures?

IMHO : yes. Why ? Because it's simple.

> I like the fact spawned creatures change the attraction, but I'll need more details on the how. :)

That's where spawning points are interesting

**Comment by Bertram25** [comment]
What I'm still lacking about that one, is if you think we should use a fixed barrier, such as 20 points like you said, or if you had something else in mind.

**Comment by hwoarangmy** [comment]
To be honest, I think spawning considering points sounds logic. If you build a big library, it seems normal that more wizards would come than if you build a minimum library. But that would be more complex so if you feel like mesing with that, IMHO, it would be better. But if you prefer a simple approach, it should be enough IMO.

**Comment by Bertram25** [comment]
I'm more than fine with the system approach, really. :)

What I'm trying to get is how we determine the number of points necessary for a creature to spawn. :) Is a fixed value ok? (I would do that as a first attempt and set it to 20 as an harcoded value.)

**Comment by hwoarangmy** [comment]
If you want headaches, let's go for that ;-)
A creature can spawn as soon as the needed values are ok (minimum values in our file). But its probabilities to spawn should be bigger when you have more things that it likes.
A simple approach could be to count the total points of spawnable creatures and choose a random number between 0 and this total. Then, spawn the creature concerned.

For example, lets say we have 3 creatures only that meets their minimum requirements : spider, troll and gnome.
spider has 50 points, troll has 30 points and gnome 70 points.
Total = 50+30+70 = 150.
You take a random number between 0 and 150. if between 0 and 50, a spider spawns. If between 50 and 80, a troll spawns. If between 80 and 150, a gnome spawns.
That would make not too complex the spawning system (even if it has to be refreshed often - maybe not at every turn if it seems too long).
The main problem will be to balance between all creatures because with this system, if a creature gets too many points, it will be the only one to spawn so we will need to choose values carefully.

BTW, points have to be considered as doubles so we can define with precision how creatures spawn.

A weak point that I can see with this technique is that if a creature needs a lot of things (several active spots from several rooms), its spawn probability will be high when its minimum requirements will be met.
If you feel it is a problem, you can also change the way points are computed between needed and additional modifiers are handled. For exemple, we can consider that every creature that meets its requirements have a spawn probability set to 10. And the points in the def file will only apply to additional needs. For exemple, if we take :

```
[SpawnConditions]
#Room: <RoomName> <minimum active spots needed to consider spawning> <points per activespots>
Room Library 3 4
Room TrainingHall 0 2
[/SpawnConditions]
```

If the dungeon have 5 library active spots and 5 training active spots, this creature will have 10 + (5-3) \* 4 + 5 \* 2 = 28 points

**Comment by Bertram25** [comment]
> For example, lets say we have 3 creatures only that meets their minimum requirements : spider, troll and gnome.
> spider has 50 points, troll has 30 points and gnome 70 points.
> Total = 50+30+70 = 150.
> You take a random number between 0 and 150. if between 0 and 50, a spider spawns. If between 50 and 80, a troll spawns. If between 80 and 150, a gnome spawns.

Ok, so it would at random based on weighted values.

> If the dungeon have 5 library active spots and 5 training active spots, this creature will have 10 + (5-3) \* 4 + 5 \* 2 = 28 points

I do also think the weighting should be checked minus the minimum requirements, with one exception:
That the first time you meet the expectations, the given creature appears next in order of minimal requirement fulfillment. 

Would this be ok?

**Comment by hwoarangmy** [comment]
> That the first time you meet the expectations, the given creature appears next in order of minimal requirement fulfillment.

Sorry, I don't get that. Could you explain ?

**Comment by Danimal696** [comment]
say, you build your first forge, and next creature is a blacksmith, then build a Cript and next creature to appear is a ghost; its like you get a 100% chance to get the creaure that the rooms spawns just one time after being built.

> Right, let's remove weapon and gold then. :)

No no no, you misunderstood, we want those in, we were just discussing in which cases a creature is attracted to a certain equipment piece.

**Comment by Bertram25** [comment]
> Sorry, I don't get that. Could you explain ?

What @Danimal696 said above. :)  You get a 100% chance to spawn the creature the first time you meet the requirements. It complicates the thing but will help visually debug it and make the player happy, IMHO.

> > Right, let's remove weapon and gold then. :)
> 
> No no no, you misunderstood, we want those in, we were just discussing in which cases a creature is attracted to a certain equipment piece.

Ah ok, I'll readd those in the description, but consider the fact that I won't implement the weapon condition for 0.4.9, ok? :)

**Comment by hwoarangmy** [comment]
> but consider the fact that I won't implement the weapon condition for 0.4.9, ok? :)

Since there are no stored weapon, I guess it is an acceptable demand ;-)

**Comment by Bertram25** [comment]
> Since there are no stored weapon, I guess it is an acceptable demand ;-)

You don't know how evil @Danimal696 can be. ;P

**Comment by Danimal696** [comment]
or worse! i guess the armory room can be reality later to store created weapons.

**Comment by Bertram25** [comment]
> i guess the armory room can be reality later to store created weapons.

IMHO, the forge slots should be used for that, somehow. Otherwise, how would the weapons be stored if you don't have the armory yet?
Maybe the armory should permit to have advanced forged stuff instead?

**Comment by Danimal696** [comment]
Thats the idea, you can only make weapons at the forge when you research "armory room" (that also unlocks the weapons Lv2) for stronger weapon (lv3 and Lv4) you need other researchs

**Comment by Bertram25** [comment]
> Thats the idea, you can only make weapons at the forge when you research "armory room"

Then, what can you make at the forge when you have researched nothing else? Traps?

**Comment by Bertram25** [comment]
@hwoarangmy Since you've dived very deeply in config and creature definition management, I wondered:
It is obvious unfortunately for me that I won't be able to write a line on this issue before a few days. Do you want me to let this one to you ? (since it will be necessary before providing a Win32 binary so @Danimal696 can test and everyone can start balancing the game.), or are you ok if I'm still on it?
I just don't want to get in your way in case you have the time and the will to take it. :)

**Comment by Danimal696** [comment]
> Thats the idea, you can only make weapons at the forge when you research "armory room"
> -Then, what can you make at the forge when you have researched nothing else? Traps?

Traps and doors, its just an idea, but weapon forging can be something unlockable, you start forging weapons of the researched quality, and once you research a better quality those became available as well.

**Comment by hwoarangmy** [comment]
> Do you want me to let this one to you ?

It is as you want. As we've already said, OD is a spare time project so it can wait if for some reason, you don't have time to work on it. But if you want me to put my claws on this one, I can relieve you.

**Comment by Bertram25** [comment]
> Traps and doors, its just an idea, but weapon forging can be something unlockable, you start forging weapons of the researched quality, and once you research a better quality those became available as well. 

I do think it's a good idea, as for me. :)

> It is as you want. As we've already said, OD is a spare time project so it can wait if for some reason, you don't have time to work on it. But if you want me to put my claws on this one, I can relieve you.

Thanks. :) Well, it depends only on you but you have my leave to bite this one if you want. The goal is to provide a common release suitable to start balancing first.
We'll be able to deal with the remaining issues and the AI in the meanwhile. :)

**Comment by hwoarangmy** [comment]
Ok. Then, I unassign you from this issue and if I feel like stealing it from you, I will assign myself. If you wanna take it before I do, just re-assign it ^^

**Comment by Bertram25** [comment]
eh eh, ok. :)

**Comment by hwoarangmy** [comment]
I am inspired, I will steal it ^^

**Comment by Bertram25** [comment]
Good, I'll find something else to play with, don't worry. ;)

**Comment by hwoarangmy** [comment]
I've been thinking about the spawning conditions and after all, I think that it may be better to use a different file from creatures.cfg because:
- For each creature, there will be spawning conditions. That means that we will have spawning conditions everywhere in creatures.cfg since a creature definition is quite big so it will not be easy to read (and it is a file supposed to be edited manually).
- Adding them in creatures.cfg implicitly makes them overridable since they are within the creature tag. IMHO, it doesn't make sense to change in a level the conditions to get a creature. Even if I agree it could serve a few times, it sounds more like a design error to me.

If we choose to not allow changing spawning conditions, that will lead us to the problem of creatures created in a level. For them, I see 3 choices:
- Not allow level defined creatures to spawn (you can use them as creatures at map load but they will not spawn through portal)
- Allow to define specific spawning conditions
- Allow to use an existing spawning pool

@Bertram25 , @Danimal696 , @akien-mga , @oyvindln What do you think ?

**Comment by Bertram25** [comment]
> Not allow level defined creatures to spawn (you can use them as creatures at map load but they will not spawn through portal)

After thinking about this for a while, I personally think it would much simpler if we don't allow them to spawn, except through events maybe. Other choices will make the design more complicated for rare needs, IMHO.
That said, a script should be able to later spawn them for scenario or events needs. (and that's not linked to spawn pools so there should be no later problems.)

**Comment by hwoarangmy** [comment]
> After thinking about this for a while, I personally think it would much simpler if we don't allow them to spawn, except through events maybe

Yes, that's also what I had in mind ^^

@Bertram25 Since you have already had a though about it, what do you think of using another file ?

**Comment by akien-mga** [comment]
> That said, a script should be able to later spawn them for scenario or events needs. (and that's not linked to spawn pools so there should be no later problems.)

As long as they can be spawned through scripts, I guess that's enough.
The use case I have in mind would be mostly for tutorials or some campaign scenarios.

**Comment by Bertram25** [comment]
> @Bertram25 Since you have already had a though about it, what do you think of using another file ?

I see no problem about it. And it clearly makes it obvious this can't be overridden. May add a note about it in the file header, for instance?
I'll also request that the file is self-documented if possible (using doc comments in the header). :)

**Comment by hwoarangmy** [comment]
> I'll also request that the file is self-documented if possible

I am a copy/paste master and I will gladly use my power to copy one of your config files and change the header documentation ^^

**Comment by Danimal696** [comment]
> Not allow level defined creatures to spawn (you can use them as creatures at map load but they will not spawn through portal)

Im all for declaring all creatures :P

**Comment by hwoarangmy** [comment]
> Im all for declaring all creatures :P

Yes. I guess using that to declare only bosses is enough ^^
Good, I'm almost done. I will create another PR as soon as my current one is OK.

**Comment by Bertram25** [comment]
The former one is merged :)

**Comment by hwoarangmy** [comment]
ok. As promised, I will upload the fix for this one ^^
