### ISSUE TITLE
Potential starving / drowsiness handling

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#260]
Hi there,

I've noticed several times that my creatures could fight even with a hunger at 100 and/or an awakeness of 0. That's because they win a bad mood test and have 80% to fight in that case.

Let's define starving as Hunger = 100.0
and Drowsy as Awakeness = 0.0

I think this kinda shows a few potential improvements needs:
- The hunger growth and awakeness loss per turn probably need to be tweaked because at the moment, the creatures aren't in a good shape for long. (but that's part of #152 #153)
- The creatures should maybe stop auto-healing when drowsy or starving?
- Should they lose HP for instance when starving?
- Should they never win a bad mood test when they are either starving or being drowsy?
- Something else?

What do you think?
@hwoarangmy @akien-mga @oyvindln @Danimal696

**Comment by hwoarangmy** [comment]
If I remember well last time we talked about that, it has been said that drowsy/starving should fight (that's the reason behind the 80%). We said that it should play on mood and that would be the reason why the keepers will have to try to have happy creatures. Otherwise, they might leave the dungeon when the mood system will be there.
IMHO, it is an interesting improvement but not a top priority for the next release. For now, there is already the 20% Fleeing probability handicap.

**Comment by Danimal696** [comment]
i think its enougth as well, they are mostly spending their lives between the hatchery and dormitory anyways instead of training. we cant made them even more useless in battle.

> The creatures should maybe stop auto-healing when drowsy or starving?
> Should they lose HP for instance when starving?

I say no, else all feral creatures on map would eventually die of hunger/sleep deprivation

**Comment by Bertram25** [comment]
> I say no, else all feral creatures on map would eventually die of hunger/sleep deprivation

True. We said earlier that we could create feral creature that don't need to eat, but this would require creating duplicate creature definitions for feral ones or add yet another option. Thus, my point is indeed irrelevant.

> If I remember well last time we talked about that, it has been said that drowsy/starving should fight (that's the reason behind the 80%). We said that it should play on mood and that would be the reason why the keepers will have to try to have happy creatures. Otherwise, they might leave the dungeon when the mood system will be there.
> IMHO, it is an interesting improvement but not a top priority for the next release. For now, there is already the 20% Fleeing probability handicap.

Ok, then it is clear now why creatures shouldn't die per starvation, but might later leave if too much bad conditions are gathered. I'll close the issue. Thanks for your answers. :)
