### ISSUE TITLE
Worker behaviour: gold stacks should be fetched in priority

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#261]
I think recovering gold stacks is already high in the priority list of workers, but I noticed a case in which they seem to ignore it: if you don't have a treasury tile when they dig gold, the gold stack is left on the ground. When you build a treasury tile afterwards, you would expect the kobolds to fetch the gold instead of e.g. claiming tiles or walls, but they don't, even if you drop them on the gold stack.

Gold stacks can be picked up by the keeper, but the kobolds should retrieve it too.

To reproduce:
Start "Scream in the dark" and dig gold before creating a first treasury tile. Then create a treasury tile.

**Comment by hwoarangmy** [comment]
This behaviour is not implemented at all. I also think it would be nice to do that but it is not a priority for the next release IMHO.

**Comment by akien-mga** [comment]
Agreed.

**Comment by Bertram25** [comment]
It's so fun to take them by hand away from your opponents ;). (Maybe I'll eventually grow bored of it but not yet. ;])

**Comment by hwoarangmy** [comment]
And I would add that it is a reason to try to get claimed tiles to reach the gold stacks before your opponent does (even if it is not a great challenge vs AI) ^^

**Comment by Bertram25** [comment]
Yeah, beware on our next lan, @akien-mga the ArchLich is known to steal gold and put it in his cannon to increase damage when shooting on captured Keepers. ;)

**Comment by hwoarangmy** [comment]
@akien-mga the ArchLich will never steal my gold because :
1 - I know the cheat code to give and steal gold
2 - I know the cheat code to make his creatures go directly in my traps

I am unbeattable \o/

**Comment by Bertram25** [comment]
Cheats should definitely be disabled in lan or I will be too tempted ;)
