### ISSUE TITLE
Find @hwoarangmy

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#264]
It looks like @Bertram25 crushed him for real in their last LAN...

**Comment by Bertram25** [comment]
I swear I didn't!! And I do apologize if I caused his departure for any reason O.O' :cry:

**Comment by Bertram25** [comment]
A forum topic has been opened there:
http://forum.freegamedev.net/viewtopic.php?f=35&t=5936

**Comment by akien-mga** [comment]
Don't worry, I don't see how you would have offended him in such a fashion that he would erase himself from github. And I'm pretty sure he would have expressed any kind of discontentment publicly before doing something rash. So it's likely just a technical issue.

**Comment by hwoarangmy** [comment]
I've answered in the forum

**Comment by Bertram25** [comment]
Seems @hwoarangmy was stated as a robot by github itself. Hopefully, they'll agree to make him come back as a human entity soon.

**Comment by akien-mga** [comment]
Hm, I bet he started working on the AI and github thought a robot was trying to improve AI algorithms to build a world dominating by AIs!

**Comment by Bertram25** [comment]
> Hm, I bet he started working on the AI and github thought a robot was trying to improve AI algorithms to build a world dominating by AIs!

In that case, that would make us people of interest. ;)

**Comment by Bertram25** [comment]
@hwoarangmy is back into the human category. Welcome back. :D
