### ISSUE TITLE
Add support to allow a creature definition extend another one

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#265]
Add an optional "BaseDefinition" parameter in creatures.cfg file. If it is found, the definition will be initialized with the BaseDefinition and the parameters under [STATS] tag that are be present will be overriden.

Note 1: if this parameter is used in the creatures.cfg, the base definition should be defined previously.
Note 2: this parameter allows to change definitions from the creatures.cfg file only. If a class is tuned in a level file and the same class is used as a base class, the parameters from the original one will be used, not the modified ones
Note 3: It is not possible to extend a class defined in a level.

**Comment by hwoarangmy** [comment]
The patch is done. It allows:
- To create a creature/weapon class from another one in the corresponding def file (note that the extended class should be defined before):
  In creatures.cfg, add at the end of the creature definitions:

```
[Creature]
    Name    BigKnight2
    BaseDefinition  BigKnight
    [Stats]
    MinHP   12
    [/Stats]
[/Creature]
```

That will create the new class that can be used like any other (and even modified in the level file)
- As said in the base message, note that it is not possible to extend a class created in a level file.

**Comment by Bertram25** [comment]
I'm testing atm... The whole thing is cleaner with the baseDefinition parameter handling :)
