### ISSUE TITLE
Cave hornet's wings aren't translucent

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#267]
Must come from something that broke while upgrading material files. I'll be on that.

**Comment by Bertram25** [comment]
The whole cave hornet is translucent on windows according to @Danimal696 . So the actual solution is to separate the wings and the body into two models using different materials.
Care to do it @Danimal696 or should I simply revert?

**Comment by Danimal696** [comment]
let me try separating first

**Comment by Danimal696** [comment]
a problem here; separating means two meshes, can the two of them be loaded at the same time?

**Comment by Bertram25** [comment]
> a problem here; separating means two meshes, can the two of them be loaded at the same time?

The golem worker seems to be using different material files for different parts:
https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/scripts/Construct_ReflGold.material
https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/scripts/Con_Worker.material

The separation may indeed be not with different model files, but is it possible to do the same here, for instance? I'm still learning here but it seems models can have different sub-entities, such as the water models (and we're using this to turn them into lava when necessary), so maybe we can play with that, too?
E.g.: https://github.com/OpenDungeons/OpenDungeons/blob/development/source/render/RenderManager.cpp#L264

**Comment by Bertram25** [comment]
Assigned to @Danimal696 since I assume he'll be on the sub-entities separation.

**Comment by Danimal696** [comment]
yes, ill take care of it eventually

**Comment by Bertram25** [comment]
Feel free to reassign to me once you're done. :)

**Comment by Bertram25** [comment]
For now, I'll revert the cave hornet material. Once this is done, I'll move this issue to Later as it's not a 0.4.9 release blocker IMHO.

**Comment by Danimal696** [comment]
please do, my time schedule is a bit busy lately

**Comment by Bertram25** [comment]
Ok, done in my latest PR. I'm setting to Later.

**Comment by Danimal696** [comment]
Fixed cave hornet wings! they have real transparencies now
http://forum.freegamedev.net/viewtopic.php?f=35&t=5604&p=60992#p60992

**Comment by Danimal696** [comment]
i also made a cleaning of unused models and textures, im sure they were useless and anyways they will remain on media repository if needed later

**Comment by Bertram25** [comment]
> i also made a cleaning of unused models and textures, im sure they were useless and anyways they will remain on media repository if needed later

thanks, is it already online somewhere? :)

**Comment by Bertram25** [comment]
> i also made a cleaning of unused models and textures, im sure they were useless and anyways they will remain on media repository if needed later

Nevermind, I saw all the commits. Time to learn how to do PR @Danimal696 ;P
I'll fix the CREDITS file accordingly.

**Comment by hwoarangmy** [comment]
wow, I had not seen @Danimal696 was commiting directly the main repository. Please try to have a look on how to fork the repository and to make a PR. If needed, we will happily help you. But commiting the main repository is definitely not what should be done. If someone forks the repository while you are updating, he might get a broken copy. Moreover, it would allow someone to check if there is no problem with your PR (making mistakes can happen)...

**Comment by akien-mga** [comment]
Hehe, nice set of commits :-)
@Bertram25, since you are the git guru around here ;-) maybe you could merge all those commits into a single one, to clear the history a bit? (I guess this can be done with a `git rebase -i` and `git push -f`).

**Comment by Danimal696** [comment]
upss

**Comment by akien-mga** [comment]
> upss

It's no big deal for this one, but yes it would be better next time to do it with a pull request (for example for your latest changes we would have probably asked you to do it all in one commit instead of one commit per removal).

Feel free to drop by the IRC channel, I'm often hanging around there so I can lead you through the needed steps to set up a fork, and then create a pull request.

**Comment by Bertram25** [comment]
There is also online help! :)
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/using-pull-requests/
Just in case. @akien-mga 's help is much better of course.

**Comment by Bertram25** [comment]
I'll fix history now. Please don't merge anything for the next ten minutes or so :)

**Comment by Bertram25** [comment]
All right, history is fixed :)

> @Bertram25, since you are the git guru around here ;-) maybe you could merge all those commits into a single one, to clear the history a bit? (I guess this can be done with a git rebase -i and git push -f).

Eh eh. I'm no guru ;) And you're right: that exactly how I did.

**Comment by akien-mga** [comment]
You even managed to make it appear as a commit from @Danimal696, well done. Git is great :-D
