### ISSUE TITLE
Update angelscript

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#268]
The version currently in the repo is 1 year old, and needs to be updated. However, there seems to have been some breaking changes, so some code changes are needed.

**Comment by akien-mga** [comment]
Linked with #132. I don't set it as a duplicate though because #132 also requires dropping phtreads-win32.

**Comment by Bertram25** [comment]
@Danimal696 @hwoarangmy @akien-mga Do you mind if I make @oyvindln a reviewer?
I think he should be able to assign issues to him self, and why not merge other's PR when they are fine.

**Comment by Danimal696** [comment]
how much is he bribing us for that? i say Ok if he pays good. ;)

**Comment by akien-mga** [comment]
Fine by me :-)

**Comment by hwoarangmy** [comment]
no problem if he wants to. But it may be better to ask him first ^^

**Comment by Bertram25** [comment]
Eh eh. Somehow, I am ;)

**Comment by Bertram25** [comment]
Ok to become a reviewer @oyvindln ?

**Comment by oyvindln** [comment]
sure

**Comment by Bertram25** [comment]
@oyvindln It's done. As simple rule, we try to never auto-merge the things we do, or never push directly to the reference repo, unless the fix is very trivial to do and is urgent to make the beast compile.
Apart from that, welcome ! :D

**Comment by oyvindln** [comment]
Solved now
