### ISSUE TITLE
Replace the spider with new one

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#269]
From here:
http://forum.freegamedev.net/viewtopic.php?f=35&t=5941&p=60530#p60530

**Comment by Danimal696** [comment]
i think i have read somewhere this model was giving fails? it was textured in an inconventional way, so that may be the cause. Please tell me if thats the case.

**Comment by Bertram25** [comment]
In any case, this model has got a non power of 2 texture and this might give problems on gpu without support for that. Can you fix this ?

**Comment by akien-mga** [comment]
> i think i have read somewhere this model was giving fails? it was textured in an inconventional way, so that may be the cause. Please tell me if thats the case.

The issue was something else, it was just a guess from @Bertram25 that it could be related to the new model, but in fact... PEBKAC :-D

**Comment by Danimal696** [comment]
ok, ill get to it
