### ISSUE TITLE
Tileset glitches: corners and oblique walls

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#273]
After merging @Bertram25's PR #258, I noticed some other glitches in our current tileset (at thought it was a regression, but then I checked @hwoarangmy's branch and the same issue appears).

See the following screenshot. On the second image, the faulty tiles are highlighted with great artistic skills.
![odscreenshot_2014-nov-02 14 36 29_0](https://cloud.githubusercontent.com/assets/4701338/4875397/8ff6b248-6295-11e4-83fe-4c4f6300772e.jpg)
![odscreenshot_2014-nov-02 14 36 29_02](https://cloud.githubusercontent.com/assets/4701338/4875401/a90e704a-6295-11e4-936a-d582ad1cd97f.jpg)

There are issues in:
- wall corners (with right and oblique angles)
- oblique walls
- water ponds where it should have one or more dirt corners

Note that the faulty water tiles also have a texture that doesn't really fit the rest of the pond.

It might be better to handle all this in #14, but since the latter means quite some work, I open the issue to as a "nice to have" for the upcoming 0.4.9 or 0.5.0 releases.

**Comment by Bertram25** [comment]
Hey :) I'm embarrassed with this issue as I'm not even sure we've got the necessary models for that. I'd say we should first check the available tiles with some thing like meshy or something. Then, can Danimal or Skorpio make the missing ones ?

**Comment by Bertram25** [comment]
@Danimal696 Help?

**Comment by Danimal696** [comment]
that is pretty annoying, i could try and have a look at the unported tiles to expand some borders, but the real solution would be a simpler tileset, needless to say that would be a huge job i would prefer to leave for later. For now im trying to get more content in but ill dig it.

**Comment by Bertram25** [comment]
Forgot to assign @Danimal696 since he'll look into the models sooner or later.

**Comment by Bertram25** [comment]
I'm sure @Danimal696 just fixed that one. What's left is to upgrade the model version and fix the the lava and water animation (But that's another issue I'm going to open.) - #694
Edit: Fixed with: 069d042267c3ede31e3fed7a659b7510d4ccd7d9
