### ISSUE TITLE
devel_tools/ and documentation/ content seems obsolete

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#276]
Hi there,

On both those folders, there seem to be quite outdated stuff.
@oyvindln @tomluchowski @hwoarangmy @akien-mga @Danimal696 Could you all have a look and tell me what we can get rid of?

**Comment by oyvindln** [comment]
Devel_tools is some source paul424 was working on, don't think it's of much use any more.
As for the documentation folder:
The thread model picture is outdated, so it can be removed if we don't want to keep if for historical purposes.
Doxyfile is for generating doxygen documentation, don't know if anyone uses that or not, the logo is also used in that.
The map I think is from some background story idea, it probably would belong in the media source repository.

**Comment by Bertram25** [comment]
@oyvindln  thanks for the info.

> Doxyfile is for generating doxygen documentation, don't know if anyone uses that or not, the logo is also used in that.

There is also a doxyfile along the source:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/Doxyfile
IMHO, the one in documentation can be removed.

> Devel_tools is some source paul424 was working on, don't think it's of much use any more.

AFAIK, the Small event system shouldn't be of use since we're planning to do events in scripts.
And the HCS has been integrated into the code, even if rather useless atm.

> The thread model picture is outdated, so it can be removed if we don't want to keep if for historical purposes.
> The map I think is from some background story idea, it probably would belong in the media source repository.

Yeah, I'd also put the old thread model in the media repo, for memory. :)

Ok with all that?

**Comment by oyvindln** [comment]
sounds good

**Comment by hwoarangmy** [comment]
For that kind of stuff, I would trust @oyvindln as he is the one with more elements

**Comment by Bertram25** [comment]
k, I'll do as discussed. :)
