### ISSUE TITLE
Spike trap (and more generally traps that covers their tile) should disable tile default rendering

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#277]
As discussed in #258 comments.
The problem is that active spots are created within doupkeep which occurs after the trap is created. We could wait for that before showing the room but IMHO, it would introduce an avoidable lag (a little bit less than 1 second) when creating a room.

**Comment by Bertram25** [comment]
I've set the Later milestone for now as it's not a release blocker, while anybody can take it, of course. :)
IIRC, you proposed to show the tile until the trap object was added, right?

**Comment by hwoarangmy** [comment]
yes
