### ISSUE TITLE
Gold dropped on the floor should follow the same mesh logic than the one in treasury rooms.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#279]
Atm, whatever amount of gold is left on dirt, the same mesh will be displayed.
An improvement would be to use the same logic about the mesh used than the one on treasury tiles, so that the player can know at a glance whether some gold piles are interesting or not.

What do you think about it? @akien-mga @oyvindln @hwoarangmy @Danimal696

**Comment by hwoarangmy** [comment]
yes it could be good

**Comment by akien-mga** [comment]
Sounds great. I already foresee a free for all map with an enormous dragon in the middle sitting on piles of gold :-D

**Comment by hwoarangmy** [comment]
> Sounds great. I already foresee a free for all map with an enormous dragon in the middle sitting on piles of gold :-D

Sounds like a good idea. Do you want to do this map ? You kill the dragon while I collect the gold...

**Comment by akien-mga** [comment]
> Sounds like a good idea. Do you want to do this map ? You kill the dragon while I collect the gold...

Hehe, I guess as long as we don't have the fog of war, it would be a race for the ones that can pick gold quickly enough :-)

**Comment by Bertram25** [comment]
I love the map idea. ;)

**Comment by Danimal696** [comment]
nice idea!
