### ISSUE TITLE
F1 Help window for new players

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#283]
Yes, there are players in the world that don't know Dungeon Keeper and even worse, certain of them don't know about OpenDungeons. ;)

That's a sad reality and the world seems not ready yet to bow before Evil Keepers while in chains and being tamed eagerly by dark mistresses.
For all those relevant reasons, a F1 text window should be added to explain the game key and the game basic functionalities. Nothing too fancy since the actual goal is to tame the world and why not make a tutorial later, but this will definitely help.

If you're ok with it guys, I'll do it.

**Comment by hwoarangmy** [comment]
Yes. A tutorial/campaign will take much too time so it'll be enough for now...
