### ISSUE TITLE
Gold behind water tiles should be diggable

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#289]
As reported by eugeneloza, should we allow and thus fix gold digging, when in the middle of water?

What do you think @hwoarangmy @Danimal696 @akien-mga @oyvindln ?

**Comment by akien-mga** [comment]
I'd say yes, since workers can swim, but with one of those two conditions:
- A bridge has to be placed so that the worker can dig while standing on the bridge, or
- The digging time should be longer

**Comment by hwoarangmy** [comment]
As long as workers can go through water, I don't see why they couldn't dig gold there...

**Comment by Danimal696** [comment]
like hwoarangmy said, the only restriction should be the natural slowness of moving over water

**Comment by Bertram25** [comment]
So if I understand correctly, we don't consider them swimming in water, but walking on it, and thus capable to dig, even from a water tile?

**Comment by Danimal696** [comment]
but if you want unpassable terrain you have already got lava, let water slowness be the only penalty

**Comment by Bertram25** [comment]
ok :)

**Comment by hwoarangmy** [comment]
I've had a look and the problem comes from floodfilling. Gold tiles behind wall are diggable. The problem in stonesiege is that there is no ground tile around. It was a wrong optimization ^^
