### ISSUE TITLE
OIS: release keyboard input when OD windows loses focus

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#293]
The described behaviour is on Linux, @Bertram25, @hwoarangmy or @Danimal696 can probably confirm this if it also happens on Windows (and add the corresponding label).

When running OD in windowed mode, if you switch to another application (typically to Firefox to comment on a github issue ;-) ), you can't type anything because OD (I guess through OIS) gets the precedence on the keyboard input. I confirmed this by opening the "Host game" menu and starting to type a nickname: if I go in another app and try to type anything, it gets added to the nickname.

Minimizing OD instead of just switching windows (i.e. clicking on the OD icon – or current non-icon, until we take care of #202 – in the taskbar) gets rid of this, and the keyboard input is given back to the desktop.

IIRC the same happens in fullscreen when leaving the application with Alt-Tab or Ctrl+Fx.

**Comment by hwoarangmy** [comment]
I have seen strange things on windows but not this one. I confirm that when I switch in windowed mode (I almost always use it), the keyboard can be use in the other applications.

The problem I've seen is more about when OD window is minimized and then, we come back, sometimes, a clic event is received from OD. But as far as I've seen, it seems to be a bug in OIS (from OD point of view, everything is right).

**Comment by Bertram25** [comment]
@akien-mga ungrabbing input is a non-default xserver option AFAIK, unfortunately.
Here is an interesting link, btw: http://www.ogre3d.org/forums/viewtopic.php?t=20690

There are options in OIS that achieve this:
http://www.ogre3d.org/tikiwiki/tiki-index.php?page=Using+OIS#Non-exclusive_input
But they seem to not work for everyone. They do for me on linux, but not for @tomluchowski for instance.

Try changing the value here to false and play the game:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/modes/InputManager.cpp#L61

If it still works, then you're lucky. :)
My only conclusion is that if we can ungrab the keyboard input (by setting false there), make tests and find workaround when and if necessary to let the game work without grabbing the keyboard, then we're out of trouble. If not, then it will be a Wontfix for me.

**Comment by Bertram25** [comment]
I proposed to add a cmake option that doesn't grab the key board on linux, disabled per default. This will help us about this.
If you're ok, with this done, I'll close this issue.
