### ISSUE TITLE
Chickens should spawn 1 per chicken coop instead of 1 per hatchery

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#296]
ATM, having a big hatchery can be worst than several small because of this, which is not what we would expect

**Comment by hwoarangmy** [comment]
For @Danimal696 In this PR, I've added support in room config file so that creatures can heal when they eat a chicken. But for now, they won't go to hatchery when injured (but they go to bed) ^^

**Comment by Danimal696** [comment]
Of course , i doubt any chicken drumstick will cut out any hemorrhage :D
