### ISSUE TITLE
Creatures should wander on random tiles when they have nothing to do

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#301]
Following #291

**Comment by Bertram25** [comment]
For more info, a specialized array of tiles should be made to make the wander fairer.

**Comment by Bertram25** [comment]
After a few games, I wonder whether this is actually still useful to do. What do you think?

**Comment by hwoarangmy** [comment]
From what I've seen, I would say no.

**Comment by Bertram25** [comment]
Ok, I'll close as well. Let's reopen a new issue if we see something.
