### ISSUE TITLE
Golem workers related upgrades

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#307]
Golem workers should be spawnable in single player only, as tier2 creatures.

**Comment by hwoarangmy** [comment]
If I remember well, @Danimal696 said golem workers were done as a reward for a campaign or for some special levels. The easiest way would be to remove them totally from the spawning pools and, since we don't have a campaign for now, to let them as initial creatures in some levels only.

**Comment by akien-mga** [comment]
Maybe they could be bought in some levels if we implement neutral shops. Think of the Goblin Shredder in Warcraft 3: http://classic.battle.net/war3/neutral/goblins.shtml :-)

**Comment by hwoarangmy** [comment]
That could be interesting. But for a very later milestone ^^

**Comment by Bertram25** [comment]
I like @hwoarangmy's proposal. As it could be simply made for the next release.
Please also note that in the next version, the workers should spawn due to a spell. Hence, the golem workers should probably follow the same logic, and not be part of spawn pools anyway... Would it be ok if we rediscuss that once we've added support for the first spell?

**Comment by hwoarangmy** [comment]
ok, we can remove it IMO

**Comment by Bertram25** [comment]
Yes, I think we agree.

**Comment by Danimal696** [comment]
he could be built at forge after some research, but at the time it would be available it wouldnt be too useful due to having a developed dungeon and good creatures, it would really shine at the start of the level; for that reason i want it to be a bit of a tank so even at later stages of a level it could be sent to where kobolds die easily, giving the player a reason to build it.

**Comment by Bertram25** [comment]
Ok, since he would be spawned due to a skill, I'd say we can remove it from spawn pools, and add him in a few levels for the show, exactly as @hwoarangmy said.

**Comment by hwoarangmy** [comment]
When #319 will be tested and merged, it will be the occasion to remove the golem worker from the spawn pool

**Comment by Bertram25** [comment]
I confirm golem workers now behave as expected and at least the big test map has got golem workers from the start. So yeah, let's remove them from the spawn pool. :)
