### ISSUE TITLE
Optionally disable console commands when playing.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#309]
To avoid cheats. Or we could disable specific commands...
Pre-requisite: #3

**Comment by hwoarangmy** [comment]
We could add something in the makefiles so that when we build a "release" version, console commands are disabled. But IMHO, we should not be too strict about it as some of them may be usefull to find out bugs

**Comment by oyvindln** [comment]
Maybe we could have a "cheat mode" or "developer mode" or something. It shouldn't bee to difficult to add, I'm already working on improving the console a bit.

**Comment by Bertram25** [comment]
I like the cheat mode command while I do think let the console commands enabled would help debugging for now. Do you think adding a enable cheat commands this could be part of the future game options?

**Comment by Bertram25** [comment]
Closing as superseded by #382
