### ISSUE TITLE
Add the possibility to setup alliances in the lobby.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#310]

**Comment by hwoarangmy** [comment]
Do we really want to setup alliances in the lobby ? IMHO, alliances are "hardcoded" in the level (mostly by dungeon placement). It would be usefull only for FFA levels where players have similar starting points (where having floating alliances makes sense)...

**Comment by akien-mga** [comment]
As you said, it would make sense only for FFA levels with similar starting points, so maybe it would be nice to have this feature, and to have a way to force the alliance in the levels file. Basically the same way as you give the possibility to choose a faction, but it is "hardcoded" in some levels (and the drop-down menu can't be used). WDYT?

**Comment by hwoarangmy** [comment]
I think it is feasible if we agree on that. We could use a team id = 0 to allow to allow setup and something else if we don't. The available values would be 1 per seat (if we have 5 seats, team id available would be 1 to 5).

@Bertram25 @Danimal696 WDYT ?

**Comment by Bertram25** [comment]
Adding support to setup alliances when and only when it's permitted in the level is totally what I had in mind. :)

**Comment by Danimal696** [comment]
not a bad idea

**Comment by hwoarangmy** [comment]
After thinking about it, do we allow to have seats with fixed team id mixed with free seats ?
I don't really see a reason to it but maybe someones has another idea. If we don't allow that, it may be a good idea to set that in the map infos (in this case, team ids would be ignored).
WDYT ?

**Comment by Bertram25** [comment]
The case I can see so far would be to add or remove a handicap. Eg:
A map has fixed alliances of two players with, let's say, three other independant players/AI.
The fact of being able to change the teal id of the remaining three ones can achieve a lot of effects for the allied players.
Thus, I'd let the possibility to have fixed and selectable team id.
After all, if you don't want it in your map, you can always set every team id as fixed. Does this sound relevant to you?

**Comment by hwoarangmy** [comment]
Honestly, I don't think we will have such maps. Usually, if you fix a team, it is because you want every other players to play FFA VS your team or all VS your team. But as you said, we always have the choice to fix teams or not so we can implement that.

But then, let's take an example. If we have a team with seats 2 and 3 team = 1. seat 1,4 and 5 can be changed. Which choice shall I get ? Can I team with the already fixed team ? Do we want to limit the teams ? For example, no more than 2 players in the same team ?

Maybe one thing we can do is to define the team id not as a number. We could choose the teams available. For example, in a 4 players map FFA free teams, we could have the players defined like:

```
1   1/2/3/4 Human   Keeper  10  10  1   1000
2   1/2/3/4 Human   Keeper  15  10  2   1000
3   1/2/3/4 Human   Keeper  20  10  3   1000
4   1/2/3/4 Human   Keeper  25  10  4   1000
```

And in an example like previously, we could have:

```
1   2/3/4   Human   Keeper  10  10  1   1000
2   1   Human   Keeper  15  10  2   1000
3   1   Human   Keeper  20  10  3   1000
4   2/3/4   Human   Keeper  25  10  4   1000
4   2/3/4   Human   Keeper  30  10  5   1000
```

WDYT ?

**Comment by Bertram25** [comment]
This model even goes further as it defines what potential subset of team ids you can choose for each player, if I understand correctly. IMHO, this could lead to very interesting maps and situations ;) So, I, for one, would be ok with it.

> Honestly, I don't think we will have such maps.

That's where I do not completely agree. ;) Having such possibilities is what will make such maps happen, IMHO, even if they might not happen right now. I may even create some of those just to test the possibilities once the feature is in. :)

All that said, you've got a very advanced proposition already (as certain finished games don't even propose this at all.). So if you're ready to take this advanced proposal, I agree with it. If you feel it's too much, I do think adding fixed or selectable teams are sufficient. Your call.

**Comment by hwoarangmy** [comment]
> it defines what potential subset of team ids you can choose for each player

When I wrote it, it seemed clearer than it really was. But your understanding is correct ^^

> I may even create some of those

It's too easy to prove I'm wrong if it's your map ;-)

> If you feel it's too much, I do think adding fixed or selectable teams are sufficient. Your call.

We have done many things harder than that ;-) So, I will do that as I think that it may open more interesting possibilities ^^

**Comment by Bertram25** [comment]
> It's too easy to prove I'm wrong if it's your map ;-)

Eh eh.

> We have done many things harder than that ;-) So, I will do that as I think that it may open more interesting possibilities.

Fine by me :)
