### ISSUE TITLE
Lan: A client leaving during the game makes it stop.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#312]

**Comment by akien-mga** [comment]
How should it be handled in game? Should the leaving player be replaced by an AI, or just deactivated?

**Comment by hwoarangmy** [comment]
IN a RTS I use to play, when a client leaves (or is disconnected), his allies gain control of his units. However, the are not merged (the buildings are not shared). In our case, that would mean that if we are playing as allies, if you get disconnected, my creatures won't be able to go eat in your hatchery.
But if we do something similar, that would mean that we would need to find a way in the gui to allow choosing the player we want to build for (in my example, I might need to build something for your creatures)...

**Comment by Bertram25** [comment]
Hey,
Sincerely, I would propose to let the other players keep on playing.

In another issue, we could describe how we could let other players take controls on the allied units, and even handle reconnection. What do you think, guys?

**Comment by Bertram25** [comment]
I would also add that adding support to build for another player isn't something I'm fond of. I'd rather let the server decide which ally takes control, until there is a reconnection for instance. Again, feel free to comment and to prove me wrong. :)

**Comment by hwoarangmy** [comment]
> I'd rather let the server decide which ally takes control, until there is a reconnection for instance

That's an interesting vision. In the games I use to play, when a client disconnects, the game waits for 1 minute if he reconnects. If not, he is dropped.
Waiting one minute and let someone (or an AI) take control until he reconnects seems like a good idea to me (so that if he reconnects after 5 minutes, he still can re-join the game).

But if an ally takes control, we still have the problem of how (in the gui) can he handle the disconnected player buildings/traps. For example, we are playing, you get dropped, I take control. When I build a hatchery, how can I choose if it is for you or for me ?

**Comment by akien-mga** [comment]
IMO it would be really simpler to let the AI take control of the leaving player. Of course it means that our AI should be robust enough to handle a game setting that it has not created itself (we don't want it to start digging the claimed walls of a full grown base as if it was the beginning of a game, as the AI does currently in Scream in the dark).

Then if we can implement this, the player could reconnect and reclaim his seat in the state that the AI left it.

**Comment by Bertram25** [comment]
Yeah, I'd rather let the player as inactive or taken by an AI until reconnection. And not add support to make one player build for another one.

**Comment by hwoarangmy** [comment]
Seems like the simplest way to handle it (as soon as, as @akien-mga said, we have a decent AI)

**Comment by Bertram25** [comment]
Then, I'd propose to let the disconnected player's team live as is for now (until reconnection), and we'll add an AI for them as soon as we have one. This will be cool. :)

**Comment by Bertram25** [comment]
@hwoarangmy Arf, I just can't remember now, but didn't 4de2a6bfc9437c405d6b9c4d0eabff0a692f7eae fixed that as well?

**Comment by hwoarangmy** [comment]
yes. That was a side effect but indeed, it is fixed. I'm closing it
