### ISSUE TITLE
The Hero faction isn't balanced at all.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#313]
They're lacking spawn conditions, and maybe are too strong.

**Comment by hwoarangmy** [comment]
> They're lacking spawn conditions, and maybe are too strong.

Just because 2 BigKnights have killed your dungeon...

**Comment by Danimal696** [comment]
didnt you have Pit Demons  to counter them? :D

**Comment by Bertram25** [comment]
> Just because 2 BigKnights have killed your dungeon...

Eh eh. It might have been your dungeon. ;P

> didnt you have Pit Demons to counter them? :D

Yes, but they do have spawn conditions. ;)

**Comment by hwoarangmy** [comment]
> Eh eh. It might have been your dungeon. ;P

If they had come to my dungeon, I would have kicked their knight asses and sent them back where they came from

**Comment by Bertram25** [comment]
lol

> If they had come to my dungeon, I would have kicked their knight asses and sent them back where they came from

Or you would have tried like to stop and ouch, things would have gone badly, and Akien would then have stepped on your creatures corpses, and ... Ok I stop ;)

**Comment by hwoarangmy** [comment]
> Or you would have tried like to stop and ouch, things would have gone badly, and Akien would then have stepped on your creatures corpses, and ... Ok I stop ;)

That was the other option ^^
But for my defense, @akien-mga said he was not playing so I didn't see he actually was until he was destroying my dungeon heart. He is as evil as I thought he was...

**Comment by Bertram25** [comment]
> But for my defense, @akien-mga said he was not playing so I didn't see he actually was until he was destroying my dungeon heart. He is as evil as I thought he was...

Remember when I dug around his walls to get an unfortified entrance while he was occupied with your scarab? ;)

**Comment by hwoarangmy** [comment]
^^

**Comment by Bertram25** [comment]
I added some spawn conditions to the bigknight as it is the biggest issue. I'll add more once I've played a bit more with the new values if nobody else does it.

**Comment by Bertram25** [comment]
Reassigning to Danimal now the base of spawn conditions has been added.

**Comment by Bertram25** [comment]
I consider this closed for now with 43fdede336bbeeac92990de88c29fd3bdaf0a5ef

Thanks to @Danimal696 for the work done on it. :)

If something not fitting happens, please open a new issue.
