### ISSUE TITLE
Some textures have broken alpha layer or (useless?) non-alpha empty space

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#318]
Disclaimer: I don't know a thing about texturing and how the texture files are used by our engine, so I might be wrong in some of my comments.

As discussed in #317, some textures imported from the media repo have a broken alpha layer, for example the LavaGolem:
- https://github.com/OpenDungeons/OpenDungeons/blob/cb29cc13a5fca20930fdc9018273a9abdd5548e7/materials/textures/LavaGolem_diffuse.png
- https://github.com/OpenDungeons/OpenDungeons/blob/cb29cc13a5fca20930fdc9018273a9abdd5548e7/materials/textures/LavaGolem_emit.png
- https://github.com/OpenDungeons/OpenDungeons/blob/cb29cc13a5fca20930fdc9018273a9abdd5548e7/materials/textures/LavaGolem_normal.png
- https://github.com/OpenDungeons/OpenDungeons/blob/cb29cc13a5fca20930fdc9018273a9abdd5548e7/materials/textures/LavaGolem_spec.png

As shown in those pictures, the alpha layer (typically _represented_ in image viewers by a checkerboard, but it should be transparent in game) is _a part of the picture_ and changes depending on the filter that were applied to the texture to create the various lighting components.

The first effect should be that the transparency of these textures is likely broken. The second effect is that the file size grows a lot, because in PNGs, every pixel weighs the same (I think), so a coloured background (or black, or white) would also add to the picture size. An alpha layer does not add to the picture size (or not much, since it's mostly a metadata and not a hardcoded colour byte).

I've seen other textures which use black or white as a background colour: IMO we should either switch such textures (I mean the ones that don't rely on transparency) to JPG or at least change the background colour to an alpha layer.

WDYT?

**Comment by Bertram25** [comment]
@Danimal696 I can fix the alpha layer transparency but it is your call on how to handle this.

@akien-mga I'm not fond to change texture to JPG as it is a format implying loss on the image quality and forcing us to keep an original in the media repo. So I wouldn't change them personnally, only for a question of transparency. I can be wrong for any other reason though.

**Comment by Danimal696** [comment]
Please lets only use PNG or TGA, jpeg is bad, lots of ugly pixels; i havent digg to see which models have this problems, but lava golem can be deleted entirely, its an unfinished thing that got in, it doesnt have skeleton or mesh, just the textures (why is it in the game in the first place?) a troll re-skinning will be a better choice than the effort to prepare this model having far better ones waiting.When i have some free time ill clean the texture folder, there is a lot of unused trash in there

**Comment by Bertram25** [comment]
Ok, I'll remove the lava golem, but it would indeed be a good thing to have a look at the textures folder once. Let's say this issue can be closed once you've done some cleaning there, ok with it?

**Comment by Danimal696** [comment]
sure, ill tell when im done

**Comment by Bertram25** [comment]
Note to self: Remove the lava golem textures...

**Comment by Bertram25** [comment]
Lava golem textures removed.
Semi-related:
Btw, aren't there unneeded models left or is there a plan for them?
barrel_destroyed.mesh
big_wood_barrel.mesh
mini_wood_barrel.mesh
RuinEntrance_01_mat.material (same for 02, 03, ...) and png
WoodWatchTower_mat.material
big_barrel.material
mini_barrel.material
 buvneurt_env5.png
mini_diffus.png normal and specular

And is this one stille needed, btw?
 Insect_low.003.skeleton

**Comment by Danimal696** [comment]
Insect_low.003.skeleton - erase

useful, keep it:
buvneurt_env5.png - 
RuinEntrance_01_mat.material (same for 02, 03, ...) and png
WoodWatchTower_mat.material

the rest can be erased

**Comment by Bertram25** [comment]
Let's clean that for next release.
