### ISSUE TITLE
Implement the Crypt logic

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#322]
From here: http://forum.freegamedev.net/viewtopic.php?p=60796#p60796
and here: http://forum.freegamedev.net/viewtopic.php?p=60821#p60821

First proposal from @Danimal696 :
- Creatures corpses are carried here by kobolds
- only one creature per coffin(active spot) allowed
- each coffin has a random rotting counter (say 30 to 50 seconds) that activates when a creature is deposited in it.
- when the counter reachs zero the coffin is "empty" ready for another corpse and some corpse points are added to the room.
- when enough corpse points are reached/stored by the room an undead creature appears with a 50/50 chance to be a ghoul or a ghost. (at least one of them for the issue. The other one can be done later.)
- the corpse points reset after an undead creature has appeared, so you cant get more than one undead at the same time if you rot an specially meaty (hp) creature like the troll, dragon or modified creature. (There should be no limit according to @hwoarangmy)

Unclear points:
- Should corpse points added per rotten creature be equal to his max Hp? the creatures rewarded by the Cript will be specialists and very strong, so you will have to rot, say, 40 spiders to get one or instead just 10 knights. I think its better than just using total quantity of corpses rotted.
  @hwoarangmy is ok with this.
- Note: I still want to use the prison as a source of cheap undeads skeletons as opposed to the stronger undeads given by the cript.
- A small chance to get a really powerful undead? 47.5% - ghoul / 47.5% ghost / 5% Sarcophag <- or just make this creature available througth sacrifies combinations at Temple?
  @bertram25 @hwoarangmy: No chance here if possible.
- @hwoarangmy : IMHO, it would be better to make the rats attack the prisoners. It's an evil game after all. And the number of active spots would change the number of rats (and, thus, the time it takes to turn them into skeletons) ^^
- @hwoarangmy : Concerning the crypt room, as you said, it could be a good thing to be able to deposit 1 corpse per central active spot. Concerning the wall active spots, they could be used to increase the amount of points you get per corpse (IMHO, it is good to always have a bonus when you manage well active spots).

@Danimal696 proposed spiders atm:
Spider model link: http://forum.freegamedev.net/viewtopic.php?p=60887#p60887

**Comment by hwoarangmy** [comment]
> IMHO, it would be better to make the rats attack the prisoners

For this, we were talking about prison, not crypt ^^ As far as I've understood, spiders will be there just for fun

**Comment by Danimal696** [comment]
Yes, only to make the Cript creepier ;)

**Comment by hwoarangmy** [comment]
I wil have a lok at spiders

**Comment by Danimal696** [comment]
Go for it!! :D

**Comment by hwoarangmy** [comment]
The crypt logic is added in my last PR. This issue will not be closed when it gets merged because of the unclear points.
At this moment, the logic is:
- Dead creatures are carried to the crypt by kobolds (the number of turns a dead body stays in its tile before being removedis now configurable)
- There can be 1 creature per central active spot
- The creature stays in its spot while rotting (number of turns configurable). At this moment, it is 10 turns
- Once rotten, its max HP are added to the crypt
- Once enough HP have been gathered (configurable), a creature spawns (configurable). At this moment, it is 10 points for a gnome ^^
- If the max number creature (now configurable) has been reached, no creature spawns.

**Comment by Bertram25** [comment]
@hwoarangmy What are the unclear points?
EDIT: I'd say you can go along the most votes, but if there is someting completely obscure, feel free to tell :)

**Comment by Danimal696** [comment]
> If the max number creature (now configurable) has been reached, no creature spawns.

Im seriously agaisnt this, lucky you made it configurable

**Comment by Bertram25** [comment]
> Im seriously agaisnt this, lucky you made it configurable

@Danimal696 I'm sure to understand. Are you against it being 15, or against a max at all? And then, why?

**Comment by Danimal696** [comment]
i would like to be able to cheat the 15 max by creating undeads, it was a hobby of mine in all DKs, to get my own undead army and devastate the whole level, i even totally forsake vile demons for this (they hated each other).

**Comment by hwoarangmy** [comment]
From what I understood, the creature given by the crypt will be pretty powerfull. If we limit only the other ones, they might become too strong...
Moreover, even if the creature max number is now configurable, it is still there and there is no exception for undeads ATM. Anyway, we can decide later (maybe when we will get the prison) if some creatures are excluded from the creature count.

**Comment by Danimal696** [comment]
Skeletons should be imo, anyways i guess the ghoul is the one model almost ready for the cript even if we change it later. Once im done with experimenting on Mocap animation ill get to him.

**Comment by hwoarangmy** [comment]
The remaining points that have to be cleared:
- Is there a bonus with active spots ? If yes, which and how ?
- Do we want to have more than 1 creature class spawnable in the crypt ? If yes, do we want equal probability ?

**Comment by Bertram25** [comment]
I would say:
1. Since active spots are already used as, well, corpse spots. I don't think it's a good idea to give another bonus.
2. As a long term vision, I mean once we have skills, it would be good to be able to research a skill that permits to switch or improve the creature spawned from the crypt. IMHO, there would be still just one, but it would show the Keeper specialization. Just an opinion, though.

I'd really like to get everyone's point of view on this, though. What do you think guys? @hwoarangmy @akien-mga @Danimal696 @oyvindln ? :)

**Comment by Danimal696** [comment]
- i would give an extra point or two for each wall spot, that way its rewarded to create a walled room.
- I like yor idea of being able to upgrade the rewarded creature  by research

**Comment by Bertram25** [comment]
> i would give an extra point or two for each wall spot, that way its rewarded to create a walled room.

Indeed, if wall spots aren't taken in account for corpse point, I couldn't agree more. Something like 1 point each? So that you get a boost for the first spawn, and have the next ones only at normal pace?

**Comment by hwoarangmy** [comment]
1 - ok for not giving anything for center spots (as they are already used for carrying corpses). Concernnig Wall spots, we can give a 2% bonus per wall spots. On a 5x5 room, it would be 20% bonus. Seems good to me ^^
2 - Good idea to have to research something to change the spawned creature. We should keep that in mind.

IMHO, once the 2% bonus per wall spot will be there, this issue can be closed. Concerning point 2, it may be a good idea to have a forum thread were we gather middle/long term ideas like that.

**Comment by hwoarangmy** [comment]
The wall active spots bonus is handled in #352. I close the issue. If we want to change something later, we can open another issue
