### ISSUE TITLE
Remove existing beds when manually destroying dormitory tiles

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#326]
I destroyed some dormitory tiles with the new "destroy room" button and noticed that the beds were still displayed, as shown in this screenshot.
![od-destroyed-room](https://cloud.githubusercontent.com/assets/4701338/5103947/3cc6e034-6fdd-11e4-8b14-0c74e75d390f.jpg)

It's only a graphical issue from what I could gather: no creature tries to use these beds, and if I place new dormitory tiles under them, creatures come and drop new beds on top of them (so there can be two different bed meshes on the same tile, with only one active).

**Comment by Danimal696** [comment]
thats a messy dungeon you have there...

**Comment by hwoarangmy** [comment]
AI manages the rooms better than you do ;)

**Comment by akien-mga** [comment]
The messier, the more evil it is... :-]
