### ISSUE TITLE
A wizard with a shield?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#327]
Introduced here: https://github.com/OpenDungeons/OpenDungeons/commit/e4a58db18fa5aee283703c680e7433b5b987e928

**Comment by hwoarangmy** [comment]
Hey, that's not a bug. It's just to show that we can change the spawning weapons within the level file ;-)

**Comment by Bertram25** [comment]
Ok, I'll close then :)
