### ISSUE TITLE
Cleaning AI source files...

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#328]
For now the AI source files are a bit messy and can easily be cleaned up.

From #15  : 
- The AI factory, can be removed.
- NullAI can be removed.
- The AI wrapper should be merged into the AI manager files.

I'd also add that the KeeperAI.cpp/h files should be removed, and the Keeper2AI.cpp/h files should be renamed to the former.

Feel free to correct the issue according to your findings. :)

**Comment by hwoarangmy** [comment]
> BaseAI

Not BaseAI ;-)

> KeeperAI.cpp/h files should be removed, and the Keeper2AI.cpp/h files should be renamed to the former

Don't you want to go for another AI ? We will need at least 2 or 3 to make it less predictable (even if based on the same logic as Keeper2AI)...

**Comment by Bertram25** [comment]
> Not BaseAI ;-)

Ok, fixed the description. :)

> Don't you want to go for another AI ? We will need at least 2 or 3 to make it less predictable (even if based on the same logic as Keeper2AI)...

I will eventually finish something, but I would use another name in that case. And now you've made a fitting one. The need is much less urgent. I might concentrate on a rush AI btw, now you've added the base of a builder AI. :)

**Comment by hwoarangmy** [comment]
ok. Then, I will do that
