### ISSUE TITLE
Strange carpet shading in the dormitory of seat 3 in Stonekeep siege

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#334]
As reported by @Bertram25 in #330.

A strange shading can be seen in the dormitory made by the AI of seat 3 in Stonekeep Siege, reproduced on Linux.

As seen by @Bertram25:
![bertram](https://cloud.githubusercontent.com/assets/765917/5134811/cf81d7be-7111-11e4-94fa-a2d74841d160.png)

As seen by myself (same output on both @Bertram25's and @hwoarangmy's branches) with Intel driver:
![akien-intel](https://cloud.githubusercontent.com/assets/4701338/5134930/ee2743e2-7112-11e4-9cfc-c89ffb2b3fe3.jpg)

As seen by myself with my nvidia GPU and the proprietary drivers (the bug is not reproduced AFAICT):
![akien-nvidia](https://cloud.githubusercontent.com/assets/4701338/5135272/08c151d0-7117-11e4-9af3-06ae8fb05490.jpg)

**Comment by akien-mga** [comment]
Ok, I edited the level to set myself as a player on seat 3, and I could notice that I can reproduce the same motif as @Bertram25 when I choose another location to build the dormitory. See:
![od-bug2](https://cloud.githubusercontent.com/assets/4701338/5135502/3c0b258c-7119-11e4-8eb6-2864678e3b32.jpg)

I tried with other rooms on "line of demarcation", they are unaffected. Is there some kind of veil/overall shading implemented in this map? Or some far away influence of lava? :-D

**Comment by akien-mga** [comment]
It also affects seat 2 (on the other side of the map, to the west):
![od-bug3](https://cloud.githubusercontent.com/assets/4701338/5135601/65868a9a-711a-11e4-99f5-7895f5ee01c0.jpg)

**Comment by akien-mga** [comment]
And just for fun, a bigger view of this artistic bug:
![od-bug4](https://cloud.githubusercontent.com/assets/4701338/5135598/5d660048-711a-11e4-832b-227b018df419.jpg)

**Comment by hwoarangmy** [comment]
I guess it is systematic then (could you please confirm ?). Do you reproduce with other rooms ? It might be linked to the dormitory mesh

**Comment by akien-mga** [comment]
It is systematic when using the open source intel driver on Linux. I can't reproduce with other rooms.

> I tried with other rooms on "line of demarcation", they are unaffected.

**Comment by Bertram25** [comment]
After thinking about this, this might be linked to light sources present in the level:
their positions: (x y z)
51 16 3.75
47 94 3.75
Also, we're applying a normal to the dormitory texture here:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/render/RenderManager.cpp#L871

The newest mesa driver 10.3 now applying normals not since a lot of time, a bug might exist between its appliance and the addition of light sources. I'll check with intel drivers on windows to see whether there is a difference in behaviour there.

If I am correct, or not too wrong at least, the normal appliance may need to be disabled for the current release, or the light sources removed. @oyvindln and me have work to do on normals and materials for the next, anyway. ;)

**Comment by hwoarangmy** [comment]
yes, that looks like the kind of problems we can get with normals. In fact, if they produce such effects, it could be better to disable them.
Can one of you disable the line pointed by @Bertram25 and make sure the bug disappears ? If yes, we could move this issue to later ^^

**Comment by Bertram25** [comment]
I'll have a go at it. (Whooo, it seems the last release blocker is... me O.O')

**Comment by oyvindln** [comment]
It looks fine for me (with proprietary nvidia driver on linux), don't have anything else capable to test on. The suggested code will have to change anyway as we have found how to set the normals in the material files, so it shouldn't be hardcoded.

**Comment by Bertram25** [comment]
> The suggested code will have to change anyway as we have found how to set the normals in the material files, so it shouldn't be hardcoded.

Indeed, I'll disable the normal for this release.
