### ISSUE TITLE
Remove the console commits by oln pushed by mistakes on the main repo.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#339]
Nothing major. I'll remove them asap but in the meanwhile, everyone knows I'm on it.

**Comment by akien-mga** [comment]
Also check 5ac13262, it seems an old commit from @Danimal696 was revived, but it doesn't do what it says (and judging by the name, I'm not sure we want to delete the Dirt material).

**Comment by Bertram25** [comment]
I got rid of that one, so it should be ok. :)

It's now done.
