### ISSUE TITLE
Check whether there is a way to make the buttons more visually responsive.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#343]
ATM, the in-game button seems to be updated every second when clicking fast on them.
I suspect them to answer double-click events or events preventing their appearance from being fine.
(This might also be the low FPS.)

This will have to investigated and hopefully a solution will have to be found.
Base on discussion in #311

**Comment by hwoarangmy** [comment]
> I suspect them to answer double-click events or events preventing their appearance from being fine.

That's also my feeling. I've not really made sure but that's why I changed the event when using worker/fighter pickup button. And it worked

**Comment by Bertram25** [comment]
Btw, still failing here. I'll open an issue on CEGUI's forums once my patch for the mouse cursor will be ready.

**Comment by Bertram25** [comment]
Might be simpler than I thought:
Example:
http://static.cegui.org.uk/static/TaharezLookProperties.html#WantsMultiClickEvents

Look'n'feel:

```
    <WidgetLook name="ceguiWidget/IconButton">
        <Property name="WantsMultiClickEvents" value="False" />
```
