### ISSUE TITLE
The default game perspective makes it hard to select certain tiles.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#345]
How should we change the default perspective to avoid selection problems? More isometric? More top-down? Something else to fix?

Once we've found a correct setting, I'd also request we add a key to permit to reset the viewpoint back to this.

**Comment by Bertram25** [comment]
Ah. also I'll check to add a isometric (top-down) view for classic players + key shortcut as well.

**Comment by tomluchowski** [comment]
"
    Ogre::Ray mouseRay = mCameraManager->getActiveCamera()->getCameraToViewportRay(mousePos.d_x / float(
            arg.state.width), mousePos.d_y / float(arg.state.height));
    mRaySceneQuery->setRay(mouseRay);
    mRaySceneQuery->setSortByDistance(true);
"

You cast a ray from the viewport into the XZ plane , instead the Ray being perpendicular into the XZ and containing somwhere our cursor ... Is that so tough to deduce that from code :P ?

I need to think  a little how to nicly achieve that ...
