### ISSUE TITLE
When saving a level in editor, the XP table is not saved when it had been overwritten

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#347]
To test it, load the small test map 2v2 skirmish and save the level. Compare the new level and the backup: the BigDragon XP table is missing.

**Comment by Bertram25** [comment]
0.4.9?

**Comment by hwoarangmy** [comment]
ok. I'll have a look. It should not be a big problem.

**Comment by Bertram25** [comment]
I quickly tried to save this map as is:
levels/skirmish/TestSingleplayerSmall.level

And the Adventurer, Knight and wizard XP table are created. Is it normal?

Other maps seem to behave correctly, even if some of them have a format not completely upgraded AFAIK.

**Comment by hwoarangmy** [comment]
I don't reproduce but I think it is an uninitialized variable. By re-reading the code, I would guess that it's because I check the XP table from 0 to MAX_LEVEL but it should be MAX_LEVEL - 1 because creatures start at level 1. I'm gonna post a patch
