### ISSUE TITLE
Remove the RenderManager queue and execute the requests as they are sent

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#349]
I've made some tries to see what happens when the RenderManager is not used - ie render messages are not queued but executed instead. On windows, I don't see anything wrong.
@Bertram25 @akien-mga could you please try to do the same ?

You just have to change in RenderManager::queueRenderRequest_priv
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/render/RenderManager.cpp#L198

Replace:
mRenderQueue.push_back(renderRequest);
by:
renderRequest->executeRequest(this);
delete renderRequest;

Please try both GameMode, EditorMode and ReplayMode.

If you see no regression with that, we might be able to remove the render manager (and let ODFrameListener handle the scene) and move render actions to the class they belong to.

Has for now, things are a little bit messy with most things done in the RenderManager but animations/moves handled by the object itself. I think it would be better now that the architecture allows it to let the objects handle themselves as they need.

**Comment by akien-mga** [comment]
I tried the replacement, it looks alright here.

**Comment by hwoarangmy** [comment]
Thanks. Linux I guess ?

**Comment by Bertram25** [comment]
Oops, completely forgot that one. I'll test during the Week-End. IIRC, we discussed that months ago, right?

**Comment by akien-mga** [comment]
Linux indeed for me, 64bit with intel drivers. I just tested with nvidia drivers, it works fine too.

(Hehe I just noticed that you can steal the gold of you ally on the 2v2 map if you're quick enough to mine it and claim tiles under it before the AI :-P).

**Comment by hwoarangmy** [comment]
> (Hehe I just noticed that you can steal the gold of you ally on the 2v2 map if you're quick enough to mine it and claim tiles under it before the AI :-P).

That's evil !!

**Comment by hwoarangmy** [comment]
> Oops, completely forgot that one. I'll test during the Week-End. IIRC, we discussed that months ago, right?

Yep. At this time there were more prioritary things. But now that we have a stable release, it might be a good thing to do ^^

**Comment by Bertram25** [comment]
> Yep. At this time there were more prioritary things. But now that we have a stable release, it might be a good thing to do ^^

Yeah, if the manager can be removed, I'm quite sure all the rendering stuff could be simplified a lot. Let's hope it will turn well.

**Comment by Bertram25** [comment]
@akien-mga It's not a good thing for me that you're becoming more and more cunning in-game :S With @hwoarangmy 's will to avenge the fallen BigKnight and your new tricks, I fear our next lan. :fearful:

**Comment by hwoarangmy** [comment]
> I'm quite sure all the rendering stuff could be simplified a lot

Yes and I guess it will help us when working on FOW

> I fear our next lan

I've seen what happened during our previous lan. I will attack you only with tentacles so that if I win, I don't care if you lower their stats.

**Comment by Bertram25** [comment]
XD deal

**Comment by hwoarangmy** [comment]
@Bertram25 Have you tried if there was an issue when not using the render queue ?

**Comment by Bertram25** [comment]
Sorry, couldn't do anything last night. Hopefully this evening. :)

**Comment by hwoarangmy** [comment]
> Sorry, couldn't do anything last night. Hopefully this evening. :)

no pb ^^

**Comment by Bertram25** [comment]
I've tested it but so far, everything went fine. All single player, multiplayer and replays went fine.
I've noticed sometimes creatures idling, I mean stuck on the same tile with the idle animation after a big battle between two AIs, but I'm not sure it's related.

**Comment by hwoarangmy** [comment]
that's where the replay rocks ^^
You can watch the game with and without the renderer patch. You will see if there is a change. Every change on the render manager only impacts the client. So, it should be relevant to make this test.

**Comment by Bertram25** [comment]
Ok, I will :)

**Comment by Bertram25** [comment]
Ok, I confirm the exact behaviour can be seen when playing without the renderer change, so I guess it may be more something like the good old creature action list being spammed with something, or similar. Anyway, that bug is very minor as the creatures gets used elsewhere rather often by the AI.
I'll open an issue if I can find a relevant way to reproduce.

In any case, I think we can go on with the renderer change. :)

**Comment by hwoarangmy** [comment]
ok ^^

**Comment by hwoarangmy** [comment]
I've had a look at how to remove the RenderManager. After all, I think it is not worth removing it because:
- It will be a pain to do and a pain to review (since there are loads of calls that will need to be adapted)
- It will be hard to roll back if we see a problem
- It allows to gather most of Ogre code. That means that when we will want to upgrade the engine, it will probably be easier like this than having to change loads of files
- If, for some reason, we want to use a thread for the render manager, it will be ready for it
- There is no real need in polymorphism because entities are clearly separated concerning rendering

But I do think it would be a good thing to not use a queue for rendering. That would allow to have an understandable callstack when there is an error and would avoid the need of processing the render queue. Moreover, we could use variables for render requests instead of pointers.

@Bertram25 @akien-mga @oyvindln WDYT ?

**Comment by oyvindln** [comment]
I think your proposals sounds reasonable, there isn't the need for the queue now that we have the client-server system. I don't like the tight coupling between the entity classes and rendering that we have, but I am not sure how best to solve that.

**Comment by hwoarangmy** [comment]
> I don't like the tight coupling between the entity classes and rendering that we have, but I am not sure how best to solve that.

Yep, that's why I wanted to remove the render manager. But I couldn't find a way to break this coupling that I was happy with.

**Comment by Bertram25** [comment]
> But I do think it would be a good thing to not use a queue for rendering.

AFAIK, Ogre does the batching in term of draw updates, so I guess it's relevant.

> That would allow to have an understandable callstack when there is an error and would avoid the need of processing the render queue. Moreover, we could use variables for render requests instead of pointers.

Sure. In any case, I do think this kind of effort can be done step by step. As you said, let's break-down this big stuff into smaller problems and fix the ones we're sure of, first.

> I don't like the tight coupling between the entity classes and rendering that we have, but I am not sure how best to solve that.

Yeah, that part always sound weird for me too, in term of design. But I'd say let's see what can be simplified once we have remove the need of the queue.
