### ISSUE TITLE
Implement the forge logic 

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#353]
For now, the forge will be used for traps only (we will see later for weapons).
When a new trap is created, it is deactivated (translucient). It needs a crafted trap from the forge to be ready.
Crafted traps are carried by Kobolds to the trap. Once there, it becomes activated and can trigger. Between 2 shots, there is a reloading time. After a few (configurable) shots, the trap is deactivated and needs another Crafted trap to work.
That brings me to some forge behaviour questions. For now, I would make the forge craft items for created traps that needs it only. Later, we could have some kind of gui to allow choosing.
For now, creatures won't go to the forge to work by themselves. But if dropped, they will work there (that will change when the PR about fighters idle bahaviour will be done and implemented)
1 - If there is no need (no deactivated trap), no creature will be allowed to work in the forge
2 - Concerning the crafted traps, they go on active spots. The forge will start by filling wall activespots. When there is none available, it will start to fill central activespots. Central active spots occupied by a crafted trap cannot be occupied by a worker until the crafted trap has been taken by a kobold
3 - Workers can work on central activespots only

**Comment by Danimal696** [comment]
what do you plan for it?

**Comment by hwoarangmy** [comment]
Sorry, I had no time to update description. But now, it's done ^^

**Comment by Bertram25** [comment]
> 1 - If there is no need (no deactivated trap), do we allow creatures to work in the forge (they could gather some work points and, when a new trap will need it, the crafted trap will be ready) ?

IMO, I'd be for letting the creatures craft the traps in need first, and then why not craft a few random traps within the makable ones. (Later depending on the skills unlocked), and leave the room once full. What do you think about it?

> 2 - [...] We could also fill wall active spots and then the central active spots (removing workers if any) like in DK.

I just don't remember how it was in DK, but if I guessed what you said rightly, you mean the crafted traps go to the wall spots if any, and then on the central spots, making those spote unusable anymore until the trap is taken by a kobold, freeing the spot? If that's it, I find it good. :)

**Comment by Danimal696** [comment]
i dont know, say, we implement weapon creation, and forge is cluttered with traps that wont be used anytime soon making creatures unable to work on it; i would prefer the creatures only work when a trap is being created leaving the forge empty when trap is finished

**Comment by Bertram25** [comment]
Ah true. Then let's them build what's needed and be done with it. It will be much more understandable as a player point of view than letting them gather conceptual forge points upfront, IMHO.

**Comment by hwoarangmy** [comment]
ok. Then we agree that only the needed traps/weapons should be crafted. Letting creatures go to the forge only when there is a trap to craft might be a little brutal but at least, it is easy to understand.
I also think that letting them gather points and have instantly finished traps doesn't make really sense in a forge (not a magical building). Anyway, we should also keep in mind that everything said here is subject to changes when we will have played some games ^^

**Comment by Danimal696** [comment]
i think they could go anyways to create weapons points in the forge once the "armory" room is researched (should be an early room, basic weapons created at first but advanced weapons would be unlocked with more research), since the points would store on the armory and not the forge.

By the way, the armory room would be a room where creatures would go to upgrade their equiped weapons (or maybe dropped in to control which creature upgrades) in the future
