### ISSUE TITLE
Creature Hp healing rate while sleeping should be configurable

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#355]
And maybe defined per unit ?

**Comment by Bertram25** [comment]
I would be fine with both solutions here as I see advantages in both. Let's ask the others. :)
@akien-mga @oyvindln @Danimal696 ?

**Comment by hwoarangmy** [comment]
yep, that's my line ^^

**Comment by Danimal696** [comment]
fine by me

**Comment by Bertram25** [comment]
> fine by me.

Eh eh. For which solution ?

**Comment by akien-mga** [comment]
For this kind of parameters, I'd like to have a creature default parameter (defined in a config file, but common to all creatures), and then the possibility to override it in creature definitions. I think this mechanism could be applied (or is already applied?) to other stats for which it might make sense to have a common value, but to fine tune it for some creatures (e.g. HP healing in % from chicken?)

**Comment by Bertram25** [comment]
So, in the finals, I guess it's a per creature for you @akien-mga ?

**Comment by Danimal696** [comment]
per creature to me  as well

**Comment by Danimal696** [comment]
picking up oldies, rigth? ;)

**Comment by hwoarangmy** [comment]
lol ^^
