### ISSUE TITLE
Add an appdata.xml file

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#356]
From what I understand [1], this aims at being a cross-distro description of the software, with screenshots and all. I'm not sure which package management software use it (Mageia's doesn't as far as I know), but I'll have a look at it.

Note that I might do this for 0.4.9, but I set the milestone to 0.5.0 for now, this is not a high priority enhancement.

[1] http://people.freedesktop.org/~hughsient/appdata/

**Comment by hwoarangmy** [comment]
isn't this closed by #488 ?

**Comment by akien-mga** [comment]
It is, I forgot to add it to the commit log.
