### ISSUE TITLE
Add a manpage

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#357]
We should provide a manpage for the opendungeons binary (typically this would be a requirement in Debian's packaging policy if we want OD included in Debian).

BTW, are there parameters that can be used with the OD binary? `opendungeons --help` starts the game normally.

**Comment by Bertram25** [comment]
Atm, there is no command line parameter handling at all AFAIK, so maybe it's better to open a spearate issue about and discuss there what we want to implement?

**Comment by akien-mga** [comment]
Sounds good. I'll just add a basic manpage that gives a description of the game and points out that there are no command line parameters currently.
