### ISSUE TITLE
CEGUI.log should go to the user data dir

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#358]
Starting opendungeons installed system wide, I notice that the CEGUI.log file is put in the working directory instead of the user data dir (~/.local/share/opendungeons on Linux).

**Comment by Bertram25** [comment]
I'll deal with that one.

**Comment by Bertram25** [comment]
For personal record:
http://static.cegui.org.uk/docs/0.8.4/classCEGUI_1_1Logger.html#ae4c43f9f8358672af7614a0665d23a0d
To be called before cegui initialization IIRC.

**Comment by akien-mga** [comment]
I still get the same behaviour as before here after your changes in 37e5afd.

When running OD from a read-only location:

```
CEGUI::FileIOException in function 'virtual void CEGUI::DefaultLogger::setLogFilename(const CEGUI::String&, bool)' (/home/iurt/rpmbuild/BUILD/cegui-0.8.4/cegui/src/DefaultLogger.cpp:153) : Failed to open file 'CEGUI.log' for writing
terminate called after throwing an instance of 'CEGUI::FileIOException'
  what():  CEGUI::FileIOException in function 'virtual void CEGUI::DefaultLogger::setLogFilename(const CEGUI::String&, bool)' (/home/iurt/rpmbuild/BUILD/cegui-0.8.4/cegui/src/DefaultLogger.cpp:153) : Failed to open file 'CEGUI.log' for writing
Abandon
```

Oops nevermind, I think I'm testing a home-built OD package which did not use the same tarball as the one I pushed to Mageia's buildsystem... PEBKAC :-D

**Comment by Bertram25** [comment]
Ah, phew :)

**Comment by akien-mga** [comment]
Yes I can confirm the fix with the updated package :-)
But it's good, I took the time to try to debug the (non-existing) issue myself now that I can read C++ syntax more easily ;-)

**Comment by Bertram25** [comment]
> But it's good, I took the time to try to debug the (non-existing) issue myself now that I can read C++ syntax more easily ;-)

Cool :) Well, you were already doing some coding with cmake anyway. And I guess packaging does count in development anyhow. :)
