### ISSUE TITLE
AI doesn't repair damaged rooms

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#375]
As seen here:
![ai-repair](https://cloud.githubusercontent.com/assets/4701338/5424171/8eca75c0-82e4-11e4-8ad1-a941a2974e55.jpg)

**Comment by akien-mga** [comment]
Maybe it builds a new one when it's completely destroyed though.
I agree with the 0.5.0 milestone, the aim for 0.4.9 was to have a basic AI, and we have already better than that :-D

**Comment by Bertram25** [comment]
Yeah, 0.4.9 will rock already. :)

**Comment by hwoarangmy** [comment]
Yep. It's cool to see that even with only a basic behaviour implemented, the AI do not seems too bad. From all the tests I've done so far, I always loose on 1v1 when I let my creatures do what they want ^^

Concerning repairing rooms, yes, we should do something about it. IMHO, to improve AI, we should:
- Add more randomness to make it less predictable
- Make it reapair damaged rooms
- Make it use traps
- Later, make it use spells

The good point is that nothing in this list seems really hard to do ^^

**Comment by hwoarangmy** [comment]
Fixed in #543
