### ISSUE TITLE
Mention developers in the AUTHORS file

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#379]
We currently have a nice CREDITS files that lists all licenses and authors for our assets, and configuration files.

I think it would be nice to also mention previous and current developers that worked on the source code.

There is a list of contributors here: http://opendungeons.sourceforge.net/?q=about
@hwoarangmy and I are missing from it though, but that's another matter :-)

**Comment by akien-mga** [comment]
I set this for the 0.4.9 milestone since it should be relatively easy to do, but let's not consider it a blocking issue. If 0.4.9 is ready, let's release it :-)

**Comment by akien-mga** [comment]
@Bertram25 @hwoarangmy @oyvindln @tomluchowski @Danimal696 
Can you confirm whether the list of contributors in http://opendungeons.sourceforge.net/?q=about is accurate (apart from missing hwoarangmy, Dm3d and myself)?

Other question: should I list "direct contributors" in another section of the CREDITS file, or should I add an AUTHORS file that lists only people involved personally in OD? (contrarily to the CREDITS file which lists the provenance of all assets in the game, with or without direct involvement of the designer)

**Comment by Danimal696** [comment]
Lets see:
Fabian Aichele - Who is this guy? unless he is one of us going with another nickname, he did nothing
ReZpawner- did nothing (except for some funny skype conversations) - dissapeared after a month

Missing people i can remember: AncientGoat, Hwoarangmy, Eugeneloza, Dm3d

**Comment by akien-mga** [comment]
Trying to relate github contributors to the list on the website and nicknames on the forum:

_Web site - Forum - GitHub_
- Bertram - Bertram - @Bertram25
- Daemon - ? - ?
- Danimal - Danimal - @Danimal696 
- Elvano - Elvano - ?
- Fabian Aichele - faichele - ?  _// was referenced here: http://forum.freegamedev.net/viewtopic.php?f=35&t=5378&p=56077#p56077_
- Nido Media - nido - @nido
- Oln - oln - @oyvindln 
- Paul424 - paul424 - @tomluchowski 
- ReZpawner - ReZ - ?  _// should be removed according to @Danimal696 comment_
- Skorpio - skorpio - ?
- Svenskmand - svenskmand - ?
- <missing> - Akien - @akien-mga
- <missing> - AncienGoat - ?
- <missing> - Dm3d - ?
- <missing> - eugeneloza - ?
- <missing> - hwoarangmy - @hwoarangmy 
- ? - ? - @Bebere 
- ? - ? - @DomtronVox 
- ? - ? - @jonanp 
- ? - ? - @Smilex   _// 8 posts in a couple of days, http://forum.freegamedev.net/search.php?author_id=2847&sr=posts_
- ? - StefanP.MUC - ?

Some might be duplicates, and I might be missing some of them too.

**Comment by akien-mga** [comment]
Some more research done by @Bertram25, even though it was focusing on assets and not that much on the code, the code licensing being easier to handle: http://forum.freegamedev.net/viewtopic.php?f=35&t=5757&p=59035&hilit=andrewbuck#p58800

Maybe we should only list contributors who got involved over at least a couple of months? Looking at the forum and my previous comment, I think the list could get really long, with many people who were there for a couple of weeks, gave some ideas and maybe got one or two patches commited.

**Comment by Smilex** [comment]
This is fun, I don't remember contributing to this.
Either way, I can't imagine I ever did much, so there's no need to add me to anything.

**Comment by oyvindln** [comment]
I thought we had a list of contributers to the code somewhere. Of the top of my head, besides the people mentioned, andrewbuck (I think @andrewbuck could be the right one, but I'm not sure), alienwolf and @MCMic  are missing at least. I think many on this list were not involved in the source code directly:
No idea about daemon
Elvano I think worked on the website?
faichele I don't think actually contributed anything, but I could be wrong. EDIT: http://sourceforge.net/u/faichele/activity/?page=0&limit=100#52d53ffe2718462de17b9433
@nido Only updated a file according to the commit log, so I don't know
I think danimal is right about ReZ
Skorpio was mostly doing models, though he might have done code too, I can't remember.
I don't think Svenskmand worked on the source code, though he might have worked with the GUI or something, he's done other things though.
TheAncientGoat was also involved with the project at one point, but I don't think he worked on the source code - (EDIT: @TheAncientGoat may be the same person)
Dm3d - though this person did models?
eugeneloza - models
@Bebere - no idea (he is listed in contributors, changing the traps, so I think it might be one of mcmics friends?)
@DomtronVox  - has listed 3 commits
@Smilex  - has committed some changes at least: https://github.com/OpenDungeons/OpenDungeons/commits?author=Smilex
stefanp.muc - did a fair bit of coding, and then disappeared.
@jonanp is also in the commit list from way back

EDIT Looked at the list on sourceforge:
I think Bodsda may have done work on code or build system or something, but I'm not sure.

**Comment by Bertram25** [comment]
I'll have a look as well. In any case, I'd rather have the contributors in a separate file as proposed.
Btw, I was completely certain faichele was another name for Elvano. I'll check my mails for a proof about this.

**Comment by akien-mga** [comment]
> Btw, I was completely certain faichele was another name for Elvano. I'll check my mails for a proof about this.

I don't think so, faichele commited some code on sourceforge, and he's from Germany according to his id on #freenode :-)

**Comment by jonan** [comment]
Nice to see activity in OD I had kind of lost track of this project and I'm glad it's still in development.

If I'm not mistaken, I think I helped with the migration to CMake. Nothing too fancy, so no need to be in the CREDITS file :)

**Comment by Bertram25** [comment]
@Smilex @jonanp Still it is cool to get some news from you guys. :)

> I don't think so, faichele commited some code on sourceforge, and he's from Germany according to his id on #freenode :-)

@akien-mga Ok, just blame my twisted mind. ;)

I don't want to patronize of course. But I think you can go on at creating an AUTHORS file with what we've got so far. If some authors complain, we'll add them. Once our both issues are sorted out, I'll be working on the release RC1 preparation + push to stable, creation of the 0.4.9 branch, etc... ;)

**Comment by akien-mga** [comment]
@Bertram25 Ok, I'm on it.

**Comment by nido** [comment]
All I have done was create some trouble in the build environment and updated FindSFML.cmake to an upstream version. I have no problem not being mentioned in the AUTHORS file as this is technically not even part of OD code.

**Comment by ryanswrt** [comment]
Yep, I'm @TheAncientGoat, did a bit of work on the original models (wyvern was one, can't remember the others) and was slightly involved in gameplay design back around 2010

**Comment by akien-mga** [comment]
@nido, @TheAncientGoat Thanks for the feedback, and glad to see you are doing well :-)

**Comment by akien-mga** [comment]
Found https://www.openhub.net/p/opendungeons
It's a good resource to find old contributors :-)

**Comment by akien-mga** [comment]
By default I won't use your real names (apart for Andrew Buck who used his real name as nickname, and myself because I'm megalomaniac and aiming for international fame :-P).

Off-topic: @oyvindln Er du dansker? :-)

**Comment by oyvindln** [comment]
@akien-mga Nei. Jeg er Norsk. Svenskmand er dansk dog.

**Comment by akien-mga** [comment]
@oyvindln How misleading of Svenskmand to be a Dane :-P
Congrats to your feminine handball team for winning the Euro cup yesterday ;-)

**Comment by ljdarj** [comment]
I don't remember having ever contributed to this project but I saw @MCMic mentioned in this conversation and I'm one of his friends so I might have got there that way. Given that I don't remember what could I have done, no need to add me to anything.
