### ISSUE TITLE
Separate test levels from "release" levels

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#381]
As discussed in #9, for future releases we might want to separate test levels from "release" levels (by "release", I mean the one that we consider interesting for singleplayer and multiplayer games and that we want normal players to play in priority).

How we want to do that is open to discussion. We might make two lists in the level selection GUI, or two different tabs. We can also remove test levels from official release builds if we consider that they aren't suitable for inclusion in release.

**Comment by akien-mga** [comment]
Actually setting the milestone to "Later", I'm not sure we'll want to do that for 0.5.0.

**Comment by akien-mga** [comment]
How about simply renaming the test levels to "[Test] Some descriptive name"?
This was they would all be at the end of the alphabetically-sorted list (since [ is after the normal latin letters).

If you agree, I can do that for 0.5.0.

**Comment by Bertram25** [comment]
Yeah, good idea. :)

**Comment by hwoarangmy** [comment]
seems easy and efficient ^^

**Comment by akien-mga** [comment]
I'll do that then.

Note to self: brackets should be escaped in the level name definition.

**Comment by Danimal696** [comment]
I also think we should only aim to make final levels when we have most features in

**Comment by akien-mga** [comment]
While I'm messing with level names, would it be okay if I changed some filenames to avoid using spaces, since those can be a pain when using the command line? e.g. "Scream in the dark.level" would become "ScreamInTheDark.level". (mostly a question for @Bertram25 and @hwoarangmy)

**Comment by Danimal696** [comment]
what about botton lines? Scream_In_The_Dark.level

**Comment by Bertram25** [comment]
@akien-mga Don't mind. Either are fine to me. :)

**Comment by akien-mga** [comment]
> what about botton lines? Scream_In_The_Dark.level

Those would be fine too. It's mostly a matter of taste there :-) I've checked some other files in the repo (materials, textures, source code), it looks like most of the time we use ThisKindOfName.ext, though there are also some This_kind_of_name.ext. I'll go with the former, but it's not necessarily a strict rule, feel free to use whichever you like best when importing models and textures.

**Comment by hwoarangmy** [comment]
You can do so for me. If there are merge conflicts, I will fix them.
