### ISSUE TITLE
Load user content from mUserDataPath

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#383]
I'm only realising it now because I hadn't tested it before, but it seems the Resource Manager does not check the user data directory (mUserDataPath, ~/.local/share/opendungeons on Linux) when loading game content.

Because of this, I can't edit a level or load a custom level placed in ~/.local/share/opendungeons/levels/skirmish. If OD is installed on the system, we _need_ this feature because we can't expect users to set /usr/share/games/opendungeons world-readable.

On a side note, there seems to be a typo here: https://github.com/OpenDungeons/OpenDungeons/blob/development/source/utils/ResourceManager.cpp#L135
I guess it should read:
`std::cout << "Game data path is: " << mGameDataPath << std::endl;`

Currently the output is:

> Game data path is: ./

Even with system-wide installations.

**Comment by akien-mga** [comment]
I would probably assign it to @Bertram25 and set the milestone to 0.4.9, but I don't want to force this on you just when we were expecting to release 0.4.9 RC1, so I'll let you decide :-)

We can still release the RC1 and get this issue fixed before the final release though.

**Comment by Bertram25** [comment]
Heya :)

I do think the problem can be split into two here. The game data path typo is a nice catch. I'll have a look and fix that one asap.

As for user content management, AFAIK we didn't implement that kind of feature, so the fact that you won't be able to edit custom levels with system-wide installation is less a bug than the lack of a feature.

I truly forgot about that so it's a nice reminder IMHO. And it shouldn't be hard to implement, but we should define first how we handle that. I'll deal with the first part of the issue, though. :)

**Comment by Bertram25** [comment]
Ah btw, about this:

> Currently the output is:     Game data path is: ./ Even with system-wide installations.

This is IMHO wrong and true at the same time. OpenDungeons will use local data when finding them instead of the system data. So if you start od from the repo main folder, it will use the data in ./

I'll add a warning to make this less confusing. :)

**Comment by Bertram25** [comment]
Ok, this should be done now for the first part. :)

**Comment by akien-mga** [comment]
Great :-)

For the second part of the issue, i.e. using the data from mUserDataPath, IMO the logic should be:
- Check for data in mUserDataPath, add it to the virtual filesystem (if it's indeed something like that that we are using, I'm not really familiar with boost::filesystem yet)
- Check for data in mGameDataPath, add it to the virtual filesystem. If a given file already exists in mUserDataPath, it should have precedence over the one in mGameDataPath (i.e. you can override default game components by putting a tweaked file in your mUserDataPath)

I'm not sure about how to handle the case where there is also data in the runtime dir, i.e. "./".
Should it have the highest priority? Following this logic, editing levels for example would result in overwriting the levels in ./levels, which can be desirable for us when running the development branch. Similarly, if we have custom levels in mUserDataPath that override default ones, they should probably not be used when testing the development branch.

So yes in the end I would say:
- Check first the runtime dir, read and write
- Check the user data dir, read and write
- Check the game data dir, read-only

WDYT?

Note that actually there are only two cases that we should support:
- Data in runtime dir + user data dir (runtime has highest priority)
- Data in game data dir + user data dir (user has highest priority)

If it simplifies the logic, we don't need to handle a case where a user compiled OD with a game data dir, installed it system wide, and then runs it from the source dir :-)

**Comment by Bertram25** [comment]
Hey,

> Data in runtime dir + user data dir (runtime has highest priority)
>     Data in game data dir + user data dir (user has highest priority)

I'm ok with the core logic. Now, to make this intuitive for the user, I'd propose this for the GUI:
Let's say one map is existing in two versions. A is the original one in the system game data or the data seen in the current dev folder, B is the user modified one.
How OD knows it's the same map? It has the same filename in the same game type folder (skirmish/multiplayer and later, campaign).
- In Skirmish / Multiplayer mode:
  A and B are displayed.
  A has got a small star icon beside its title showing it is the original.
  B has got a small user/demon/community icon showing it's user made.
- In the editor mode:
  A and B are displayed.
  A has got a small lock beside its title, showing it can't be modified. If the user selects it to edit, the editor will save the same name file in the user folder. If another file exists already, it should ask the user whether it can overwrite it.
  B has got a small user/demon/community icon showing it's user made.

What do you think guys? @hwoarangmy @oyvindln @akien-mga

**Comment by akien-mga** [comment]
Your proposal sounds great \o/

Just one question: will OD/Ogre/boost know how to handle files from two different absolute locations that have the same name without having them conflicting with each other?

This also brings up the question of whether the multiplayer mode will be able to handle it well: if one player hosts a server using a user-made map, will it work for clients that don't have the same version of the map locally? IIRC correctly @hwoarangmy wants to go towards not loading the map on the client and let the server send everything that is needed, so in that case it should be fine, but presently, we're not there yet I think.

**Comment by Bertram25** [comment]
> Just one question: will OD/Ogre/boost know how to handle files from two different absolute locations that have the same name without having them conflicting with each other?

Fortunately, levels file names and paths are handled by boost::filesystem, which is, more or less, working with std::string as a result, so it's up to us to make sure they are differentiated in the implementation, but it's feasible and I'd even say usually common work. :)
EDIT: Before, we already used to list files using their stems (The filename without the path to it), while keeping in memory the full and absolute filepath, so there should be no problem, IMO.

**Comment by akien-mga** [comment]
> Fortunately, levels file names and paths are handled by boost::filesystem, which is, more or less, working with std::string as a result, so it's up to us to make sure they are differentiated in the implementation, but it's feasible and I'd even say usually common work. :)

Great :-) I'll pay a close attention to the correspond commits, I think at least part of it might be within my reach and a good example for learning.

**Comment by hwoarangmy** [comment]
> How OD knows it's the same map? It has the same filename in the same game type folder

Seems good

> What do you think guys?

I think it is a good way to handle this ^^

> IIRC correctly @hwoarangmy wants to go towards not loading the map on the client

Well, as you say, we are far from there. It would some more communication (if we consider a 100x100 map with 20% gold/rocks, that would mean 500 tiles to transfer => 500 \* 2 \* 4 = 4kbytes). But it would solve this kind of problem. So, we will see if it is possible.
Anyway, if we don't do that, the server will have to allow the clients to download it.

> Just one question: will OD/Ogre/boost know how to handle files from two different absolute locations that have the same name without having them conflicting with each other?

That's not a problem. As @Bertram25 pointed out, it is only a matter of loading the maps from different places and adding the corresponding icons. But the path is not hardcoded while used so it should work.

**Comment by hwoarangmy** [comment]
> IIRC correctly @hwoarangmy wants to go towards not loading the map on the client and let the server send everything that is needed

FYI, to make a server side FOW, I've tried to load the map on server side only and send the needed to the clients and it seems ok (I feel it doesn't take much more time to load). So, the problems you were pointing out might be gone ^^ We will see.

**Comment by Bertram25** [comment]
Woohoo :)

**Comment by Bertram25** [comment]
I'll be on that one next.
