### ISSUE TITLE
Random game crash when selecting the back button after choosing a map.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#386]
From @tomluchowski 

> One cannot click on the 'Back' button after choosing a map -> the game crashes
> http://pastebin.com/nfPJwhs3

From @akien-mga 

> I confirm that such glitches happen from time to time, in my case systematically after you've loaded and close several maps several times (or one map several times, or several maps one time... :-P), usually quickly after each other (i.e. when doing quick tests).
> I guess some things are not cleaned properly when closing a map, or when closing it while it's still loading content.

**Comment by Bertram25** [comment]
Btw, isn't this fixed?

**Comment by hwoarangmy** [comment]
> Btw, isn't this fixed?

IMHO, no. But I've never seen it. And if it happens to someone, please post at least the backtrace so we can have more information

**Comment by hwoarangmy** [comment]
I've tried yesterday night to reproduce it but I couldn't.
@tomluchowski @akien-mga could you please try to reproduce this crash and post the stacktrace ?
If nobody can reproduce it, I will close this issue within a few days.

**Comment by Bertram25** [comment]
I can't reproduce a crash from a few tries. I will try to insist tonight.

**Comment by Bertram25** [comment]
Tested it with fierce. The game won't budge. IMO, this is fixed.

**Comment by akien-mga** [comment]
Yep, I just got berserk with the UI, opening dozens of maps to quit them after a second, map editor, host multiplayer, join multiplayer, skirmish map again, several times the same one, changing teams and so on, all really quickly to try to find some memory not released properly, and zero crash :-)

Closing then.
