### ISSUE TITLE
Should we keep The DirectX renderer/HLSL shaders? If so, why?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#389]
Everything is in the title! :)

**Comment by oyvindln** [comment]
On windows, OpenGL can sometimes not work to well with certain driver/card combinations (default drivers, or intel graphics), so I think we should keep them as long as we aren't doing any custom shaders, or other stuff that means having to do extra work to support both systems.

**Comment by Bertram25** [comment]
Well, I don't mind as long as we're not starting to use compositing. :)

WDYT guys? @akien-mga @hwoarangmy

**Comment by hwoarangmy** [comment]
I think what @oyvindln said is pretty relevant: as far as we don't have any specific stuff to do, I see no problem with supporting both.

**Comment by Bertram25** [comment]
Ok, I'll reenable the D3D renderer for windows as before. :)

**Comment by akien-mga** [comment]
Not closed yet since @Bertram25 re-removed the D3D renderer :-)
I think we can keep this issue as a "if someone wants to reimplement the D3D renderer and make it work, feel free".

**Comment by Bertram25** [comment]
> I think we can keep this issue as a "if someone wants to reimplement the D3D renderer and make it work, feel free".

Well, I do think that we should only open issues about features we're, as a team, ready to add. If @oyvindln wants to add D3D renderer support back, I'll let him open an issue or better, a PR, but I don't think anyone else will want to do it. Thus, I'll ask to close this issue for now, if you don't actually mind, of course.

**Comment by akien-mga** [comment]
Sounds good. So closing the issue as a "Not for now" answer to the initial question :-)

**Comment by hwoarangmy** [comment]
Yep, I agree with @Bertram25. We should only open issues on what we are doing or what we want to do.
If someone wants to implement something else, there is no problem. The best would be to discuss about it to make sure it is not rejected. In any case, he can always create a PR and it will be discussed.
AFAIK, nobody, even @oyvindln does want to work on that so we should better close it.

EDIT : @akien-mga was faster to close it as I was ^^

**Comment by oyvindln** [comment]
I tested the previous snapshot on a computer with an NVidia last week, and the D3D9 renderer worked, though the minimap looked wrong. (Which may indicate that there is something wrong with it.) D3D11 renderer complained about missing shaders, D3D10 was missing so I haven't tested it.
