### ISSUE TITLE
Tile refresh small regression

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#39]
Hi,
- On single player mode, when selecting tiles to dig, the tiles don't get colored. They only get colored when the neighbor tile are dug.
- The room tiles on newer rooms (after the map was loaded) aren't displayed. Only the room objects are displayed once the neighbor tiles are later changed to claimed walls for instance.

This was only seen on Linux. I didn't try on Windows yet.

Introduced since commit https://github.com/OpenDungeons/OpenDungeons/commit/d18a98e3dbf3b18b77cdeb9325e9c88125f47af2

**Comment by Bertram25** [comment]
@hwoarangmy For info.

**Comment by hwoarangmy** [comment]
Seems like I need to test better on linux :)

**Comment by Bertram25** [comment]
Np. Nothing can be perfect from the start. ;)
No useless pressure though. We'll find out eventually.

**Comment by Bertram25** [comment]
@hwoarangmy

> On single player mode, when selecting tiles to dig, the tiles don't get colored. They only get colored when the neighbor tile are dug.

Seems related to #41 in fact from what I've seen. Have you got the GLSL warning when having marked tiles to dig on screen (on ubuntu)?
