### ISSUE TITLE
Check the portal animations

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#390]
@Danimal696 reported that the portal animation wasn't done properly some time ago, and it seems the 'Triggered' animation isn't used.
(TODO: try to find the link back to the original discussion.)

**Comment by Danimal696** [comment]
i tried, but is hard; for the record, new portal has the "Idle" and "Triggered" animations

**Comment by Bertram25** [comment]
oh? I was thinking the bug was on the code side?

**Comment by Danimal696** [comment]
yes, you told me the code used "idle" as "trigerred" and then stopped animation

**Comment by Danimal696** [comment]
found it, its at he end: 
https://github.com/OpenDungeons/OpenDungeons/issues/323

**Comment by Bertram25** [comment]
Thanks :D I was able to fix IMHO.
