### ISSUE TITLE
Keeper / Hero voices support

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#393]
Pre-requisite: #3 

Being able to select the Keeper/Hero voice when playing in game should be added.
Then, in game, according to the events, voice cast should be used to bring some mood to the game.

Wav/oggs can be found here: (Thanks to eugeneloza)
http://forum.freegamedev.net/viewtopic.php?p=61638#p61638

**Comment by Bertram25** [comment]
Pay day voice will be needed as well. (If it isn't already there, I'll have to listen to it again.)

**Comment by eugeneloza** [comment]
No, this phrase is not yet there. Should I do it ASAP (and for which voices?)? Or it waits for a 'larger' upgrade to include more phrases like news, etc.?

**Comment by hwoarangmy** [comment]
@eugeneloza If you are on making some more voice events, I would add:
- Pay day
- Creature unhappy
- Creature wants to leave the dungeon
- Creature became rogue

BTW, welcome to github ^^

**Comment by akien-mga** [comment]
> Should I do it ASAP (and for which voices?)? Or it waits for a 'larger' upgrade to include more phrases like news, etc.?

IMO you can wait a bit for this and the ones that @hwoarangmy suggested. Maybe we could open an issue on github as a todo list for voice acting scripts, and then you can do everything at once.
I also think that we'll get plenty of new ideas once the current samples are integrated in the game.

**Comment by hwoarangmy** [comment]
> Maybe we could open an issue on github as a todo list

This issue seems not a bad choice... ;-)

**Comment by akien-mga** [comment]
> This issue seems not a bad choice... ;-)

Indeed, silly me, I thought we were hijacking an issue about pay day :-p

**Comment by eugeneloza** [comment]
Good. So it's better to wait until the next script version. Since recording a voice is much better as one chunk - it will sound more natural. I was just wondering of recording a single pay-day phrase.

**Comment by Bertram25** [comment]
@eugeneloza Welcome :)

**Comment by eugeneloza** [comment]
Thanks :)

**Comment by akien-mga** [comment]
Looking forward to hearing those in-game!

_shameless bump_ :-D

**Comment by Bertram25** [comment]
Now that was shameless. ;P Might fell on my shoulders, eh. ;)
