### ISSUE TITLE
When a claimed tile is claimed by an ennemy, it should become dirt before getting claimed again

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#395]
or it should at least be claimed without seat

**Comment by akien-mga** [comment]
So basically one would have to first unclaim tiles before they can be claimed again. That sounds sensible.

**Comment by hwoarangmy** [comment]
> So basically one would have to first unclaim tiles before they can be claimed again

Yes. In reality, that's already what is happening ATM. But the bug is that the tile is displayed claimed for the original seat until it is claimed by the new one. That means that if the kobold stops claiming just before finishing, the first player will have a tile displayed with his color where he cannot drop creatures and that his kobolds will try to claim.

**Comment by Bertram25** [comment]
Yeah, I confirm the bug. It can be seen especially when you're stealing enemy's tiles and defending your kobolds with fighters. As there a lot of fleeing and back and forth, the bug is more often seen.
