### ISSUE TITLE
Creature vision is not well computed

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#396]
On corridors, they see only at 1 tile distance.
Moreover, when we display visual debug, we can see that sometimes, they see behind tiles with fullness > 0.

**Comment by Bertram25** [comment]
Also, sometimes they see through walls when looking exactly at 45° through a tile with an oblique hole, AFAIK.

**Comment by Danimal696** [comment]
Thas was also a flaw of DK1, you could blew creatures througth that cracks

**Comment by hwoarangmy** [comment]
> Also, sometimes they see through walls when looking exactly at 45° through a tile with an oblique hole

Well, they don't even need walls with 45°. From what I've seen, they sometimes see behind walls (see screenshot)
![odscreenshot_2015-01-08_181125_1](https://cloud.githubusercontent.com/assets/7493706/5666731/0acdde0a-9762-11e4-8eb4-8d57422b7f98.png)
