### ISSUE TITLE
Ingame menu tooltip prevents from selecting a room/trap/creature

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#397]
When you hover over an icon of the ingame menu, the tooltip displays after a short while. If you click on the icon while the tooltip is on, it will discard the tooltip, but it won't count as a click on the icon.

I find that it happens quite often to me, that I click on an icon, try to place a room, and nothing happens, because there was a tooltip when I clicked the icon.

**Comment by Bertram25** [comment]
Yep, I've started a discussion about this on CEGUI but it seems we have time understanding each other there. What I'll need to do next is provide a video about this issue.

**Comment by hwoarangmy** [comment]
That explains why I sometimes had problems grabing units using the button...

**Comment by Bertram25** [comment]
We've been speaking about this and Nyast provided some good info:
http://cegui.org.uk/forum/viewtopic.php?p=33002#p33002

This is a CEGUI bug: http://cegui.org.uk/mantis/view.php?id=1058
I'll give help there if I can.

**Comment by Bertram25** [comment]
Setting to Later as the bug belongs and thus depends on upstream.

**Comment by Bertram25** [comment]
Btw, this bug only happens when you 'hide' the cegui mouse cursor and use the OS one. I wonder whether you would agree to use some cegui custom cursor to workaround this bug?

**Comment by hwoarangmy** [comment]
I've had a look when integrating the keeper hand at how to display an animated mesh as CEGUI cursor but I couldn't make it work. If you find a way, I think it would be really nice to have the keeper hand as a cursor in every screen instead of a mesh in the game mode only

**Comment by Bertram25** [comment]
Closed by https://github.com/OpenDungeons/OpenDungeons/commit/712ccab32e2aa03f990729062c71f980c25edbb9

As for displaying the keeper hand above the CEGUI layer, we'll have to disable automatic rendering in CEGUI, add 3 separate rendering queues in Ogre and setup rendering in all those three layers.
But I've read there are problem with the z-buffer in that case, so it will be a longer term goal and I won't do that now as it may make things complicated once we improve lights, material and their shadows, ... So let's do that first, IMHO.
We might also want to use animated icons instead. If that one is raising any interest, please open an issue. :)
