### ISSUE TITLE
std::bad_alloc segfault

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#398]
I got a segfault after ~1h20 in a map (I had played ~30 minutes, then let the game go on to see what the AI would achieve), i.e. 5831 turns.

Here's the tail of my log:

```
Computing turn 5830SERVER - Removing rendered object RenderedMovableEntity_Crypt30_5111,MeshName=SmallSpider

During this turn there were 2 calls to GameMap::path().miscUpkeepTime=9424
Server sends newturn=5830
Client received turnStarted=5830
CLIENT - Removing rendered object RenderedMovableEntity_Crypt30_5111,MeshName=SmallSpider

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Computing turn 5831Abandon
```

There is not much significant there, I'll try to let the game run with gdb to see if I can reproduce and get more info.

This was with #394, but I can't say if it's related to it or not (I rarely let the game run so long).

**Comment by Bertram25** [comment]
I added the Question tag as some @akien-mga spoke about making a bt.
EDIt: I'll let a game run with gdb as well.

**Comment by hwoarangmy** [comment]
FYI, I've already let a game run for much more time (something like 4 hours on greed or might) - with gdb and did not see any problem. So, that may not be related to the time a game is lasting but to something that happened during the game.
From what I've seen, bad_alloc happens when you have no more memory available. We might also have a look at memory usage to check if we don't have too many leaks.

**Comment by akien-mga** [comment]
Yes I've run the game 1h30 with gdb and had no issue. When the game segfaulted previously, I had left the laptop idle for 30min or so, so I wasn't doing much that used a lot of memory. But maybe the AI uses more and more memory when all creatures can't find a sensible thing to do?

**Comment by Bertram25** [comment]
For the record, this issue might be hidden by #403 btw.

**Comment by hwoarangmy** [comment]
> For the record, this issue might be hidden by #403 btw.

I've looked (and fixed) #403 . It is due to setting the carried entity too early (and thus, trying to remove it before it has been created). But there should be no segfault because of it.

**Comment by Bertram25** [comment]
Cool :)

**Comment by Bertram25** [comment]
Probably fixed by https://github.com/OpenDungeons/OpenDungeons/commit/6f2b8f3488bd2f06779cadfc4630db94854313a0 as reported by @hwoarangmy 
Please, reopen or open a new issue if some bad allocation error happens again. :)

**Comment by akien-mga** [comment]
I'm not sure @hwoarangmy meant that the issue in #403 would potentially cause a bad_alloc segfault (especially since when it happened on my system the AI was hidden behind its claimed walls I had claimed most of the remaining tiles, so kobolds probably weren't carrying too much stuff).

But this bad_alloc segfault is quite hard to reproduce, I'll reopen the bug if I encounter it again.
