### ISSUE TITLE
Fetched gold stacks are displayed with a +2,+2 offset

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#399]
When fetching a gold stack (at least a stack that was left on the ground because there was no available treasury tile), the gold stack is displayed two tiles to the east and to the north of the kobold that fetches it, as shown on those screenshots:

![od-gold](https://cloud.githubusercontent.com/assets/4701338/5564147/58fe39b2-8eac-11e4-9399-a66c6048d3d2.jpg)
![od-gold1](https://cloud.githubusercontent.com/assets/4701338/5564148/59d7aeea-8eac-11e4-834c-ff592bc44717.jpg)

When the kobold grabs the stack, the stack is "teleported" at its +2,+2 location, so the kobold is correctly placed but not the stack.

**Comment by Bertram25** [comment]
I confirm the issue for everything carried, btw : corpses, traps, ...

**Comment by Danimal696** [comment]
> I confirm the issue for everything carried, btw : corpses, traps, ... 

Same here
