### ISSUE TITLE
Creature behaviour enhancement.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#4]
- [x] Clear out the creature active action list when they are taken by the Keeper, so that they start fresh when dropped somewhere.
- [x] Check the current code to make sure the fighters attack or flee as soon as they see enemy creatures.
- [x] Make the worker more likely flee when they see enemy creatures.
- [ ] Make the workers check for marked-to-dig tiles anywhere in the map, when they don't see any dig-able tiles in sight.

**Comment by Bertram25** [comment]
The task list is obsolete as is, but the given point will have to be checked once what is discussed below is implemented:
http://forum.freegamedev.net/viewtopic.php?p=58430#p58430

**Comment by akien-mga** [comment]
For the sake of completeness, I've noticed that creatures that were fighting a dummy become idle (actually frozen) when the training room is destroyed under their feet:
![od-create-no-reaction](https://cloud.githubusercontent.com/assets/4701338/3962389/e513e154-2769-11e4-9f43-1e3ec5bc2dbd.jpg)

(This yellow guy just killed the drake's dummy... and killed the frozen drake afterwards ;-))

**Comment by Bertram25** [comment]
@akien-mageia I think it's a new issue. Could you create it separately?

@hwoarangmy This issue has been obsoleted by your latest improvement. IMHO, we can close it, and eventually open a new one if something is needed later.

What do you both think?

**Comment by akien-mga** [comment]
Ok I'll open a new issue for this. I'll just wait to be sure that it's easily reproducible (there are still a few glitches with creatures behaviour, so it's not 100% sure that the issue happens each time you destroy a room's active spot).

**Comment by hwoarangmy** [comment]
Well, the code is supposed to handle this situation. When an active spot is removed, the creature is supposed to stop using it. But I have never seen it in action so there may be something tricky.
But IMO, this will anyway be fixed when we will have a correct fighting behaviour. I don't think we can reach a situation where 2 creatures are so close and do not engage...

**Comment by hwoarangmy** [comment]
BTW, this issue states 

> Make the worker more likely flee when they see enemy creatures.

I think it has been discussed on the forum that they should continue to work until they get damage (or at least until an ennemy attacks it). In the small map, it is quite obvious that there is something weird with the current behaviour as it is really hard to get workers claim tiles when they are not far from the ennemy base

**Comment by Bertram25** [comment]
> I think it has been discussed on the forum that they should continue to work until they get damage (or at least until an ennemy attacks it). In the small map, it is quite obvious that there is something weird with the current behaviour as it is really hard to get workers claim tiles when they are not far from the ennemy base

The issue list as been stated as obsolete thanks to the latest improvement. :) 
I'll open a new issue about what was discussed on the forums.

According to the latest discussion state here, I think we can close this issue. Other ones can be opened on need. Ok with it?

**Comment by akien-mga** [comment]
I'm fine with it :-)

**Comment by Bertram25** [comment]
Created #90 and I'll adapt #9
