### ISSUE TITLE
Angelscript MSVC files polluting git clones (Linux, UTF-8)

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#40]
Each time I want to update my git clone of the repo, I am warned that some angelscript files are modified locally, and that I should commit or stash my changes prior to do a pull --rebase.

I suspect an encoding issue, but it's quite bothersome; would there be a way to get rid of these unwanted local changes?

```
[akien@cauldron OpenDungeons (development)]$ git checkout
M       dependencies/angelscript/add_on/autowrapper/generator/generator.sln
M       dependencies/angelscript/angelscript/projects/msvc10/angelscript.sln
M       dependencies/angelscript/angelscript/projects/msvc2012/angelscript.sln
M       dependencies/angelscript/angelscript/projects/msvc7/msvc7.sln
M       dependencies/angelscript/angelscript/projects/msvc8/angelscript.sln
M       dependencies/angelscript/angelscript/projects/msvc9/angelscript.sln
M       dependencies/angelscript/samples/asbuild/projects/msvc9/asbuild.sln
M       dependencies/angelscript/samples/asrun/projects/msvc9/asrun.sln
M       dependencies/angelscript/samples/concurrent/projects/msvc7/msvc7.sln
M       dependencies/angelscript/samples/concurrent/projects/msvc9/msvc9.sln
M       dependencies/angelscript/samples/console/projects/msvc7/msvc7.sln
M       dependencies/angelscript/samples/console/projects/msvc9/msvc9.sln
M       dependencies/angelscript/samples/coroutine/projects/msvc7/msvc7.sln
M       dependencies/angelscript/samples/coroutine/projects/msvc9/msvc9.sln
M       dependencies/angelscript/samples/events/projects/msvc7/msvc7.sln
M       dependencies/angelscript/samples/events/projects/msvc9/msvc9.sln
M       dependencies/angelscript/samples/game/projects/msvc9/msvc9.sln
M       dependencies/angelscript/samples/include/projects/msvc7/msvc7.sln
M       dependencies/angelscript/samples/include/projects/msvc9/msvc9.sln
M       dependencies/angelscript/samples/tutorial/projects/msvc7/msvc7.sln
M       dependencies/angelscript/samples/tutorial/projects/msvc8/msvc8.sln
M       dependencies/angelscript/samples/tutorial/projects/msvc9/msvc9.sln
M       dependencies/angelscript/tests/test_feature/projects/msvc9/msvc9.sln
Your branch is up-to-date with 'origin/development'.

[akien@cauldron OpenDungeons (development)]$ git pull --rebase
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
```

**Comment by Bertram25** [comment]
It's weird. I don't have this problem. o.O'

A good way to fix this would be to import the latest stable AS source files with the correct encoding/line endings.

**Comment by akien-mga** [comment]
It seems that the problematic files have a funny encoding:

> ./dependencies/angelscript/angelscript/projects/msvc10/angelscript.sln:                         UTF-8 Unicode (with BOM) text, with CRLF line terminators

git diff indeed shows <U+FEFF> at the top of the file (git diff simply shows me the whole file content remove, and then the whole file content added. Textually, it's the same content).

First time I hear of BOM: http://en.wikipedia.org/wiki/Byte_order_mark

My system is plain UTF-8, maybe that's related?

**Comment by akien-mga** [comment]
It seems the Unicode standard does not recommand using BOMs:

> 2.6 Encoding Schemes
> ... Use of a BOM is neither required nor recommended for UTF-8, but may be encountered in contexts where UTF-8 data is converted from other encoding forms that use a BOM or where the BOM is used as a UTF-8 signature. See the “Byte Order Mark” subsection in Section 16.8, Specials, for more information.

Seen here: http://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom

**Comment by Bertram25** [comment]
@akien-mageia You can tell it: BOM is something stupid, when used in UTF8 files. ;)
We should remove any BOM found as soon as we can.
That said, please remember that sln files are MSVC project files and are to be used only on windows where it makes sense to have CR+LF line endings (Let Microsoftian sotware use BOM if they want, it's not important.).

The .gitattributes should prevent git from setting the incorrect line endings for those files, so I wonder: Why does git translate the line endings back to CR-LF as it should already be the case anyway?

**Comment by Bertram25** [comment]
@akien-mageia Do you still have this issue?

If yes, and to get through it, could you check whether the BOM disappear when the modified files are listed? If it's the only modification, I do think you can push them.

**Comment by akien-mga** [comment]
I'll check in the evening, but I think the issue is still there, and the BOM did not disappear. IIRC the git diff output shows that the whole content of the file is removed, and readded (including the <U+FEFF> character).

I'll try download an angelscript file manually from the repo and then comparing it with the changed one from a git clone, hopefully this will show some changes that git does automatically on my machine.

**Comment by Bertram25** [comment]
> IIRC the git diff output shows that the whole content of the file is removed, and readded (including the <U+FEFF> character).

This means line endings have changed usually. CR+LF -> LF, I'd say. Again, .gitattributes should prevent git from doing that but maybe you have global settings telling the reverse for git?
http://stackoverflow.com/questions/2114111/where-does-git-config-global-get-written-to

**Comment by akien-mga** [comment]
I'll check again, but for example FindSFML.cmake is CR+LF, and the line endings are untouched.

**Comment by hwoarangmy** [comment]
I also have this issue. I've not looked what was the difference, through

**Comment by Bertram25** [comment]
> I'll check again, but for example FindSFML.cmake is CR+LF, and the line endings are untouched.
> Lol. Well, the following .gitattributes means that a check on the line endings of .sln file is to be done on checkouts at this line:
> https://github.com/OpenDungeons/OpenDungeons/blob/development/.gitattributes#L14

For instance, *vcproj files should also be CR+LF but doesn't seem to cause a line ending change since the .gitattributes doesn't tell anything about it.

All this can only mean one thing:
The *.sln files were already LFed and your git installation does put them back into CR+LF.

If you open the sln when they're auto-modified using an advanced text editor, can you tell me what line ending it is telling you?
If the files have CR+LF line endings after modification, then my guess is correct and the flawed git installation is mine, not yours.

In that case, you can push the modified files.

Regards,

**Comment by hwoarangmy** [comment]
What I do remember is that when I download a fresh version from github, they do not appear as changed. After compiling, it does (I'm not sure if it is after first compilation or if it is more tricky)
I use :
- CMake-gui
- Code-Blocks with MinGW

EDIT : Code-Blocks is configured with Unix line-ending (LF) and WINDOWS-1252 charset.

**Comment by akien-mga** [comment]
Actually I don't have the issue anymore on my local git clone :-o
I have no idea what changed though.

**Comment by Bertram25** [comment]
> Actually I don't have the issue anymore on my local git clone :-o
> I have no idea what changed though.

Think about me when it reappears. ;)

**Comment by Bertram25** [comment]
> What I do remember is that when I download a fresh version from github, they do not appear as changed. After compiling, it does (I'm not sure if it is after first compilation or if it is more tricky)

Weird, I wonder how is cmake and code::blocks linked with the change on line-endings of sln files. O.O'

**Comment by Bertram25** [comment]
Shouldn't block the release, and since it's not reproducible, let's wait for this.

**Comment by akien-mga** [comment]
I've reinstalled a clean version of Mageia cauldron because I wanted to make some changes to the partitioning of my HDD (not enough place to build lots of OpenDungeons instances :-P).

In a fresh git clone of the repo, the issue is back... So I guess I wasn't seeing the issue anymore because of a configuration difference (maybe I told git to ignore .sln files globally?).

**Comment by Bertram25** [comment]
@akien-mga Now you have the issue again. Can you check the line ending format after they are auto-modified?
My bet is that they are CR+LF after begin modified. ;)

**Comment by akien-mga** [comment]
Actually it's quite strange, if I do several clones of the repo, the files are sometimes modified, sometimes not.

The file description are the same whether they are flagged as modified or not:

> $ file dependencies/angelscript/add_on/autowrapper/generator/generator.sln 
> dependencies/angelscript/add_on/autowrapper/generator/generator.sln: UTF-8 Unicode (with BOM) text, with CRLF line terminators

Doing a `diff -u` between a file considered modified in a clone and non modified in another clone does not produce any output: the files are identical. It seems the permissions are also the same:

> $ ll dependencies/angelscript/add_on/autowrapper/generator/generator.sln ../../OpenDungeons/dependencies/angelscript/add_on/autowrapper/generator/generator.sln 
> -rw-r--r-- 1 akien akien 888 sept. 10 16:26 dependencies/angelscript/add_on/autowrapper/generator/generator.sln
> -rw-r--r-- 1 akien akien 888 sept. 10 23:39 ../../OpenDungeons/dependencies/angelscript/add_on/autowrapper/generator/generator.sln

I've noticed that if I comment out the `*.sln text eol=crlf` line in .gitattributes, the issue disappears instantly.

**Comment by Bertram25** [comment]
> I've noticed that if I comment out the *.sln text eol=crlf line in .gitattributes, the issue disappears instantly.

It means the git repository will apply the default behaviour I guess. Let's remove that line, then.

**Comment by Bertram25** [comment]
@akien-mga 

> It means the git repository will apply the default behaviour I guess. Let's remove that line, then.

Wants to do it, or can I?

**Comment by akien-mga** [comment]
You can do it, you know your way around git and its .gitattributes better than I do :-)

**Comment by Bertram25** [comment]
ok :) I'll handle this one :)
