### ISSUE TITLE
Engine config files should not be installed in the data path on Linux

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#400]
Currently we install user config files (plugins.cfg and resources.cfg) in the OD_DATA_PATH, e.g. `/usr/share/games/opendungeons` on Mageia and Debian.

I just met an issue that this situation creates: plugins.cfg hardcodes the path to the OGRE plugin dir (on Mageia, it's `/usr/lib/OGRE` on 32bit and `/usr/lib64/OGRE` on 64bit). Data in /usr/share is normally arch-independent and for Mageia I packaged it as "noarch", i.e. it's included in an arch-independent opendungeons-data package. Since the latter is built on 32bit by convention, the path in plugins.cfg is `/usr/lib/OGRE`, so the 64bit version of OD segfaults.

There are two possible solutions for this:
- Put the "general" config files (by opposition to the gameplay config files from ./config that can be left with the rest of the data) in `/etc/opendungeons`, which would be the standard path for system-wide config files.
- Do not package such config files, but have them generated automatically and put in `~/.config/opendungeons` at run time if they don't exist yet (just like the ogre.cfg file).

If we opt for the first solution, it would also be nice to copy the files from `/etc/opendungeons` to `~/.config/opendungeons` at the first run (or when the user space files do not exist), so that OD can be configured per-user and not only by the system administrator in /etc.

**Comment by Bertram25** [comment]
OpenDungeons starts if I add a second PluginFolder=... line in the plugin.cfg file.
What happens if you bundle a file with both arch lines there?

**Comment by Bertram25** [comment]
Arf, nevermind, it only takes in account the first line read.

**Comment by Bertram25** [comment]
And , what if the plugin.cfg file is part of the game package (as opposed to the data package?)

**Comment by akien-mga** [comment]
> And , what if the plugin.cfg file is part of the game package (as opposed to the data package?)

That works and that's what I did for Mageia. But that's a bad practice, and I can already foresee that packagers from other distros will do the same mistake as I did. So there is no urgency, but it would be best to implement one of the two solutions above, normally there should not be arch-dependent stuff in `/usr/share`.

**Comment by akien-mga** [comment]
And `/etc` is meant for system-wide config, so it would make sense to use it. Of course that's yet another non-centralised thing that we need to take into account different for Linux system-wide and for Windows...

**Comment by Bertram25** [comment]
ok, then I'll handle the change to look into /etc/opendungeons for the plugin.cfg file. This looks like the sanest change.

Just for info, as far as I have looked, the ember project for instance is even hardcoding the pluginFolder path within the app code using this:
http://anonscm.debian.org/cgit/pkg-games/ember.git/tree/configure
(Line 18862)

``` shell
cat >>confdefs.h <<_ACEOF
#define OGRE_PLUGINDIR "`pkg-config --variable=plugindir OGRE`"
_ACEOF
```

I must say I still don't know whether it's actually a tolerated practice, but it seems we're not the only ones getting in troubles. O.O'

**Comment by Bertram25** [comment]
I'd propose to add a plugin data path option in cmake. What do you think?

**Comment by akien-mga** [comment]
> I'd propose to add a plugin data path option in cmake. What do you think?

It's already the case: https://github.com/OpenDungeons/OpenDungeons/blob/development/CMakeLists.txt#L523-L553
Basically if you can use OGRE_PLUGIN_DIR directly in the code instead of relying on plugins.cfg, then it's all set. The current CMake script already finds the correct plugin path based on pkg-config and stores it in OGRE_PLUGIN_DIR_REL, which is used to initialize plugins.cfg.

**Comment by Bertram25** [comment]
And I guess /etc/opendungeons/plugin.cfg file would be part of the arch-dependent binary package?
If yes, should we name the plugin files dependently on the arch used to avoid multiarch conflicts?

**Comment by Bertram25** [comment]
> It's already the case: https://github.com/OpenDungeons/OpenDungeons/blob/development/CMakeLists.txt#L523-L553

Arf, no. When I was speaking of the plugin data path, I meant the plugin.cfg file data path. And it's not done in the CMake file yet.

> And I guess /etc/opendungeons/plugin.cfg file would be part of the arch-dependent binary package?
> If yes, should we name the plugin files dependently on the arch used to avoid multiarch conflicts?

Those two questions remain, though.

**Comment by akien-mga** [comment]
> Arf, no. When I was speaking of the plugin data path, I meant the plugin.cfg file data path. And it's not done in the CMake file yet.

Ah ok, I thought you were building upon the ember example (where they seem to hardcode the plugin dir in the code instead of relying on a plugins.cfg file).

> And I guess /etc/opendungeons/plugin.cfg file would be part of the arch-dependent binary package?
> If yes, should we name the plugin files dependently on the arch used to avoid multiarch conflicts?

/etc/opendungeons/plugin.cfg would be part of the arch-dependent binary package yes, i.e. the "opendungeons" package on most distros I suppose. I don't think we need to give it an arch-dependent name though, the 32bit opendungeons package would conflict its 64bit counterpart anyway, since both provide the game binary in /usr/games/opendungeons.

Looking at some examples, they don't seem to bother with that either, e.g.:
$ find /etc/mplayer/
/etc/mplayer/
/etc/mplayer/mplayer.conf
/etc/mplayer/menu.conf

**Comment by Bertram25** [comment]
ok :)

**Comment by Bertram25** [comment]
I'll be on this once the research tree pending research part view is done if nobody else does.

**Comment by Bertram25** [comment]
> Put the "general" config files (by opposition to the gameplay config files from ./config that can be left with the rest of the data) in /etc/opendungeons, which would be the standard path for system-wide config files.

Ok, I'll be on this along with the config seat bug now.
