### ISSUE TITLE
Game is slow on multiplayer for more than 150x150 tiles maps

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#401]
Time is lost on:
In unsigned long int GameMap::doMiscUpkeep():
==> getTile(ii,jj)->computeVisibleTiles();

And in void Seat::sendVisibleTiles():
 while checking difference between mTilesWithVisionLast and mTilesWithVision

**Comment by Bertram25** [comment]
This is it. i remember what it was and how we fixed it. (It was a some old version of TMW, for the record).
mTileswithVision and TileWithVisionLast could each be turned into int***, read: a pointer of a two-dimensional array or integers.
When a seat has vision on one tile the turn number is set on the tile X,Y position of the array.
Each turns, the arrays are swapped.
Then when look for what changed, we check both:
- For the same position, we check whether the current array has got the current turn number and the previous one has the number of the previous turn. If so, we send nothing.
- If not, we send the tile at the given corresponding position.

I'm telling it's perfect but this way we don't care about duplicate and setting a values more than one time and we have a more constant memory allocation.
I'm not telling this is truth, so feel free to comment if you see obvious flaws in my proposal. :)

**Comment by hwoarangmy** [comment]
I had more or less the same kind of idea. I was thinking about adding a vector(vector(bool)) with the number of tiles (will be memory consuming but same as what you propose).
Then, it would be easy to check if we already have vision on a tile. Moreover, we could also use a
vector(vector(std::pair(bool,bool))) the first bool being the vision last turn and the second one the vision for this turn. That would avoid aving 2 lists.
WDYT ?

**Comment by Bertram25** [comment]
This is also a relevant way to use the same concept. The vector memory overhead shouldn't  be problematic anyway, and if you reserve the vector memory (or even fill it with false at map load time), memory allocation shouldn't be problematic. So yes, it's viable, IMHO. :)
