### ISSUE TITLE
Add a checkbox on the quit window, to optionally disable the replay creation.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#406]
The check will be unchecked by default, to avoid creating multiple replays without the user leave.

**Comment by akien-mga** [comment]
Personally I would prefer an opt-out box to _enable_ replay creation, i.e.:
- [x] Save the game's replay

_Edit:_ On a second thought I don't care that much, both variants would be fine :-)

**Comment by akien-mga** [comment]
Actually re-reading the first comment, I think you mean to have an opt-in checkbox (i.e. unchecked) to _enable_ replay creation (and not to _disable_ it as said in the title), so:
- [ ] Save the game's replay

That would be best IMO: you only save the replay if it is worth it. Maybe the replay should be automatically saved too when the game crashes though, so that would mean that the replay is always saved, but it is deleted if you quit the game and did not check the checkbox.

**Comment by hwoarangmy** [comment]
In any case, keeping the replay in the memory until the user chooses to save it would be memory consuming for a side feature. The easiest is, as you say, to write it on the hdd and erase it if the player chooses not to keep it. Moreover, that would solve the "game crash replay lost problem" ^^

**Comment by Bertram25** [comment]
>  The easiest is, as you say, to write it on the hdd and erase it if the player chooses not to keep it. Moreover, that would solve the "game crash replay lost problem" ^^

Yeah, keeping something ever-growing in memory isn't a good idea, IMO, anyway.

**Comment by Bertram25** [comment]
Note to self: With PR about the GUI done, Only this is needed to be added in the game mode part, to add the checkbox, next to the No button window declaration:

``` xml
            <Window type="OD/Checkbox" name="SaveReplayCheckbox" >
                <Property name="Area" value="{{0,29},{0,140},{0,149},{0,190}}" />
                <Property name="Text" value="Save the game's replay?" />
            </Window>
```

The rest will be some code.

**Comment by hwoarangmy** [comment]
Now that you talk about it, it could be cool to have some kind of real window (like the creature stats) for exiting. The ones that can be moved (again, like creature stats).

**Comment by Bertram25** [comment]
> Now that you talk about it, it could be cool to have some kind of real window (like the creature stats) for exiting. The ones that can be moved (again, like creature stats).

Ok, I'll handle it.

**Comment by hwoarangmy** [comment]
thanks ^^

**Comment by Bertram25** [comment]
Note to self: use a layout: 

``` c++
CEGUI::Window* newWindow = CEGUI::WindowManager::getSingleton().loadLayoutFromFile("QuitMenu.layout");
myRoot->addChildWindow(newWindow);
```
