### ISSUE TITLE
Kobold carriers: Make dug gold be carried item as traps and corpses, gold on claimed tiles.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#407]
Gold stacks should be carried items also when digging gold.
This will be visually more appealing and make it clear why a kobold stops digging and goes back to the treasury.

Are you ok with this feature request, guys?

**Comment by Danimal696** [comment]
i guess its good, since you can kill the kobold and get the gold, while otherwise it just dissapear on death

**Comment by hwoarangmy** [comment]
Gold stacks are already carried when the kobolds wants to. But the priority is probably too low, and, thus, they usually don't do that until they have nothing else to do.

**Comment by Bertram25** [comment]
@hwoarangmy Yes, but here, I'm speaking of the gold they carry after digging some gold tiles. It isn't shown at all, in fact.

**Comment by Bertram25** [comment]
> i guess its good, since you can kill the kobold and get the gold, while otherwise it just dissapear on death

Good point. I think gold shouldn't disappear. Adds some strategy. :>

**Comment by hwoarangmy** [comment]
> Yes, but here, I'm speaking of the gold they carry after digging some gold tiles

Sorry, i didn't understand ^^
But in this case, we should take care. What about fighters carrying gold ? Will they bring a stack ? Do we want a different behaviour ? In any case, we can always create a gold stack when a kobold carrying gold dies.

**Comment by Bertram25** [comment]
> What about fighters carrying gold ? Will they bring a stack ? Do we want a different behaviour ?

IMO, Fighters carried stuff (be it special objects, or gold) should appear only on death, as suggested in #34 
For workers on the other hand, and as one of their primary use is to carry things, I would show it and possibly use a common logic for that. Visually, it would more appealing, again, IMO.

**Comment by hwoarangmy** [comment]
Well that could easily be done by creating a gold stack as a worker digs gold and raising carry task priority (at least for gold).

**Comment by Danimal696** [comment]
im feeling that in the future we will add the dreadful payday -_-,

**Comment by hwoarangmy** [comment]
> im feeling that in the future we will add the dreadful payday

It's a must have to make gold needed. I would say that it is currently the biggest problem in the game. Actually, ATM, the AI just stops working when it gots enough gold. And because it doesn't spend anything after that, it just does nothing (until we implement spells and they start to attack ^^)
