### ISSUE TITLE
Implement trap logic

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#408]
Here is what was decided so far:
- When a trap is built, only the player creating it (and his allies) should see it.
- Once a trap has triggered, it becomes visible to the ennemy teams that had vision on the tile.
- Fighters should not engage attackable traps that are not visible for their owning player.
- Traps should not be visible for ennemy players until a crafted trap has activated them. However, if the tile is claimed by an ennemy, the trap is destroyed.
- Deactivated traps should be shown as deactivated after triggering for every player who got vision on it (including ennemies)
- Some traps (like spike trap) should be able to hidden the default tile mesh they are on when visible.

If someone sees something to add, please feel free

**Comment by Danimal696** [comment]
> Traps should not be visible for ennemy players until a crafted trap has activated them ?

Yes, its not nice that something that doesnt even exist yet, just on planes, is destroyed for good. Getting that tile claimed by enemy team would be exception, since it destrpys the blueprint over it

> Deactivated traps should disappear (for example the boulder after it triggered)?

I would prefer that they go transparent waiting for a new one to be forged and mounted on the same place, it saves having to do it manually each time

> Do we want traps visible even before getting triggered (like cannons) ?

No, let it be a surprise the first time its encountered

**Comment by hwoarangmy** [comment]
> I would prefer that they go transparent waiting for a new one to be forged and mounted on the same place, it saves having to do it manually each time

Sorry, my sentence was not clear. I meant for ennemy players. Should they see the trap as it was ready to trigger when deactivated ? Or should it disappear ?

**Comment by Danimal696** [comment]
i think they should see it as desactivated (transparent), it will help a lot on 1 player levels and hurry they up to attack your weakened defenses :D

**Comment by Bertram25** [comment]
As for cannon, I guess they won't stay hidden for a long time though, as they'd appear once shooting anyway. So the overall logic is fine, IMHO.

**Comment by hwoarangmy** [comment]
I've updated the main text. Moreover, I've added:
- A trap becomes visible for an ennemy when it triggers while he has got vision.

That means that if you play FFA and an ennemy triggers a trap from someone else while you got vision, you will see the trap. Moreover, if a trap (like cannon) shoots while you don't have vision, you won't see it until you are closer.
Are you ok with this ?

**Comment by Danimal696** [comment]
its a good addition

**Comment by hwoarangmy** [comment]
That would also make usefull a spell that would reduce creature vision ^^

**Comment by Bertram25** [comment]
lol :)
