### ISSUE TITLE
Try to find a workaround for the GLSL error: Error prior to using GLSL Program Object : invalid value

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#41]
> This error happens in output on linux when the beetle Golem (the bigger yellow worker) is on screen, so it might be related to its material file.

This above was wrong: The error happens when you have tiles marked to be dug on screen. I could reproduce it 100% of the time when marking dirt or gold to dig.

This also might be the (or a) cause of the lack of coloring when marking a tile as described in #39

**Comment by Bertram25** [comment]
@hwoarangmy @Danimal696 
My laptop GPU (and linux drivers) might be in cause there.

I'll have a look at whether it is possible to disable the normal sub state rendering (SRS) when marking a tile to dig and renable it when unmarking it.

**Comment by akien-mga** [comment]
I could reproduce the crash on Linux with my Intel GPU, I'll try with my nvidia GPU now.

```
Computing turn 150
During this turn there were 175 calls to GameMap::path().Processing deletion queues on turn 150
Server sends newturn=150
Client received turnStarted=150
Error prior to using GLSL Program Object : invalid value
Error prior to using GLSL Program Object : invalid value
An internal Ogre3D error ocurred: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_17_12_7_node' not found. in SceneManager::getSceneNode at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 920)
Internal Ogre3D exception: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_17_12_7_node' not found. in SceneManager::getSceneNode at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 920)
*** ERROR: Internal Ogre3D exception: OGRE EXCEPTION(5:ItemIdentityException): SceneNode 'Treasury_17_12_7_node' not found. in SceneManager::getSceneNode at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreSceneManager.cpp (line 920)
```

I'm not 100% sure how I reproduced it, I'm still learning the gameplay :P

**Comment by akien-mga** [comment]
It seems the GLSL issue does not appear with my nvidia GPU, though I got a crash for similar reasons (i.e. Treasury_*_node not found).

**Comment by Bertram25** [comment]
News: There is a log of work on improving GLSL shader parsing atm.
Commit log example:

```
glsl/glcpp: Rename one test to avoid a duplicate test number    Carl Worth  2   -0/+0
glsl/glcpp: Fix handling of commas that result from macro expansion Carl Worth  3   -12/+45
glsl/glcpp: Integrate recent glcpp-test-cr-lf test into "make check"    Carl Worth  4   -13/+42
glsl/glcpp: Fix glcpp-test to correctly extract test-specific arguments Carl Worth  1   -1/+1
glsl/glcpp: Fix line-continuation code to handle multiple newline flavors   Carl Worth  1   -9/+87
glsl/glcpp: Don't include any newline characters in #error token    Carl Worth  1   -1/+1
glsl/glcpp: Treat CR+LF pair as a single newline    Carl Worth  2   -5/+9
glsl/glcpp: Add test script for testing various line-termination characters Carl Worth  2   -11/+137
glsl/glcpp: Fix for macros that expand to include "defined" operators   Carl Worth  3   -45/+387
glsl/glcpp: Swallow empty #pragma directives.   Carl Worth  2   -1/+7
glsl/glcpp: Fix #pragma to not over-increment the line-number count Carl Worth  3   -2/+12
glsl/glcpp: Add testing for null directives with spaces and comments    Carl Worth  2   -0/+18
glsl/glcpp: Fix NULL directives when followed by a single-line comment  Carl Worth  1   -1/+1
glsl/glcpp: Add tests for #define followed by comments  Carl Worth  2   -2/+8
glsl/glcpp: Allow single-line comments immediately after #define    Carl Worth  1   -1/+1
glsl/glcpp: Add test for "#define without macro name"   Carl Worth  2   -0/+4
glsl/glcpp: Add explicit error for "#define without macro name"
```

So I'd say let's wait for next mesa versions & intel glx drivers.

**Comment by akien-mga** [comment]
Nice :-)

BTW, do you know if the GLSL shader issues are a regression in cutting-edge mesa and intel drivers, or would it also affect previous versions? I'm running Xorg 1.16 with the latest mesa and intel versions here.

**Comment by Bertram25** [comment]
The former glsl shaders were the one from Ogre 1.7 and weren't working for some reason on linux when used against Ogre 1.9 AFAIK.

So I can't tell whether it is a regression in Ogre shaders, in intel drivers, or on both sides.
I'd need to setup some glsl shader debugger (like glslDevil) and have a look at which file(s) and which statement(s) is(are) actually triggering the warning as a start point, but the debugger itself might not see anything, as for instance, glslDevil is using is own parser IIRC.

I'm using Xorg 1.15 and mesa/intel 12.2.4 here atm. (and I can play XCOM on my laptop!! Yay!!) ;)

**Comment by akien-mga** [comment]
For the reference, GLSL with the intel driver seems to be supported in SuperTuxKart, at least their irrlicht fork says so.

**Comment by Bertram25** [comment]
> For the reference, GLSL with the intel driver seems to be supported in SuperTuxKart, at least their irrlicht fork says so.

As far as I understood, GLSL is supported with the latest intel drivers on linux. It's just they have cases where either the shaders aren't well parsed, well compiled, ...
But I'm sure this will improve a lot with 10.3 as I've seen some work on it lately.

**Comment by Bertram25** [comment]
Tested with mesa 12.2.6. The warnings are still here. I guess it will have to wait for 10.3 (hopefully) ??

**Comment by akien-mga** [comment]
I still get the warning with mesa 10.3 RC1 :-(

**Comment by Bertram25** [comment]
> I still get the warning with mesa 10.3 RC1 :-(

There is so much glsl bug reports in mesa I don't think our case will be handled right away, but in any case, the glsl error can come from an glsl mishandling but also from a gl feature not supported by the mesa drivers as said here as well:
http://www.ogre3d.org/forums/viewtopic.php?f=2&t=44132&start=25

I'll try to find the actual line breaking the glsl shader compilation and maybe we'll find more clues. ;)

EDIT: note to self: http://www.ogre3d.org/forums/viewtopic.php?f=5&t=63604

**Comment by Bertram25** [comment]
Why I am not in a hurry to fix this shader bug:
http://yosoygames.com.ar/wp/2014/05/a-glimpse-of-whats-comming-to-ogre-2-0-final/

**Comment by oyvindln** [comment]
I am getting this message spammed when I try the very small test map. It only appears when the yellow golem thing is on screen as you wrote first. I am not getting it simply by marking tiles for digging. The spinning thing under the golem also becomes opaque, with the transparent parts taking the team colour value when it's over claimed tiles. I have an old (dx9) nvidia card (quadro 3500m).

Also, can't wait for ogre 2.0 :)

**Comment by Danimal696** [comment]
that minion-thing is due to dissapear soon, i wouldnt worry about it

**Comment by Bertram25** [comment]
Unassigned myself. I'll only keep assignment where I'm actual working on stuff. It's saner IMHO.

**Comment by Bertram25** [comment]
I've just read somewhere that glsl shader compilers could sometimes trigger a warning or an error when a float values was expected on a uniform while a value without dots would be given. Example:
0 instead of 0.0 or 4 instead of 4.0

I'll check several material files tonight and will apply trivial fixes there. This can't hurt.

**Comment by akien-mga** [comment]
I confirm that the fix removed the warnings for me too.
