### ISSUE TITLE
Upgrade the remaining UI

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#419]
Most notably, the Check-boxes and combo-box need a lifting.
The tooltip may look better if they are black with some white text.

**Comment by Bertram25** [comment]
Check-boxes and radio buttons done.
The tooltip have also been updated.

What's left mainly are the combo boxes.
Then, what's left needs to be checked if it's actually use somewhere and if so, can be ported.

**Comment by hwoarangmy** [comment]
There are combo boxes in the seat configuration lobby (to choose player/faction/team).

**Comment by Bertram25** [comment]
> There are combo boxes in the seat configuration lobby (to choose player/faction/team).

Yep, that's why they'll be my next victims. :>

**Comment by Bertram25** [comment]
Teaser-on: I've locally prepared the options and quit menus.
And added support for horizontal sliders in the look n feel, functional but still ugly looking. :fearful: 

I've now got to polish all that, and deal with the pixel side. :smile: 
I guess I'll deal with #406 first and add some of the work along with it, to keep small steps PR.
Teaser-off. ;)

**Comment by hwoarangmy** [comment]
> I've locally prepared the options and quit menus.

^^

> functional but still ugly looking.

hehe

**Comment by Bertram25** [comment]
Next plan is to separate the in-game bottom tab UI from a standard tab UI for other controls.
This will permit me to make the KeeperTab better looking. :)

**Comment by hwoarangmy** [comment]
BTW, I've tested the new UI and it is pretty nice. The only thing that seems weird is the picture on the south tab background. But I like the rest ^^

**Comment by Bertram25** [comment]
Thanks :) The tab content pane background is atm only a try so please don't give too much heed, I'll first replace it with a boring standard tabs content pane and will then specialize that tab to use more keeper like graphics. :)

**Comment by hwoarangmy** [comment]
ok, no pb. IMHO, it is better like that than it was. We will see what can be improved later ^^

**Comment by Bertram25** [comment]
A graphical teaser :)
![opendungeonsskin](https://cloud.githubusercontent.com/assets/765917/5916677/fdadc5bc-a613-11e4-8c61-b6707fdbee54.png)
See any differences? ;)

**Comment by hwoarangmy** [comment]
> See any differences? ;)

I would guess at scroll bars ? And a new background for the rooms/traps/... tabs ;-)
Cool ^^

**Comment by Bertram25** [comment]
Almost! My only shame is that I didn't reach the point where I've made cooler in-game tabs.
For now, I've made them simple again, (So they can be used in the options menu, for instance),
and I'll add specialized tab widgets for each factions. :)

I've managed to improve the sliders, and added 2 working and improved progress bars. :)
And list menu working graphics. The UI is almost done as a first 1.0 version. ;)

Once this is done, I'll be back on tabs. :>

**Comment by Bertram25** [comment]
Ok, Gui 1.0 Done. What's next is adding fancy tabs per faction. But that won't be part of the next PR: :)
![od-gui-1 0](https://cloud.githubusercontent.com/assets/765917/5919223/14a226a0-a632-11e4-845c-79a19c7416d5.png)
Feedback very welcome :)

**Comment by hwoarangmy** [comment]
> What's next is adding fancy tabs per faction

Yep, that's a later issue ^^

> Feedback very welcome :)

The new gui seems nice (BTW, I think I've never had the occasion to say I like the new UI ingame). What are the grey bars for ? Scrollbars ? They seem a little bit... grey to me but we will see ingame ^^

**Comment by Bertram25** [comment]
> The new gui seems nice (BTW, I think I've never had the occasion to say I like the new UI ingame). What are the grey bars for ? Scrollbars ? They seem a little bit... grey to me but we will see ingame ^^

They are sliders, indeed, and yeah, they are still too greyish. I must say I had some problems to figure out stuff with the look'n'feel linked to them so I was happy once they were working fine without focusing too much on their graphics.
Now the look'n'feel has been tamed, I'll change those to make them more inline with the rest.
