### ISSUE TITLE
App mouse icon handling

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#420]
This issue is about deciding what we want and can add as a the app mouse cursor.

I see several possibilities we can discuss, of course. :)
- **Long-term solution/nicest one:**
  Use the keeper hand mesh as the app icon for everything. This means we'll have to stop using the default rendering queues of Ogre, and setup the engine to render 3 layers in a specific order, the game, the GUI and then the hand.
  This is the hardest solution and may give problems with the z-buffer as far as I have seen but it is not impossible to do.
- **Short-term/cheapest one:**
  Use a CEGUI icon. This is easy, cheap, and can be done right away. It also involves removing the hand in game.
- **Some kind of compromise:**
  Make the icon show when you are on the GUI, and hide to be replace by the hand when you're in game.

Please comment. :)

**Comment by Danimal696** [comment]
> Some kind of compromise:
> Make the icon show when you are on the GUI, and hide to be replace by the hand when you're in game.

This one looks the better, Lets search for a hand icon to show over the GUI and resembles the 3D one

**Comment by hwoarangmy** [comment]
> Some kind of compromise

Seems better for now.

**Comment by Bertram25** [comment]
An icon for the heroes faction ;]: http://opengameart.org/content/pointers-part-5

As for the keeper's one, I'd love to see something like this: http://www.iloveswords.com/images/LOTR/LOTR_gauntletLRG.jpg

**Comment by hwoarangmy** [comment]
> As for the keeper's one, I'd love to see something like this: http://www.iloveswords.com/images/LOTR/LOTR_gauntletLRG.jpg

That's very nice. And that could fit also for heroes ^^

**Comment by Bertram25** [comment]
Second point I wanted to open (but not for 0.5.0, rather when it comes and if it comes(tm)):

ATM, the hand and the light is moving tiles per tiles, just like the tile selector which is already fine.
As a way to make this smoother, I wondered whether we could keep the current behaviour for the tile selector, but make the light and hand location placed under the cursor and not forcefully on the current tile center. This would make moving the hand and lighting much less stuttering, IMHO.

WDYT?

**Comment by Bertram25** [comment]
Pinging @akien-mga @oyvindln

**Comment by akien-mga** [comment]
I think this would make the lighting look awesome at the very least :-)

**Comment by Danimal696** [comment]
yes, the ligth change is so sudden that along with normals you feel some models skin "shifting"

**Comment by Bertram25** [comment]
> yes, the ligth change is so sudden that along with normals you feel some models skin "shifting"

+1. That's how I noticed it at first, in fact.
