### ISSUE TITLE
Change the engine version from 0.4.9 to 0.5.0 now we have a stable release. :)

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#424]
This is trivial to do but will have to be done anyway. ;)

The CMakeLists.txt file and the maps will have to be adapted.

**Comment by akien-mga** [comment]
Should we have a -dev suffix or something to confirm that it's a development version and not the final 0.5.0? We would have to remove the -dev suffix when releasing stable versions though.

_Edit:_ The dev suffix would be only for the CMakeLists.txt IMO, no need for the levels.

**Comment by Bertram25** [comment]
> Edit: The dev suffix would be only for the CMakeLists.txt IMO, no need for the levels.

The levels check the game version using a '==' IIRC, atm. This means it can't work that way, unfortunately, without some code change.
This brings the following point. IIRC, we weren't willing to do some backward compatibiliy handling, at least now the beast is still changing fast.
Feel free to comment on how you see backward compatibility handling, though.

**Comment by hwoarangmy** [comment]
It's fixed in the associated commit
