### ISSUE TITLE
Wiki decision and info update.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#426]
Hey there,

Atm, we have a wiki on the website that is unfortunately not quite responding and start to be out of date.
As the github wiki is available and can support images upload, I was wondering whether you guys were willing to keep using the one on sourceforge or start importing data here.

Once we have decided that, there are several stuff that needs to be done to prevent us from forgetting all the available feature OD already has. :)
- Compiling.
- How to play + game play features explained.
- Level Editing how-to + Seat, aliances setup how-to.
- Factions available and what they are.
- Rooms available and planned.
- Units available and planned.
- Research tree.
- Sounds handling (Creatures class, ...)
- Anything else fitting there...

We could separate what's done from what's planned by added some TODO tag next to what is planned, for instance.

IMHO, this issue is becoming more and more important as the game is already a complex beast and time already works against our memory. ;)

**Comment by akien-mga** [comment]
Since there is no so much content on the SF wiki currently (at least from what I could see), I think we could go with the GitHub option, thus having most things in one place.

BTW we should discuss with Elvano what we want to do with the main website. Currently it's a static website with minimalistic design that can be managed via SF's FTP. We've discussed it a bit with Elvano and we both think that a static website could be enough for the current usage that we make of it: show some screenshots and videos, add some explanation about the game and its development, downloads links, forum + wiki + GitHub links, and occasionally some news.

**Comment by Wout-van-Dongen** [comment]
A new platform may not be much of an answer if nobody will use it, as it was the problem with the wiki. It turned out to be a place to post ideas and dreams rather than facts when it was new and it was soon forgotten afterwards.
If you feel that Github offers a better alternative, as far I am concerned you are free to use it, but be aware it shall require (firm) management.

**Comment by akien-mga** [comment]
The main problem of the current wiki is that some active contributors that arrived after it being set up (@hwoarangmy and I, I guess) have no credentials to edit it. Of course we could request credentials from @Wout-van-Dongen (Elvano in disguise! :-P), but it's harder to manage credentials through one contributor that via GitHub IMO that would let practically all registered contributors from OD edit the wiki, and those are easy to manage.

Another advantage of using GitHub for the wiki is that most important stuff (code, bug reports, wiki) would be in the same place, and (hopefully) that can encourage us to write content in the wiki (and do contextual links to relevant bug reports, etc.).

Now I'm not strongly against keeping the SF wiki, we would just have to decide what we want to put in there, how it should be organise, and I'll harass @Wout-van-Dongen to get credentials ;-)

**Comment by Bertram25** [comment]
>  @Wout-van-Dongen (Elvano in disguise! :-P)

Ah, I knew it! :P Welcome Elvano.

> show some screenshots and videos, add some explanation about the game and its development, downloads links, forum + wiki + GitHub links, and occasionally some news.

I do agree as it would indeed suffice to show what we have while my main point is to avoid killing you guys in making super-heavy web development for something that can pretty straight-froward, so I'm all for a simple static website that does the job and doesn't require a full web-designer's team.

> If you feel that Github offers a better alternative, as far I am concerned you are free to use it,

For the record, I have nothing against or for github's wiki or the sf one, sincerely. I'm just making options clear for everyone so we can choose with sufficient intel.

> A new platform may not be much of an answer if nobody will use it, as it was the problem with the wiki. It turned out to be a place to post ideas and dreams rather than facts when it was new and it was soon forgotten afterwards.
> ... but be aware it shall require (firm) management.

Exactly. This is an interesting point raised, btw.
Wikis are often falsely used as a location to dump dreams and more or less crazy goals, especially in young spare-time projects. And sorry to say that bluntly, but IMHO and taken from some experience in it, I do think it's plain wrong to use it that way, or at least mix the crazy dream content with the work actually done or about to be done.

That's what I'm requesting here mainly, that we:
- Document the current game modes, their options, and how we can play, map edit and mod the game atm.
- Document what content is to be added for the given milestone, be it units, rooms, or certain concepts not that obvious.
- Maybe add a few longer-term guidelines but not much.

In this, I mean the wiki should not be the place to add crazy campaign ideas, advanced scripting concepts, long list to spells to do in 12 milestones, and the like ... We have the forums for that, IMHO.
But we can add the units done and missing to make keepers and heroes equal for the current milestone, talk about the few rooms missing and the ones ready, about the research tree as it is rather small AFAIK, ...

I hope we can have a consensus about this.

Best regards,

**Comment by hwoarangmy** [comment]
I don't care which platform we use but I definitely think we should add in the wiki the needed how to (compile and stuff). Concerning The goals, I think another project "UFO AI" did something not stupid that we could also do: quote in the wiki the most usefull things said on the forum. This way, it is some kind of copy/paste that just needs some ordering ^^

BTW, I would also had some kind of dev guide explaining the general philosophy of the game (client-server behaviour, ...)

**Comment by Bertram25** [comment]
> BTW, I would also had some kind of dev guide explaining the general philosophy of the game (client-server behaviour, ...)

Yeah, some quick dev explanation of the architecture, nothing long, would be great.
Something more extensive should go for the players, and the modders. :)

> Concerning The goals, I think another project "UFO AI" did something not stupid that we could also do: quote in the wiki the most usefull things said on the forum. This way, it is some kind of copy/paste that just needs some ordering ^^

I've looked into their wiki a bit and I didn't see anything looking like copy/pasted quotes. Could you give me a link of what you have in mind?
Btw, the UFO AI wiki is one of the best stuff I've ever seen in an open-source project. I won't dare being that audacious for a first refresh. ;)

If @Wout-van-Dongen isn't too much against it, I'll start adding stuff in github's wiki to see how it turns. First things first, I'll import the existing and we'll see whether it feels better or worse that way.

**Comment by akien-mga** [comment]
> I'll start adding stuff in github's wiki to see how it turns. First things first, I'll import the existing and we'll see whether it feels better or worse that way.

If we start fresh on a new platform, maybe we should first decide what we want to keep from the existing wiki before we import it? Maybe we can start by designing the main page, and then fill in the blanks with content from the existing wiki and new stuff?

**Comment by Bertram25** [comment]
> If we start fresh on a new platform, maybe we should first decide what we want to keep from the existing wiki before we import it? Maybe we can start by designing the main page, and then fill in the blanks with content from the existing wiki and new stuff?

Yep, I'm making a small proposal atm right there. Then, I'll ask for your comments and fixes, guys. :)
I'm sure together this can be sorted out very easily.

**Comment by hwoarangmy** [comment]
> I've looked into their wiki a bit and I didn't see anything looking like copy/pasted quotes. Could you give me a link of what you have in mind?

Yep, seems like they have updated it since the last time I've read (one year ago). I couldn't find either what I was talking about. But that's pretty simple. For example, that could look like:

```
Research tree mock-up
The keeper should be able make researchs in the library to specialize into 3 paths: Spells, traps or creatures.

[QUOTE="Danimal"]The colour represent focus (or Paths of Evil) Red: strength - strong minions, Grey: neutral - versatile and defensive , Blue: magic - lots of spells.
The darker rows show research difficulty tiers (3 or 4 ? i think we only have enough content to fill 3) they could be locked on campaign until completing some level and awarding access to the next tier.
First row is free and pre-unlocked, since they are the most basic and essential rooms, we should block the research button to the condition of having a library
You need to research at least 1 item to proceed to a lower row of the same branch (Path)
Overall you could research all items of the low and medium tier for versatility or rush to the end of the highest tier and get some heavy firepower if you are faster than your opponents, or research everything on the same level if you feel god-like[/QUOTE]
```

And in the quote, we would copy/paste the more relevant summary of what has been decided

**Comment by Bertram25** [comment]
Ah I see. I don't mind keeping the author of the "quote", but as we'll be formatting it to obtain the most fitting gist sooner or later, I would let it as a quote but as real documentation.

That said, it's just a matter of taste and as long as we have the info, I'm taking it. :)

**Comment by Bertram25** [comment]
Btw, to add images to the github wiki, one has to clone the wiki repository and push images there.
I'll do it asap but if somebody does it before me, could you add images in a images/ folder for instance only (I mean not alongside the .md pages.)?

Thanks!

**Comment by Bertram25** [comment]
Ok, I've added a bit of content in the github wiki.

I'll add images this week-end. Feel free to tell me if the overall stuff looks going in the right direction and make corresponding fixes. :)

**Comment by hwoarangmy** [comment]
I've updated the how to compile with MSVS2013 but the page is not accessible anymore. After my changes, I've tested it and it was working fine. I've even tried to access it with my browser history but the page seems to be gone. Is there a way to see what happened ?
The page is:
https://github.com/OpenDungeons/OpenDungeons/wiki/How-to-compile-using-MSVC-Express-2013-

and it used to be
https://github.com/OpenDungeons/OpenDungeons/wiki/How-to-compile-using-MSVC-Express-2012-

**Comment by akien-mga** [comment]
It seems that the last dash (maybe representing the + in "2013+"?) got removed somehow, you page is here: https://github.com/OpenDungeons/OpenDungeons/wiki/How-to-compile-using-MSVC-Express-2013

I found it by cloning the wiki repo at https://github.com/OpenDungeons/OpenDungeons.wiki.git

**Comment by hwoarangmy** [comment]
ok. Thanks for the trick about how to find the pages ^^

**Comment by Bertram25** [comment]
Don't forget that you have the Pages tab on the right part of the screen where your page should be listed, whatever its name.

While we're on the subject, cloning the wiki is also the sole way to get images there (without external links, of course.)
I'll push images of the icon how-to so we have an example of how to use that. :)

**Comment by Bertram25** [comment]
Ah, also: git with push access clone command:
`git clone git@github.com:OpenDungeons/OpenDungeons.wiki.git od-wiki`

**Comment by hwoarangmy** [comment]
ok, thanks. I've fixed the links.

**Comment by Bertram25** [comment]
Ok, I've added a few images. I'll add the rest once I've found my save of the former ones...
But basically, if you go to the how to make an icon, you should have a working sample.

**Comment by Bertram25** [comment]
Note to self: Add the missing images in the icon how-to. The images are there: http://forum.freegamedev.net/viewtopic.php?p=58762#p58762

**Comment by Bertram25** [comment]
Note to self: Bis: Import the how to make models tutorial in the wiki as well.

**Comment by Bertram25** [comment]
Missing images in both how to + models how to imported. Let's open new issues as we see specific needs.
