### ISSUE TITLE
Obsolete replays: Assert failed file source/modes/MenuModeReplay.cpp lines 204 and 206

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#427]
When clicking on replays without starting them in the "Replay" GUI, I get spammed with this assert failure:

```
ERROR: Assert failed file /home/akien/Projects/opendungeons/OpenDungeons/source/modes/MenuModeReplay.cpp line 204
ERROR: Assert failed file /home/akien/Projects/opendungeons/OpenDungeons/source/modes/MenuModeReplay.cpp line 206
```

If I start a replay, I get a segfault with std::bad_alloc:

```
Reading replay from file /home/akien/.local/share/opendungeons/replay/replay_20141209_235923.odr
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abandon
```

**Comment by akien-mga** [comment]
Actually this happened when clicking on or trying to load replays from 2014 that were recorded before the FoW implementation, so it's understandable that they would not work.

@hwoarangmy I'll let you see whether you want to close this one as wontfix, or if you want to add a check for "conformity" of the replay (I notice e.g. that with a replay from 2015, I don't get the failed assert at MenuModeReplay.cpp:204 and MenuModeReplay.cpp:206, so these asserts might be a good way to find out broken replays and prevent from loading them).

**Comment by Bertram25** [comment]
I was wondering. I guess replays should be linked to a game version and in that, shouldn't be supported if you run another game version than the one it was created with, right?

Maybe some kind of check should be done about this?

**Comment by akien-mga** [comment]
> I was wondering. I guess replays should be linked to a game version and in that, shouldn't be supported if you run another game version than the one it was created with, right?

I agree, that would probably be the simpler thing to implement. (We can always revert if starting with 0.8.x the game is stable enough that replays from previous versions will still work ;-).
And if replays break during the development of a milestone, that's okay, we don't provide that kind of extended support for developers :-P

**Comment by Bertram25** [comment]
Then #424 is a pre-requisite to this one, IMHO.

**Comment by hwoarangmy** [comment]
Yes, there have been many changes with FOW (removed some messages and changed the game initialization now that client do not read the level file). And, thus, old replays are broken. So, it's a won't fix.

As you said, the easiest is to check for version to know if a replay is good or not. But I'm not sure we should do that right now because we are regularly breaking replays with our PRs (and sometimes, without changinf version). IMHO, checking for version would make us have to be sure replays are not broken when we do a patch which is too early. That's why it is an experimental feature ;)

**Comment by akien-mga** [comment]
Alright, closing for now. Let's see when replays are stable enough :-)

**Comment by hwoarangmy** [comment]
IMHO, we will have to deal with this kind of feature when we will go far the menu to navigate through replays.

**Comment by Bertram25** [comment]
> IMHO, checking for version would make us have to be sure replays are not broken when we do a patch which is too early. That's why it is an experimental feature ;)

IMHO, as long as we display this menu in stable release, we should make sure replays are functional between every stable release. This feature is not that experimental as it is working great usually. :)

My point is that check the replays version will help us and the other users select what replays they still can watch and thus should be done anyway, IMHO.

**Comment by hwoarangmy** [comment]
It is done in #430. As you say, because the menu is displayed in the release, having a segfault is not acceptable ^^
