### ISSUE TITLE
Replay menu: Sort replays alphabetically

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#429]
The replays in the replay menu are currently displayed in an apparent random sorting, as shown on this screenshot:
![od-replays](https://cloud.githubusercontent.com/assets/4701338/5665495/1c9e41f0-9759-11e4-89fa-843eab703143.jpg)

It would be nice to sort replays alphabetically, so that you can locate the replay of a given date easily.

**Comment by Bertram25** [comment]
I would also sort alphabetically the skirmish and multiplayer map lists.

Could the window right part be used to display the game version as well, by any chance?

**Comment by hwoarangmy** [comment]
yep, i was also thinking of sorting everything

**Comment by hwoarangmy** [comment]
> Could the window right part be used to display the game version as well, by any chance?

Only for replay or for every map ?

**Comment by Bertram25** [comment]
Well, as we have no kind of backward compatibility for now, the map displayed should be of the right version. But later, it will be useful
