### ISSUE TITLE
Implementing pay day

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#431]
Proposition for pay day (to be discussed)
- Every X turns (configurable), creatures will go to the nearest non empty treasury and try to get their fee
- The fee should be calculated like HP: base + quantity per level
- If a creature is not paid, it has a (huge) impact on its mood
- When a creature (fighter) carrying gold is killed (by the keeper or an enemy), the carried gold is dropped. Carried gold cannot be more than 1 pay (if it is over, it's lost).

If you see something else to add, please feel free ^^

**Comment by Danimal696** [comment]
they use that gold for gambling at casino? maybe to pay for weapon upgrades as well?

**Comment by Bertram25** [comment]
> When a creature (fighter) carrying gold is killed (by the keeper or an enemy), the gold is lost ?

Yeah, they either have to spend it, or we can drop just latest wage until money spending is implemented.

What do you think?

**Comment by hwoarangmy** [comment]
I think we should at most drop the latest wage (but clearly not more). And we might also want to decrease this amount each turn to avoid strategies where we would take expendable units, wait for next pay day and kill them before they go to the treasury to get back the money.

> they use that gold for gambling at casino?

That would mean that a creature that just came to the dungeon or that has no money cannot go to casino. Well, if everybody agrees with that, why not ?

> maybe to pay for weapon upgrades as well?

They would pay for weapon upgrades themselves ? IMHO, that's the keeper's duty...

**Comment by Bertram25** [comment]
> I think we should at most drop the latest wage (but clearly not more). And we might also want to decrease this amount each turn to avoid strategies where we would take expendable units, wait for next pay day and kill them before they go to the treasury to get back the money.

Sincerely, I would allow that twisted strategy as a game permitted twist. ;) Plus, if we make wages disappear, creatures will never have time to play Casino, or any Evil game we shall invent someday for them.

> They would pay for weapon upgrades themselves ? IMHO, that's the keeper's duty...

It's a good question and I do think this should remain our thing, but practically how do you see improved equipment handling, step by step?

**Comment by Bertram25** [comment]
I was also thinking, if we add some kind of casino room, where will the benefits of this evil room go? :>

**Comment by hwoarangmy** [comment]
> Sincerely, I would allow that twisted strategy as a game permitted twist. ;) Plus, if we make wages disappear, creatures will never have time to play Casino, or any Evil game we shall invent someday for them.

Well, in reality, we don't need them to have money to be allowed in the casion ;)

> It's a good question and I do think this should remain our thing, but practically how do you see improved equipment handling, step by step?

I've not really thought about it yet but I would see a GUI screen showing the available weapons to craft. We could select some and the forge workers would start to craft them. Then, they would go to the armory and creatures could take them.
I agree it is not really clear how to choose which creature would be assigned which weapon. But I guess @Danimal696 is the one who thought the most about it so he might have ideas about it.

**Comment by Danimal696** [comment]
> I was also thinking, if we add some kind of casino room, where will the benefits of this evil room go? :>

To our treasury, of course!

Regarding the forge system, ill post on forum a draft
