### ISSUE TITLE
Some tiles are not highlighted when hovered by the selection zone

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#434]
Seen when testing #432, but this might be a regression due to the FoW:

![od-select](https://cloud.githubusercontent.com/assets/4701338/5719749/8f8d9b28-9b1b-11e4-8867-5cddfb0a524e.jpg)
As detailed in the topic, this happened when hovering a rectangular area with the "dig" marker (click on a tile + drag to create the rectangular area).
Clicking does produce the expected output (all dirt and gold tiles under the selection zone are marked to be dug).

This was on Greed or Might, I'll see if I can reproduce.

**Comment by akien-mga** [comment]
It can't be systematically reproduce, I'll keep an eye open for another manifestation of this bug.

**Comment by Bertram25** [comment]
Same to me, it's random but rather near game start, right?

**Comment by akien-mga** [comment]
> Same to me, it's random but rather near game start, right?

On my screenshot it is, but I haven't reproduced it a second time yet. It seems to be affected by the rooms that I've already dug (or previously marked to dig).

**Comment by hwoarangmy** [comment]
I've already seen that before the FOW PR. In fact, I think I've seen that from the start...

**Comment by hwoarangmy** [comment]
Is this still true ? I've not seen it for a while...

**Comment by akien-mga** [comment]
I don't know, personally I've only seen it once, and it's in the above screenshot. I'd propose to drop the 0.5.0 milestone for now, and if we find a reliable way to reproduce, we can always raise the priority again.

**Comment by akien-mga** [comment]
It's good to keep the issue open anyway until we're confident enough that the issue was fixed, so that players can find this issue and comment on it if they experience the same thing.

**Comment by hwoarangmy** [comment]
ok for me

**Comment by Bertram25** [comment]
Yeah, let's move that to the backlog.

**Comment by hwoarangmy** [comment]
I think I understood what was happening. It is easy to reproduce. Just launch a level, select some tiles, go back to main menu and launch again the level. Try to select the same tiles and they will not be shown. I guess the tile selector is not destroyed between 2 games. Note that the problem is probably with the entity which means that the bug relies on tile coords, no matter the level you launch.

**Comment by Bertram25** [comment]
Cool ":D
