### ISSUE TITLE
Notify the seat when gold can't be added to the treasury

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#435]
Either because the treasury is full, or because it is missing. It seems most of our players have trouble understanding the concept of placing a first free treasury tile before they mine, it's true that it's a bit strange, so this message should help a lot.

cf. http://forum.freegamedev.net/viewtopic.php?f=35&t=6051&p=61979#p61976

For now this should probably be a written message in the chatbox, in the future we might want to have eugeneloza's voice acting for this.

**Comment by Bertram25** [comment]
Yeah, I agree, not easy to get without being explained first.

**Comment by hwoarangmy** [comment]
ok. I will add a message for that.
