### ISSUE TITLE
Someone add the goblin and his bed

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#438]
http://forum.freegamedev.net/viewtopic.php?f=38&t=6102

**Comment by Bertram25** [comment]
k, I'll handle it. :D

**Comment by Bertram25** [comment]
@Danimal696 Btw, any hints about its stats?

**Comment by Danimal696** [comment]
Same as the old goblin, just rescale to 0.15

**Comment by Bertram25** [comment]
k, will do. Thanks.
