### ISSUE TITLE
Improve GameMap::circularRegion()

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#439]
Atm, this function does add tiles from bottom left to top right using a radius and coordinates.

But this makes it unoptimized to compute visible tiles for creatures afterwards.
As noted by @hwoarangmy in #437 

> For example if we fill mTilesWithinSightRadius (sic: the circularRegion result) with nearest tiles at first and we process them in revert order in GameMap::visibleTiles(), it would be more efficient.

**Comment by hwoarangmy** [comment]
I would also add that within the handleIdleAction, reachableTiles are built from mTilesWithinSightRadius and when the creature chooses to wander, it takes a tile randomly in the second half of reachable tiles (because it expects the tiles to be sorted by distance). By doing that, right now, we favorize creatures to wander up from their position instead of in a far away tile.

See:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/entities/Creature.cpp#L1078
and
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/entities/Creature.cpp#L1130
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/entities/Creature.cpp#L1154

**Comment by hwoarangmy** [comment]
For the record, I've achieved pretty good results by computing a list of tiles sorted at GameMap initialisation and using that to compute tiles in sight. I have nearly the same execution time (even a bit better on the tests I've done) than the actual algorithm but now, tiles are ordered from closest to farthest.
I'm currently having a look if we can use this computed list to improve visible tiles. My feeling is that it is possible but I don't know if it will be easy/fast to do that (BTW, when parsing the tiles in sight in reverse order, I get 10% less time with visible tiles computation than when using the actual GameMap::circularRegion list of tiles)

The bad point with my algorithm is that it uses a pre-built list of coordinates to allow to sort tiles in sight. That means that we have to pre-build the list with a given radius.
circularRegion has a const modifier so if I go for changing the pre-built list at execution, I will have to remove it.
I was thinking of checking at GameMap init the creature max sight to compute the pre-built list but if we add a spell later that increases creature sight or if we allow to spawn through AS a creature that is not defined in creature.cfg or in the level file and have greater vision, we might have a problem.
@Bertram25  @oyvindln WDYT ?

**Comment by hwoarangmy** [comment]
I'm almost done with my commit ^^
It was not easy but I could manage to compute at gamemap creation a class that computes how each tile hides other tiles (when full). Then, the computed tiles are applied for creatures to choose which are visible or not. If we see 50% or more of the tile, it is visible. If we see less than 50%, it is hidden.
On the tries I've made, 30000 calls to visibleTiles, with the old algorithm (the one that uses tiles in sight on reverse order - 10% better than the previous), I get 70147 ms. With the new algorithm, I get 14738 which is a little bit less than 5 times better ^^
From the tests I've made ingame, the visible tiles seems more natural (previously, creatures had too much vision sometimes nearly behind full tiles).

The PR is incoming (maybe tonight)

**Comment by Bertram25** [comment]
Cool, I need to try that.

**Comment by Bertram25** [comment]
From what i could see in your latest patch, the max radius will get recomputed on need. So IMHO, the question of adding a new creature or increase the creature sight radius will be problematic only for a fraction of one turn, which is good. :)

I'll do a more thorough review asap.

**Comment by hwoarangmy** [comment]
yep. But to do that, I had to remove the const modifier of the function.

**Comment by Bertram25** [comment]
Arf, there is worse. I wouldn't worry too much. :)

**Comment by hwoarangmy** [comment]
> Arf, there is worse. I wouldn't worry too much. :)

lol. I was more thinking about AS binding (even if I don't really know why it would need that). In any case, I think I should be able to sleep even after that ;-)
