### ISSUE TITLE
Hardware/ Software cursor  switch in game >_> ?

### ISSUE THREAD

**Issue by tomluchowski** [OpenDungeons/OpenDungeons#443]
Where should the swtich between hardware -- software cursor be placed ? 
Should it be only in game ? Problem is in some platforms default of the two variants might not work. How do you imagine clicking and choosing from GUI the proper options when say the cursor is invisible  ?
Would you like me to have that option be set by CMAKE ?

**Comment by hwoarangmy** [comment]
In which case do you think the cursor won't be displayed ?
IMHO, a CMAKE option is not the way to go as most of the players won't compile the game. We need to find a way to display the cursor in every case...

**Comment by Bertram25** [comment]
If I understand well, you're speaking of the cursor management described in #420 , right?

Then, there is no cmake option, as the cursor will be fully hardward, except when using the hand mesh. From the latest decisions, we were planning to make the hand mesh displayed when the cursor is on the 3d game part and use an hardware cursor (a hand image) when hovering the GUI part or on the main menus.

As to grab the input or not, this is described in #415 and we decided to work toward grabbing input when in fullscreen and follow a grab input option in the still in the making options menu when in windowed mode.

Please read carefully the corresponding issues and try to understand well the need described there.
Once it is done, if you have more questions, feel free to tell them in the corresponding one.
