### ISSUE TITLE
Sources do not compile with MinGW

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#444]
Since PR #441, the use of std::to_string, stof/stoi/stod has broken MinGW compilation.
For such functions, we should use the Helper.

**Comment by Bertram25** [comment]
@hwoarangmy I shouldn't have merged so fast. Sorry! :S 
Are you ok taking care of it, though?

**Comment by oyvindln** [comment]
This is apparently a bug in MinGW:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52015

**Comment by Bertram25** [comment]
Unfortunately, not going to be fixed anytime soon. :S

**Comment by oyvindln** [comment]
The quickest way to solve this would be to replace the calls with boost::lexical_cast, as the code relies on exceptions for errors. (While the Helper functions return 0 on invalid values as they use stringstream.)

**Comment by hwoarangmy** [comment]
Yes. I've fixed the compilation issues, that was not a big job. But now, I'm facing something a bit more strange. I cannot launch OD. I get a runtime error.
Fortunately, I have working sources not too old (I think just before @Bertram25 PR about removing replay).
I'm going to try to add things one after the other to find what breaks execution. From what I've seen in @oyvindln there is no new module included (last time I had this kind of error, it was the reason why). But I will check.

**Comment by hwoarangmy** [comment]
I've figured out what is happening. The problem comes from the regex. When I change "const std::regex NO_WHITESPACE("\S*");" to "const std::regex NO_WHITESPACE("");", I get no runtime error. @oyvindln I'm no regex expert. I've looked at the code but some comments let think that it is related to alphanumeric chars but the name being NO_WHITESPACE, I'm not really sure what it means. Could you please tell me what this regex is supposed to do so I can try to replace it ?

BTW, it is probably a MinGW issue...

**Comment by hwoarangmy** [comment]
Well, after looking a bit more, I've seen the regex is only used to test if the commands contain unexpected chars. Why did you make that check ? Do you expect to allow to add command console from an external way (like a text file or something) ?
If not, I would remove the regex as IMHO, we should expect coders to add correct commands in code and to test if it works (and thus, to see if they made a mistake in the command). Moreover, currently, the output is in the console which, IMO, makes this test useless (if we want to keep that kind of test, the outputs should be in the logs so that we can analyse if there is a problem).
@oyvindln WDYT ?

**Comment by oyvindln** [comment]
Nah, you can probably remove it if it causes problems. It's just a safety check.

**Comment by hwoarangmy** [comment]
@oyvindln .ok. Then, I will remove it. For my information, why did you declare the const regex in an empty namespace ? What's the difference with declaring it outside any namespace ?

**Comment by oyvindln** [comment]
It means it can't be used outside the file.

**Comment by hwoarangmy** [comment]
Thanks. But what's the difference with a static variable (I'm talking about C-style static) ?

**Comment by Bertram25** [comment]
> Thanks. But what's the difference with a static variable (I'm talking about C-style static) ?

AFAIK, for instance and in the context of your question, the static could be reused using an 'extern' keyword in another file.

**Comment by hwoarangmy** [comment]
> AFAIK, for instance and in the context of your question, the static could be reused using an 'extern' keyword in another file.

For having used C for a while, i can confirm that in C style, static means visible only in the source file it is declared.
