### ISSUE TITLE
Lighting issues with coloured materials and normal maps

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#446]
We have to sort this somehow, right now the claimed tiles and walls look hideous.

I've tried to look into it, but I can't find a simple way to make it work by adjusting light values and blending without shading the whole tile. The alternative then is to either generate textures on the fly, or use a coloured dummy object or decal attached to the tile. So, my question is then, what would we prefer?

**Comment by Danimal696** [comment]
did you notice that when you set a wall for digging normals start working on the model?

**Comment by oyvindln** [comment]
No, I haven't noticed that.  (Unless you are talking about the dirt walls, it's only an issue on the materials that have team colour stuff on them. Normal maps work fine otherwise, they are just not specified in the material file for most models.)

**Comment by Danimal696** [comment]
could you provide a working sample for a creature model and maybe a built room as well?

**Comment by oyvindln** [comment]
If you what you mean is how to set a normal map:
https://gist.github.com/oyvindln/f79922f0a34f66a7aae3#file-dirt-material

**Comment by Bertram25** [comment]
Almost done with #448

**Comment by Bertram25** [comment]
@oyvindln Isn't this issue fixed, except for #456 ?

**Comment by oyvindln** [comment]
Yep
