### ISSUE TITLE
Goblin is missing bone assignments

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#449]
```
Mesh: Loading Goblin.mesh.
Skeleton: Loading Goblin.skeleton
WARNING: Goblin.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.
Texture: goblin-texture.png: Loading 1 faces(PF_A8R8G8B8,1024x1024x1) with 10 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,1024x1024x1.
Texture: Goblin-Knife-texture.png: Loading 1 faces(PF_A8R8G8B8,1024x1024x1) with 10 hardware generated mipmaps from Image. Internal format is PF_A8R8G8B8,1024x1024x1.
An internal Ogre3D error ocurred: OGRE EXCEPTION(5:ItemIdentityException): Bone named 'Weapon_L' not found. in Skeleton::getBone at /build/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSkeleton.cpp (line 521)
```

**Comment by Danimal696** [comment]
the only error i can get is that you are trying to load a goblin with a weapon equiped, they cant equip anymore, so " Bone named 'Weapon_L' not found" is the result, check the map file and look for any goblin with rusty swords or shields.

**Comment by oyvindln** [comment]
So they are not supposed to be able to equip weapons anymore is what you are saying? They were in some of the maps in the past.

**Comment by Bertram25** [comment]
Hey there,

Without even speaking of how to handle meshes bones yet, could it be possible to turn that exception into a warning when loading creatures definition?

**Comment by Danimal696** [comment]
> So they are not supposed to be able to equip weapons anymore is what you are saying? They were in some of the maps in the past.

Yes, but given they are now just glorified cannonfodder i wanted to let them out of the weapon upgrade system, weapons will go to stronger creatures once implemented

**Comment by Bertram25** [comment]
Then, I'd be to add a warning when visually equipping fails, and remove the weapons from the goblins in old maps once done to close this issue.

If the visual bone binding fails, should we (stats speaking) equip the creature anyway?

**Comment by oyvindln** [comment]
I think we should, having stats depend on what model file is loaded is bound to cause problems, for instance if someone has replaced a model tries to play multiplayer.

**Comment by Bertram25** [comment]
Fair point. Ok, then we'll have to add a check visually "unequipping" (destroying the weapon mesh for another one) to avoid an exception there as well, I guess.

**Comment by hwoarangmy** [comment]
> If the visual bone binding fails, should we (stats speaking) equip the creature anyway?

Failing to equip the weapon because of bone will happen on client side only (and not on server since there is no rendering). Changing stats in this case would not be straightforward. The most easy would be to make sure we properly release what needs to be released (about the concerned weapon) and log the problem (keeping the stats). That should be enough...

**Comment by Danimal696** [comment]
doesnt it rises the problem of someone cheating with a super unit? if they mod the goblin or whatever to be uber, what happens them?

**Comment by hwoarangmy** [comment]
> doesnt it rises the problem of someone cheating with a super unit?

Well, if playing as server, anybody can spawn a super unit by modding a level or the creature.cfg. We need to trust the server. That's why I will never play if you are hosting :p

**Comment by Bertram25** [comment]
> doesnt it rises the problem of someone cheating with a super unit

Well, of course, as @hwoarangmy pointed out, the game is very moddable now. The best would have creatures with both weapons set so that at least, it is a question of config only. Would you mind adding the bones names for such possible cases?

> That's why I will never play if you are hosting :p

Yeah better let me host. :>

**Comment by hwoarangmy** [comment]
> Yeah better let me host. :>

Well, now that you talk about it, I think I would prefer to let @Danimal696... ;-)

**Comment by Danimal696** [comment]
i can put dummy bones on the goblin, most other creatures will have them working thougth. The question, goblin is intended to not upgrade its weapon, will having weapons bones cause him to try and upgrade? if the solution is worse than the problem i could try and find a few knifes and ugly shields to include him into the upgrade system...

**Comment by akien-mga** [comment]
> The question, goblin is intended to not upgrade its weapon, will having weapons bones cause him to try and upgrade?

I don't think so, the weapon upgrade system will probably rely on configuration tokens in the creature definition sheet, for example a lot of weapon IDs that the creature would be looking for. IMO it would be difficult (and error-prone) to base the upgrade behaviour on the meshes.

**Comment by hwoarangmy** [comment]
> will having weapons bones cause him to try and upgrade?

Definitely not. As pointed by @akien-mga and myself, the meshes will never be used to take such decisions. First of all because the decisions are taken on the server side gamemap (that do not uses the render manager - have no information about meshes).
We will have to find some way in the configuration files to say if weapon evolution is allowed and how (when the time comes)

**Comment by Bertram25** [comment]
In any case, please put dummy bones on creatures, so we can get rid of potential useless warnings. Thanks a lot. :)

**Comment by Danimal696** [comment]
sure

**Comment by Danimal696** [comment]
since the old maps are not working anymore and they were the ones with armed goblins, is it still needed him having the dummy bones?

**Comment by Bertram25** [comment]
> since the old maps are not working anymore and they were the ones with armed goblins, is it still needed him having the dummy bones?

There is no urgency at all, but I think that yes, for several reasons:
The first and the less important one being that the game is moddable and that it would prevent an useless warning.
The second one is that you'll have to re-export the model anyway (with normal support).
The third one is because you love us. Wait, no that's not a valid point in fact. ;)
