### ISSUE TITLE
Tile::getPosition() vs Tile::getX() & Tile::getY()

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#452]
I fixed mPosition to be updated by mX and mY in one of my latest patch so at least both can be used.

The actual question is: Shouldn't we keep only one of the two?

**Comment by hwoarangmy** [comment]
Many times, we need the position as a int. Removing mX and mY would mean much more casts. I don't know how expensive a cast is. That being said, if we can avoid dupplicated variables, it is better.

**Comment by oyvindln** [comment]
I though mX and mY was the position in the tile array, while getPosition returned the position in the world geometry, so I don't think they should be merged.

**Comment by hwoarangmy** [comment]
Well, in reality, the tile position in the array and in the world geometry is the same. I would agree if it was to be changed but in reality, I think it cannot be changed as it is tied everywhere in the code (the most important being getPositionTile):
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/entities/GameEntity.cpp#L76

**Comment by Bertram25** [comment]
> I though mX and mY was the position in the tile array, while getPosition returned the position in the world geometry, so I don't think they should be merged.
> 
> in reality, the tile position in the array and in the world geometry is the same. I would agree if it was to be changed but in reality, I think it cannot be changed as it is tied everywhere in the code (the most important being getPositionTile):

Ok, I get the point better now. As I said above, in one of my latest patch I made the tile class sync its mPosition vector when mX and mY, so this is working fine at least for now, even if not perfect.

As every tile position is linked to the world geometry and as I don't think we'll change that one day, I think we can remove the mX, mY members if the casts made aren't too heavy.
If they are, then the current behaviour (with my patch) is the most ideal state and we should call it a day.

I'll have a look at how heavy is a float/double to int cast.

**Comment by Bertram25** [comment]
As there are 196*2 calls to getX() / getY(), IMHO the current behaviour is fine.
Btw, getX() or static_cast<int>(getPosition().getX()) does give the same result now.
