### ISSUE TITLE
Choosing the best SceneManager once we have normals support.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#453]
Linked to #446 and once #448 is merged, we'll have normals support.
But we'll also have heavier frame update calls and some drop on the FPS when using a higher view.
(Which shows that the Ogre culling manager is working since closer views are quicker, btw.)

To try and improve this, and as a first simple step, what do you think about testing the different SceneManagers Ogre is offering?
http://www.ogre3d.org/tikiwiki/SceneManagersFAQ

If my request seems sound to you all, I'd say we should try to change the scenemanager type used and have a look at how the FPS are doing.
Then, based on the results, we'll be able to choose the best one.

You can change the scene manager plugin used here:
https://github.com/OpenDungeons/OpenDungeons/blob/development/cmake/config/plugins.cfg.in#L15

**Comment by oyvindln** [comment]
I don't think the choice of sceneManager will make much difference, as we are not currently using any static geometry, which is the main purpose of the sceneManagers. I don't think there is much that could be made static either, except maybe rock tiles. 
Ogre 2.0 seems to have functionality that helps here us though: http://www.yosoygames.com.ar/wp/2013/08/hw-instancing-static-mode-benchmark-on-2-0/

**Comment by Bertram25** [comment]
@oyvindln Once again, I can't wait to see what Ogre 2.0 can offer, really. :)

In the meanwhile, the Octree plugin seemed to make me earn a few FPS (when tested against the others but without normals), that's why I switched to it at the time. But I sincerely don't know the reason why it was better.

Once we have normals on walls and ground, I can make a quick test myself and see whether empirically something is changing.
If not, I'll close the issue.

**Comment by oyvindln** [comment]
Yeah, we should be using the octree one, I don't know why it has been switched to something else.

**Comment by Bertram25** [comment]
Tested. So far, it doesn't make any differences. The current settings are fine, then.
