### ISSUE TITLE
In the editor, Traps are not displayed

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#455]
Seems like the trap hiding system is too strong ^^

**Comment by hwoarangmy** [comment]
That will wait for #436 for the gamemap function to know if we are in editor mode.

**Comment by Bertram25** [comment]
Arg, you are putting pressure on me :P

**Comment by hwoarangmy** [comment]
> Arg, you are putting pressure on me :P

Work you coding monkey !!!

**Comment by Bertram25** [comment]
> Work you coding monkey !!!

![images](https://cloud.githubusercontent.com/assets/765917/5923037/a5c31f0e-a650-11e4-90af-3e2f56009ff7.jpg)

**Comment by hwoarangmy** [comment]
I like your glasses. It suits you well ^^

**Comment by Bertram25** [comment]
> I like your glasses. It suits you well ^^

Eh eh.
