### ISSUE TITLE
Claimed walls top side not coloured when marked

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#456]
Since #448 

![odscreenshot_2015-01-25_090110_0](https://cloud.githubusercontent.com/assets/7493706/5890840/bdf9efe4-a470-11e4-9201-4fdc9980cc71.png)

**Comment by hwoarangmy** [comment]
I've just noticed that some dirt have the same bug (it is not obvious but the dirt tiles in the center are marked):
![odscreenshot_2015-01-28_000025_0](https://cloud.githubusercontent.com/assets/7493706/5929120/24ed5ab2-a681-11e4-8502-41eb3ccfc745.png)

**Comment by oyvindln** [comment]
It looks like the normal map isn't working on the tiles where this is happening, and the lighting is acting weird, so there is still some issue with it not being applied all the time. I've had similar things happen, but I haven't managed to make it happen consistently, so I'm not sure what's causing it.

**Comment by Bertram25** [comment]
Just out of intuition, do you think things like vertices with inverted coordinates and the like might give problems with normals and colors with certain drivers?
@Danimal696 Could check whether claim walls have something different from the dirt tile in term of topology, coords used, ...?

**Comment by oyvindln** [comment]
That is a possibility yes.

**Comment by hwoarangmy** [comment]
@oyvindln FYI, I've tried on another computer (windows 7 / Intel GC). I've activated glsl150 and I've exactly the same behaviour as with the other computer (windows 7 / nvidia GC): with OpenGL renderer, normals don't work and I have graphical glitches and with GL3+ renderer, black screen.
Note that I compile and use debug versions (of OD and the renderers)
The GL3+ renderer might be broken (it is marked as experimental)

**Comment by Bertram25** [comment]
@hwoarangmy On the other computer, do you still have normals problems?

**Comment by hwoarangmy** [comment]
> On the other computer, do you still have normals problems?

I have exactly the same behaviour: with latest @oyvindln patch, normals work but marked top claimed wall/some dirt tiles don't.
And with glsl150/GL3+ renderer, same as what I posted on @oyvindln PR.

**Comment by Bertram25** [comment]
k, thanks for all the tests. I bet you'll be our eyes on this one. (While I'll also test on windows asap. Hopefully, I'll have the issue.)
Still, I do think the models themselves might have their part of responsability, and I wish I knew how to make sure of it. Maybe it's time to restart blender for me. ;)

**Comment by Danimal696** [comment]
that piece seems to be Dirt_10001000b, its exactly the same as all the others material,texture, normal wise. Could you try a dirty trick? erase that piece .mesh and replace/rename with Dirt_10001000a or any other mesh that works. If its a problem of only that piece ill try redoing/re-exporting or whatever is needed.

**Comment by Danimal696** [comment]
Also,sorry for low activity but my college exams are taking all my time.

**Comment by Bertram25** [comment]
> Could you try a dirty trick? erase that piece .mesh and replace/rename with Dirt_10001000a or any other mesh that works.

The mesh replacement is here: https://github.com/OpenDungeons/OpenDungeons-media-source/blob/master/Models/OD_Tilesets/OD_Tilesets_export/Tilesets_binary/Dirt_10001000a.mesh

> Also,sorry for low activity but my college exams are taking all my time.

Np at all for me. Exams first. It's cool to know you're around from time to time, though. :)
Break a leg.

**Comment by hwoarangmy** [comment]
> Maybe it's time to restart blender for me

FYI, I've already had a look (I've already had occasions to test blender) and I've seen nothing special about normals (direction is ok on all the models I've seen). It may be an export problem, though, since all the tileset is in one blend file.

**Comment by Bertram25** [comment]
Ok, then it might be time to try new exports, indeed. :)

**Comment by hwoarangmy** [comment]
> Could you try a dirty trick?

Seems like a good idea to figureout if the problem comes from the mesh or from the materials/code. I will make some tests tonight.

**Comment by hwoarangmy** [comment]
I've stubbed the mesh creation to use Dirt_10001111.mesh (mesh that works) for every refreshed tile. With this tile, it woks. Then, I've done the same with Dirt_00000010.mesh and I see the problem with every tile. I've also tried to change the rotation (to see if something was done in code) and I always have the problem with Dirt_00000010.mesh.
So, that seems to be a mesh problem...

**Comment by Danimal696** [comment]
then, its the mesh problem, i kindly request a new release to mess with :)

**Comment by Bertram25** [comment]
Yep, I'll be on it asap. :)

**Comment by hwoarangmy** [comment]
I've noticed something I'm sure @oyvindln will love. When I launch skirmish big test map, the dirt tiles are normal (normals are correct). But when I launch skirmish 2v2 small test map, the tiles are like in my previous screenshot (even if I launch the second map after loading the first one without quitting OD).
I don't know if it can help but it means that the bug is probably not in the models after all...
BTW, in both maps, claimed wall tiles are not coloured on top.

**Comment by hwoarangmy** [comment]
I've made some tries to see why dirt tiles do not behave the same in the small test map or in the big test map and I've seen that when I add rock tiles in the skirmish small test map, the corresponding dirt tiles are well displayed (if I place a single rock tiles, the single dirt tiles will be well displayed while the others dirt tiles will be displayed like in the screenshot). I've tried to add the rock tiles at the beginning of the map ( coords 0,0) or the end and it is the same. It seems it is not a matter of loading order.
@oyvindln  @Bertram25 Any clue of what can do that ?

**Comment by Bertram25** [comment]
As the rock is the same mesh with an override on the texture, I wonder whether there could something interesting behind that. Nice clue, thanks for sharing it. I'll have a look in the ogre forums and in their code during the week. :)

**Comment by Bertram25** [comment]
This was a problem of the passes order in fact.

**Comment by hwoarangmy** [comment]
Cool ^^
