### ISSUE TITLE
Readd models with normal support.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#458]
Now that @oyvindln took care of the normal support main effort, we can now benefit from it. :)

I'd propose this issue about tracking which model is being done, and waiting upgrade.

Part of this issue is also about adding the necessary wiki doc about one makes a models with normal support.

**Comment by Bertram25** [comment]
@Danimal696 Do you mind taking up this one?

**Comment by Danimal696** [comment]
ok, but this need some on-site testing to see if the results are good or not, ill start when you do a new release, for now all rooms and new creatures models would need it.

**Comment by Bertram25** [comment]
Note to self: Time for a new windows release. ;)

**Comment by Bertram25** [comment]
@Danimal696 Speaking of normals, how do you see the status of this task? What's left in your opinion?

**Comment by Danimal696** [comment]
statues from cript and traps, but traps normal and transpaarencies dont mix well

**Comment by Bertram25** [comment]
I think we should forget normals on models needing transparency for now...

**Comment by hwoarangmy** [comment]
> I think we should forget normals on models needing transparency for now...

Yep, I agree

**Comment by Bertram25** [comment]
@Danimal696 Basically, what do you see left for this issue to be considered done in your opinion?
I admit the issue description is a bit vague and it's my fault, sorry. ;)

Ah, and btw, the issue is also speaking about adding the normal how-to in the wiki. An example of how to create a model with transparency would be cool, too.

**Comment by Bertram25** [comment]
Same here, moving to Later as it is non-blocking.

**Comment by Bertram25** [comment]
> Ah, and btw, the issue is also speaking about adding the normal how-to in the wiki. An example of how to create a model with transparency would be cool, too.

@Danimal696
Now the wiki has been updated and that we stated we won't mix transparency and normals for now. What is left about this issue in your opinion?

**Comment by Danimal696** [comment]
Only statues from cript, the rest is all done

**Comment by akien-mga** [comment]
> Only statues from cript, the rest is all done

Which is #566, so I'll close this issue as fixed (in 0.5.0 to be precise).
