### ISSUE TITLE
Turn the forge into the workshop

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#459]
The current forge should be turned into the workshop.

The workshop will still be used to craft traps, but its models have to be changed as the forge models will be reused to create the new forge, where creature equipment will be forged.

Also the workshop logic will have to be upgraded so that traps are crafted only when needed and not at random. More info at: http://forum.freegamedev.net/viewtopic.php?p=61975#p61975 (and on)

**Comment by Bertram25** [comment]
The current need are the models. ;)

**Comment by Danimal696** [comment]
will have to wait until i finish my exams next week

**Comment by Bertram25** [comment]
Np at all. :)

**Comment by Bertram25** [comment]
@hwoarangmy @Danimal696 @akien-mga @oyvindln the Workshop icon:
![workshop](https://cloud.githubusercontent.com/assets/765917/6664021/2a41354a-cbcc-11e4-9288-3a8cc1bf35a6.png)

**Comment by akien-mga** [comment]
Nice! :)

**Comment by hwoarangmy** [comment]
Nice icon ^^

**Comment by Bertram25** [comment]
If nobody else does it, I'll add it to the icons resource tonight.

**Comment by hwoarangmy** [comment]
Now that @Danimal696 is done with the forge, its @Bertram25 turn ^^

**Comment by Bertram25** [comment]
The icon is there. :)

**Comment by Bertram25** [comment]
Want me to deal with the models change as well?

**Comment by hwoarangmy** [comment]
If, you can, yes. I'm pretty busy ATM with saving traps and rooms.

**Comment by Bertram25** [comment]
> If, you can, yes. I'm pretty busy ATM with saving traps and rooms.

Np. I'll make the change tonight. :)
