### ISSUE TITLE
CMake: OD_OGRE_PLUGIN_DIR_REL is not properly assessed on Ubuntu 14.10

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#461]
Follow-up of this PlayDeb bug report: https://bugs.launchpad.net/getdeb.net/+bug/1415604

The OD_OGRE_PLUGIN_DIR_REL variable ends up as an empty string on Ubuntu 14.10 (using the ogre-1.9-dev package from the Ubuntu Universe repository I suppose), therefore the PluginPath is empty in plugins.cfg: https://github.com/OpenDungeons/OpenDungeons/blob/development/cmake/config/plugins.cfg.in#L4

The variable is defined in this chunk: https://github.com/OpenDungeons/OpenDungeons/blob/development/CMakeLists.txt#L529-L555

**Comment by oyvindln** [comment]
Hm, I'm using Ubuntu 14.10, and using pkg-config to find the plugin directory has worked fine here. It looks like it may have something to do with the lookup when packaging, as from the log it's looking in the deb build directory. (/build/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreDynLib)

**Comment by akien-mga** [comment]
Maybe pkg-config is missing during the packaging? It's not listed explicitly as a build-depends, but I don't know if it would be part of a minimal buildsystem by default: https://github.com/ckorn/PlayDeb/blob/utopic/opendungeons/control

**Comment by akien-mga** [comment]
Side note: we should probably display a BIG warning when OD_OGRE_PLUGIN_DIR_REL can't be defined properly, something that would catch the eyes of packagers and other users (even if it should not prevent the CMake step to succeed IMO).

**Comment by oyvindln** [comment]
That could be the issue yes. And yeah, there is currently no output if pkg-config is missing, we should add a big warning. Another question is why the OGRE find script isn't finding it in the first place.

**Comment by oyvindln** [comment]
There seems to be a bug in FindOGRE.cmake, it's not taking into account the version suffix for the ogre plugin folder. It seems to be fixed upstream, so updating the ogre cmake files (FindOGRE.cmake, not sure if the other files need updating.) should solve it. I can fix that in this branch in my next PR. Though, should we also update it in the stable branch, or should we simply ask the getDeb people to update for the deb source package?

**Comment by Bertram25** [comment]
If it can be useful for you guys, I can cherry-pick a commit back to stable, if you give me enough pointers.

**Comment by oyvindln** [comment]
Updating FindOGRE.cmake to [this](https://bitbucket.org/sinbad/ogre/src/5ee010d450fd064007b61442124222bfb3d57a58/CMake/Packages/FindOGRE.cmake?at=default) should be enough.

**Comment by Bertram25** [comment]
> Updating FindOGRE.cmake to this should be enough.

Didn't check yet but i suppose this is what you've done, right?
If yes, I'll create a PR for stable asap (since it will need testing).

**Comment by oyvindln** [comment]
Well I updated some more files, and removed the part of the script that used pgk-config to look for the file if the find script wasn't finding it, though that shouldn't be needed if you want to keep the change small, see https://github.com/oyvindln/OpenDungeons/commit/641e426df0ae70dc4e7b498a61c2193d2604bcd0

**Comment by akien-mga** [comment]
This should have been fixed by 641e426.
