### ISSUE TITLE
GUI: drop down-menus show a caret (text cursor) on hover

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#462]
When you hover over a drop down menu (e.g. in a skirmish level configuration screen), there comes a caret (aka text cursor) under the mouse pointer, so you end up with two pointers: the system one + the caret.

This does not make much sense since no text can be typed in the drop down menus, so it would be nice to get rid of it.

**Comment by akien-mga** [comment]
I don't see a method to hide the caret in the CEGUI::Combobox class reference: http://static.cegui.org.uk/docs/0.8/classCEGUI_1_1Combobox.html

**Comment by Bertram25** [comment]
Basically, the "bug" comes from the use of the following mouse image parameter:
https://github.com/OpenDungeons/OpenDungeons/blob/development/gui/OpenDungeons.looknfeel#L2198

Though, this parameter shouldn't be used when in read only mode, or more precisely, a mouse cursor parameter should be specified for both read-only and not read-only combo-boxes.
I'll open a topic on the CEGUI forums but it might not be fixed asap and may not be backward compatible if fixed.

In the meanwhile, I do think we should simply change that parameter to the invisible default mouse cursor.

WDYT?

**Comment by akien-mga** [comment]
That sounds good, especially the part about you providing feedback upstream to get it sorted out. The proposed workaround would do in the meantime :)

**Comment by Bertram25** [comment]
For the record: http://cegui.org.uk/forum/viewtopic.php?f=10&t=6980

**Comment by Bertram25** [comment]
It's almost official, this is a now recognized CEGUI bug I may be able to fix for the version 1.0 (or even 0.8.5) thanks to Ident.
We'll have to use the workaround in any case in the meanwhile.

**Comment by hwoarangmy** [comment]
Well, if the workaround implies changing CEGUI sources, I would be for living with this bug. I agree it's not the expected behaviour but I don't think it's worth having to patch cegui. IMHO, we can wait for the official version including this patch.

**Comment by Bertram25** [comment]
> Well, if the workaround implies changing CEGUI sources

Nope, in fact the work around is about simply using the default mouse cursor, even for editable edit boxes. There is nothing better for now, I'm afraid.

> I agree it's not the expected behaviour but I don't think it's worth having to patch cegui. IMHO, we can wait for the official version including this patch.

To be perfectly clear, when I was saying I'd patch Cegui, I meant creating a PR for upstream. ;)
I agree we shouldn't at all import the cegui sources, don't worry.

And btw, good news, I had words with the cegui maintainer on Debian, and he's going to upgrade Cegui packages after Jessie is out. :)
I'll then work with him to get the python bindings and CEED packaged for Debian. :D

**Comment by hwoarangmy** [comment]
ok. cool ^^

**Comment by akien-mga** [comment]
> And btw, good news, I had words with the cegui maintainer on Debian, and he's going to upgrade Cegui packages after Jessie is out. :)
> I'll then work with him to get the python bindings and CEED packaged for Debian. :D 

And OD :-D

**Comment by Bertram25** [comment]
Btw, I've added a fix to the next 0.9/1.0 cegui version here:
https://bitbucket.org/cegui/cegui/pull-request/155/added-support-for-a-read-only-mouse-cursor/diff

According to Ident, the fix is good and will be reviewed in the next few days. :)

**Comment by Bertram25** [comment]
The fix has been accepted and merged. :)
We'll now have support for readonly cursor image on editboxes. :)
