### ISSUE TITLE
Create a portable binary release of OD 0.4.9

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#463]
As the title says :-)

I've done some work on this, building OD and its dependencies in a chroot for a relatively old release (to prevent building against a too recent glibc that won't be backward compatible). I chose Mageia 3 for the matter, it's not the oldest one out there (was out mid-2013), but it was supported until recently so I don't have to fear too much about bundling security flaws.

Then the process implies building the executable with a RPATH to $ORIGIN/lib, and bundling all needed libs in this ./lib directory (apart from X11, GL, glibc libs).

I have a WIP 32bit tarball, hopefully this issue will soon be closed ;-)

**Comment by akien-mga** [comment]
Here's a portable binary release for 32bit linux, if one of you has such a distro or VM, I'd be glad to have some tests: http://dl.free.fr/uxCTKwrhA

_Edit:_ I also uploaded the file on my FTP, since dl.free.fr is not that friendly to non-French speaking users :)
_Edit2:_ With the link, it's better: http://remi.verschelde.fr/files/opendungeons/opendungeons-0.4.9-linux-i586.tar.xz

I build it in a Mageia 3 chroot, and then tested the beast on Mageia 4 in a minimal VM, it worked fine.

**Comment by akien-mga** [comment]
I'm now preparing a 64bit Mageia 3 chroot to create 64bit portable binaries.

**Comment by akien-mga** [comment]
64bit portable binary release: http://remi.verschelde.fr/files/opendungeons/opendungeons-0.4.9-linux-x86_64.tar.xz

I tested this one on Mageia 5 (it was also built in a Mageia 3 chroot), it works fine. I'd be glad to have some tests on Debian (@Bertram25), Ubuntu (@oyvindln) or openSUSE (@tomluchowski).

**Comment by Bertram25** [comment]
@akien-mga ack. I'll test on Debian. :)

**Comment by akien-mga** [comment]
I just got a confirmation that it works on Fedora 64bit.

Note that since I built the binaries on Mageia 3, they most likely require glibc > 2.17 to work, i.e. it should work on distros like Ubuntu 13.04 and RHEL 7, but it probably won't work on Debian 7 stable (wheezy). But IIRC you are on Testing?

On the other hand, I think we'll provide such binaries more for the sake of convenience, and as long as the game is in alpha or beta, we probably don't have to worry too much about our binaries not being super portable. We are using relatively cutting edge dependencies, and I guess it wouldn't be that easy to build OGRE 1.9.0 and CEGUI 0.8.4 on a Debian stable, especially against old gcc/cmake/boost/etc.

If 90% of players can run the binaries, that's already great :-)

**Comment by Bertram25** [comment]
> But IIRC you are on Testing?

Worse. ;) A continously improving mix of SId/Experimental. I mean more and more Sid, less and less Exp as the time flies.

Are those static builds, I suppose, btw? Such builds are cool and aren't very common. I hope this will help people play OD with more ease. :) Thanks for the effort.

**Comment by akien-mga** [comment]
I did not make static builds but I bundled the shared libraries using a RPATH, following this nice guide: http://freegamedev.net/wiki/Portable_binaries
So you'll find (hopefully) all relevant shared libraries in ./lib, and the binary will still expect to find some system-wide libraries for glibc, OpenGL, etc.

**Comment by Bertram25** [comment]
Ah, even better. :)

**Comment by akien-mga** [comment]
I've already had a couple reports that the binaries worked fine on Fedora and Calculate Linux, so I'll upload them to SourceForge. If you notice something wrong with the binaries though, I'll gladly try to fix them.

Instructions to build the binaries incoming in #464 :-)

**Comment by akien-mga** [comment]
The binaries are now online: https://sourceforge.net/projects/opendungeons/files/

**Comment by oyvindln** [comment]
> 64bit portable binary release: http://remi.verschelde.fr/files/opendungeons/opendungeons-0.4.9-linux-x86_64.tar.xz

When testing this file I get (Xubuntu 14.10):
`./opendungeons.x86_64: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory`

**Comment by akien-mga** [comment]
Reopening then, it seems I need to bundle pcre too. Can you check with ldd if other libs might be missing?

Basically `ldd ./opendungeons.x86_64 | grep "not found"` should tell you the missing libs.

**Comment by Bertram25** [comment]
Just tested x64, same error than @oyvindln .

ldd interesting output:

```
/libfreetype.so.6 (0x00007f6e491ab000)
        libpcre.so.1 => not found
```

no other libs seems missing for me.

**Comment by akien-mga** [comment]
Thanks, I'm now uploading binaries with bundled pcre.

**Comment by akien-mga** [comment]
I updated the files on SourceForge, they should be available in ~30 min.

**Comment by Bertram25** [comment]
Cool, I'll retest by then. :)

**Comment by Bertram25** [comment]
I've tested the x64 build. It's running fine! :)

**Comment by oyvindln** [comment]
works fine here.
