### ISSUE TITLE
Disable angelscript untill we actually use it again

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#465]
Since we aren't using angelscript for anything at the moment, I propose we disable or remove it, as it's only causing longer compile time and unneeded complexity.

**Comment by hwoarangmy** [comment]
I completely agree.

**Comment by Bertram25** [comment]
Assigning @oyvindln since he's done it in #466

**Comment by oyvindln** [comment]
I haven't completely disabled it yet. It's still compiled and linked despite not being used. (Should I remove that too?)

**Comment by Bertram25** [comment]
> I haven't completely disabled it yet. It's still compiled and linked despite not being used. (Should I remove that too?)

I guess you're speaking about the libangelscript.a part? IMHO, yes, you can if you have the time to add a fix for that.

**Comment by oyvindln** [comment]
Fixed in 68ad24c4d08418c8005bbc5dbf010ba84e72bfa4
