### ISSUE TITLE
OpenAL segfaults on exit

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#468]
This happens to me occasionally. The segfault is happening in OpenAL somewhere, and not in the main thread, so I can't get a sensible bactrace to easily find where it is.

**Comment by hwoarangmy** [comment]
I confirm it has already happened to me and I also had no interesting backtrace for the same reason

**Comment by Bertram25** [comment]
It's more a SFML problem IMHO. I'll have a look at their bug database.

**Comment by oyvindln** [comment]
I think it could easily be a problem in our code.

**Comment by hwoarangmy** [comment]
Yes, I would also guess at a wrong use of SFML (calling functions in a way we shouldn't). Since it happens when exiting the game, we might call some close function when SFML is in a state it cannot be closed. Or we can also imagine that we don't call a close function before exiting so it is not properly closed.

**Comment by Bertram25** [comment]
Or that yes. What's bothering me is that it is random. In any case, I'm surely guilty here, eh.

**Comment by oyvindln** [comment]
I've had a look at this, and it seems that SFML creates a static AudioDevice object whenever the first sound or music object is created, which sets up an OpenAL context on creation, and destroys it when it is destroyed. (https://github.com/LaurentGomila/SFML/blob/2.1/src/SFML/Audio/AudioDevice.cpp#L58) Since the crash happens after everything that happens in main (which I tested), I suspect this is where the crash happens. I found that if the first sound object is created AFTER the Ogre::Root object is created, the game will crash on exit. (For me it happens every time on exit, but not if I run the program from gdb...). If I add a dummy music object before Ogre::Root is initialised, the crash doesn't happen. I have no idea why this would happen, it's not like OGRE touches OpenAL, but this works as a workaround for now at least. (We currently load the music after ogre is initialised, as we are using the ogre resource manager for finding audio files.)

**Comment by Bertram25** [comment]
Wow, nice find.
I wonder if they somehow are stored contiguously in memory or something similar, explaining the crash if for instance, when deleting Ogre::root, the deletion doesn't actually respect the object length.
I've seen that once or twice. For instance it happened once in Flare, btw.

It's a wild guess, but could it be also that the resource path given by Ogre is linked in a weird way by SFML or something?

In any case, I think it may be a good idea to make this workaround as nice as possible and add it for now.

**Comment by oyvindln** [comment]
This was worked around in 68ad24c4d08418c8005bbc5dbf010ba84e72bfa4
