### ISSUE TITLE
Hero faction AI do not build rooms

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#470]
To dig tiles, the code searches for the first available kobold (in the GameMap class - hardcoded). Since the PR about changing the worker per faction, the hero faction do not have kobolds anymore and, thus, cannot dig.

**Comment by Bertram25** [comment]
Oops, my fault. I'll fix it if you want.

**Comment by hwoarangmy** [comment]
> Oops, my fault. I'll fix it if you want.

No problem, it happens ^^
I've not done anything about this one so feel free to take it

**Comment by Bertram25** [comment]
k, on it. :)
