### ISSUE TITLE
Remove the non-ascii character from materials/textures/Env-blaugrünF.png

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#476]
I'm preparing an OD installer for Lutris: https://lutris.net
and I'm faced with this error when Lutris tries to extract the archive:

> UnicodeDecodeError('ascii', '/opendungeons-0.4.9-linux-x86_64/materials/textures/Env-blaugr\xc3\xbcnF.png', 62, 63, 'ordinal not in range(128)')

This is a Python issue that I'll report to the Lutris devs, but at any rate I think we should try to refrain from using non-ascii characters in file names, it can only bring trouble in a cross-platform game such as ours.

**Comment by akien-mga** [comment]
No idea where this texture file is used though, @Danimal696 ?

**Comment by Danimal696** [comment]
its a shader, i thought was used on the dungeon temple material file, but its not. I have no idea who it belongs to, i erased it and everything looked fine, maybe the old gobling used it? it belonged to something green, but neither the new goblin or tentacles use it.

**Comment by oyvindln** [comment]
It's not present in any of the material files, so I assume it's not in use.

**Comment by Danimal696** [comment]
just rename it, if later is still unused we can just erase it
