### ISSUE TITLE
Workers don't go to the nearest treasury tile anymore.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#480]
As described here:
http://forum.freegamedev.net/viewtopic.php?p=62341#p62341

They now fill the treasury in the tile creation order, or so it seems.

**Comment by hwoarangmy** [comment]
Yes. That's true for all carryable entities (gold, corpses, traps, ...)
I've been thinking about an algorithm to avoid to compute all the paths to possible rooms (as path computing is probably one of the most cpu consuming action we can do) where a carryable entity can be carried. It's all about magic numbers but I have an idea that may work ^^
