### ISSUE TITLE
Creatures should only train on central active spots in Training hall. Wall active spots giving only a bonus

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#485]

**Comment by Danimal696** [comment]
why? you should have already seen you are always short on training spots, theres no point in limiting them anymore, and the bonus would be too poor to justify building a square/walled room

**Comment by hwoarangmy** [comment]
Well, I can see several reasons:
- ATM, TrainingHall is the only room where wall active spots can be used by creatures. IMHO, it would be easier to understand if we had the same behaviour for all rooms.
- When nearby active spots from a training hall are used at the same time, there are too many creatures one over each other and its pretty messy
- When creatures use wall active spots, there are too many. On a 5x5 room, we have 14 active spots. The maximum number of creatures being 15, 1 5x5 room is enough for a game. IMHO, that's too much. I think that if a player wants to go for improving creatures, he should need to build at least 2 training halls.

@Bertram25 @akien-mga @oyvindln @eugeneloza WDYT ?

**Comment by eugeneloza** [comment]
Hmm... I can't say I understand the mechanics, but I think it's a good idea to require the player/ai to build larger bases. At least for visual effect. However, usually dungeons are meant to be 'narrow' and 'overcrowded', rather than having a huge training hall.

**Comment by Danimal696** [comment]
ok, remember me to create a couple more of wall objects

**Comment by hwoarangmy** [comment]
> ok, remember me to create a couple more of wall objects

ok for using only central active spots ?
Concerning wal objects, you can do as many as you want ^^
Especially for workshop or new rooms

**Comment by Danimal696** [comment]
> ok for using only central active spots ?

Yeah, im fine; training room could use at least another wall object

**Comment by Bertram25** [comment]
> ok for using only central active spots ?

Fine as well, it's simply easier to get for the player. :)
