### ISSUE TITLE
Editor: Workers and spell tabs improvements.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#487]
- [x] ~~The Spell tab shouldn't appear in the editor.~~ Yes, it should, to be able to add spells in game as gift boxes.
- [x] The worker button should create the default seat worker and not forcefully a kobold.

**Comment by hwoarangmy** [comment]
I agree with the second point but the first one was added on purpose. IIRC, we said that spells would have to be carried to the dungeon temple like crafted traps. The spell tab was added to allow adding those in the editor.

**Comment by Bertram25** [comment]
Ah ok, then. Nevermind. I don't recall the discussion but the point is valid nevertheless.

**Comment by hwoarangmy** [comment]
> I don't recall the discussion

It's in #411 
BTW, nothing is decided for now. In the issue, it was just an idea, we can change whatever we want if someone has something better in mind ^^

**Comment by Bertram25** [comment]
Sure, but here I think you're definitely right, as for me.
