### ISSUE TITLE
To know which trap a forge should craft, we should craft seats instead of checking on forge rooms

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#489]
As discussed in #411 
The idea is to set the seat when the trap is crafted. Then, when it is carried, the worker changes the seat to his one. However, any worker can carry a crafted trap owned by someone else.

Do we also allow to carry crafted traps from an ally ? I can see pros and cons. but as it is an evil game, my vote will be for yes ^^

**Comment by Bertram25** [comment]
+1
