### ISSUE TITLE
Certain textures are unused.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#492]
We should list them, and then move them into the media repository.
- [x] materials/textures/Env-blaugruenF.png

**Comment by Bertram25** [comment]
@Danimal696 While you're dealing with textures and materials, could you have a look at which are unused? I know I may be demanding but you'll have an opportunity to avenge on our next lan. ;)

**Comment by Danimal696** [comment]
ok, ill have a look

**Comment by akien-mga** [comment]
I'd like to give a hand on this one, since I know @Danimal696 is busy and we have more interesting tasks for him :-D

But I need to understand better how the textures are linked to our meshes, etc. Do we strictly rely on the text materials files, or are some textures hard-linked into binary meshes? Said differently, can I find out which textures are used and which aren't just by searching for their filename in text files, or do I also need to use blender? :)

**Comment by Bertram25** [comment]
@akien-mga I'd say, watch the material files, move the textures not listed elsewhere and have an advanced play with both factions. Then, if the logs don't complain about something missing, you are good to go. :)

Then, you can list them here and we can let @Danimal696 decide for each of them whether he wants to keep it (and then we move it to the media repo) or not.

Then, the job is easy (Watch for the CREDITS file update. ;])

**Comment by Danimal696** [comment]
by chance i discovered its used by the hand, now it depends if @hwoarangmy exported the hand using it or not to remove from texture files. All the the other textures seem to be ok and used.

**Comment by hwoarangmy** [comment]
I just used blender to ogre feature. I didn't change anything about textures.

**Comment by Danimal696** [comment]
then please look at the hand material, if its not in there it can be erased (you have a newer version than i do)

**Comment by Bertram25** [comment]
@Danimal696 Sorry, I'm not getting what you both talked about here:
- Is the Env-blaugruenF.png file used by the hand mesh? Or is it another texture?
- Are the other textures all used for something?

**Comment by Danimal696** [comment]
> Is the Env-blaugruenF.png file used by the hand mesh? Or is it another texture?

Yes, by the hand only

> Are the other textures all used for something?

at least for the ones into the texture folder, i did a clean up some time ago, the rest are clean

**Comment by Bertram25** [comment]
Ok, bonus questions: ;)
- Is this material used by the hand? (easily testable but I can't atm)
  https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/scripts/Keeperhand.material

More general question while I think about it (or note to self):
- Is the general.material content still used?

**Comment by Bertram25** [comment]
> Yes, by the hand only

Btw, since the texture was renamed to remove the umlaut, was the hand mesh updated afterward?

If yes, I think we can close this issue. :) (I'll check the general.material use)

**Comment by Bertram25** [comment]
I'm closing this issue based on @Danimal696 's input. The general.material has been removed and every textures are used.

**Comment by akien-mga** [comment]
> > Are the other textures all used for something?
> 
> at least for the ones into the texture folder, i did a clean up some time ago, the rest are clean

What about this one? https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/textures/WoodWatchTower_colour.png
I noticed it because it's HUGE (9 MB, that's 10% of our repo). It seems to be used in the "pskmat1" material: https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/scripts/WoodWatchTower_mat.material
But this pskmat1 material isn't used anywhere in the code AFAICT.

**Comment by akien-mga** [comment]
Note: I'd like to have something done bout the WoodWatchTower_colour.png huge texture (if it's actually used, it can probably be scaled down, it's 2048x2048 right now).
I'll open another issue for a more long-term tidying up of our binary data, for now it's a bit hard to know what is used where, we should probably make names more explicit.

**Comment by oyvindln** [comment]
The material names used for the models are defined in the .mesh files, so you'll have to look at them to check whether materials are used or not. There are only a few materials that are referenced in the code, for objects where the material is changed from the default one. And yeah, we don't need textures as large as 2048x2048. I can't see the mentioned material being referenced anywhere by grepping at least. We could also run a png optimiser on the texture files, maybe that would bring down the sizes a bit.

**Comment by Bertram25** [comment]
Ah, I see the point now. @Danimal696 You were a bit quick on this one. ;)

@Danimal696 May I request you to list the models that are directly using textures (and not using materials for them)?

**Comment by Bertram25** [comment]
>  We could also run a png optimiser on the texture files, maybe that would bring down the sizes a bit.

Yeah, but then we would need a way to make sure the textures are all ok.

**Comment by Danimal696** [comment]
you and your materials... ill shot the lot of you...
So far i settled on 2 texture sizes, 512x512 for tiles/rooms/rooms models and 1024x1024 for creatures; but only the files i have worked with follow that, older ones will need to get revised.

Watchtower is unused, but i see potential on it as a future model, you can move it to media and erase from the main branch

**Comment by Danimal696** [comment]
upss sorry, wrong button. IMO just move anything that its not used

**Comment by Bertram25** [comment]
@akien-mga Mind killing this one since you made the suppa script?
I'd rather spare @Danimal696 for such stuff, I must say. ;)

**Comment by akien-mga** [comment]
Yep, I'm on it :)
I'll ask @Danimal696 for confirmation before dropping any texture though, there might some that he plans to use really soon when adding normals to existing models.

**Comment by Danimal696** [comment]
i have access to all repositories and older game versions have all that textures, ill readd them, so you can erase/move without worries.

> I'd rather spare @Danimal696 for such stuff, I must say. ;)

Please, material are taking too much time i could be using for something else

**Comment by akien-mga** [comment]
Fixed by #591.
