### ISSUE TITLE
Camera should go to the last battle field when pressing space

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#499]
As asked by @eugeneloza.

**Comment by akien-mga** [comment]
I guess you meant "when pressing _space_" as in the forum topic, escape already has some stuff to do ;)

**Comment by hwoarangmy** [comment]
yep, you are right ^^

**Comment by Bertram25** [comment]
I do also think something should be shown on the minimap. Like a skull or small crossed swords where the conflict started. WDYT?

**Comment by eugeneloza** [comment]
Actually I thought rather of minimap icon or a button than a keypress (e.g. a battle may take place at different places simulaneousely and one needs to switch between them quickly to issue orders). Maybe, even something like 'favourite places' with battle events automatically added, e.g. to quickly grab a unit and place it to the resting place.

**Comment by Bertram25** [comment]
> Actually I thought rather of minimap icon or a button than a keypress (e.g. a battle may take place at different places simulaneousely and one needs to switch between them quickly to issue orders).

As for the icon, I think we agree. As for the button and the rest, it looks like the event queue on DK2 where you could click on an event and go there. In practice, this was (on DK) more cumbersome than useful, but that's all about taste, right? ;)
I'd like to see icons where conflicts have started, but let's not add/request too much in this area at once. Once we have the space key and the icon, we'll see what's next is lacking.
Ok for you?

**Comment by eugeneloza** [comment]
Yes, definitely :)

**Comment by Danimal696** [comment]
i remember in DK you could rigth click on a room icon and it would cicle your view trougth all of the same type rooms. I also think that if there several battles at the same time "space" could cicle between them

**Comment by hwoarangmy** [comment]
Space is definitely needed because the minimap do not show the entire map. Thus, the battle icon might not be visible

**Comment by Bertram25** [comment]
> Space is definitely needed because the minimap do not show the entire map. Thus, the battle icon might not be visible

Sure. The space button and the icon are separate issues about the same concept, IMHO. Depending on how people are at ease implementing those features, we may separate the icon feature in another issue, if needed.
