### ISSUE TITLE
Chatbox stops working after a while

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#50]
When playing a local game, I was able to speak to myself at first. After a while, the chatbox stopped working: it could be opened and closed, but typing letters would only trigger the usual GUI behaviour of those keys.

I will investigate better tomorrow.

**Comment by akien-mga** [comment]
The causes seems to be related with the console that can be accessed through F12. After you've toggled it once, the chatbox does not accept input anymore.

**Comment by hwoarangmy** [comment]
I can reproduce. I will see asap

**Comment by akien-mga** [comment]
Fix confirmed. Now the music stops when you open the console, but the chat is still working :-)
