### ISSUE TITLE
Levels name are cut in the levels list when going in the editor

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#500]
To allow displaying more of the name, instead of displaying SKIRMISH - LevelName or MULTIPLAYER - LevelName, we could display SK-LevelName and MP-LevelName.

WDYT ?

**Comment by Bertram25** [comment]
Fine by me. Good idea.

**Comment by Bertram25** [comment]
Btw, issue #500!!

**Comment by hwoarangmy** [comment]
> Btw, issue #500!!

You are right. Then, I should take it ^^
