### ISSUE TITLE
Certain beds remain when you kill your own creatures

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#510]
Yeah, I know, it's evil to do that.

What often happens when I'm playing:
I obtain a few spiders, slimes and tentacles. 
I give them a room, feed them and train them to prevent rush attacks from the enemy.

And then, once I have a library and why not a Crypt, I become greedy and want more powerful creatures. So I start destroying my own army to get space for new and potentially stronger creatures.

But not all previous beds gets deleted from the dormitory. (seen with tentacles mostly)

**Comment by hwoarangmy** [comment]
Well, I do the same and I've never seen that. If that happens again, could you please provide logs/replay ?
I will try with tentacles to see if I can reproduce.

**Comment by Danimal696** [comment]
since they spawn so fast you see your dungeon flooded with tier 1 minions, one fix would be to made the portals claimable, so you only dig to them when your dungeon is built (at least the basics to attract tier 2 minions) or make posible to get rid of creatures by dropping them into the portal.

**Comment by Bertram25** [comment]
> Well, I do the same and I've never seen that. If that happens again, could you please provide logs/replay ?

I dumbly didn't have the reflex the last time but I'll sure do.

> since they spawn so fast you see your dungeon flooded with tier 1 minions, one fix would be to made the portals claimable, so you only dig to them when your dungeon is built (at least the basics to attract tier 2 minions) or make posible to get rid of creatures by dropping them into the portal.

Getting rid of minions with a room is an idea. (Portal of anything else.) Slapping them to death isn't a problem for me, since I also get the money back. ;>
Claiming the portal, or simply put activating the portal when one worker reaches it may be considered, but it should be carefully and globally thought.

Wait, aren't we discussing advanced gameplay features? ;)

**Comment by hwoarangmy** [comment]
@Bertram25 I've just had a thought. Did you have a crypt in this game ?

**Comment by Bertram25** [comment]
Yes, I had one. Linked to corpses, you think?

**Comment by hwoarangmy** [comment]
I don't really know. Let's say that normal dying is pretty well tested and the only other way I can think of for a creature to be removed is the crypt. But I will have a look tonight

**Comment by hwoarangmy** [comment]
I confirm I could reproduce the bug. When the dead corpse is removed from gamemap, the bed is not removed. I've moved the code destroying the bed into removefromgamemap to make sure it is not forgotten anymore

**Comment by Bertram25** [comment]
Cool, I'll test asap. :)
