### ISSUE TITLE
Certain tiles seems to get lit multiple times?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#516]
As seen in the following discussion, certain dirt tiles are overlit when their rock corresponding tiles weren't added in the same map. The tile loading order doesn't seem to have an importance:
https://github.com/OpenDungeons/OpenDungeons/pull/507#issuecomment-75150437
![od-strange-dirt-tiles](https://cloud.githubusercontent.com/assets/4701338/6277470/f0a58fe8-b88e-11e4-9911-2e23eab9f795.jpg)

**Comment by hwoarangmy** [comment]
Seems fixed (at least for me) by #514

**Comment by Bertram25** [comment]
Yeah, I confirm the bug is also fixed for me by #514 :D

**Comment by hwoarangmy** [comment]
Closed by #514
