### ISSUE TITLE
Misc admin stuff for Elvano

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#518]
(N.B.: I'll assign him as soon as he'll accept being part of the team on github)
@Wout-van-Dongen 
Please Elvano, make the following happen. Thanks  lot :D
- [x] Remove the site under maintenance notice.
- [x] Give access to files to @hwoarangmy on sf.
- [x] Give us some heads-up on the next-gen temple!
- [x] Stay cool. ;) (Not really an issue, more a reminder.)

**Comment by akien-mga** [comment]
@hwoarangmy should now be able to upload stuff in the Files section on SF, thanks @Wout-van-Dongen.

It seems the first point has been handled too. I just added a mention to the Win32 development builds in the download section.

**Comment by hwoarangmy** [comment]
I confirm I can upload files. Thanks ^^

**Comment by Bertram25** [comment]
I think the news about the next-gen temple can wait. I'm closing.
