### ISSUE TITLE
Ground tile should not be shown when claiming "neutral" claimed tiles

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#526]
I think this is a regression due to recent changes. When workers claim a "neutral" claimed tile, it switches first to plain ground before the claimed tile reappears with the correct seat colour.

IIRC, the previous behaviour was that the coloured tile appeared directly in place of the grey neutral claimed tile, which gives a nicer effect.

**Comment by Bertram25** [comment]
No, it's a desired behaviour. Plus, it simplifies how tiles gets refreshed IIRC.
In term of gameplay, I, for one, can understand you have to remove the former stones to add yours.

I'll let @hwoarangmy have the final word on this one, though, but I'd tag it as invalid/won't fix.
Thanks for your vigilance though. We never know what we could fall upon.

**Comment by akien-mga** [comment]
>  In term of gameplay, I, for one, can understand you have to remove the former stones to add yours.

Well there is two cases IMO:
- You claim an enemy tile: you need to break the existing tile, and then build your own tile on top of it. So then the path is: claimed tile -> ground -> claimed tile.
- You claim an neutral tile: it's here for the taking, you just need to put some paint on it. You don't need to "deconstruct" it first as you would with an enemy tile.

It's a similar behaviour in RTS where you battle for strategic points: if a point is claimed, you need to unclaim it first, and then it neutral and you can grab it. If it's already neutral, you just have to claim it.

**Comment by akien-mga** [comment]
I don't have a strong opinion though, if the current behaviour is preferred, it's fine by me :-)

**Comment by hwoarangmy** [comment]
Yes, that's the wanted behaviour. Actually, that's not neutral but rogue. So, we can consider it is enemy (even if it is enemy for everybody).

**Comment by Bertram25** [comment]
Let's close then.
