### ISSUE TITLE
Minimap: It is slow and badly rendered

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#530]
Some code around the minimap is slow.
I don't know yet whether it's the pixelBox update or the swapping/rendering itself. @oyvindln will tell. ;)

Second thing, it is likely to use the GL_NEAREST method to magnify the texture and this is looking quite ugly in game.
We should have a look at making the minimap texture have smooth edges.

I'm setting this to 0.5.0 but if it becomes to hard to improve, we'll move it to later.

**Comment by Bertram25** [comment]
After looking at the code, the pixels are drawn square per squares after applying the view rotation, explaining why it can be so ugly.
To fix this, the pixels should be rendered unrotated and the texture should be rendered rotated.

**Comment by Bertram25** [comment]
Just had another idea, if we draw the texture unscaled (with a grain of 1) and let cegui rescale it, we may have the desired effect. I'll try it.

**Comment by oyvindln** [comment]
It's also possible to rotate the CEGUI window, rather than drawing rotated. I don't how that would affect performance though.

**Comment by Bertram25** [comment]
> It's also possible to rotate the CEGUI window, rather than drawing rotated. I don't how that would affect performance though.

I've tried, unfortunately, it looks rather poor. Btw, I managed to make the texture be rendered unscaled and zoom it but it also looks poor as it is too smoothed.
I'll thus try the reverse now: Draw the texture at a bigger size than required and make it smaller it when rendered.

**Comment by oyvindln** [comment]
As for performance, it may make sense to draw directly to the texture instead of via a buffer, at least if we drop trying to render 4x4 blocks as we are now. Otherwise I think data locality could be an issue when it comes to performance. Changing the temporary buffer to be a single vector may help a bit, and should be quite straight forward, but on the tile container side that would be much bigger task. The tiles are currently allocated individually on the heap, which may not be ideal performance-wise.

**Comment by Bertram25** [comment]
> It's also possible to rotate the CEGUI window, rather than drawing rotated. I don't how that would affect performance though.

After thinking about this, I wondered whether adding a sub-image to the map background image widget and rotating that one would be feasible. This way, the rotated map, as a child of the map baground image would be scissored correctly when rotated. I may look at that sooner or later when time permits.

**Comment by oyvindln** [comment]
One option for later could also be to simply use renter-to-texture with an isometric camera instead of hand-drawing the minimap.

**Comment by Bertram25** [comment]
> One option for later could also be to simply use renter-to-texture with an isometric camera instead of hand-drawing the minimap.

Yeah, that would be the coolest way to do it. :) Wonder how easy/hard Ogre makes that for us?

**Comment by oyvindln** [comment]
I don't think it's very complicated to do, but we probably want to add support for LOD first.

**Comment by Bertram25** [comment]
> I don't think it's very complicated to do, but we probably want to add support for LOD first.

Btw, 1.10 has got a LOD generator: :) http://www.ogre3d.org/tikiwiki/MeshLod

**Comment by Bertram25** [comment]
IMHO, this issue is solved. The minimap isn't perfect but at least it is not badly rendered anymore.
I'll open a new issue about the possibility to switch minimap type and hide it.

Unimplemented part supported by #839
