### ISSUE TITLE
Savegames and tiles

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#531]
This is more a reminder of what I'm planning to do for saving tiles. If you see something or want to comment, please feel free.

To remind the tile state for each player:
I would remove "claimed" from tile type (to avoid loosing the tile type when it is claimed). It would be replaced by a boolean (or by testing seat != nullptr && mClaimedPercentage>= 1.0).

To avoid showing gold tiles that have been digged somewhere you never had vision, I would display any gold tile (even with fullness = 0) as full gold tiles. That would also allow map creators to hide creatures within gold tiles (and having to had dirt tiles in the middle of gold tiles that makes too visible that there is something strange).

To allow to display room/traps after gamesave, in the room/trap definition, I would had the list of players that have seen this building. Moreover, rooms and traps would not be removed from gamemap when all their tiles are destroyed but also when no player have not refreshed vision since the building was destroyed (ie every human player did not see the room before it got destroyed or they got vision again after).

**Comment by Danimal696** [comment]
are you saving creature weapons?

**Comment by hwoarangmy** [comment]
They are already saved in the creature

**Comment by Bertram25** [comment]
How far are you concerning this issue? So much has happen that I must say I'd use some news about this. XD

**Comment by hwoarangmy** [comment]
ATM, only rooms, traps and marked tiles are not kept after map saving.
I've already started to add names to rooms/traps to allow persistant objects to link at map loading so that the room knows a building object has been created.
As a side effect, that will also open possibility for a goal to need to save a room (or to let him unharmed)

Not everything else is perfectly saved (creature activity and such) but I think it is enough. From the player point of view, most creatures will continue their activity (unless they have been forced to do something). But IMHO, that's acceptable.

**Comment by Bertram25** [comment]
> ATM, only rooms, traps and marked tiles are not kept after map saving.

Ok. Makes things clearer. I wasn't sure for traps I must say.

> As a side effect, that will also open possibility for a goal to need to save a room (or to let him unharmed)

A side bonus effect, then :sunglasses: 

> Not everything else is perfectly saved (creature activity and such) but I think it is enough. From the player point of view, most creatures will continue their activity (unless they have been forced to do something). But IMHO, that's acceptable.

I don't even think it's noticeable without knowing it. Yeah, let's wait for feed-back about it, IMHO.

**Comment by Bertram25** [comment]
Marked tiles are in. I need to test again as I don't remember: Are rooms and traps in, btw?

**Comment by hwoarangmy** [comment]
I'm currently working on traps. Rooms are not in and need some love (to save tile health and remind tiles you have seen)

**Comment by Bertram25** [comment]
Ok, I should have something for the research tree soon enough, btw. ;)

**Comment by Bertram25** [comment]
@hwoarangmy Btw, so you know you're not alone struggling with save feature stuff. ;)
http://www.uberent.com/pa/2015/03/12/single-player-saveload-first-pass/

**Comment by hwoarangmy** [comment]
> Btw, so you know you're not alone struggling with save feature stuff. ;)

Yep. Not an easy feature I guess ^^

**Comment by Bertram25** [comment]
> Yep. Not an easy feature I guess ^^

IMHO, one of the nastier you're biting so far.

**Comment by hwoarangmy** [comment]
> IMHO, one of the nastier you're biting so far.

Well the most annoying thing, IMHO, is that my next PR will be a big game breaker because I had to change many things in the code architecture. And that's probably not the best thing to do few days before a release ^^

**Comment by akien-mga** [comment]
> Well the most annoying thing, IMHO, is that my next PR will be a big game breaker because I had to change many things in the code architecture. And that's probably not the best thing to do few days before a release ^^

IMO that's fine, we'll take the time that we need to fix the potential regressions, and we'll release afterwards :)

**Comment by Bertram25** [comment]
> IMO that's fine, we'll take the time that we need to fix the potential regressions, and we'll release afterwards :)

+1 There is no such thing as a deadline here, except for the pressure we're putting ourselves on our own shoulders because we want to actually show the work done.
So, please, take the time needed. :)
