### ISSUE TITLE
Two issues with the saved game naming method

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#539]
I found two issues with the saved game naming method, which are visible in this example for @hwoarangmy's latest PR:

```
$ ls -1 ~/.local/share/opendungeons/saves/
2015-03-12_102601-SK-GreedOrMight.level
2015-03-12_102758-MP-2015-03-12_102601-SK-GreedOrMight.level
2015-03-12_102820-MP-2015-03-12_102758-MP-2015-03-12_102601-SK-GreedOrMight.level
```

I first started Greed or Might in skirmish and create the first saved game. Then I loaded this saved game and saved again. Finally, I loaded the second saved game and saved it again.

We can see that:
- The name of the previous saved level is appended in the saved game name, we should probably keep only the name of the level and not the former date
- When loading a saved skirmish game, OD incorrectly seems to interpret the saved level as a multiplayer game, so it adds "MP" in the saved game name

**Comment by hwoarangmy** [comment]
> we should probably keep only the name of the level and not the former date

Yes, I've already thought about it. I wasn't sure if we would prefer to overwrite the saved game or create a new one. WDYT ?

> OD incorrectly seems to interpret the saved level as a multiplayer game, so it adds "MP" in the saved game name

That will also be fixed when fixing point 1 as we will need to parse the filename.

**Comment by akien-mga** [comment]
> > we should probably keep only the name of the level and not the former date
> 
> Yes, I've already thought about it. I wasn't sure if we would prefer to overwrite the saved game or create a new one. WDYT ?

For the time being, I think we should create a new one but parse the name of the original save to retrieve only the original level name and game mode, and add the date prefix as we do currently.

In the long run we'll probably want to let users define the same of their saved game, so the above behaviour would probably become obsolete (or will be converted to handle "autosaves" with F5).

**Comment by Bertram25** [comment]
> In the long run we'll probably want to let users define the same of their saved game, so the above behaviour would probably become obsolete (or will be converted to handle "autosaves" with F5).

I'd let autosave, indeed. While later adding an explorer save box will be requested (I'm alsmost sure of it. ;])

**Comment by akien-mga** [comment]
I meant "quicksave" actually (no point of binding "autosave" to F5 ;-)), but you got the idea :-)

**Comment by Bertram25** [comment]
> I meant "quicksave" actually (no point of binding "autosave" to F5 ;-)), but you got the idea :-)

Yep. :)
