### ISSUE TITLE
Game overall too dark with Nvidia on Linux (optimus/bumblebee)

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#54]
I was not mistaken yesterday when I said the game was a bit too dark, even for a "damp, dark and dangerous" dungeon :-D

Here are two comparative screenshots, one taken with my Intel GPU (where we know GLSL shaders don't work as per issue #41), and one taken with my Nvidia GPU. Note that I'm accessing the Nvidia GPU through the bumblebee daemon on Linux, which is kind of a hack, so the issue might be related (though it works fine in most games).

Intel (open source) driver
![odscreenshot_1](https://cloud.githubusercontent.com/assets/4701338/3865775/733dec36-1fa9-11e4-8181-da48e831d0d3.png)

Nvidia (proprietary) driver
![opendungeons-bug-nvidia-too-dark](https://cloud.githubusercontent.com/assets/4701338/3865777/b5f447aa-1fa9-11e4-81c6-8710d79ea8d5.png)

As a side note, I noticed that the screenshot feature in OD works fine with my Intel GPU, but does not work with the Nvidia GPU. My guess would be that the culprit is bumblebee, could someone with Linux and a non-optimus Nvidia GPU confirm that?

**Comment by Bertram25** [comment]
@akien-mageia Ah indeed, it's dark ;)
I wondered: Did change the gamma in the nvidia settings, for instance? We don't have any configurable video options, so this might be a cause. ;)

Also, I'm sure the actual goal will later be to create a source light per rooms, for instance. As it seems some code was prepared for this. This would help a with you issue, IMHO.

**Comment by hwoarangmy** [comment]
yes, I've seen some code for it too. But it has been deactivated so there might be a reason (too laggy?)... We could ask oln. Maybe he remembers why...

**Comment by akien-mga** [comment]
I'll try to change the gamma in the nvidia settings to see if it's better.

**Comment by Bertram25** [comment]
> yes, I've seen some code for it too. But it has been deactivated so there might be a reason (too laggy?)... We could ask oln. Maybe he remembers why...

For info, on Ogre 1.7, when adding too much light sources, the RT shader was crashing from what I read, and I guess that's the main reason lights code was removed.
Note that before, the code was adding a light source per room tile, which was way too much.
Also, light handling has improved (a bit) with Ogre 1.9.
@oyvindln may indeed have more info.

I'd thus propose to add a light source when the room is reaching a sufficient size, like at least 9 tiles. The source light should then be recentered if the room grows up. A second room light could added when the room reaches 18 tiles and so on.
Would the room go below 9 tiles, the light source should be removed.

All in all, room lights would be handled very much like room objects.

What do you think?

**Comment by Bertram25** [comment]
@akien-mga Btw, is it still the case with the upgrade of the materials used?

**Comment by akien-mga** [comment]
You did well to ping me, it's been effectively solved by the recent changes. The game is now gorgeous with the nvidia driver :-)

![od-nvidia](https://cloud.githubusercontent.com/assets/4701338/6257125/e614d678-b7bd-11e4-89ee-f5d4c9fcb867.jpg)

**Comment by akien-mga** [comment]
I didn't bisect to confirm, but for the sake of completeness, this bug should have been fixed thanks to #448.

**Comment by Bertram25** [comment]
Cool, one less bug. :)
