### ISSUE TITLE
Marked tiles weird color

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#541]
Since attenuation has been reduced, marked tiles have strange color when far from the keeper hand. I guess this issue was not visible before because attenuation was too high and we couldn't reach a distance where the tile color changed

![odscreenshot_2015-03-12_203615_2](https://cloud.githubusercontent.com/assets/7493706/6626775/9a166b40-c8f9-11e4-881c-a057e2af12a4.png)

**Comment by Bertram25** [comment]
Yep, confirmed.

**Comment by hwoarangmy** [comment]
@Bertram25 @oyvindln An idea how to fix this ? IMHO, that needs to be fixed for 0.5.0

**Comment by Bertram25** [comment]
@hwoarangmy Must say I'm not sure. Maybe add some emissive when marked?
@oyvindln Any idea yourself?

**Comment by oyvindln** [comment]
I don't understand what the error is from the picture, is it the black tiles?

**Comment by hwoarangmy** [comment]
@oyvindln  If you look closer, you will see that I've marked a square. But as I move the light, far tiles (distance > 10) become really dark (almost as not marked).
I guess it comes from decreasing attenuation (before you say it, increasing attenuation is not an option ;) )

**Comment by Bertram25** [comment]
I don't know yet whether this can help but I noticed yesterday that the marked gold tiles don't seem to suffer from that bug.

**Comment by akien-mga** [comment]
Here is a video that shows the issue: http://remi.verschelde.fr/files/misc/od-marking.mkv

**Comment by oyvindln** [comment]
Hm. Maybe it has something with the fact that we are using lighting values to add the shading to the tile, and if the tiles are only hit by ambient light it doesn't work properly. Though I'm still not sure why, maybe ogre does some trickery to disable lighting in the background or something. I was planning to change the way tiles are shaded anyhow, so maybe that will fix it, I haven't been able to do much work on it lately though.

**Comment by akien-mga** [comment]
Do we have an idea about which commit caused this bug? If we're not sure I can try to bisect it.

**Comment by Bertram25** [comment]
I'd say around this one:
https://github.com/OpenDungeons/OpenDungeons/commit/ee56e51299d15c65446ebc250ef9e27a8781d145

But I don't think this "bug" is a regression. Rather an undercover one revealed by fixes on lights.

**Comment by hwoarangmy** [comment]
I am pretty sure it is the commit from @oyvindln about changing light attenuation. It was set to 50 at he set it to something like 10 (which seems much saner BTW). But as a consequence, now, you can see enough tiles to be able to put the hand light somewhere and have more tiles in your screen than the current attenuation.
I also do believe it is not a regression but it was just not visible before this commit.

**Comment by Bertram25** [comment]
Yep, and btw, Gold doesn't use normals yet, explaining why there is no light "bug" on it (or maybe this is a Fixed function pipeline bug that lights aren't applied correctly?)
https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/scripts/Gold.material
https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/scripts/Dirt.material

While we're on this, note that the Grimoire has got warnings because its light values are placed within the `texture_unit` section while they should be placed in the `pass decal` section AFAIK.

So as a first try, I wonder whether adding lighting values similar to Gold there could help in Dirt.material?

If that doesn't work at all, maybe as a (even temporary) workaround, we could use a no-normal-using dirt material when the tile is marked?
WDYT?

**Comment by hwoarangmy** [comment]
> While we're on this, note that the Grimoire has got warnings because its light values

Many materials have this bug. There was in issue about it #529 fixed by @oyvindln. I guess those you are talking about were introduced after the corresponding PR.

> So as a first try, I wonder whether adding lighting values similar to Gold there could help in Dirt.material?

In any case, IMHO, it would be better to use "live" material customization for seat color only and use material files for everything else (marked tiles, tiles without vision).
Of course, that means we will have to adapt tilesets.

**Comment by Bertram25** [comment]
> Many materials have this bug. There was in issue about it #529 fixed by @oyvindln. I guess those you are talking about were introduced after the corresponding PR.

Yeah, I've opened #570 about this. If you see others, feel free to list them there.

> In any case, IMHO, it would be better to use "live" material customization for seat color only and use material files for everything else (marked tiles, tiles without vision).
> Of course, that means we will have to adapt tilesets.

Agreed, fortunately both of my proposals are following that road.

**Comment by Bertram25** [comment]
I'll make some tries tonight, btw, but I don't say I have the solution yet. ;)

**Comment by Bertram25** [comment]
I have it! :)
