### ISSUE TITLE
Proposal: Add a git repo for the website

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#545]
So everyone can contribute, make reviews as well, ...

I'll be honest, having a repo from the even static website would permit me to skin it. ;)

**Comment by akien-mga** [comment]
That would be nice indeed, though how don't know if that can be done using the opendungeons.sf.net domain.

If we want to move yet another service to GitHub instead of SF, we could use https://pages.github.com/ :-)

**Comment by Bertram25** [comment]
> That would be nice indeed, though how don't know if that can be done using the opendungeons.sf.net domain.

I guess the syncing would still have to be done manually or through a local script with credentials.

> If we want to move yet another service to GitHub instead of SF, we could use https://pages.github.com/ :-)

Yes, this could also be studied as well. :)

WDYT @hwoarangmy @oyvindln @Danimal696 @Wout-van-Dongen ?

**Comment by Danimal696** [comment]
yes, i also proposed some time ago to give the ability to ours downloaders to write their opinions, not everyone annoys themselves to register at a  forum

**Comment by Bertram25** [comment]
> yes, i also proposed some time ago to give the ability to ours downloaders to write their opinions, not everyone annoys themselves to register at a forum

Adding Web 2.0 features within the website seems to mean using Jekyll if we're using github's pages. This should be carefully thought and tried before taking any conclusion, IMHO.
Plus, from actual and recent experience, anonymous comments are usually a nasty thing as they are a common source of spam you have to delete. So IMHO, even comments should be made after registration, which is interesting only if you can log in through facebook, g+ or whatever famous userbase accounts. If not, I'll prefer forums, as for me and there is no actual interest for us in adding support for them.

**Comment by akien-mga** [comment]
I've discussed this on IRC with Elvano, and we'd like to give a try to github's pages.
According to the documentation [1], we need to create an OpenDungeons/opendungeons.github.io repo that will be used to generate the opendungeons.github.io website. Can you do this @Bertram25?
Then maybe the "Developers" group should be extended to have commit rights on this repo too, so that we can manage it easily.

[1] https://help.github.com/articles/user-organization-and-project-pages/

**Comment by Bertram25** [comment]
I'll have a look at creating this, but if I can, I'd rather create a new group for that. Adding people there is trivial. ;)

**Comment by akien-mga** [comment]
> I'll have a look at creating this, but if I can, I'd rather create a new group for that. Adding people there is trivial. ;)

Sounds good to me. I'd like to be in there if possible :-)

**Comment by Bertram25** [comment]
> Sounds good to me. I'd like to be in there if possible :-)

I think all current active devs should. And, yes, you're a dev now.

**Comment by Bertram25** [comment]
It is done. :)
Now the HTML has to be imported unless you both have better plans. I'll let you ignite it.
As a side note, I'd rather have website issues stay in the common opendungeons issue tracker, same for wiki, so I disabled both for the website repo.

**Comment by akien-mga** [comment]
> As a side note, I'd rather have website issues stay in the common opendungeons issue tracker, same for wiki, so I disabled both for the website repo.

Sounds good :)

**Comment by Bertram25** [comment]
@Wout-van-Dongen @akien-mga Need help porting the HTML website? Or have you got other plans?

**Comment by hwoarangmy** [comment]
Seems like this one is done. I close it
