### ISSUE TITLE
Keeper hand does not rotate with map

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#547]
As said in the title, the keeper hand does not rotate with the map. It's handled as all the other models, so if you rotate the map by 90°, then the keeper hand appears rotated too.

Since we use it as the mouse cursor, it would be more natural if it kept a constant direction regardless of the map rotation.

As a side note, its position with regard to the system cursor should also be adjusted so that it looks more natural, as pointed out in #543:

> I think though that the mouse pointer is too high now (it's at the tip of the fingers), I would expect the hands active spot to be under the palm or the beginning of the fingers. It's particularly visible when grabbing a creature: the hand grabs the air of the tile below the targeted creature :)

**Comment by Bertram25** [comment]
Moving the hand to be under the cursor is IMHO part of 0.5.0. The rotation is something else as it could harder. @hwoarangmy How did your experience ended with changing the hand offset, btw?

**Comment by Bertram25** [comment]
>  @hwoarangmy How did your experience ended with changing the hand offset, btw?

Nevermind, somehow, I didn't realize you've fixed it. ;) The rotation is left to be done. 0.5.0 or 0.6.0?

**Comment by akien-mga** [comment]
I'm setting the rotation to 0.6.0 for now, since it's probably related to bigger issues like #420, and it hasn't bugged us too much so far ;-)

As for the offset adjustments I talked about in comment 0, I'd still like to see something done for 0.5.0.
