### ISSUE TITLE
Adapt the F1 help to the 0.5.0 gameplay

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#548]
Title says it all. Basically, we just need to proofread the help, and do some adjustments for the gameplay changes in 0.5.0, e.g. the research logic.

**Comment by Bertram25** [comment]
For info, in multiline edit widgets, you can use icon and colors within the text. See there:
http://cegui.org.uk/wiki/Formatting_Tags_in_CEGUI

Might make the text more appealing. ;)

**Comment by Bertram25** [comment]
Ah, and the windows should auto-add a scrollbar if the text is longer than the screen so you should have all the space you want.

**Comment by akien-mga** [comment]
I'll consider this one closed for now, though I might continue to work on the help text in the near future depending on the feedback we get about it :-)

**Comment by akien-mga** [comment]
Fixed by 2b1b630.
