### ISSUE TITLE
Picked-up and then dropped gold mesh stays in hand.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#549]
When you pick up some gold on one of your claimed tiles, and drop it into the treasury, the gold is added but the mesh stays visible in small size next to the keeper hand.

**Comment by akien-mga** [comment]
I can sort of reproduce the issue. The difference here is that I simply don't manage to drop the gold, that's why it stays in hand.

**Comment by akien-mga** [comment]
It's also easy to reproduce: collect gold, destroy a treasury tile, grab the orphaned gold, and see that you can't drop it anymore :)

**Comment by Bertram25** [comment]
Ah? Wait, was I able to put it back? Now you tell it, maybe I wasn't, eh.

**Comment by hwoarangmy** [comment]
I guess it is again related to the changes I've done about fullness on client side. It's easy to fix and I will do that ASAP.
For the record, I will check all dropable entities as they probably have the same bug.
