### ISSUE TITLE
Missing model for the cannon trap

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#55]
The cannon trap can be placed in-game, but it has no model, so it's a bit confusing. See:

![odscreenshot_22](https://cloud.githubusercontent.com/assets/4701338/3865887/f23b4ca6-1fb1-11e4-8640-edb348494d0f.jpg)
The claimed tile under the cursor (in the middle of the training area) is my cannon trap, and it just fired a cannonball at a drake! :)

**Comment by Bertram25** [comment]
Might be the same bug than with the rooms not showing, as the trap cannon was shown before.
Nice catch anyway. :)

**Comment by hwoarangmy** [comment]
Yes, I've had a look and it is the same bug. Seems like I missed it while I was hunting yesterday :)

**Comment by akien-mga** [comment]
Fix confirmed.
