### ISSUE TITLE
Improve icon alignment in OpenDungeonsIcons.png

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#552]
I've had a closer look at our gui/OpenDungeonsIcons.png tileset, and I've noticed that the grid-alignment is not OCD-perfect ;-) Apart from the small 32x32 icons, all other icons should fit in a 64x64 frame, but I've noticed that some are not properly centred along a orthogonal grid with a base dimension of 64.

See the following screenshots taken in GIMP with the said grid.
Note: the first and second screenshot have a grid offset of 32 px at the top to account for the row of 32x32 icons. It seems the icons at the bottom are more aligned as if there was no 32 px row, so I also made a screenshot with no grid offset.
![icons1](https://cloud.githubusercontent.com/assets/4701338/6690342/5a5e2b6c-ccc0-11e4-9620-deb9917cd5f6.jpg)
![icons2](https://cloud.githubusercontent.com/assets/4701338/6690344/5b44cb4e-ccc0-11e4-9191-72b6091d5507.jpg)
![icons3](https://cloud.githubusercontent.com/assets/4701338/6690345/5c267eb8-ccc0-11e4-9967-70177a8daa99.jpg)

You can see for example that the gold tile is 63x64, and some other icons are not properly centred or do not fit in their supposed frame. I haven't looked at the CEGUI code yet, but my guess is that @Bertram25 used coordinates that were fitting, without forcefully checking that everything is centred on a 64x64 grid.

If you can confirm that, and point me to the relevant code that I'll have to edit if I move icons around, I propose to reorder the icons to fit on a 64x64 grid and let my OCD be at ease ;-)
I would also propose to leave two rows on top for the 32x32 icons (even though the ones we are currently using fit on one row), this way we'll know that for the big icons, they always start at a multiple of 64, and not 64*n + 32.

WDYT?

**Comment by hwoarangmy** [comment]
You should only have to mess with CEGUI files for most icons (text files easy to change in gui path).
Concerning optional gui icons (like the green check), I'm not sure. I don't remember @Bertram25 PR but he should be able to tell you ^^

**Comment by akien-mga** [comment]
Here is my proposal:
![opendungeonsicons](https://cloud.githubusercontent.com/assets/4701338/6691547/9ba4a0fe-ccc7-11e4-9102-928578fa63d9.png)

With the grid:
![icons6](https://cloud.githubusercontent.com/assets/4701338/6691559/a6fce286-ccc7-11e4-8eac-b01138aa5da0.jpg)
![icons4](https://cloud.githubusercontent.com/assets/4701338/6691555/a501b434-ccc7-11e4-9776-e11c8fc55aad.jpg)
![icons5](https://cloud.githubusercontent.com/assets/4701338/6691557/a5a38d9a-ccc7-11e4-96d8-fff22dd198e8.jpg)

If you like it I'll do the corresponding adjustment in the CEGUI files and do a PR.

**Comment by Bertram25** [comment]
I like it, looks professional. :) (I should have done that from the start.)

**Comment by hwoarangmy** [comment]
Yep, seems perfect ^^
