### ISSUE TITLE
Unlocked GUI elements via research are not reset when starting a new game

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#559]
Oops :-)

**Comment by akien-mga** [comment]
Actually my diagnosis was wrong, so I change the topic. The research progress is properly reset, but the GUI is not refreshed so you can still try to place unlocked rooms and traps. It doesn't work though.

**Comment by Bertram25** [comment]
Silly me, I'm almost sure it is all about asking a gui refresh after loading the map.
