### ISSUE TITLE
Segfault with no helpful backtrace

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#560]
Playing @Bertram25's current game, I experienced two segfaults so far, with unhelpful backtraces:

```
Computing turn 2118SERVER - Removing room Workshop36
> 20 loops in Creature::doUpkeep name:Troll96 seat id: 3. Breaking out..
SERVER - Removing rendered object RenderedMovableEntity_Crypt5_2418,MeshName=SmallSpider
signal 11 (Segmentation fault), address is 0x7fad14320af8 from 0x7fad14320af8

[bt]: (1) [0x7fad14320af8]
[bt]: (2) [0x7fad14320af8]

signal 11 (Segmentation fault), address is 0 from 0

[bt]: (1) [(nil)]
```

```
Computing turn 1664> 20 loops in Creature::doUpkeep name:Knight92 seat id: 0. Breaking out..
> 20 loops in Creature::doUpkeep name:Knight93 seat id: 0. Breaking out..
> 20 loops in Creature::doUpkeep name:Knight94 seat id: 0. Breaking out..
SERVER - Removing room Farm33
SERVER - Removing rendered object RenderedMovableEntity_Cannon_8_1298,MeshName=Cannonball
signal 11 (Segmentation fault), address is 0x7f7e7c0001c8 from 0x7f7e7c0001c8

[bt]: (1) [0x7f7e7c0001c8]
[bt]: (2) [0x7f7e7c0001c8]
```

I can't say if it's related to @Bertram25's current PR though, I hadn't played long games for a while, and my two segfaults appeared in mid game (turns 1664 and 2118).

**Comment by akien-mga** [comment]
Well actually the output is not that useless, since in both cases the segfaults happened when removing a name room, so my guess would be that the culprit is @hwoarangmy's room naming ;-)

**Comment by Bertram25** [comment]
@akien-mga Is there a common event type that could be linked to your segfault in both games? Were you being attacked or attacking an AI?

**Comment by Bertram25** [comment]
Ah and what was(were) the map(s) played?

**Comment by akien-mga** [comment]
> Ah and what was(were) the map(s) played?

The first segfault was on Scream in the Dark, and the second segfault was on Stonekeep Siege.

**Comment by hwoarangmy** [comment]
I've already seen and fixed this segfault few days ago. It will be released in my PR. It comes from an architecture problem because we don't clean removed entities after AI turn. It is now visible because of the AI repairing rooms.
