### ISSUE TITLE
Workers should learn to work in teams

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#565]
Currently the workers choose their tasks based on pre-defined priorities, and it's working fine. But it is really common to see a group of workers heading to the exact same tile to do the exact same action, e.g. picking up a completed research grimoire, or claiming a wall.

This results in an important loss of efficiency since the logic is:
- find a prioritary task to do
- go to the task's location
- check if there is still a task to do there - ah no another worker came here first
- repeat

Workers should probably have a way to tell each other: I'm handling this task at this location, find another one.

**Comment by Danimal696** [comment]
that would also fix the problem of legion of them digging the same wall

**Comment by Bertram25** [comment]
Not simple. ;) But relevant.

**Comment by hwoarangmy** [comment]
Not simple at all, indeed ^^

**Comment by akien-mga** [comment]
Hey, teamwork never was an easy-to-learn skill ;-)
