### ISSUE TITLE
Make backup of the logs of the last couple of games

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#567]
I often find myself stumbling into a bug while playing, and then I start a new game to try to better diagnose this game. Most of the time I forget to backup the first log that might contain interesting stuff, and I might end up losing valuable info.

So for impulsive bung hunters like me, it would be nice to have some backups of the previous log. I don't mean to make logs with unique names, that would soon be bothersome, but keep the last or N last logs as opendungeons.log.old or opendungeons.log.{1,2,3} for example.

**Comment by akien-mga** [comment]
To make it clearer: when starting a new instance of OD, opendungeons.log (the one from the last game) should be renamed opendungeons.log.old (overriding the penultimate log).

**Comment by akien-mga** [comment]
I've had a look at this one but I run into a boost::filesystem bug: https://svn.boost.org/trac/boost/ticket/10038

```
$ LC_ALL=C make -j3
Scanning dependencies of target opendungeons
[  1%] Building CXX object CMakeFiles/opendungeons.dir/source/utils/ResourceManager.cpp.o
Linking CXX executable opendungeons
CMakeFiles/opendungeons.dir/source/utils/ResourceManager.cpp.o: In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
```

Using this code in ResourceManager::setupUserDataFolders():

```
    // Backup the previous Ogre log file
    boost::filesystem::copy_file(mOgreLogFile, mOgreLogFile + ".old", boost::filesystem::copy_option::overwrite_if_exists);
```

Looks like this bug is fixed in boost 1.57.0, but we don't want to break compatibility with earlier boost versions just to copy a file IMO :-)

**Comment by akien-mga** [comment]
I worked around the issue by using boost::filesystem::rename in the end.

**Comment by hwoarangmy** [comment]
> I worked around the issue by using boost::filesystem::rename in the end.

That's what I was going to say. Renaming seems better suited than copying

**Comment by Bertram25** [comment]
OMG, what have we done?! Look, @akien-mga is a dev now. His girlfriend will kill us for that. ;P

**Comment by akien-mga** [comment]
> OMG, what have we done?! Look, @akien-mga is a dev now. His girlfriend will kill us for that. ;P

So far she was mostly amused to see me jubilating after I had managed to add a GUI element that shows how many creatures I have :-D

I'll stick to junior jobs for now, since for the bigger ones you would have half of my work to redo to get a good implementation. So if you notice things that should be easy to fix/implement and that you're not already handling in your PR, feel free to open an issue and assign it to me :-)

I find that browsing through the code with a feature/bugfix in mind is an entertaining way to get familiarised with our code base.

**Comment by Bertram25** [comment]
> I'll stick to junior jobs for now, since for the bigger ones you would have half of my work to redo to get a good implementation. So if you notice things that should be easy to fix/implement and that you're not already handling in your PR, feel free to open an issue and assign it to me :-)

I'll never be bold enough to assign things to you without having even an hint of your consent about it first. ;) But I may sometimes do that to @hwoarangmy because of the BigKnight's use. ;P

> I find that browsing through the code with a feature/bugfix in mind is an entertaining way to get familiarised with our code base.

Best way, too, IMHO. We're a crazy bunch of fellows making a crazy good game. Let's keep that fun, indeed. :)
