### ISSUE TITLE
Revise the spawning logic

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#568]
_Note:_ I'll sum up the current state of the discussions here and copy paste some relevant bits from #562 in the first comment.

**Current spawning logic**
- The portal can spawn a creature if the total number of controlled creatures (both spawned fighters and summoned workers) is less than MaxCreaturesPerSeat defined in config/global.cfg (set to 15)
- The crypt follows the same logic
- The SummonWorker spell currently does no check, but it will follow the same logic as above once #562 has been merged.

@Bertram25 said that the intended logic is that MaxCreaturesPerSeat is the total number of fighting creatures that can be spawned through the portal, and that additional portals increase this value by 5. I'm not sure this is actually implemented in the spawning logic though, since from what I saw both the portal and the crypt test only for MaxCreaturesPerSeat.

**New spawning logic**
- Workers should be out of creature count (if max creature number is 20, it means 20 fighters not including workers)
- The maximum creature number should be raised to 20

**Comment by akien-mga** [comment]
From @Bertram25:

> There are few things, I'd like to precise about the creature number. The 15 value is fact what we defined as the max number of spawnable creatures through the portal.
> That number should even be increased by something like 5 per supplementary portals.
> The number of worker creatures and the number of creature spawned at the crypt aren't even considered by this limit.
> 
> I'd request that the max number of creature is turned into the max number of portal creature and that this number is displayed between brackets for instance in the GUI if displayed at all.
> I'd also request that this limit is checked only for portals.
> 
> Also, I do think an absolute max number of creature per seat should be defined and applied in game, but it should be higher than 15 + 8 creatures. Let's 25-30 as a first row?
> And the game should in any case warn the player it has reached the max.

From @hwoarangmy:

> We should define a strategie (maximum creatures computation like @Bertram25 said about owning portals). Then, we should define if workers should be taken into account when computing creature numbers (from what I've read here, it seems "no" is the most wanted answer).
> When the time comes, we might also want to have some creatures that also do not count like skeletons.

From @Danimal696:

> yes, creatures from the crypt and future prison shouldnt be counted in the max, else there is no reason to have those rooms built in the first place

**Comment by hwoarangmy** [comment]
IMHO, as a first step, we could increase max creature number and remove workers from it.
The bonus per portal is a good thing since it would make a bonus to agressive players but it means claiming portals and should be done in a second step.
In any case, maximum creatures per seat should be kept for performance purposes.

BTW, ATM workers count in the total creatures number (worked like that from the beginning in OD) which can be seen as an upkeep penalty for players with many workers. I think we should just drop this penalty and see later if we feel we want to change that (leaving only the cost per worker increase).

**Comment by Bertram25** [comment]
Agreed.
Btw, I wondered whether we wanted different limits for single player and multiplayer maps?
WDYT?

**Comment by akien-mga** [comment]
> Btw, I wondered whether we wanted different limits for single player and multiplayer maps?

Not forcefully for now, but I'd like to envision this under another angle: should we have the possibility to override the limits from global.cfg in the level files? IMO yes, and that would make it possible to set different limits for skirmish and multiplayer.

**Comment by hwoarangmy** [comment]
I agree with @akien-mga. Not in a first step and later by overriding limits

**Comment by Bertram25** [comment]
Yeah, sounds clever and it's the logic used for creatures. Ok, let's see that later with that in mind.

**Comment by Bertram25** [comment]
The last release blocker IMHO.

**Comment by hwoarangmy** [comment]
I will handle this when my PR gets merged
