### ISSUE TITLE
Several materials are giving warnings - take 2

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#570]
The Workshop, workshopMachine1 and Grimoire material files are giving similar warnings to this one:

```
Compiler error: unknown error in TrainingDummy1.material(23): token "ambient" is not recognized
Compiler error: unknown error in TrainingDummy1.material(24): token "diffuse" is not recognized
Compiler error: unknown error in TrainingDummy1.material(25): token "specular" is not recognized
Compiler error: unknown error in TrainingDummy1.material(26): token "emissive" is not recognized
```

Same as seen in #529 

Have a look at #546 and https://github.com/oyvindln/OpenDungeons/commit/60bcd45a6703b39576ca85925c6a55cab77bb732 to know how it was fixed for other materials.

**Comment by Danimal696** [comment]
the materials need a full overhaul, ill get on it little by little

**Comment by Bertram25** [comment]
This issue is fixed in itself.

Other warnings will be fixed as a background task. I'm closing.
