### ISSUE TITLE
The research entity should be brought to the temple center.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#576]
Atm, the worker will go to the first temple tile. It's just a nifty detail, though.
So, if it brings too much burden, we can move it to 0.6.0 if you want guys.

**Comment by akien-mga** [comment]
Another small detail on this topic: from what I could see workers grab the last research entity instead of grabbing the first one. So if they were quite busy and you accumulated three or four research entities, you might have to wait a bit until the first one (that you probably want to build first, e.g. a training room) becomes available.

**Comment by hwoarangmy** [comment]
> So, if it brings too much burden, we can move it to 0.6.0 if you want guys.

No, its easy to do.

> from what I could see workers grab the last research entity instead of grabbing the first one

IIRC, they should take the closest to them, not the last one. But indeed, that might result in enabling rooms where dependencies are still disabled.
But the reason was to allow to steal research entities...
This one might be more tricky depending on what we decide to do.

**Comment by akien-mga** [comment]
> > from what I could see workers grab the last research entity instead of grabbing the first one
> 
> IIRC, they should take the closest to them, not the last one. But indeed, that might result in enabling rooms where dependencies are still disabled.
> But the reason was to allow to steal research entities...
> This one might be more tricky depending on what we decide to do.

We should probably leave this part for now and come back to it for 0.6.0 then.

**Comment by Bertram25** [comment]
> IIRC, they should take the closest to them, not the last one. But indeed, that might result in enabling rooms where dependencies are still disabled.
> But the reason was to allow to steal research entities...
> This one might be more tricky depending on what we decide to do.

This is an actual nasty detail to fix later on. I'm not even sure we should let the creature work on a research before its dependencies have been brought to the temple. the creatures should then maybe try the next research in queue that has no unmet dependencies instead?

While we're on almost off-topic things ;) do you mind if I increase research points for depending on the research location in tree? I'd go for +50 points per row as a start.

**Comment by akien-mga** [comment]
> While we're on almost off-topic things ;) do you mind if I increase research points for depending on the research location in tree? I'd go for +50 points per row as a start.

The current "timing" feels right for the training room and first couple of researches, but then it goes too fast IMO compared to the current game duration. So I'm all for increasing the requirements for high-tier researches.

**Comment by hwoarangmy** [comment]
> I'm not even sure we should let the creature work on a research before its dependencies have been brought to the temple.

Well, it was done this way to avoid creatures leaving the library after each research if you try to do everything in a row. However, IMHO, the best if we find this is really an issue, would be to let creatures gather points and only release a new research entity when its dependencies are brought to the temple.

**Comment by Bertram25** [comment]
> Well, it was done this way to avoid creatures leaving the library after each research if you try to do everything in a row. However, IMHO, the best if we find this is really an issue, would be to let creatures gather points and only release a new research entity when its dependencies are brought to the temple.

Yep, but if you add several feasible researches in the queue (researches with dependencies met), shouldn't the creatures start the next feasible one?

> IMHO, the best if we find this is really an issue, would be to let creatures gather points and only release a new research entity when its dependencies are brought to the temple.

May be a solution without being too much a burden for the player, yes. Ok, we'll be back on this for 0.6.0. ;)

**Comment by hwoarangmy** [comment]
> Yep, but if you add several feasible researches in the queue (researches with dependencies met), shouldn't the creatures start the next feasible one?

If several feasible researches are pending, i agree there is no problem. But if a player wants to rush for the last spell, IMHO, it is not acceptable to have all his creatures stop working after each research...

**Comment by Bertram25** [comment]
> If several feasible researches are pending, i agree there is no problem. But if a player wants to rush for the last spell, IMHO, it is not acceptable to have all his creatures stop working after each research...

Fair point. I agree on the solution then if we go that way. This needs a proper issue. Created:  #577

**Comment by Bertram25** [comment]
Since he has already done it, I'm assigning @hwoarangmy :)
