### ISSUE TITLE
Research dependencies handling.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#577]
As reported in #576, Research can be started even when their dependencies aren't met.

If this is actually a problem (To be decided and my vote is yes, it is).
Then a sane proposal from @hwoarangmy is to let the workers gather research points and make the research entity happen only when the research dependency/ies entity has/have been brought to the temple.

This way, players that are rushing for advanced spells in one area aren't subdued compared to the ones searching everything on the same research level before moving on.

**Comment by hwoarangmy** [comment]
Now that we are talking about research, what about finding a research entity (stealing from enemy or dropped by a creature) if you don't have the required dependencies ?

**Comment by Bertram25** [comment]
> Now that we are talking about research, what about finding a research entity (stealing from enemy or dropped by a creature) if you don't have the required dependencies ?

IMHO, There are two options:
1. It can enable the corresponding research whatever its level. (More strategical)
or
2. Give the equivalent amount of research points. (More flexible if we later make a research tree per faction, or a specific one for the campaign for instance.)

Note that the 1. could also be done through hidden gift boxes, and/or item found after killing a creature.

What does everyone think about it? @akien-mga @Danimal696 @oyvindln

**Comment by hwoarangmy** [comment]
@Bertram25 Sorry I missed this one. IMHO, 1 is more understandable from a player point of view and easier to do. So, I will choose this one.

**Comment by hwoarangmy** [comment]
Closed by #831
