### ISSUE TITLE
Make OD system-wide installable on Linux

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#58]
I've started working on proper "make install" instructions for Linux. I will soon commit some changes to my fork and we can discuss them here before I do a proper pull request.

I managed to install OD on my system, putting the two binaries (script and OpenDungeons.bin) into /usr/games and the data into /usr/share/games/opendungeons
The data is:

```
$ ls /usr/share/games/opendungeons/
gui/  levels/  materials/  models/  music/  plugins.cfg  resources.cfg  resources.zip.cfg  sounds/
```

Now, I'm having an issue with the "levels" folder, since it is not linked in resources.cfg nor in resources.zip.cfg. I tried adding a "[Level]" or "[Levels]" category, but obviously it does not work, so my guess is that the "./levels" path is hardcoded for now. Any clue about reading it from the resources.cfg too?

EDIT: The above is also valid for the "scripts" folder. For now I worked around the issue by adding "cd /usr/share/games/opendungeons" in the launch script, so that the executable is started from a folder containing the "levels" and "scripts" folder. That's really messy :-p

**Comment by akien-mga** [comment]
I have three commits there starting the work to make OD system-wide installable: https://github.com/akien-mageia/OpenDungeons/compare/OpenDungeons:development...development

"make install" now should work fine, but the approach I tried to use to make it still possible to run the game from the build directory seems not to be functional: I defined the paths in resources.cfg using ${CMAKE_SOURCE_DIR}, so that the binary retrieves the data from the root dir, but it seems that OGRE doesn't like the absolute path. Replacing the absolute path with "../" (since I built in a "build" subdirectory) does the trick, but I don't know a cmake variable that would be the ${CMAKE_SOURCE_DIR} as a relative path.
Maybe I should try another approach.

It might be that my changes broken the Windows build too, or at least it probably doesn't fix an already broken "make install" on Windows :)

My branch is a WIP, feel free to comment and give advice on how to do it in a better way.

**Comment by hwoarangmy** [comment]
The level dir is hardcoded in MenuModeSingleplayer.cpp and MenuModeMultiplayer.cpp

Concerning the media, I believe the ressource file is used by ogre so I'm not sure if we can safely add new entries nor if we can read it on our own after having sent it to ogre. Anyway, I agree that it would be better to have the important dir in a config file rather than hardcoded.

**Comment by Bertram25** [comment]
IMO, there are two ways here:
- Either we have sane names for base directories and thus we can hard-code only that part. (I mean only the `levels/` part for instance, not `/opendungeons/levels/` of course.)
- Or we can set up filenames to give the full reference: when loading a filename we call: `"levels/myLevel.level"` instead of `"myLevel.level"`

Atm, the first way is used: (except for levels)
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/ResourceManager.cpp#L60

Adding a file telling where everything is, from experience and seeing other projects, usually a useless layer adding complexity.

I'd even say, if we ever go crazy, and take the example where we add modding support: All we would need to set is where the base data directory lies. The modder would only have to follow the inner structure given or give fuller filenames.

Other solutions are IMHO too much work for what it's worth.

What do you think?

**Comment by Bertram25** [comment]
Also, about running OD from the bin directory. IMO, the binary should cd to the data path automatically.

**Comment by akien-mga** [comment]
I think the first approach you described is the best indeed. What would seem best IMO would be a hard-coded relative data structure (path to relevant data dirs from the main data path, e.g. "levels/" or "scripts/"), and a customisable/expandable list of main data paths, that would stored only in one place, so that we can support multiple paths, e.g.:

```
~/.local/share/opendungeons/   -- Hardcoded location extracted from the OD userdir
/usr/share/games/opendungeons/   -- Hardcoded location taken from the cmake data path variable
```

The first path would have precedence over the second one, so that user can e.g. add new levels or replace existing ones by their local content, without touching the root filesystem.

**Comment by Bertram25** [comment]
> The first path would have precedence over the second one, so that user can e.g. add new levels or replace existing ones by their local content, without touching the root filesystem.

I second that, but in another step.

**Comment by Bertram25** [comment]
@akien-mageia I think you should create a first pull request with all your changes on the CMake script, so we can test them.
Once they're good enough, I do think the step afterward will be to make the binary auto cd to its data folder depending on the platform.
Once this is done, #57 will be trivial to do.

**Comment by akien-mga** [comment]
As you said there are two sides for this issue:
- [x] Make the code retrieve the data path from the cmake call and hardcode it at compilation time
- [ ] Write installation instructions in CMakeLists.txt

I think it would make more sense to do the code part first (maybe deciding upon the variable name that should be used), and then to write the installation instructions. It would save quite some work on the CMake files with regard to the launcher script and so on. WDYT? Is it something that could be easily implemented?

**Comment by Bertram25** [comment]
@akien-mga Hey :)

Just to make sure of. Is it something you're working on (sooner or later) since you wanted to package OD, or do you want to leave this out for now?

**Comment by akien-mga** [comment]
In the two points listed above:

> - Make the code retrieve the data path from the cmake call and hardcode it at compilation time
> - Write installation instructions in CMakeLists.txt

I thought you could handle the first one, and I would then cater to the second one :-)

**Comment by Bertram25** [comment]
> I thought you could handle the first one, and I would then cater to the second one :-)

Late answer, but ok, I'll add this on my todo list. :)

**Comment by Bertram25** [comment]
@akien-mga After checking the CMake file, `OPENDUNGEONS_DATA_PATH` is used to set where the data are meant to be installed:
https://github.com/OpenDungeons/OpenDungeons/blob/development/CMakeLists.txt#L515

Could you tell me whether adding `-DCMAKE_INSTALL_PREFIX="/usr"` in the cmake invocation is making something useful for you, at least speaking on installing the data?

**Comment by akien-mga** [comment]
@Bertram25 IIRC, it was only used to configure the resources_install.cfg file with the proper path. I had a WIP patch that adds system wide installation for Linux (but was not that well written in terms of cross-platform compatibility), I'll look for it.

**Comment by akien-mga** [comment]
Here it is, it's an enhanced version of https://github.com/OpenDungeons/OpenDungeons/blob/development/CMakeLists.txt#L530-L544

```
##################################
#### Installation ################
##################################

if(UNIX)
    set(OPENDUNGEONS_BINARIES ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_BINARY_NAME}
                              ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME_LOWERCASE})

    set(OPENDUNGEONS_CONFIGFILES ${CMAKE_CURRENT_BINARY_DIR}/plugins.cfg
                                 ${CMAKE_CURRENT_BINARY_DIR}/resources.cfg
                                 ${CMAKE_CURRENT_BINARY_DIR}/resources.zip.cfg)

    set(OPENDUNGEONS_RESOURCES ${CMAKE_SOURCE_DIR}/gui
                               ${CMAKE_SOURCE_DIR}/levels
                               ${CMAKE_SOURCE_DIR}/materials
                               ${CMAKE_SOURCE_DIR}/models
                               ${CMAKE_SOURCE_DIR}/music
                               ${CMAKE_SOURCE_DIR}/sounds)

    install(FILES ${OPENDUNGEONS_BINARIES} DESTINATION ${OPENDUNGEONS_BIN_DEST}
            PERMISSIONS OWNER_WRITE OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    install(FILES ${OPENDUNGEONS_CONFIGFILES} DESTINATION ${OPENDUNGEONS_DATA_DEST})
    install(DIRECTORY ${OPENDUNGEONS_RESOURCES} DESTINATION ${OPENDUNGEONS_DATA_DEST})
endif()
```

**Comment by akien-mga** [comment]
Basically on the code side, you would have to retrieve the value of OPENDUNGEONS_DATA_PATH and add it to a virtual filesystem of some sort, maybe together with the build directory (with a relative path), so that the game can still be run in the source tree on Linux and Windows.

Edit: This would be to fix #57, but both topics are closely related.

**Comment by Bertram25** [comment]
> Basically on the code side, you would have to retrieve the value of OPENDUNGEONS_DATA_PATH and add it to a virtual filesystem of some sort, maybe together with the build directory (with a relative path), so that the game can still be run in the source tree on Linux and Windows.

Ok, I think I'm mostly done with that. I'll add a patch asap.

**Comment by akien-mga** [comment]
Great! Then I'll have a look at refining my WIP for the system wide installation, and I won't hesitate to ask for some help if I can't do everything as I want it :-p

**Comment by Bertram25** [comment]
@akien-mga See #184 :)

**Comment by Bertram25** [comment]
Considered ok with #184 for system-wide use. I'll be on #25 now.

@akien-mga Still ok for the installation part? :)

**Comment by akien-mga** [comment]
Yep, assigning this one to myself now, you've done everything that I need for an easy system wide installation :-)
