### ISSUE TITLE
Do we use packs/OgreCore.zip?

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#580]
Does someone know what OgreCore.zip is, and if we use it at all? I thought it could be related to the Ogre startup config window, but removing packs/OgreCore.zip doesn't seem to affect starting and playing OD from my quick tests.

If we don't need it, can we remove it? That's already one folder less in our crowded root folder :-)

**Comment by oyvindln** [comment]
I looked at my own setup, and I haven't put it in my build folder, so I would assume it's unused leftovers from the ogre examples and safe to remove.

**Comment by Bertram25** [comment]
> I looked at my own setup, and I haven't put it in my build folder, so I would assume it's unused leftovers from the ogre examples and safe to remove.

Last time I compiled on MSVC, it was still requested to start. Let's ask @hwoarangmy whether the windows binary needs it.

**Comment by hwoarangmy** [comment]
I don't think so. Unless it is silently used and I didn't notice...
I will check asap

@Bertram25 when is it supposed to be used?

**Comment by Bertram25** [comment]
> @Bertram25 when is it supposed to be used?

Oops, just saw that, sorry. The pack is supposed to be used when displaying the Ogre config window (You can see an ogre head graphic as the window background which is part of that pack.)

**Comment by akien-mga** [comment]
Fixed by a59b159.
