### ISSUE TITLE
Do we use od.cppcheck and ogre.cfg?

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#581]
Yeah, you've got the gist of it, I like clean tree (I'm a bit of an environmentalist ;-)), so if we have unused files, I think we should do away with them.

**Comment by akien-mga** [comment]
od.cppcheck might still be used if some of use use cppcheck, but the contents are so basic that I wonder if it's something worth having in the git repo? Shouldn't we add it to .gitignore and let those of us who use it initialise their cppcheck project by telling it the source code is in source/?

As per ogre.cfg, the config file is now in mUserConfigPath, and I think it's generated on the fly by Ogre, so we don't need to keep the other one in the tree.

**Comment by oyvindln** [comment]
We are not using it right now, but we probably should. It may catch some bugs, and I think it's possible to integrate it to run automatically with cmake. It's only used for development though, it shouldn't need to be copied anywhere. Ogre.cfg should be deleted and put in .gitignore. No reason to keep that in the repo.

**Comment by Bertram25** [comment]
Ok to remove Ogre.cfg from repo and ignore it.
The cppcheck invocation script should maybe be moved into the new and shiny tools/ folder if still working?
Running cppcheck and valgrind should indeed be done from time to time, indeed but this is not actually an issue. so far, IMHO.

**Comment by akien-mga** [comment]
> The cppcheck invocation script should maybe be moved into the new and shiny tools/ folder if still working?

Sounds like a plan. I guess the paths to the source folder should be updated accordingly? i.e. s|source|../source| in https://github.com/OpenDungeons/OpenDungeons/blob/development/od.cppcheck

**Comment by akien-mga** [comment]
> Sounds like a plan. I guess the paths to the source folder should be updated accordingly? i.e. s|source|../source|

Or simply changing `<root name="."/>` to `<root name=".."/>` maybe.

**Comment by oyvindln** [comment]
Looking at how cppcheck is invoked, I don't think we really need to store the config for now.
