### ISSUE TITLE
Make the tile fullness concept more understandable (or alternatively drop the intermediate stages)

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#590]
_Edit:_ See the first two comments for a better description of the scope of this issue.

Currently the editor lets you switch between a tile fullness of 0%, 25%, 50%, 75% and 100%. This is very tiresome when you only want to switch between "wall" (100%) and "ground" (0%).
IIRC we stopped using the fullness distinction for value > 0. There is still a lot of code related to handling different levels of fullness it seems, but I guess cleaning it will be part of 0.6.0.

I guess we could fix the editor GUI part for 0.5.0 though.

**Comment by hwoarangmy** [comment]
Well, there is a difference with fullness. The higher the fullness is, the longer it will take for workers to dig and the less gold you will get if gold tiles. However, I agree it may be confusing and I am not against removing the fullnesses between 0 and 100.

**Comment by akien-mga** [comment]
> Well, there is a difference with fullness. The higher the fullness is, the longer it will take for workers to dig and the less gold you will get if gold tiles. However, I agree it may be confusing and I am not against removing the fullnesses between 0 and 100.

Ah that makes sense. I saw a recent commit where you put all wall tiles to fullness 100, so I thought we were no longer using the distinction.

Well actually the fullness concept as you describe it is interesting, we should probably not remove it. What we'd need is more to have different meshes depending on the fullness. It could be increasingly crackled dirt for dirt tiles (i.e. if you start digging and drop the fullness to 50% then leave, the tile would visually appear as partly dug/crackled) and less rich gold textures for gold tiles for example.

I'll rename the topic to make it a more general discussion on tile fullness then.

**Comment by hwoarangmy** [comment]
That was what was done in the first tileset but requires 5 mesh per tile type. To make things more simple (avoiding hundreds of combinations in the tileset) and because digging a 100 full tile is very fast, we dropped the visual concept.

**Comment by akien-mga** [comment]
Couldn't we use a decal of some sort to avoid avoid to use different meshes? If we could change the material script on the fly, and this way apply a different textures, we wouldn't have to care about tileset combinations.

**Comment by hwoarangmy** [comment]
IMO, tiles are digged too fast to make it worth the effort.

**Comment by Bertram25** [comment]
> IMO, tiles are digged too fast to make it worth the effort.

+1. What matters IMHO is that we can have different dig length for different tile type, like when a claimed walls is taking more time to dig than some dirt.
Yeah, let's remove the difference between 0 and 100 as people won't understand why a tile gives more gold than another anyway, since visually they are alike.

**Comment by Bertram25** [comment]
Yet, please keep in mind that we'll later want special tiles that can give a lot more gold out of them. (for single player purpose.)

**Comment by Danimal696** [comment]
+1 i never knew wht fullness meant;  

> Yet, please keep in mind that we'll later want special tiles that can give a lot more gold out of them. (for single player purpose.)

i propose a gem tile for that (besides the infinite gem mine structure)

**Comment by Bertram25** [comment]
@hwoarangmy Do you think it's possible to clean this now, so we don't have to think about it later?

**Comment by hwoarangmy** [comment]
ok
