### ISSUE TITLE
Editor: portals and dungeon temples can't be destroyed

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#595]
We should add support to delete (destroy) portals and dungeon temples when in the editor.

**Comment by hwoarangmy** [comment]
It is already there. You just have to use the sell button and sell the portal or dungeon. Is there an issue with that ?

**Comment by hwoarangmy** [comment]
@akien-mga I tested it yesterday after rebasing and it works. You just have to choose the destroy room icon and select the temple or portal you want to erase.

**Comment by akien-mga** [comment]
Indeed it seems to work now. I must have been doing something wrong last time :)
