### ISSUE TITLE
Add support for a entities catalog file.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#60]
Tiles, rooms, room objects, equipment, creatures and every 3D objects are entities loaded the same way by Ogre. And a lot of their parameter is hard-coded in different places.

In order to remove hard-coded parameters, make it more customizable, and help artists self-integrate their new art for testing, an entities catalog file is to be created listing the different parameters needed to make the entity properly shown in game. Then, the code will have to be adapted so that calling an entity name will suffice to get its parameters set through the catalog file.
This is also a pre-requisite of #14 and is also a pre-requisite in de-hard-coding the normal applied on models through the RenderManager:rtssTest() function, for instance.

The currently identified parameters are:
- Model filename
- Scaling factors (x, y, z)
- Normal texture filename to apply (optional)

Possible missing parameters (Probably done in another issue):
- Rotation fix factor (for when the default model isn't rotated like the standard ones.)
- Animation related parameters (such as creature actions, object triggering action name, ...)
- See also #34

**Comment by Bertram25** [comment]
Moving it to later, as it doesn't bring anything frankly visible for the next release. (But I'm still on it!)

**Comment by Bertram25** [comment]
Unassigned myself. I'll only keep assignment where I'm actual working on stuff. It's saner IMHO.

**Comment by oyvindln** [comment]
Not sure why I haven't seen this before, but in the example RTShader material files, it's shown how a normal map is supposed to be defined for the RTSS materials. I tested it on one material, and it worked, so normal maps shouldn't have to be defined in the catalog file.
https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/RTShaderLib/materials/RTShaderSystem.material#L110

**Comment by Bertram25** [comment]
@oyvindln If you're right, that would be good news. :)

Can you tell me exactly how you tested it? I'll then have a look at making sure every instance of the given object does have the normal applied, and we could move on with this.

**Comment by oyvindln** [comment]
I changed the Dirt material file like [this](https://gist.github.com/oyvindln/f79922f0a34f66a7aae3#file-dirt-material)

(It's the wrong normal map file, as there wasn't one for the dirt material.)

**Comment by Bertram25** [comment]
Np, the example is cool. I'll have a look at whether we could use that for everything. @Danimal696 would be so happy. ;)

**Comment by oyvindln** [comment]
If there are no problems with it, I suggest we edit the materials, and remove the hardcoded function that adds the normal maps.

**Comment by Bertram25** [comment]
> If there are no problems with it, I suggest we edit the materials, and remove the hardcoded function that adds the normal maps.

Yeah, I'm all for simplification in that area. I didn't take the time to check that, though. Wanna do it?

**Comment by Bertram25** [comment]
With all the development and the addition of the tileset being done. It appears this entities catalog file looks like being obsolete now.
Plus, I do have to say I prefer seeing config files without too much mandatory links between them.
I'd thus propose to close this issue as won't fix and open a new more relevant one if the need and the will appears. WDYT @oyvindln @akien-mga @hwoarangmy ?

**Comment by akien-mga** [comment]
Fine by me :)

**Comment by hwoarangmy** [comment]
I'm always for closing obsolete issues and recreate new ones more accurate if needed ^^
