### ISSUE TITLE
Too many parameters for material light values in material files

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#606]
```
Compiler error: fewer parameters expected in Hammock.material(21): ambient must have at most 4 parameters
```

This happens for a lot of materials. 
From #593.
Please check log before merging next time.

**Comment by akien-mga** [comment]
Ah indeed, I had noticed that the ambient field had 5 parameters instead of 4 previously, but I thought the 5th one was an optional parameter. Should have checked the logs indeed :)

**Comment by akien-mga** [comment]
I guess dropping the 5th argument on all materials scripts will do the trick.

**Comment by akien-mga** [comment]
For the reference, I fixed this issue with this little script:

```
for file in *; do
    if [ $(grep ambient $file | wc -w) = 6 ]; then
        sed -i '/ambient/s/ \S*$//' $file;
    fi
    if [ $(grep diffuse $file | wc -w) = 6 ]; then
        sed -i '/diffuse/s/ \S*$//' $file;
    fi
    if [ $(grep emissive $file | wc -w) = 6 ]; then
        sed -i '/emissive/s/ \S*$//' $file;
    fi
done
```
