### ISSUE TITLE
Alpha value for lighting parameters is often wrong, creatures change opacity when getting superposed

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#615]
The recent changes on materials introduced another regression (I guess I was a bit quick to merge them without checking the syntax), as the 4th setting for ambient, diffuse, specular and emissive should be the alpha parameter (i.e. transparency/opacity), but @Danimal696 often used the exact same value as for the first three parameters (red, green, blue).

**Comment by akien-mga** [comment]
Unless otherwise told, I'll be on setting 1.0 everywhere for this alpha parameter.

**Comment by Danimal696** [comment]
please do it, my sanity is going down with each new material issue

**Comment by Bertram25** [comment]
Yes, 1.0 is the default value anyway. Thanks for catching up this one.

**Comment by akien-mga** [comment]
Reference doc: http://www.ogre3d.org/docs/manual/manual_16.html
