### ISSUE TITLE
Portals should not spawn units when no more dungeon temple

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#618]
Since from now, portals are claimable, they continue spawning units even when the player is killed until someone claims the portal. Shouldn't we turn off spawning once the dungeon temple is killed ? After all, no creature would like to go to a dead dungeon...

**Comment by akien-mga** [comment]
I guess disabling them when they are claimed to a non-existing dungeon temple would be a good idea yes.

**Comment by Bertram25** [comment]
Makes sense. +1

**Comment by hwoarangmy** [comment]
ok. I will stop spawning once the player is dead then ^^
