### ISSUE TITLE
Add animation for dummies in the training room

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#62]
When training, creatures should go in the training room and attack dummies.

**Comment by Bertram25** [comment]
For info:
I do think the creature attack animation is or was once triggered there.
Also, the new training dummies have got the "Triggered" animation ready IIRC.

**Comment by hwoarangmy** [comment]
ok, I will have a look

**Comment by hwoarangmy** [comment]
I've seen in the code that room use is actually hardcoded in the creature behaviour (even training room). What do you think of trying to use object for that ? I mean creatures should have a tile for quarters, hatchery and working room (can be forge, training room, ...). As creatures are more generic than rooms, we could try to move the code that decide what to do into the room (to make the creature walk until the active spot and set the requested animation). This way, we could even have different behaviours on the same room.

**Comment by Bertram25** [comment]
It's hard to me to fully get what you mean without doing the job. ;)

Usually, the code resides in the object doing the action for more readability. Now, it depends on which one is actually triggering the action. If you think the code could be more simple, more readable or more extensible that way, just go ahead. :)

The diff will talk for you.

**Comment by hwoarangmy** [comment]
Usually, the code resides in the object doing the action for more readability
I agree but in this case, I believe that we might want the creature to have special behaviours depending on rooms. Some might allow several creatures to use the same spot from different positions, for example, and make them do coordinated actions. I think it will be a lot of switch case and the creature class will become big and unreadable. But in any case, we can always move the code if needed :)

**Comment by Bertram25** [comment]
Yeah, feel free to follow your instinct. I'm trusting your reasoning. :)

**Comment by hwoarangmy** [comment]
The training room seems to work but I have 2 issues :
1 - The dummies positions makes that creatures go one on the other while training. In fact, in a full room, we have dummies like (X=nothing and D=dummy) :
- XDX
- DDD
- XDX

To train on the ones on the wall, the creatures go all on the central tile (one over the other) and to train on the central tile, they go on the bottom dummy. Shall we re-arange the dummies ? We could do, for example :
- XXD
- XDX
- DXX

2 - Some creatures (at least the troll) have an attack animation that lasts more than 1 turn. As expected, it is cutted before the end. Should we ask the artist to have a maximum length for animation ? Or should we reserve 2 turns ? For now, the problem appears in the training room but I guess it will happen in other rooms too and maybe during fights

**Comment by Bertram25** [comment]
> 1 - The dummies positions makes that creatures go one on the other while training. In fact, in a full room, we have dummies like (X=nothing and D=dummy)

Good notice. It's true it is looking messy atm.
Note that the dummies position on borders should be set to be against the corresponding wall. I'm also not fond of changing the number of active spots (and room objects) without carefully thinking about different room shapes, game balance, ...
IMHO, the creatures should be able to go next to the dummy they are attacking without forcefully being on the center of the other tile (by adding an offset to their position.)
This, plus pushing the border dummies against the wall should help already if not fix the problem.

Feel free to tell me where I could be wrong, though. :)

> 2 - Some creatures (at least the troll) have an attack animation that lasts more than 1 turn. As expected, it is cutted before the end. Should we ask the artist to have a maximum length for animation ? Or should we reserve 2 turns ? For now, the problem appears in the training room but I guess it will happen in other rooms too and maybe during fights

IMHO, all that isn't the actual solution, even if I'm not asking you to fix everything at once, of course. :)
Later on, it is desired to add creature skills, obtained through leveling. The creatures will trigger their skills in battle and wait their corresponding cooldown to end.
The same principle should be done for the attack itself, IMO. I mean that the attack should have a duration (can be a parameter), and the creature can't attack and trigger the attack animation before that time has expired. See this as an attack time, or cooldown.

This way, we could have slower attackers dealing mortal blows, such as our nice golems. ;)

In the meanwhile, I truly don't care if the attack animation is cut, though.

What do you think?

**Comment by hwoarangmy** [comment]
> Note that the dummies position on borders should be set to be against the corresponding wall

Yes but they will always be in the tile in front of the wall, close to the creatures.

> I'm also not fond of changing the number of active spots (and room objects) without carefully thinking about different room shapes, game balance, ...

It's funny, I was thinking the exact opposite. In fact, we could imagine a room where there is only 1 active spot shared by the creatures (like a table game in casino). Having active spots common for every room is already not followed by existing rooms like portal and dungeon temple.
The hatchery will also not obey this rule.
To say the truth, I was even thinking of having a virtual function for updateActiveSpots and some protected fonctions in Room class to fill it for standard ways (like the actual one) so that functions not using spots may not have them.

> IMHO, the creatures should be able to go next to the dummy they are attacking without forcefully being on the center of the other tile (by adding an offset to their position.)

For having tested the dummy in the center attacked by a creature in the front tile, it looks pretty good. I have not tested having an offset to the creature position but I'm not sure it will look that nice. And from what I've seen in the code, it is not ready at all to support that. I can try to hack that tomorrow to see how it looks. We will see :)

> See this as an attack time, or cooldown.

Yes, that's a good idea. And it just means doing nothing so I agree :)

> In the meanwhile, I truly don't care if the attack animation is cut, though.

We agree :)

**Comment by Bertram25** [comment]
> It's funny, I was thinking the exact opposite. In fact, we could imagine a room where there is only 1 active spot shared by the creatures (like a table game in casino). Having active spots common for every room is already not followed by existing rooms like portal and dungeon temple.
> The hatchery will also not obey this rule.
> To say the truth, I was even thinking of having a virtual function for updateActiveSpots and some protected fonctions in Room class to fill it for standard ways (like the actual one) so that functions not using spots may not have them.

After thinking about it some more, here is the spirit: The number of active spots (the number of creature that can use the room at the same time) computation rules shouldn't change without being carefully thought, IMHO. (Note that I spoke of the number, not their position ;])
Now, if you can make something visually attractive while keeping the number correct, I'm ok with it.
If you can prove that number is too high/low for a room or another, I'm also ok for a corresponding change.

I wouldn't like to sound like some old bear not willing to change stuff out of a fashion (^^) while I wouldn't want a complete change of philosophy without proper reasons.

Best regards,

**Comment by hwoarangmy** [comment]
Ok. I was thinking of active spots as roomobjects, not as number of creatures. Then, I'm ok for the rule :)
FYI, I have seen a bug in the way activespots are handled since the server paradigm. I will make a function to update room objets independently from the room mesh.

**Comment by Bertram25** [comment]
Great! :)

**Comment by hwoarangmy** [comment]
I've tried to add an offset to the creatures position and, as expected, it is messy with big creatures. I'm gonna test it a bit more but I think the patch is ready.
Changing position was easier than expected but we can see it is not the expected behaviour (the creature seems to teleport when it is almost arrived)

**Comment by Bertram25** [comment]
>  (the creature seems to teleport when it is almost arrived)

Noted. thanks for the info. My turn to say sorry for the useless tests. :)

**Comment by hwoarangmy** [comment]
Well, for now, that's better than letting all creatures go on the center tile. I will let it as is so that everybody can test and we will see if it is ok or not.

**Comment by Bertram25** [comment]
Fixed with https://github.com/OpenDungeons/OpenDungeons/commit/ff9cf421534ec90247d608a73ecbc37f7dd71c2c and confirmed by @akien-mageia
