### ISSUE TITLE
Final balancing needs before release?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#624]
@akien-mga @hwoarangmy @Danimal696 @oyvindln 

Do we need some balancing obvious fixes before release and what would they be?

IMHO, the research points need to be 50 on first row, 75 on second, 87 on third, ... as a first start on tweaking.

The waves in Falling Keeper need tweakin even if I've got no idea what. ;)

Apart from that, and the last bugs to fix, we can release, IMHO.

Note:
Transfered all stuff to #418 to make sure most changes are gathered there (so it is easier to make the change log)

**Comment by Danimal696** [comment]
i would say: cheaper wages, less gold stored in each treasure room, reduce all creatures walking speed by a 10%, rise their working times in rooms, set armor increase value to 0.1 for all creatures and raise experience got in battle to be higher than in training room

**Comment by hwoarangmy** [comment]
Increasing research for higher level things makes sense.
I agree wages are too high and treasure rooms can have too much gold (almost no need to build more than 1 treasury).

Concerning waves in falling keeper, it may be too high but I've never really tried the level (unless playing alone to test the portal wave).

IMHO, we should try to set up a lan and try multiplayer ^^

**Comment by akien-mga** [comment]
So to sum up, we should:
- [x] Increase research points needed for higher level researches (50 for first row, 75 for second, 90 for third, 100 for fourth as a first try).
- [x] Decrease wages (say by 30%?)
- [x] Decrease amount of gold stored in each treasury tile (currently 5000, we can make it 2500)
- [x] Reduce creature walking speed by 10%
- [x] Set armor increase/level to 0.1 for all creatures
- [x] Raise gained experience from battle
- [x] Increase mana cost of Call to War
- [ ] Do something for falling keeper waves

About @Danimal696's "rise their working times in rooms", what do you mean exactly? Should we lower creatures' "working efficiency" (if we have such a parameter) or increase the needed research points and crafting points?

**Comment by Danimal696** [comment]
Hi, what i mean is that currently the game plays like its on crack/cocaine, everything is way too fast paced, its good for development but an actual gameplay will suffer from that pace.

There are some points to refine in there:
Walking speed -> too fast in general
Portal spawing time -> you get your dungeon full of critters in no time, increasing the time would be good so we can build some rooms and stop getting flies, also to value a bit more whatever creature you get - mitigated by deciding when you claim portal
Walls -> increase walling time, it should take way longer taking into account its a perfect fortress
Room work time-> its now way better than before actually, some time ago i felt creatures just worked a few seconds and then went to sleep/eat, i would say its an extension of lowering the pace
Gold-> i would even say 1000 per tile

**Comment by hwoarangmy** [comment]
I've updated the main text with the wanted changes. If you want to discuss something, please do not hesitate ^^

**Comment by Bertram25** [comment]
I'd say:
-25% on spawning speed.
+10% on xp when fighting (Let's tweak carefully this one)
Call to War cost x2
Claiming rate -15% but not less IMHO.
I'd request hitting an enemy creature gives a little bit of good mood back. But few.
WDYT?

**Comment by akien-mga** [comment]
Ok with your proposal @Bertram25, apart from the claiming rate reduction: IMO we should only reduce the wall claiming rate, and not the ground tiles claiming rate. Claimed ground is vital to be able to setup your base, and the current rate is good IMO, but as @Danimal696 said the claimed walls are too easy to get.
If we use the same rate for both ground and walls, then it's probably worth discussing whether we want to make a difference between the two.

**Comment by Bertram25** [comment]
Well, to be honest, I wouldn't change the claiming rates either, and aren't the claiming **times** different due to the tiles fullness?

Danimal says the game is too fast but it's not my own feeling, so I guess it's a matter of taste.

I would thus propose to try the requested change as an average speed value and later make the game speed a settings parameter.

**Comment by hwoarangmy** [comment]
Well, I must say that I agree with @Danimal696 concerning claiming wall speed. It is so fast that I sometimes manage to wall with 1 kobold while a hero worker is digging to my dungeon in the 2v2 skirmish test map...

**Comment by Bertram25** [comment]
Are we ok to look at reducing the wall claiming rate (but not the ground one yet)?

I'll update the list for the other items.

**Comment by hwoarangmy** [comment]
> Are we ok to look at reducing the wall claiming rate (but not the ground one yet)?

I am ^^

**Comment by hwoarangmy** [comment]
> I'd request hitting an enemy creature gives a little bit of good mood back. But few.

What about adding a variable in Creature class "time without battle" and using it in a mood modifier ?
That would allow to increase creature mood when fighting and to add a (big) negative mood modifier when not fighting for naturally aggressive creatures

**Comment by Bertram25** [comment]
Sounds good. :) And compatible with how the mood modifiers are implemented.
Ok to dissociate the wall claiming rate from ground one. But I'd say that the wall claiming rate should be something like 80% of the ground claiming rate to avoid creating yet another creature stat. WDYT?

**Comment by hwoarangmy** [comment]
> But I'd say that the wall claiming rate should be something like 80% of the ground claiming rate to avoid creating yet another creature stat

IMHO, it makes sense to use the same stat (if a worker is good at claiming ground, it is good at claiming walls). However, the penalty percentage may be in the config file to allow easy tweaking...

**Comment by akien-mga** [comment]
> > But I'd say that the wall claiming rate should be something like 80% of the ground claiming rate to avoid creating yet another creature stat
> 
> IMHO, it makes sense to use the same stat (if a worker is good at claiming ground, it is good at claiming walls). However, the penalty percentage may be in the config file to allow easy tweaking...

Yes to both :-)

**Comment by Bertram25** [comment]
+1 :)

**Comment by hwoarangmy** [comment]
I've copied what was decided to #418 so I close this issue
