### ISSUE TITLE
Claimed walls should be unclaimed when the temple is destroyed.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#630]
At least that's what I'm thinking, because it will permit to dig dead keepers/heroes walls, and rip their dungeon's content apart.

And you guys, WDYT?

I'm also tentatively setting this to 0.5.0 but as a non-bocker.

**Comment by hwoarangmy** [comment]
The problem with unclaiming dead keepers walls is that if you have common walls with an allied keeper and he dies, you will be exposed...

**Comment by Bertram25** [comment]
Arf, you're right. I've been thinking about this and the true solution is the spell that unclaim them all.
I'll close as invalid.
