### ISSUE TITLE
Segfault when attempting to load a saved game

### ISSUE THREAD

**Issue by lowerthanred** [OpenDungeons/OpenDungeons#635]
The crash occurs when clicking "Start game" (under the list of seats) after choosing the saved game from the list.
Backtrace: http://pastebin.com/8p2Jf7Gy
Saved game: http://www.mediafire.com/download/d45tnvj89l7wvns/2015-04-09_203337-SK-ScreamInTheDark.level

**Comment by akien-mga** [comment]
Just to clarify, was this saved game generated with the same OD version, or with a previous development snapshot? The saves are not necessarily compatible between versions since some stuff change in the way the saved content is handled.

**Comment by hwoarangmy** [comment]
I will give a try right now to see what's going on. Thanks for the feed back

**Comment by hwoarangmy** [comment]
Hmm, I can't even launch the saved game. Could you please tell us which version you played ?

**Comment by lowerthanred** [comment]
Yes, the saved game was generated with the same version (dev snapshot from April 9).
Yes, as the issue describes, the crash occurs before launching the game itself.

**Comment by hwoarangmy** [comment]
I've had a look. The bug is easy to fix but more important than I expected (somehow, I've broken map saving). I will release a fix in my next PR
