### ISSUE TITLE
Display level name instead of filename in configure seat screen

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#636]
As in the title.

**Comment by akien-mga** [comment]
Note that when #383 is implemented, we might want to add a marker that shows if the levels comes from a different paths that the game dir's levels/ folder.

**Comment by Bertram25** [comment]
@akien-mga You mean if the level is official or not, right?

**Comment by akien-mga** [comment]
> You mean if the level is official or not, right?

Yes. Or we could check the md5sum of the level to know if it's official, but I'm not sure we want to add md5sum as a dependency on windows ;)

**Comment by Bertram25** [comment]
I'd rather have SHA256 for instance, and there a few open-source c++ implementations we can borrow. ;) (I already did that for mana after all)

**Comment by Bertram25** [comment]
https://github.com/mana/mana/blob/master/src/utils/sha256.cpp for reference

**Comment by akien-mga** [comment]
Sounds good :)

**Comment by Bertram25** [comment]
The sha stuff will be for later and we'll open a new issue when we get there (after initial support for user content.)

For now, let's display the map inner title if possible.

**Comment by Bertram25** [comment]
Btw, the server does send the entire level info to clients now. So there is no need to checksum both level files anyway. The server should tell whether it's a custom level but that's a detail for later.
