### ISSUE TITLE
Possible enhancements for the chatbox

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#638]
Dumping the ideas I got when playing online today:
- Escape key in the chatbox should discard the message and close the chatbox. Currently it sends the typed message.
- Movement keys should be disabled in the chatbox (i.e. if you press "Left" to try to edit a message, it should not move the camera).
- It would be nice to be able to browse the chat history. Maybe record the chat and show a scrollbar when hovering the chatbox? Or only show the scrollbar when the user has toggled the chatbox to type something (i.e. chatbox on == scrollbar, chatbox off == no scrollbar).

**Comment by Bertram25** [comment]
I may do some for 0.5.0, but I'll let this for 0.6.0 ;)
