### ISSUE TITLE
Game play: Add 'skull flags' support over creatures

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#64]
![green half life](https://cloud.githubusercontent.com/assets/765917/3902441/e5b97f8e-22bd-11e4-9b12-29b6d7031063.png)

As described here:
http://forum.freegamedev.net/viewtopic.php?p=57403#p57403

the skull flag would describe a creature team color, health and level in a quick glance and would let the player take better decision upon battles, ...

The skull flag should be placed:
- Above the creature's head.
- Above all visible same-team creatures when you hold a key. (Shift) or when you mouse-hover one of them.
- The shield color, and level will appear and the color fill will represent the HP.
- When hurt, the flag shouldn't become transparent but rather as in the example image.
- I'd propose to use one flag image not changing per team. This image will be a seat parameter, permitting to add cool new flags, btw.

**Comment by Bertram25** [comment]
Ah, btw and for the record, I'd rather we use Ogre image layer for that rather than CEGUI's ones. CEGUI should be reserved for strict GUI handling if possible.

**Comment by Danimal696** [comment]
It should be possible to also change the image inside the flag to show something besides the skull like icons to show a creature mood

**Comment by hwoarangmy** [comment]
![odscreenshot_2015-02-23_230545_0](https://cloud.githubusercontent.com/assets/7493706/6338639/900c17ea-bbb0-11e4-94dc-6fe7ecbe968e.png)

I felt like fighting a little bit more with Ogre. Note that the skull flag is not exactly coloured the same everywhere. That's to show that if we use different materials, we can display health. WDYT ?

**Comment by Bertram25** [comment]
OMG, great! :D Congrats!!
What are the different health states you're displaying here?
Can't wait to see that in game!! :D 

As we are on this:
- I'd show automatically the skull flag of creatures that are currently fighting, and that are hurt (not at full health) as a first step.
- I'd only show every skull flag when holding the N key, not toggling it.
- Ah, and when you hover a creature.

What do you think about that logic?

**Comment by Danimal696** [comment]
Looking cool :D

**Comment by hwoarangmy** [comment]
Well, first, we need to decide how many health level do we want ? 4 or 5 (more would mean too many materials) ?
Then, yes, we can display that as we want. In any case, this is a client feature so the client can display it when he wants

**Comment by Bertram25** [comment]
> Well, first, we need to decide how many health level do we want ? 4 or 5 (more would mean too many materials) ?

4 sounds relevant for me. :) 
- Full health
- 3/4 a few scratches
- 1/2 definitely hurt
- 1/4 health panic

A fifth could be added for corpses though:
- 0 health dead. Waiting a for a crypt. ;)

**Comment by Bertram25** [comment]
In any case, this is a milestone reached in itself. :+1:

**Comment by Bertram25** [comment]
ah, and I just saw the 'you are under attack' ;)

**Comment by hwoarangmy** [comment]
ok. Then, let's go for 4 ^^

**Comment by hwoarangmy** [comment]
After thinking a bit about it, I think the best would be to have this states:
- Full health (IMO, that's the most important as it allows to see at a glance which creatures should sleep)
- 100% > hp >= 75%
- 75% > hp >= 50%
- 50% > hp >= 25%
- 25% > hp >= 0%

Which means 5 values. Concerning death, do we really want to display something different since there is already the animation ?

**Comment by Bertram25** [comment]
> Concerning death, do we really want to display something different since there is already the animation ?

Fine to me. + I must say corpses are more of an item than anything else in term of gameplay.

**Comment by hwoarangmy** [comment]
> I'd show automatically the skull flag of creatures that are currently fighting, and that are hurt (not at full health) as a first step.

On client side, creatures do not know if they are fighting or not. That would imply another message to warn them about it (and another to warn them they are not fighting anymore). Plus, I'm not sure that's what I would like to have (it can be messy with overlays everywhere). In the RTS I use to play: pressing a key to display health (it doesn't popup during fights).

> I'd only show every skull flag when holding the N key, not toggling it

ok

**Comment by akien-mga** [comment]
> I'd only show every skull flag when holding the N key, not toggling it.

How about using the Alt key for this instead of N (unless we already use it for something else)? It's easier to reach when you have the hand over WASD, and it would be at least a familiar key for players used to hack'n'slash RPGs like Diablo :)

**Comment by Danimal696** [comment]
yes, ALT sounds better

**Comment by hwoarangmy** [comment]
ok. Let's go for alt

**Comment by Bertram25** [comment]
> On client side, creatures do not know if they are fighting or not. That would imply another message to warn them about it (and another to warn them they are not fighting anymore). Plus, I'm not sure that's what I would like to have (it can be messy with overlays everywhere). In the RTS I use to play: pressing a key to display health (it doesn't popup during fights).

Sounds fair. Nevermind then. :) Let's test it with alt first. :D 
Teaser: Some GUI update incoming. Then, and only then, I'll be plugging the research tree. Mwahahaha.

**Comment by Bertram25** [comment]
New lighting support + new skull flag system + normals on rooms + FOW + research + ...
OMG, just try 0.4.9 again and you'll be shocked. :D

**Comment by akien-mga** [comment]
> New lighting support + new skull flag system + normals on rooms + FOW + research + ...
> OMG, just try 0.4.9 again and you'll be shocked. :D 

Indeed! And try 0.4.8 after playing 0.5.0... :-P

**Comment by Bertram25** [comment]
Yeah, I remember the main menu.
