### ISSUE TITLE
Can't connect after a failed connection attempt

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#640]
After a failed connection attempt (like when trying to join an already full game), it looks like some stuff stays badly initialised as one can't connect to another game, OD needs to be restarted first for it to work.

**Comment by Bertram25** [comment]
Tested locally after latest @hwoarangmy 's changes on setting the player with config support. It seems I'm able to connect to the host even after I first try to connect to a wrong IP or before the host has created the game.

Can you reproduce on your own?

What's still to be done IMHO, btw, is to see whether e can add a timeout on client connections attempts.

**Comment by Bertram25** [comment]
Ok, after adding https://github.com/Bertram25/OpenDungeons/commit/0dd0f45286537ae25c2da6d70d24299f8eec9cd7 , I can much more easily reproduce that bug.

I'll make a few tests.

**Comment by Bertram25** [comment]
I think I've got it. ;) Now, the Join button is functional even if the first joint attempt fails.
