### ISSUE TITLE
Monospace font for in-game chat

### ISSUE THREAD

**Issue by alketii** [OpenDungeons/OpenDungeons#642]
Monospace font for in-game chat since i think its better to read when you're playing, and not lot of time to read.

**Comment by Bertram25** [comment]
+1
I also wondered. Should we keep all the chat log for instance?

**Comment by akien-mga** [comment]
I'd like to have the chat log browsable in-game yes (and maybe saved to disk as chat.log or something?)

**Comment by hwoarangmy** [comment]
> I also wondered. Should we keep all the chat log for instance?

IMHO, it would be better

**Comment by Bertram25** [comment]
Ok, should we save the chat on request, or anytime?
Should newer games overwrite the old chat.log or append to it?

**Comment by Bertram25** [comment]
(Yes, I'll take that one for 0.6.0 ;})

**Comment by akien-mga** [comment]
> Ok, should we save the chat on request, or anytime?

I'd say anytime, but it should be probably be configurable in the settings menu.

> Should newer games overwrite the old chat.log or append to it?

Append to it IMO, as long as we only record player chat and not the other textboxes (creatures notifications, server notifications, etc.).

**Comment by Bertram25** [comment]
> Append to it IMO, as long as we only record player chat and not the other textboxes (creatures notifications, server notifications, etc.).

I've been thinking about this and I must say I'm not fond of setting up an ever-growing chat.log file.
I'd rather have it overwritten on each game. And why not, optionally disable its creation in the config.

Ok with it?

**Comment by akien-mga** [comment]
As you prefer, logging only the last game is also fine IMO. We're not an IRC client after all :)

**Comment by Bertram25** [comment]
k :)

**Comment by hwoarangmy** [comment]
yep. One game is enough.

**Comment by hwoarangmy** [comment]
BTW, I had not seen you were talking about a chat log. IMHO, that's not needed (unless you prefer to use a file instead of memory for storing chat messages).
In any case, I think it is better to be able to browse 1 game chat history (during the game).

**Comment by Bertram25** [comment]
I'm not needing a chat.log file either. I proposed to keep only the latest chat as @akien-mga seems fond of the idea.
Currently, the latest game chat history is viewable until the game's end, so if we don't add a chat log, then all the best for me. ;)
Shall we vote on what we want?
Chat log or no chat log, that is the question?
@oyvindln @Danimal696 ?

**Comment by akien-mga** [comment]
Well I'm not a strong advocate of keeping chat logs either, it's just that lately when tend to do some debugging in the ingame chat, so it could be useful to have the history right at hand. But I don't think it's a useful feature for players, and writing down bugs on a piece of paper as we encounter them is also just fine :-)

**Comment by Bertram25** [comment]
Ok, so more against, than for so far. I'll focus on adding the monospaced font for chat then.

**Comment by hwoarangmy** [comment]
Well, if it is just for debug purpose, we print chat messages received in ODClient in opendungeons.log

**Comment by Bertram25** [comment]
> Well, if it is just for debug purpose, we print chat messages received in ODClient in opendungeons.log

Pretty true, btw. k, I'll do that a comprise way.

**Comment by Bertram25** [comment]
@hwoarangmy While thinking about this, this could become pretty awkward when we'll ask the log to players. I guess we'll have to go with a separate file if any.

I'll close the issue for now (after my next PR's merge.). If a log is actually requested with proper grounds, we'll open a new issue. ;)
