### ISSUE TITLE
Lan: Remote clients shouldn't be able to call the save function.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#645]
Atm, clients are able to make the server save on the server's machine.
Only the local client should be able to do that.

**Comment by hwoarangmy** [comment]
Actually, I had already seen that but I think we shoould somehow handle in the server a way to choose which player is the "leader" ie the one that can change configuration.
ATM, in the seat lobby, we check if the server is connected. That works but assumes that the server is also a client. We should not make such assumptions. I will have a look if it is not too heavy
