### ISSUE TITLE
Add support for the Keeper's Hand cursor.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#65]
There is a model ready for that:
https://github.com/OpenDungeons/OpenDungeons/raw/development/models/Keeperhand.mesh

Later, adding support to slap own creature's to make them go quicker may be considered. ;)

**Comment by hwoarangmy** [comment]
I've had a look at the keeper hand but it seems to have problems with it. First, the skeleton file is wrong (can't remember the name but I had to rename it) and the only available animations are "Walk" and "Idle".
After renaming, the keeper hand is white. Maybe a missing texture ?

**Comment by Bertram25** [comment]
> After renaming, the keeper hand is white. Maybe a missing texture ?

Definitely, or a miss in a material file. The default system material name is WhiteBase, for the pure record, btw.

When looking at the material file, no doubt it's broken:
https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/scripts/Keeperhand.material

Try replacing the file content with this, for a start:

``` script
import RTSS/NormalMapping_MultiPass from "RTShaderSystem.material"
material Keeperhand RTSS/NormalMapping_MultiPass
{
    technique
    {
        pass
        {
            texture_unit decalmap
            {
                texture Keeperhand_colC.png
            }
        }
    }
}
```

We'll deal with normal and specular later.

**Comment by hwoarangmy** [comment]
ok. I will try that tonight. Thanks

**Comment by Bertram25** [comment]
Speaking of which, if we had the keeper hand back, we may take the opportunity to change/improve the tile selector as well. What do you think guys?

**Comment by akien-mga** [comment]
Yes, the tile selector definitely needs some tuning, it's sometimes hard to select a given tile due to perspective effects.

**Comment by Bertram25** [comment]
The default perspective also needs tweaking, you're right about it, but here I was speaking of pure graphics.
But you raised a valid point: I'll open an issue about it.

**Comment by hwoarangmy** [comment]
If we have a better tile selector, why not. But the current one is not that bad IMHO. The perspective effect @akien-mga is talking about is another problem ^^

**Comment by hwoarangmy** [comment]
I've had a look and it works by changing the material file. I tried to replace the cursor by the mesh but it seems to be a mess from what I've seen. DO you know if there is a way to display a mesh instead of the cursor ?

**Comment by Bertram25** [comment]
I remember some commented code about the keeper hand. But I can't put on hand on it atm...

**Comment by hwoarangmy** [comment]
BTW, shall I make a PR for what I've done on the keeper hand ? Currently, the slapped creatures do not work faster but they loose 20% of there max hp when slapped. That can allow at least to kill the creatures and display the hand...

**Comment by Bertram25** [comment]
> BTW, shall I make a PR for what I've done on the keeper hand ? Currently, the slapped creatures do not work faster but they loose 20% of there max hp when slapped. That can allow at least to kill the creatures and display the hand...

Lol :> Erm, I mean, how can you do that to those poor creatures...

IMHo, you can do a PR and we will see whether this can be integrated for the release. (This would be a nice last minute surprise ;])

**Comment by hwoarangmy** [comment]
ok. I will do that tonight after integrating yours as there will probably some conflicts. I've moved some code to GameEntity to allow more generic actions. Nothing big but as you changed pretty much this class, there might be conflicts. Since there are only 2 animations for the hand, I've used something that looks more like picking up than slapping but I guess it is better to have an animation for slapping than for picking up. When the model will be redone with proper animations, we can use them for other actions.

IMHO, it would be nice to integrate.

**Comment by Danimal696** [comment]
isnt 20% too much? 10% is more sensible

**Comment by hwoarangmy** [comment]
ok. I will add that in the config file then and will set it to 15% ;-) because I usually use it when i want to kill a creature so i prefer not to have to slap it for ages ^^

**Comment by hwoarangmy** [comment]
I've tried modifying the material for opacity and it works
I don't need your patch after all ^^
