### ISSUE TITLE
Regression - Goblin weapon is untextured

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#651]

**Comment by akien-mga** [comment]
Actually I think I never saw it textured even when I merge the PR where you introduced it. The mesh seems to link the good material "GoblinKnife", which links the good texture "GoblinKnife.png".

**Comment by akien-mga** [comment]
If I remove the normal component, I see some bits of texture, or at least the blade is not white but a mix of white and grey. Maybe the mesh does not reference the correct part of the texture file?

**Comment by Danimal696** [comment]
it worked before on ,materials seem to be ok, maybe the mesh upgrade did something to it? im checking as well

**Comment by Danimal696** [comment]
its working on the 29/03/15 release, thats it the one before the materials clean-up, im betting that the material name was changed but the mesh is still calling the older name, can you check?

**Comment by akien-mga** [comment]
I've checked the names and everything seems to be correct. I'll investigate this a bit deeper, maybe the mesh upgrade did something wrong as you say.

**Comment by Danimal696** [comment]
did the mesh call the correct material name? thats the only thing i cant check

**Comment by akien-mga** [comment]
Yep:
`<submesh material="GoblinKnife" usesharedvertices="true" use32bitindexes="false" operationtype="triangle_list">`
(that's from the XML version of the mesh)

**Comment by akien-mga** [comment]
You are right the texture is well displayed in the 29/03/15 release. This was before the whole material upgrade with added normals, I'll compare the material files to find what went wrong.

**Comment by akien-mga** [comment]
Ok I found the issue. It looks like you removed `tex_coord_set 1` in the texture_unit part of the material file: https://github.com/OpenDungeons/OpenDungeons/commit/91a5f27fa521b6fa1cba838b65ed0eac9a92c229#diff-c7476a08969ea16055ffc7e967122081
Adding it back solves the issue.

**Comment by Danimal696** [comment]
My bad, thanks for the fix :)
