### ISSUE TITLE
Skirmish - Configuring seats: The player 'Player' can be put two times.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#659]
How to reproduce:
Select 'Scream in the Dark...' in Skirmish mode.
Then, make the Local Player be on seat 5 for instance. The Seat 1 is left empty.
Select the Seat 1 and put back 'Player'.

'Player' is then on both seats as seen here:
![od-bug1](https://cloud.githubusercontent.com/assets/765917/7103161/8f24d4ac-e09a-11e4-931a-afa2b10fad07.png)

Starting the game leads (obviously) to a crash.

**Comment by akien-mga** [comment]
I can confirm the issue, actually Player can be added in all seats :)
There is no issue on Greed or Might where all seats are defined as "Choice". On the other hand, Scream in the Dark has all seats predefined, so the player should not be able to change them.

I guess it's a regression from c5c3f08.

**Comment by hwoarangmy** [comment]
k. I will have a look

**Comment by Bertram25** [comment]
Thanks, I was on something else. ;)

**Comment by hwoarangmy** [comment]
k. I've seen that the problem is that seats forced to AI/Inactive seem to be usable. If you try a level that allows players (like 2v2 multiplayer), it works. I will make a fix soon
