### ISSUE TITLE
Unwanted texture addition when several similar creatures are on top of each other

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#660]
When some similar creatures are in the exact same position on the exact same tile (and with the current AI, it actually opens relatively often), it looks like their textures are superimposed additively, as if the models were semitransparent.

This screenshot speaks better than words:
![lizards](https://cloud.githubusercontent.com/assets/4701338/7103352/f587e07e-e0a2-11e4-87d0-1cbcb5429466.jpg)
From left to right, there are: 1 lizardman, 2 lizardmen on the same tile, 3 lizardmen on the same tile and 4 lizardmen on the same tile.

**Comment by akien-mga** [comment]
The effect is similar if I disable the normal texture, so that's not the culprit.

**Comment by akien-mga** [comment]
Actually if I remove all references to the RTShaderSystem from the material script, the bug disappears.

**Comment by Bertram25** [comment]
Pinging @oyvindln .

IMHO, this may be more a feature than a bug but you're right, it is always better to report anyway.
I'll set this to 0.6.0 as I don't see any "easy" way to get rid of this for now.

**Comment by Danimal696** [comment]
didnt we talk about offseting creatures into the same tile so they dont visually merge into one?

**Comment by Bertram25** [comment]
Yes, we did. I'll open a new issue about that if nobody does it before me. Nice catch.
Also, I'll be honest, I don't think we'll fix this issue unless @oyvindln has got some trick about it even if I do think this issue is relevant. :)
Hopefully, @Danimal696 point will help minimize this one.
