### ISSUE TITLE
Dedicated server

### ISSUE THREAD

**Issue by Wout-van-Dongen** [OpenDungeons/OpenDungeons#665]
Would it be possible to add in a "dedicated server" feature to OD so that games/maps can be hosted on an external machine?

**Comment by hwoarangmy** [comment]
Yes. That's something I was already thinking of bitting but I am waiting for the 0.5.0 to be ready.

**Comment by Bertram25** [comment]
The beginnings of a server lobby? :)

**Comment by hwoarangmy** [comment]
BTW, @Wout-van-Dongen What do you have in mind ?
For my part, I was thinking about allowing to let a server alone probably by allowing to launch OD with command parameters to open a server and launch a game. Then, clients would be allowed to connect.

**Comment by hwoarangmy** [comment]
Fixed by #775
