### ISSUE TITLE
Add a human readable changelog / release notes

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#668]
It would be nice to have a changelog in-tree, so that distro packagers could add it as a documentation file in their packages and we could also include it in our binary releases for curious users.

Seeing how much progress we're doing might motivate some users to get involved in the team :)

Slightly related, we might also need a "distribution" README, i.e. not an explanation of the repo organisation like the current one but more a detailed presentation of the game, maybe a link to the tutorial video, etc. This README could live in dist/ and replace the code-focused README in binary releases.

**Comment by Bertram25** [comment]
I must say that for the sake of simplicity, I'd do all that in the news and why not git shortlog for the rest + minor cleanups of its output.

WDYT?

**Comment by akien-mga** [comment]
Hm I'm not sure about git shortlog, that's not really what I would like to read as a player. If people are interested in the git history, browsing github is way better than a static version of the shortlog IMO.

What I had in mind is more a text file version of the 0.5.0 "what's new?" that we'll base on the content of #418.

**Comment by Bertram25** [comment]
> What I had in mind is more a text file version of the 0.5.0 "what's new?" that we'll base on the content of #418.

Ah sure :) But still, I wouldn't bother adding a distribution README and rather point to the what's new of the website.

As for the dynamic page, we could use the compage page of github: https://help.github.com/articles/comparing-commits-across-time/

WDYT? :)

**Comment by Bertram25** [comment]
Ah seems we got @akien-mga on the case. ;)

**Comment by akien-mga** [comment]
What would be a good name for this file? It won't be a changelog strictly speaking, I just want to name the new features and important bug fixes as we do in release announcements, not give a complete commit history.

It could be: CHANGES, NEWS, CHANGELOG, RELEASE-NOTES, or one of those with .txt or .md at the end, depending on the formatting we want to use and if we want to make the files easy to open on Windows.

_Edit:_ I haven't checked if recent Windows still rely only on file extensions to determine the mime type or if it's become more clever :)

**Comment by hwoarangmy** [comment]
I would vote for release notes. That's pretty generic and can fit with almost everything (be it a full change log or not).
AFAIK, windows only rely on extensions. I've no win8 or win10 to test, however.

**Comment by Bertram25** [comment]
Agreed for release notes. And linux doesn't mind a .txt so let's be open and add it for Windowsians?

**Comment by akien-mga** [comment]
> Agreed for release notes. And linux doesn't mind a .txt so let's be open and add it for Windowsians?

Yeah I'm trying not to be too sectarian ;-)
I'll go with .md if that's fine with you, so that we can have a nice display on GitHub. I'll make sure not too use too much Markdown formatting though apart from titles and such, so that it stays easily readable in a text editor.

**Comment by akien-mga** [comment]
I think I'll also rework the README afterwards, switch it to Markdown and make a better distinction between contribution-related stuff and end-user content.

**Comment by Bertram25** [comment]
Fine by me. :)

**Comment by akien-mga** [comment]
Fixed by #679.
The only thing left to do will be to add the actual release date in the release notes.
