### ISSUE TITLE
Seat colors : Seat 5 is too close from Seat 1.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#672]
Very visible when playing Scream in the Dark...

**Comment by akien-mga** [comment]
That's the kind of change that we could easily make for 0.5.0 IMO.

**Comment by akien-mga** [comment]
I've made the colour of seat 5 more orange-ish to be distinct from the dark red of seat 1. Then I've made seat 7 purple instead of gold previously, since it would be too close to the orange of seat 5. And seat 8 is now pink instead of purple :)
