### ISSUE TITLE
The news have no date.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#676]
The 0.4.9 news should have a small indication of its date.
The next one too. :)

**Comment by akien-mga** [comment]
I agree. This can probably be made right now with a hardcoded date.
I'll discuss his plans with @Wout-van-Dongen, personally I'd like to split the main page into several static pages sharing the same menu: News (main page), Downloads, The project.
And then news should be made more "blog-like" indeed.

**Comment by Bertram25** [comment]
Cool. I think we'll also need some kind of "What is OD?" page once the split is done. :)

**Comment by Bertram25** [comment]
Fixed with https://github.com/OpenDungeons/opendungeons.github.io/commit/c071021d04d365590f9a1f421bf9e13260473087
