### ISSUE TITLE
Update or drop the FAQ.txt

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#677]
As says the title. It's partly outdated right now, and the formatting and English could use some love. IMO we should either update it (and maybe move it to the wiki), or drop it depending on whether it's still relevant for us or not.

**Comment by akien-mga** [comment]
Setting to 0.5.0 milestone but if we haven't reached a decision before publishing 0.5.0, that's fine by me :)
So definitely not a blocker.

**Comment by Bertram25** [comment]
I'd be to move the useful content from it to the wiki, so we can centralize documentation, at least until the game features are more or less in place.

**Comment by akien-mga** [comment]
I agree. I'll have a look at what's salvageable then :-p

**Comment by hwoarangmy** [comment]
I agree the wiki seems a pretty good place for a FAQ...
