### ISSUE TITLE
Screenshots for the release announcement

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#678]
We're about to release OD 0.5.0, and for that we'll need some good screenshots to show our game. @Wout-van-Dongen is planning a "media" page on the website to hold screenshots, so we might need a good deal of them, but the focus should be first on 2-3 really neat screenshots for the release announcement IMO.

@Danimal696 Do you think you could make a new "showcase" image similar to the family photo you did a while back? http://forum.freegamedev.net/download/file.php?id=8895&mode=view
It would be nice if there could also be some of the great new room models, e.g. we could see one creature working on a workshop table, etc. So basically not just an in-game screenshot but slightly-scenarised custom rendering of our most awesome models :)

**Comment by Danimal696** [comment]
ok, i can try, give me some time

**Comment by akien-mga** [comment]
Here are some first screenshots, feel free to propose yours :)

![screen1](https://cloud.githubusercontent.com/assets/4701338/7219594/b5659bac-e6a7-11e4-8859-b53591adf536.jpg)
![screen2](https://cloud.githubusercontent.com/assets/4701338/7219595/b75e42b0-e6a7-11e4-8001-a65d10cb982e.jpg)
![screen3](https://cloud.githubusercontent.com/assets/4701338/7219596/b956685e-e6a7-11e4-9a98-99b58079b08d.jpg)
![screen4](https://cloud.githubusercontent.com/assets/4701338/7219598/bb338fe4-e6a7-11e4-8945-f363c6f03de1.jpg)
![screen5](https://cloud.githubusercontent.com/assets/4701338/7219599/bd273d5a-e6a7-11e4-8262-24f2017bb413.jpg)
![screen6](https://cloud.githubusercontent.com/assets/4701338/7219600/beed1fce-e6a7-11e4-9237-d41b7607c15e.jpg)
![screen7](https://cloud.githubusercontent.com/assets/4701338/7219602/c105bde8-e6a7-11e4-8ff0-a6c7eb070bce.jpg)
![screen8](https://cloud.githubusercontent.com/assets/4701338/7219603/c2982092-e6a7-11e4-87d2-e0b9de270515.jpg)

**Comment by Danimal696** [comment]
not bad at all; i had to make a report for the uni this weekend so i didnt progress much, but expect them soon, tomorrow at most. I also like that map a lot, its pretty well done

**Comment by Bertram25** [comment]
@akien-mga About the release notes. Will the screen shots be part of it?
Did you want to add another page about the game itself or something?
Just tell me and I'll try to help as much as I can. :)

**Comment by akien-mga** [comment]
> Will the screen shots be part of it?

Not necessarily all of them, but we definitely need to add some visuals to the release announcement. Maybe a couple of screenshots, and the treat that @Danimal696 is cooking for us right now :)

> Did you want to add another page about the game itself or something?

That would be the plan, but IMO we should first publish the new version, and in the short to middle term, work on improving the website. We'll never get this release out if we try to get everything perfect before :-)

**Comment by Bertram25** [comment]
> That would be the plan, but IMO we should first publish the new version, and in the short to middle term, work on improving the website. We'll never get this release out if we try to get everything perfect before :-)

Thinking the same actually. :) Yet, I'm ok if someone see something in need of love, just as you did for the doc.

> Not necessarily all of them, but we definitely need to add some visuals to the release announcement. Maybe a couple of screenshots, and the treat that @Danimal696 is cooking for us right now :)

Ok, I'll make something and use one or two of them. Then, you'll be able to tell me what's wrong about it.

**Comment by Danimal696** [comment]
Do you want them zipped or will get them from here?
![showcase1](https://cloud.githubusercontent.com/assets/8299756/7230508/ebd6fc2c-e76e-11e4-90b4-c43ba4d863d9.png)

**Comment by akien-mga** [comment]
Wow @Danimal696 this is looking freaking awesome! :-D

If you can confirm that the screenshot are in full resolution on GitHub, then it's okay to link them here (what I can download now is 960x540 px).

**Comment by Danimal696** [comment]
do you want it in 1920? i lowered resolution in case it was too big, a second one is in the oven rigth now; i feel like we are cheating by showing this :-P

**Comment by akien-mga** [comment]
Yeah please send them to me in full resolution too at: rverschelde ::at:: gmail ::dot:: com.
We'll probably use the lower res ones for the release announcement, but the high res ones could be used for other stuff too, e.g. @eugeneloza's trailer or maybe official OD wallpapers to put on our website :)

**Comment by Danimal696** [comment]
the zip is heavy, 20 mb, here a smaller version of the second one, in the future these will look cooler with more creatures in :D
![showcase2mini](https://cloud.githubusercontent.com/assets/8299756/7233153/e912a958-e77f-11e4-89bf-6728832abb37.png)

**Comment by Bertram25** [comment]
> or maybe official OD wallpapers to put on our website :)

:D

**Comment by akien-mga** [comment]
I had an interesting discussion with some Lutris guys who thought that those awesome Blender renderings could be seen as in-game renderings by people who don't know OD, and thus they could be disappointed that the game does not look like that "for real".

So for the Lutris page I added the logo + a small line to make it crystal clear that those are not in-game renderings (even though I hope our in-game fights will look that awesome one day!): https://lutris.net/games/opendungeons/

For the release announcement however, I'm not sure we need to bother with adding this warning, it's pretty expected there to see custom artwork IMO.

**Comment by Bertram25** [comment]
Screenshots are there. @akien-mga I'll let you close this one when you think it's ok about it.

**Comment by Bertram25** [comment]
> For the release announcement however, I'm not sure we need to bother with adding this warning, it's pretty expected there to see custom artwork IMO.

Yeah, it's pretty clear, IMHO.
