### ISSUE TITLE
Spell logic

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#683]
To summarize what has been said:
- Spells should have a cooldown after casting (displayed on the text near the keeper hand)
- Spell cost should be per target (depending on spell type, can be allied allied claimed tiles, allied creatures, enemy creatures, ...)
- If a spell is cast on several targets but there is not enough mana for all, it should be cast randomly on affected targets until there is no mana left. For example, if a summon worker spell is cast on 5 tiles but there is mana for only 2 workers, 2 should be summoned on 2 of the 5 selected tiles (choosen randomly)

**Comment by Bertram25** [comment]
DK had it IIRC. Mana cost and cooldown, and certain spells didn't have any cooldown.
My opinion is thatif we have an example of spell where a cooldown is needed, then it's relevant.

Should we be able to spam healing, or spam lightning casting, for instance?

**Comment by hwoarangmy** [comment]
> Should we be able to spam healing, or spam lightning casting, for instance?

That's the question ;-)

**Comment by akien-mga** [comment]
IMO we need to implement cooldown, because it's an easy way to balance the game without having to rely solely on mana cost. If there was no cooldown for e.g. a lighting spell that strikes enemy creatures, we would need to make it _really_ expensive to prevent players from being able to cast it 10 times in a row if they accumulated enough mana.

**Comment by hwoarangmy** [comment]
I agree for the cooldown. @Bertram25 If we go for cooldown, do you know if there is some way to have the button background color it self as a progress bar to display cooldown ?

**Comment by Bertram25** [comment]
> @Bertram25 If we go for cooldown, do you know if there is some way to have the button background color it self as a progress bar to display cooldown ?

Maybe by creating a widget in the look'n'feel that is composed of a button and a progressbar.
Yet, that's all theory for now. I'll have a look and if I'm helpless, I'll ask on cegui forums.

**Comment by hwoarangmy** [comment]
> Maybe by creating a widget in the look'n'feel that is composed of a button and a progressbar.
> Yet, that's all theory for now. I'll have a look and if I'm helpless, I'll ask on cegui forums.

Well, as a first step, we could display cooldown time in the selected action text (displayed near the keeper hand).
- Should we be able to cast spells on many tiles (like healing or firebolt). If so, will the mana cost be 1 per selected tile or 1 per tile where there will be an effect (for example, if we cast healing on an array of 5 tiles with 2 creatures, will the price be 5 or 2?). It could also be 1 per affected creature (in this case, casting a heal spell on a tile free of creature would have no effect).
- If we choose a per tile cost, what should we do if a spell is cast on tiles with several creatures ?

IMHO, a per effect cost is better (ie if you cast heal on 25 tiles where there are 3 creatures, the price should be 3). And if you don't have enough mana for all creatures, it sould affect creatures until no more mana is left).

@Bertram25 @akien-mga @Danimal696 @oyvindln @eugeneloza WDYT ?

**Comment by Danimal696** [comment]
> IMHO, a per effect cost is better (ie if you cast heal on 25 tiles where there are 3 creatures, the price should be 3). And if you don't have enough mana for all creatures, it sould affect creatures until no more mana is left).

I prefer this one, making games too punitive its not a good idea

**Comment by Bertram25** [comment]
> It could also be 1 per affected creature (in this case, casting a heal spell on a tile free of creature would have no effect).

+1 too, a per target effect. While, I would add that if the player triggers the spell in the middle of nowhere, the cooldown should trigger. So he knows he'd better aim next time. ;)

**Comment by Bertram25** [comment]
> > Maybe by creating a widget in the look'n'feel that is composed of a button and a progressbar.
> > Yet, that's all theory for now. I'll have a look and if I'm helpless, I'll ask on cegui forums.
> 
> Well, as a first step, we could display cooldown time in the selected action text (displayed near the keeper hand).

Yep, in any case, I'll make sure to add text support to the button type used. :)

But I wanted to tell that I've witnessed a button behaving the way you want in TorchLight II (which is using CEGUI 0.7.x). By opening a few files, I've noticed nothing relevant in the look'n'feel but I couldn't open the layout files as they have an unknown (and non-standard) encoding.
I'll open a new topic on CEGUI shortly. ;)
EDIT: done: http://cegui.org.uk/forum/viewtopic.php?f=10&t=7021

**Comment by hwoarangmy** [comment]
@Bertram25 I've followed your tuto about icons to create spells buttons but it seems you do not use "Rock.png" for them as they look pretty different from the other ones. Could you please tell me which one do you use for the current icons ?

**Comment by Bertram25** [comment]
Ah, funny, I'm actually using that one: https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/textures/Rock.png

Have you made sure to increase the lighting/decrease saturation of the rock texture layer above the icon before inverting colors for instance?
If the tuto happens to be vague, I'll add here an image of the result per step, so you get an idea where things got wrong.

**Comment by hwoarangmy** [comment]
Yep, I had forgotten the opacity step ^^
It's good now

**Comment by Bertram25** [comment]
After some research, it seems they are likely to use a child widget (such as a staticImage) to buttons and setting its opacity and area through the code to show the cooldown.

Once your PR is in, I'll open an issue to myself so I don't forget to test that. :)
