### ISSUE TITLE
Key to hide keeper hand and tile selector

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#684]
This could come in handy when taking screenshots of the game without having the tile selector in the picture :)

**Comment by hwoarangmy** [comment]
Should not be very hard. However, a console command might not be the best suited. That's a client side command to do client side stuff (that do not impact the game). IMHO, a keyboard key (like FXX) is more suited.

**Comment by Bertram25** [comment]
> IMHO, a keyboard key (like FXX) is more suited.

+1
