### ISSUE TITLE
Add command-line options

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#688]
This would be useful for quickly changing between settings, particularly when developing, e.g to test keyboard grab. Boost has a [nice library](http://www.boost.org/doc/libs/1_58_0/doc/html/program_options.html) for this.

**Comment by hwoarangmy** [comment]
I've had a quick look at the boost library and it seems pretty nice. For my part, I've always tried to not cache ConfigManager values and most of the code I've reviewed does the same. So, using such a library should be pretty straight forward to change settings at runtime.
IMHO, you can feel free to use that if you want to.

**Comment by Bertram25** [comment]
Hey,

Before doing this, I'd request more use cases. ;) Why? Because: 1. I'm Evil, and 2. because I wouldn't want you to invest time on this without a clear view of what we want.

**Comment by hwoarangmy** [comment]
From what I've read, it is a replacement/enhancement for the ConfigManager allowing to change config values at runtime (avoiding to have to quit/launch OD to change a config value). That would allow, for example, to change the max number of creatures at runtime (for debug purposes).
@oyvindln Please correct me if I'm wrong or if it isn't what you had in mind ^^

**Comment by oyvindln** [comment]
By command line options I meant adding options when starting, e.g:
`opendungeons --no-keyboard-grab`

**Comment by akien-mga** [comment]
I guess what @Bertram25 would like is more examples of the options we would like to support.
Once we've added the options in the in-game menu and possibly got rid of the Ogre launcher, we'll probably want to be able to override at least some graphics-related options from the command line, like:
- renderer
- fullscreen
- resolution
  So that if the game can't start in fullscreen for example, or if it starts windowed with a bigger resolution than the monitor, it can be worked around easily.

We shouldn't overdo it though, if everything can already be configured via the settings menu, we probably don't need to add command-line equivalents for all options.

**Comment by oyvindln** [comment]
It would be mainly for things that may require the settings to be done before starting, like graphics, as stated. 
Other useful feature this could be useful for would be setting the logging level, and specifying alternate paths for resources/data.

**Comment by hwoarangmy** [comment]
Seems like I've read too fast. If it doesn't allow to modify parameters at runtime, I'm not sure it is that usefull. However, if it doesn't imply linking with another library and it is usefull for you, I wouldn't be against if you want to go for it.
The hardest part will be to convince @Bertram25 ^^

**Comment by akien-mga** [comment]
>  Other useful feature this could be useful for would be setting the logging level, and specifying alternate paths for resources/data.

+1
Also setting the log file and stuff like that.

**Comment by Bertram25** [comment]
k, indeed, I wasn't asking about how to use the command line but have a few example explaining why you need it in the first place. :)
To make things clear, I wasn't mistrusting or anything, I'm just trying to make everyone specify the need before entering the code battle arena. As usual. ;)
I'd also add the help function listing all the commands. @oyvindln I guess you'll want to do it a bit like we did for the console?

**Comment by hwoarangmy** [comment]
In any case, using command line options is, IMHO, required. The question is more to use boost or not for that.
The main reason I can see is to allow to start OD in standalone server mode (and passing a level that would be open automatically).
Another good thing would be to force the log filename to allow splitting logs when debugging and using the same computer for client and server.

**Comment by Bertram25** [comment]
+1 for the use of boost. We're extensively using it already, anyway, and the lib looks fantastic. :)

**Comment by akien-mga** [comment]
Since we are already relying on a good deal of boost libraries, I don't see a reason not to continue this way. At least for people who would like to build OD, if they have boost headers, they most likely have the whole of the boost libraries installed.

**Comment by hwoarangmy** [comment]
@oyvindln Are you on this one ? It looks like a prerequisite to allowing to use command line option to launch OD in server mode.

**Comment by oyvindln** [comment]
Nope, I'm not really active on the project at all for the time being.
