### ISSUE TITLE
0.5.0 libstdc++-6.dll runtime error

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#689]
Got this message yesterday when trying to run 0.5.0
https://www.dropbox.com/sh/58sm1t97etbdaf2/AAD4bmDFpF96rgz2ugRil4Aba?dl=0 (temporary link)
I'm a fraid I couldn't attach the files here for some reason.

**Comment by akien-mga** [comment]
@Bertram25 had to make a new Win32 build to fix a similar error yesterday, could you check whether you are using the new build or the previous one? https://sourceforge.net/projects/opendungeons/files/

If you are using the old build, it should be lacking libCEGUIExpatParser.dll among others.

**Comment by eugeneloza** [comment]
I've been using one from freegamedev link (at ~12:00 GMT+2)
OpenDungeons-0.5.0-Win32.zip from http://sourceforge.net/projects/opendungeons/files/

**Comment by akien-mga** [comment]
Yeah so 12:00 GMT+2 would be before the new OpenDungeons-0.5.0-Win32.zip which was uploaded around 17:00 CEST. Could you try that one?

**Comment by eugeneloza** [comment]
Yes... but I'm on a conference now... the internet is absolutely awful here :D

**Comment by Bertram25** [comment]
Yeah, sorry again for the three-time upload for the release. It was my first MingW OD binary. ;)
The newest zip has now all necessary deps. :)

**Comment by Bertram25** [comment]
Ah, just tell if it's ok now. :)

**Comment by eugeneloza** [comment]
I've downloaded the latest variant and it's working! :)
