### ISSUE TITLE
RectLayoutManager - is it used for anything?

### ISSUE THREAD

**Issue by oyvindln** [OpenDungeons/OpenDungeons#690]
This class/header isn't included anywhere. Is it supposed to be used for anything? Otherwise it should be removed.

**Comment by Bertram25** [comment]
Hey @oyvindln . IIRC, @hwoarangmy created this class to manage Skull Flags as billboards. I can't tell more and I guess he'll answer when he's back from holidays? ;)

**Comment by hwoarangmy** [comment]
@Bertram25 is right, that's a remaining from skull flags. Actually, that's code I had downloaded to test overlays and it wasn't expected to be pushed to OD. If you want to remove it, please assign this issue and do so. Otherwise, I will do it when I'm back. Sorry for not cleaning my mess.
