### ISSUE TITLE
Tileset: Lava and water animation is broken due to tiles mesh rotation.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#694]
As displayed below:
![od-bug4](https://cloud.githubusercontent.com/assets/765917/7325931/05b43c76-eac2-11e4-8a22-a01620e60b53.png)
This is more visible live, of course.

Should we reuse certain deleted models?
Useful progression forum link:
http://forum.freegamedev.net/viewtopic.php?p=64465#p64465

**Comment by Bertram25** [comment]
@Danimal696 Hey,

To fix this one, (and finally have a good looking default tileset), do you think you could recreate the lava borders tiles with differently rotated lava textures?
This way we could fix the tileset config to get the desired result.
@hwoarangmy @akien-mga @oyvindln Are you ok with my proposal?

**Comment by Danimal696** [comment]
we would need to add more tiles then (4 for lava + 4 for water) since we are just using the same one but rotated, no big problem but someone will have to modify the config file afterwards to included them

**Comment by hwoarangmy** [comment]
@Danimal696 if you want, I can handle this one

**Comment by Danimal696** [comment]
please do, but bear in mind to use the fixed tiles

**Comment by hwoarangmy** [comment]
@Danimal696 Sorry, I've had a look but rotating the material doesn't work when there is an animation. Could you please do it ?

**Comment by Danimal696** [comment]
ok

**Comment by akien-mga** [comment]
Isn't there a way to handle the animation as a particle effect or something similar, so that we don't have to make sure every mesh orientation matches the overall animation?

**Comment by Bertram25** [comment]
The problem is the "ground" texture orientation (The texture flat part). Animated or not. 
If you look carefully, dirt and gold tiles are also affected.
But we can later add particles on lava. :)

**Comment by akien-mga** [comment]
> The problem is the "ground" texture orientation (The texture flat part). Animated or not.
> If you look carefully, dirt and gold tiles are also affected.

I'm not sure I see what you mean. I thought the problem in this bug report is that the water and lava tiles have a texture animation, and the rotated meshes on the edges break the flow by making the animation transversal or backwards.

**Comment by Bertram25** [comment]
> I'm not sure I see what you mean. I thought the problem in this bug report is that the water and lava tiles have a texture animation, and the rotated meshes on the edges break the flow by making the animation transversal or backwards.

Unfortunately, not only. the animation makes the problem more visible, but rotated tiles have got the same problem of textures being not seamless.
I'll make a few screenies asap to show the problem.

**Comment by Danimal696** [comment]
Hwoarangmy, what is in your opinion the best way to solve this? water and lava rotation are material-made so the tiles can be copied( to retain the corner fix) and asigned differently rotated materials? or just go back to the old system?

**Comment by hwoarangmy** [comment]
I've tried to change materials to make rotation work when rotated but I couldn't achieve an acceptable effect. However, you have more experience with this kind of stuff so you might do it better.
If not, as you say, there is the option of using 1 different mesh per rotation as it used to be

**Comment by Danimal696** [comment]
i can export them but you will have to redo the tileset config file

**Comment by hwoarangmy** [comment]
If you are to re-create the tiles, will they be different from the ones we used to have previously to tilesets ?
If not, just tell me and I will take them back. If there is no simple solution playing with materials, it will save you time (for the kobold replacement ;) As @Bertram25 said, internet never forgets - so do I ^^ )

**Comment by Bertram25** [comment]
+1 :)

**Comment by Danimal696** [comment]
The tile will be the same as now (fixed corners)

kobold... grumble... damn it - the kobold is actually pending on some mocap files, so it be ready eventually... hope not as eventually as duke nuken was

**Comment by hwoarangmy** [comment]
@Danimal696 I've tried to take tiles from the old tileset but it seems you have changed them as I have holes between tiles (as we used to have). I think we have no choice, we need you to export all tiles again (1 per tile position) :-(
If you can export them, I will happily handle the tileset (which will be pretty easy BTW). Note that AFAIK, there is only the water tileset (we used to patch the material). If you can provide water tiles, I will handle lava.

**Comment by Bertram25** [comment]
@Danimal696 What models are left here?

**Comment by Bertram25** [comment]
Nevermind, saw this:
http://forum.freegamedev.net/viewtopic.php?p=64465#p64465

**Comment by Danimal696** [comment]
Im leaving my tileset blender file here:
http://forum.freegamedev.net/viewtopic.php?f=38&t=6380&p=64795#p64795

**Comment by akien-mga** [comment]
Maybe we can already add the fixed tiles from http://forum.freegamedev.net/viewtopic.php?p=64465#p64668 in the main repo, and handle the two meshes that are still problematic afterwards?

**Comment by Bertram25** [comment]
Assigning to @hwoarangmy since he said he would have a look, now @Danimal696 has uploaded new files on the forum.
No pressure though, it's just glitches and should be fixed little by little and serenely. :)
