### ISSUE TITLE
Add a position offset to creature position when there are more than one on the same tile.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#697]
This could also concern other entities such as gold.

**Comment by akien-mga** [comment]
Will it really suffice to add a tile-based offset, or will we run into problems when they are more than one creatures on two adjacent files, and some creatures might overlap at the tile junction?

What about handling collision between creatures? Would it hurt performance a lot? (I suppose so, but you're more experienced than me with this stuff :p)

**Comment by hwoarangmy** [comment]
Most of all, we have to define how we want creatures to behave. For example, if we allow 2 creatures per tile, what happens if 2 are on the same tile and want to go north. But on the north tile, there are already 2 creatures that want to go south.
Moreover, what happens if a keeper drops more than 2 creatures on the same tile ?

In any case, an advanced behaviour would have to be handled on server side and there might be some problems with synchronization between clients and server. ATM, it's not very visible but the more precise the moves sent by the server are, the most visible synchronization problems can become.

**Comment by Bertram25** [comment]
IMHO:
- We shouldn't limit the creature number per tile or we should limit it to a high value. Otherwise, we will have noxious and rare pathfinding problems.
  Creatures should still be able to get through one another and stand on the same tile, or corridors will break your dungeon. :)
- When dropping creatures, they should be dropped on a random offset (with a margin safety for floating point imprecisions), so that it is "visually" better.
- The server shouldn't care too much about the precise creature position (the tile offset computation) (unless it really isn't a bottleneck), and the client should handle itself computing the offset when creatures are on the same tiles. The server does not care about that after all.
- About the tile offset computation, to the least or as a fallback, it could be random. Otherwise we could use predetermined nice-looking offsets when one, two, three, ... creatures are on the same tile or going to the same tile during the same turn.

WDYT?

**Comment by hwoarangmy** [comment]
FYI, in my current PR (not already released, I'm waiting for the current one to be merged), I have added creatures to the tiles on client side (as it is done on server side). That might allow to know on client side how many creatures there are per tile and, thus, find nice offsets.

Concerning the other points you raised, I agree as long as we don't want to handle collisions. The real question is: do we want to handle collisions ^^
From your answer, I guess it is no for you and I am on the same line as it will become quickly tricky to handle it on corridors.

**Comment by Bertram25** [comment]
> do we want to handle collisions ^^
> From your answer, I guess it is no for you and I am on the same line as it will become quickly tricky to handle it on corridors.

Yep. :) It is way too nasty to get into for such a small benefit, IMHO.

**Comment by hwoarangmy** [comment]
I've tried to add a random offset and it is not too bad. I will upload it once my actual PR is in.
