### ISSUE TITLE
Create the Arena!

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#699]
The arena room is used to make creatures fight one against another and can be hurt badly in this one.
But it is the only way to train a creature higher than in the training room.

More specs:
Creatures should still get mood change and if they come hate one another, you could lose a few of them if you're careless.
The XP formula earned there should be the same than in combat.

**Comment by Danimal696** [comment]
i think this will trigger a "KO" state discussion, it will be a feature needed for the prison as well. Basically you decide if to kill creatures on combat or KO them, KO creatures behave like dead ones but get on their feet after some time, giving time to kobolds to carry them to the jail (or their bed if KO´ed in Arena?)
I also think that arena XP should be higher than combat one, unless creatures go there by their own will and abandon combat at half or 1/3 life, that way you dont have to drop them by hand.

**Comment by Bertram25** [comment]
KO will need an icon btw. I'll add that one in #734 ;)

Arena icon proposal: http://game-icons.net/sbed/originals/arena.html
http://game-icons.net/lorc/originals/sword-in-stone.html

**Comment by Danimal696** [comment]
first one is no good, i cant make out, what it is; a few of my own:
http://game-icons.net/lorc/originals/all-for-one.html
http://game-icons.net/delapouite/originals/aqueduct.html <- Feels like a coliseum

**Comment by hwoarangmy** [comment]
IMHO, aqueduct is the best one. I don't like the 3 others (it isn't clear at all what an arena is)

**Comment by akien-mga** [comment]
+1 for the aqueduct. I like the sword in stone though, but to use it we would have to make a clear reference to it in the arena model ;)

**Comment by Bertram25** [comment]
k, I'll work on the aqueduct one. :)

**Comment by Bertram25** [comment]
Here it is: :)
![aqueduct](https://cloud.githubusercontent.com/assets/765917/7516540/622460f4-f4d0-11e4-9cb8-21a31488d05b.png)
