### ISSUE TITLE
Creatures stats upgrade Mark I

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#7]
- Make the creatures stats handled as described here: http://forum.freegamedev.net/viewtopic.php?p=56808#p56808
- [x] Water and lava should be set passable/impassable independently. #101 
- [x] Creature not flying should be made slower in lava/water and not walk above but lower in the tile.
- [x] MP should disappear as later add support for skills obtained on a given level, with a cool down. (in another issue)
- [x] Every stats/level stats should be in the `levels/creatures.def` file:
  Missing stats in creatures.def:
  - [x] `moveSpeedPerLevel` Tells the movespeed bonus acquired when leveling up.
  - ~~`maxMoveSpeed`  Absolute max for any kind of terrain, or should we separate per terrain type?~~
  - [x] `digRatePerLevel` Tells the dig rate bonus acquired when leveling up.
  - ~~`maxDigRate` Absolute dig rate max.~~
  - [x] `danceRatePerLevel` Tells the dance rate bonus acquired when leveling up.
  - ~~`maxDanceRate` Absolute dance rate max.~~
- [x] The creatures current `hp`, `level`, and equipment should be part of the level file.

**Comment by Bertram25** [comment]
Moved the equipment catalog parameter into it own issue as it is less urgent: #138

**Comment by Bertram25** [comment]
I listed precisely the missing stats about creatures before this issue can be closed. Feel free to tell me whether something looks missing or wrong. :)

**Comment by Danimal696** [comment]
Well there can be added a lot of things; setting a max may not be needed with proper care and sensible stat wins per level up. Ill made a post in the forum with all i think we will need. You can have an easier look at it later.

**Comment by Bertram25** [comment]
> setting a max may not be needed with proper care and sensible stat wins per level up.

Hmm, depends. The max is there when you want to add a quicker growth on something that is capped earlier. Like monsters that have a higher movement bonus that stays capped not very high.
What I think you want is to add non-linear growth and maybe XP table, but I'd need more input from you to understand where you're going.

In anyway, the stat system should be reviewed asap if we want to get through this.

**Comment by Danimal696** [comment]
please have a look at forum again

**Comment by Bertram25** [comment]
I just did. What is set there is well-thought. :)
IMO, we should follow your newest specs there:
http://forum.freegamedev.net/viewtopic.php?p=59362#p59362

Would you be ok with this guys?

**Comment by akien-mga** [comment]
Agreed, it's a nice and clear proposal.

**Comment by Danimal696** [comment]
i guess we should add the sound clasiffications in there as well? but it would become an useless stub until sound is better handled, ill let it to your judgement:
http://forum.freegamedev.net/viewtopic.php?f=39&t=5695&start=25#p59177

**Comment by Bertram25** [comment]
Superseded by #151 #152 and #153
