### ISSUE TITLE
Segfault in graphics drivers

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#700]
I'm back in the arena ^^
During my holydays, I've tested OD on a friend computer (I think it was 0.5.0 RC1). He got a segfault very similar to @lowerthanred had (segfault with the last log being a creature remove). I've also had something pretty similar with my laptop with last nvidia drivers. I also got something pretty similar on a laptop with an Intel HD 4500 (but in the drivers after removing a creature).
After googling a bit, similar bugs seem to be related to shaders and graphic cards drivers. However, we have too many compared to what we could expect looking at what we find with google.

I will try to make a binary release with MSVS2013 and see if I reproduce the segfault. If yes, I will try if it works with another renderer.
Having a release with MSVS2013 will imply downloaders to install VS runtime library but if it avoids segfaults...

**Comment by Bertram25** [comment]
@hwoarangmy Let's move it to later as the answer may happen sooner or later than 0.6.

**Comment by hwoarangmy** [comment]
For the record, for some unknown reason, I get what looks like a systematic crash when opening RuinsOfTheConfluent level in the editor and exiting with the camera looking at the player 1 dungeon temple with the troll on the top right of the screen.
I get no callstack so I'm not really sure if it is related to this bug but it might be. The good news is that I get the bug even in debug mode. By using breakpoints, I've seen that the bug happens after having cleaned the gamemap when we call CEGUI::System::getSingleton().renderAllGUIContexts();

However, I've not found the exact instruction that causes the crash but it seems pretty deep in CEGUI Ogre renderer.

To be continued...

**Comment by hwoarangmy** [comment]
I could find a pretty (nasty) workaround to avoid the crash. With it, I couldn't reproduce the crash (that was almost systematic). I will try to update my PR ASAP.
Note that I could reproduce the crash by slapping a creature so it seems to confirm that it is the same bug
