### ISSUE TITLE
Make a better distinction between names of game UI tabs and configuration menus

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#703]
Currently in gui/ we have a lot of OpenDungeonsMenu\* layout files, but some refer to configuration menus (OpenDungeonsMenuConfigureSeats, OpenDungeonsMenuLoad, etc.), while others refer to the tabs in the game or editor interface (OpenDungeonsMenuSpells, OpenDungeonsMenuTraps, etc.).

IMO we should use distinctive names for both "things" to avoid confusion.

**Comment by Bertram25** [comment]
+1 (+1000 in fact. ;])
What kind of renaming or maybe subfolder sorting have you got in mind?

**Comment by akien-mga** [comment]
>  What kind of renaming or maybe subfolder sorting have you got in mind?

No precise idea yet, but I thought I'd raise the issue so that we can decide what would be fitting.
This is btw partly related to #670, depending on what we do with modes we might want to use one word or another.

**Comment by akien-mga** [comment]
Another related question is, do we want to keep the "OpenDungeons" prefix that makes all filenames quite long? What was the reason behind it initially?

**Comment by Bertram25** [comment]
> Another related question is, do we want to keep the "OpenDungeons" prefix that makes all filenames quite long? What was the reason behind it initially?

I don't know the initial reason, the OpenDungeons prefix can be removed, as for me, or changed to OD if we somehow want to keep it. :)

**Comment by akien-mga** [comment]
> I don't know the initial reason, the OpenDungeons prefix can be removed, as for me, or changed to OD if we somehow want to keep it. :)

IMO we can remove it altogether, as it's pretty obvious in the OpenDungeons source tree that the stuff is related to OD :) It would make sense if some files were from CEGUI upstream, while others were tailor-made for OD, but AFAICT all files are tailor-made for OD (even if some are based upon upstream templates).

**Comment by Bertram25** [comment]
> but AFAICT all files are tailor-made for OD (even if some are based upon upstream templates).

Yep. :)

**Comment by hwoarangmy** [comment]
Funny, I had the same thought yesterday. ATM, it is messy and hard to know if a file is a real menu or if it is just a tab.
Concerning the prefix, I agree it is not that needed...
+1 for renaming, so ^^
