### ISSUE TITLE
Gold handling

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#704]
ATM, when a creature gets killed, it gives back the money it has up to 1 pay day. That means that gold is lost as soon as a creature gets a second payday.

In the games we have played, gold was always a problem. So, what about recycling all the money letting creatures give everything back when they die. That would allow to kill weaker creatures to get better ones. And that would not kill game play because once a player have a good leveled creature, killing it will make him have to re-train another one and, thus, will weaken his army enough to not be a problem. Moreover, that would allow, when gold is running out, to kill the weakest to not allowing good ones to leave.

However, creatures quitting the dungeon will make money disapear.

@Bertram25 @akien-mga @Danimal696 @oyvindln WDYT ?

**Comment by akien-mga** [comment]
Sounds good to me :)

**Comment by Bertram25** [comment]
I'm fine with it. This will have to be done anyway, when we'll add rooms to make creatures spend their money onto.

**Comment by hwoarangmy** [comment]
BTW, I forgot to add that it will also give another good reason to players to be aggresive. If you can kill a dungeon, you will get more money and that can become a needed source of income ^^

**Comment by Bertram25** [comment]
True. :)
