### ISSUE TITLE
Document Creatures and Rooms per Tiers in the wiki

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#705]
Details here:
http://forum.freegamedev.net/viewtopic.php?f=37&t=5851&p=59643&hilit=tier#p59643

Taken from around here: http://forum.freegamedev.net/viewtopic.php?p=63914#p63914

From @Danimal696 : 

> I did make a list for creatures before, but basically tier 1 creeps and low level figthers (spider, goblins, adventurers, dwarf1...) tier 2 useful figthers (knigths, defender, orcs, lizarman...) tier 3 strong warriors (troll, scarab, runelord...) tier 4 unique units like bigknigth and pitdevil, as for rooms:
> tier 1 the ones you get for free + training hall;
> tier 2: common rooms like forge, prison, cript...;
> tier 3: temples? we dont have enought to fill this list yet...

**Comment by Bertram25** [comment]
I just did Spells: https://github.com/OpenDungeons/OpenDungeons/wiki/Spells

I'll work on the rest. :)

**Comment by akien-mga** [comment]
> I just did Spells: https://github.com/OpenDungeons/OpenDungeons/wiki/Spells

It looks awesome :-D
You should probably make it clearer that the spells from 0.5.0 are also in 0.6.0.

**Comment by Bertram25** [comment]
> You should probably make it clearer that the spells from 0.5.0 are also in 0.6.0.

Yep. :) Btw, do you remember what rooms were in 0.5.0 and 0.4.9?

**Comment by akien-mga** [comment]
> Btw, do you remember what rooms were in 0.5.0 and 0.4.9?

Check the release notes ;-)

**Comment by Bertram25** [comment]
ah true. thanks. :)

**Comment by Bertram25** [comment]
Precised version in spells, added rooms:
https://github.com/OpenDungeons/OpenDungeons/wiki/Rooms

**Comment by Bertram25** [comment]
Improved a bit the research tree page:
https://github.com/OpenDungeons/OpenDungeons/wiki/Research-Tree

Once @hwoarangmy will have done more progress on it, I'll follow with according changes.

**Comment by hwoarangmy** [comment]
@Bertram25 The wiki is really nice. The only thing I've seen is that you didn't use the icon for haste spell and you made a note about the workshop under the trainingroom.

**Comment by Bertram25** [comment]
> @Bertram25 The wiki is really nice. The only thing I've seen is that you didn't use the icon for haste spell and you made a note about the workshop under the trainingroom.

Yeah, I had a branch without the icon. As soon as I've finished the creature page, i'll fix up the spells and rooms pages. :)

**Comment by Bertram25** [comment]
spells and room pages are fixed. I'll resume the creatures page.

**Comment by Danimal696** [comment]
Go for it! :D

**Comment by Bertram25** [comment]
Ok, I should be done now.
What can be done to improve all that for instance would be to take screenies of models using meshy to get a better profile, and why not add details about their fighting, crafting and research proficiency using a ranking, like the one one can see on website with stars:
https://mlsvc01-prod.s3.amazonaws.com/914e81f3101/ce883c9a-4f4b-4efa-99ce-ecccf5e8dd64.png

**Comment by Bertram25** [comment]
In any case, this should be enough to close this issue. I'll do it now but feel free to have a look and fix typo or tell me to fix anything you see.

**Comment by akien-mga** [comment]
> What can be done to improve all that for instance would be to take screenies of models using meshy to get a better profile, and why not add details about their fighting, crafting and research proficiency using a ranking, like the one one can see on website with stars

That could be pretty cool, but I don't think you should spend too much time on it right now as the game might still need some balancing to be more fun.

**Comment by Bertram25** [comment]
> That could be pretty cool, but I don't think you should spend too much time on it right now as the game might still need some balancing to be more fun.

I'll polish it from time to time. But for the moment, I'll get back to more urgent stuff. :)
