### ISSUE TITLE
Recreate the particle flare.png texture to get rid of its license mud.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#709]
I'll handle it once the particles PR is merged.

**Comment by hwoarangmy** [comment]
Thanks for that ^^
BTW, since it is also used for the heal spell, we could use some heart like images in a second step (but for now, a flare like would be more than enough).

**Comment by Bertram25** [comment]
> BTW, since it is also used for the heal spell, we could use some heart like images in a second step (but for now, a flare like would be more than enough).

True. I can handle that. Then, may I request we change the "not-intel-compatible" particle first so I can have a view at what it is looking like. Then, I'll make a proposition. :)
WDYT?
I can have a go at playing with the particle effect if you're ok with it.

**Comment by hwoarangmy** [comment]
I've not taken the particle effect bug so feel free to take it and play as you want. Anyway, I'm not best suited since I don't reproduce the problem so...

**Comment by Bertram25** [comment]
I've found the "offending" statements:
In the SpellCreatureHeal.material file:
If you comment those, the effect works again.

```
        //point_sprites on
        //point_size 1
        //point_size_attenuation on
```

There are rose dots going up. Is that the correct effect? I mean: is the effect similar for you?

**Comment by Bertram25** [comment]
For the record, I think we should avoid using point based quads for intel graphics?
http://www.ogre3d.org/docs/manual/manual_16.html#point_005fsprites

@oyvindln WDYT?

**Comment by hwoarangmy** [comment]
> There are rose dots going up. Is that the correct effect? I mean: is the effect similar for you?

yep ^^

**Comment by Bertram25** [comment]
PR incoming then. ;)
