### ISSUE TITLE
Heal animation does not work on Intel HD Graphics chipsets on Linux

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#711]
To investigate this further, @Bertram25, @oyvindln and or @akien-mga should try the Ogre samples so that we can narrow down what is not supported by the Intel chipsets.

**Comment by akien-mga** [comment]
I've tested the "Nimbus" animation in Ogre's SampleBrowser, and indeed it does not work with my Intel chipset. It works fine with my Nvidia GPU. The other particle effects seem to display just fine.

**Comment by eugeneloza** [comment]
No particles for my Radeon HD5400 either.

**Comment by hwoarangmy** [comment]
Ok. Then it is a problem with the effect himself. I will have a look at google since it should be pretty easy to find something about it if it happens with Ogre samples. In any case, the effect is pretty easy to change by playing with the particle script file.
