### ISSUE TITLE
Improvement to the text overlay

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#713]
- [x] Now we have more spells and more rooms, it would be better to make the text overlay display the unit along with the cost.
  Example:
  Training Hall [150 Gold]
  Heal [5000 Mana]
- [x] The spells and rooms overlay texts shouldn't show a 0 cost when unspawnable/uncastable, just the text in red.

**Comment by hwoarangmy** [comment]
true

**Comment by Bertram25** [comment]
Ah, btw, while we're speaking about it. 
Both debug and room/spells/trap text overlay should be hidden when leaving the game/editor modes.
Atm, if you leave the game with those shown, they'll stay shown on the main menu.

**Comment by Bertram25** [comment]
Done with commit b96b57e7821c16bced7ed6881987a74c7ac42694
