### ISSUE TITLE
It's payday... but no one to pay.

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#715]
I've got a message 'It's pay day' but I've got no creatures to pay (strangely, but none came to the dungeon for a long time and the only spieder came was immediately after the pay day so it took no fee).

**Comment by eugeneloza** [comment]
Moreover, got 'its pay day' after defeat.

**Comment by hwoarangmy** [comment]
Yes, payday message is not related to having creatures or not. But adding a check should not hurt too much if it bothers you.

**Comment by Bertram25** [comment]
Having a payday should indeed happen to those still having a temple IMHO. Once you've lost, it's not relevant indeed.

**Comment by hwoarangmy** [comment]
I'm having a look at this one. Note that we said that a player who loses his dungeon temple can still manage his creatures (but his mana stops increasing and no more creatures will come to his dungeon even if he still holds a portal). That means that he won't see why his creatures get more and more angry when a new payday happens.

**Comment by Bertram25** [comment]
My bad. Yes, let's check only for fighter creatures, then.
