### ISSUE TITLE
Darkened gold in treasury

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#717]
One pile of gold is of darker color than others... can be seen at any angles/zooms, dependless if there are any creatures around. After some creature took its fee from the pile it changed to normal color, but when kobolds replaced it, it again became darker than others.
![treasury_color](https://cloud.githubusercontent.com/assets/10726162/7444792/e36738c4-f194-11e4-8f05-75df836881a2.png)

**Comment by Danimal696** [comment]
anything staking will darken its texture (gold or creatures) on the pic there are two money bags stacking on each other, problably a kobold carried it to the treasure room, saw it full and dumped it there, later when some space was empty on it another properly added the gold to the room. Ill open an issue with a soultion

**Comment by hwoarangmy** [comment]
As @Danimal696 said, it comes from the meshes being one over the other. Adding a rotation offset would look weird IMHO (since most of the bag would be superposed). But we can add a random offset ingame and, why not, a random rotation would make it look better.

**Comment by Bertram25** [comment]
Superseded by #725 as @Danimal696 told. :)
It's good to see we're at a level of details that means the quality is high already. :)
Keep them coming. :)
