### ISSUE TITLE
A training hall dummy after temple destroyed

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#719]
After the temple is destroyed a training hall dummy was hanging around at its center. It's cool to see the keeper hanged up :) But it seems to be not as planned :)
https://www.dropbox.com/s/lxvahzvbtbms8gq/replay_20150503_133520.odr?dl=0 /// the very end of the replay.

**Comment by eugeneloza** [comment]
![odscreenshot_2015-05-03_145026_5](https://cloud.githubusercontent.com/assets/10726162/7444924/e6ce2a48-f19b-11e4-9519-7b7d70431580.png)

**Comment by Danimal696** [comment]
are you sure its not the "Call to war" spell? currently it has that icon as a placeholder, but thinking about it, maybe its the way portal home into dungeons? Hmwo should know about this...

**Comment by eugeneloza** [comment]
I've never used "Call to war" and its definitely not the case. However, it disappeared after a few secs. So might that be a kind of 'autocast' on game end? Or enemy heroes cast this one at my temple?

**Comment by akien-mga** [comment]
That would be your enemy casting "Call to war" I think :)

**Comment by hwoarangmy** [comment]
Yep, that's how it works. The portal wave digs a way to your dungeon (if any) and, once it has opened a way, it cast a call to war spell to make sure the creatures go at the good place. And that's what you see here ^^
