### ISSUE TITLE
Easy to sacrifice the creature when placing it

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#722]
Right mouse button is used to place creatures and sacrifice them. But when you have ~15 fighting creatures selected and you need to place them quickly you're easy to miss the amount of clicks and smash your own creatures when you need them most. Maybe shift-right click to sacrifice? It's not a very often option in contrast to throwing all your fighters at the enemy.

**Comment by Danimal696** [comment]
you mean slapping, and its true, i have killed a few almost dead creatures rescued from combat when dropping them on the dormitory

**Comment by hwoarangmy** [comment]
Yep, some of my creatures got slapped for this same reason ^^

**Comment by akien-mga** [comment]
I killed a lot of creatures like that too. I'm not sure if we want to keep this as a feature since we're an evil game, or if we want to make it easier to drop creatures without killing them :)

**Comment by Danimal696** [comment]
should a restriction of one second be added to use slap after any action of the hand?

**Comment by eugeneloza** [comment]
... after 'drop'. But as for me, those should be different keys (i.e. right-mouse click and shift-right-mouse click)

**Comment by Bertram25** [comment]
> ... after 'drop'. But as for me, those should be different keys (i.e. right-mouse click and shift-right-mouse click)

I also think @eugeneloza is right here. Slapping should be a conscious thing. ;>
I don't mind about the Shift+Right-click, but if you can think about something simpler, feel free to tell.

> I killed a lot of creatures like that too. I'm not sure if we want to keep this as a feature since we're an evil game, or if we want to make it easier to drop creatures without killing them :)

Eh eh. :)

**Comment by hwoarangmy** [comment]
Since @Bertram25 wants to fix this for 0.6.0, we should decide what we want to do here.

IMHO, using a shift / ctrl / tab / alt seems a bit too complex for players  and I guess many won't use this feature because they won't know it is there. Moreover, it seems a bit too much for what we need.

As @Danimal696 stated, one solution could be to not allow slapping creatures during let's say 1 or 2 seconds after dropping a creature. That would allow the crazy clickers to not kill their creatures.

@OpenDungeons/developers WDYT ?

**Comment by Bertram25** [comment]
> As @Danimal696 stated, one solution could be to not allow slapping creatures during let's say 1 or 2 seconds after dropping a creature. That would allow the crazy clickers to not kill their creatures.

I like this idea but I wouldn't want to prevent overall slapping for 2 seconds, more making the dropped creature unslappable for 2 secs.
This makes me think that we didn't talk about what happens to dropped minions? (for later) Should they get hurt? Should they stay with the 'dead/ko' animation for one second before getting up?

**Comment by hwoarangmy** [comment]
> more making the dropped creature unslappable for 2 secs.

Good idea.

> This makes me think that we didn't talk about what happens to dropped minions? (for later) Should they get hurt? Should they stay with the 'dead/ko' animation for one second before getting up?

I prefer them to be KO instead of hurt because we might end up by killing creatures when trying to save near dead ones.

**Comment by Bertram25** [comment]
K, I'll create an issue for the next milestone.

**Comment by Bertram25** [comment]
Done. #833

**Comment by Bertram25** [comment]
Ah, also we shouldn't slap when right clicking to unselect an option above a creature (room, trap, spell, ...)
