### ISSUE TITLE
Add a cheat to unlock all skills at once

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#729]
For testing purposes of course... Mouahahaha :smiling_imp:

**Comment by hwoarangmy** [comment]
For every player or just those with a nick starting by "aki" ?

**Comment by akien-mga** [comment]
Lol :-) More seriously I was thinking about a server-side command like "unlockskills" that would instantly make all skills researched, so that one can easily test spells/higher tier rooms without having to play for too long.

**Comment by akien-mga** [comment]
The alternative is to make all researches achieved on test levels, as currently done (or at least partly) on the 2v2 test map.

**Comment by hwoarangmy** [comment]
No, I guess the console command makes sense as it can allow to test more easily
