### ISSUE TITLE
Add support for a starting mana value per seat

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#730]
Just for the sake of completness. ;)
I think the 0.6.0 release will be the magic & lights one. ;)

**Comment by akien-mga** [comment]
There's already support for that, no?
https://github.com/OpenDungeons/OpenDungeons/blob/development/levels/skirmish/FallingKeeper.level#L21

**Comment by hwoarangmy** [comment]
Yep, there is. It is not configurable in the editor (like the other seat related stuff) but it works

**Comment by akien-mga** [comment]
Closing then.

**Comment by Bertram25** [comment]
My bad. Cool if it's done. :)
