### ISSUE TITLE
Add the door trap.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#732]
- [x] Model + Texture needed.
- [x] Icon needed.
- [x] Wiring it in game is then to be specified and done.

Specs:
the door is a special trap that can be closed/opened when slapping it.
A closed door must be identified as walkable for allies, but as a visible trap for enemies.
Doors can only be placed on ally claimed grounds when there are two ally claimed wall next to it.

**Comment by Danimal696** [comment]
> A closed door must be identified as walkable for allies

Are you sure? i expect my creatures to not being able to cross it while locked and enemies to always find it locked

**Comment by hwoarangmy** [comment]
> Are you sure? i expect my creatures to not being able to cross it while locked and enemies to always find it locked

I would also expect allied creatures to not be able to go through a locked door.

**Comment by Bertram25** [comment]
It's true that it's sometimes useful to lock creatures. I agree.

**Comment by Bertram25** [comment]
Proposition for the wooden (and first type of) door:
http://game-icons.net/lorc/originals/wooden-door.html
![wooden-door](https://cloud.githubusercontent.com/assets/765917/7513898/8270d6de-f4b8-11e4-8294-223a0436f46e.png)

**Comment by akien-mga** [comment]
Looks great :)

**Comment by hwoarangmy** [comment]
Yep, looks good

**Comment by Bertram25** [comment]
Here we go :D 
![wooden-door](https://cloud.githubusercontent.com/assets/765917/7516483/01fa1eee-f4d0-11e4-9bd1-bf0ab2183ee1.png)

**Comment by Danimal696** [comment]
How do you we want to handle the closed door case? i can make a lock model to put over the doors when its closed or do you have any other idea? by the way, wooden door is very advanced by now.

**Comment by hwoarangmy** [comment]
animations are always welcome ^^
IMHO, an open door when the door is open and closed when closed would be ok

**Comment by hwoarangmy** [comment]
I'm almost done with implementing door logic. On allied side, it works well. When open, creatures can go through and when closed, allied creatures cannot.
Doors appears as soon as they are in sight and can be attacked.

However, fighting logic is not totally implemented. ATM, enemy creatures can see through doors and they will engage creatures behind (with a buggy behaviour because they cannot go through the door - melee units currently attack from the door like ranged units ^^).

So, do we want enemy creatures to see through doors ? Be them open or closed ?
Can allied ranged units attack through doors ? What about enemies ?

@Bertram25 @akien-mga  @Danimal696 @oyvindln @eugeneloza 

WDYT ?

**Comment by Danimal696** [comment]
> So, do we want enemy creatures to see through doors ? Be them open or closed ?

Nop, only when open

> Can allied ranged units attack through doors ? What about enemies ?

If open, yes; its something quite logical that shouldnt be messed with

**Comment by hwoarangmy** [comment]
The good news is that it is the easiest to implement ^^
So, if the door is closed, creatures cannot see through (and won't attack enemy creatures on the other side).
If open creatures can go through and ranged units can attack through. Note that enemy creatures can go through open doors if they see enemy units on the other side (but if there is no enemy unit on the other side, they will attack the door)

**Comment by akien-mga** [comment]
Yes I agree with @Danimal696. My understanding is that open doors should behave as if there was no door, and closed doors should behave as if they were a wall (apart from the door attacking mechanism).

**Comment by hwoarangmy** [comment]
The current implementation should be ok then ^^

**Comment by Bertram25** [comment]
Looks fine in game. The mesh to be changed later of course. :)
I can finally lock-up my minions while I'm preparing an attack!
I caught a crash but I don't think it's related to the PR. (I'll make an issue.)

**Comment by Danimal696** [comment]
Almost ready, expect it later today

**Comment by akien-mga** [comment]
Wooden Door mesh and animations have been merged in #765, now the code should be adapted to handle three non-looped animations (open, close, destroy) and select the proper orientation for the door based on surrounding tiles.

**Comment by Bertram25** [comment]
Nice team job guys. :)
