### ISSUE TITLE
Infinite gold tile support.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#735]
This is a new tile type that permits to dig gold forever but as a slower rate (let's say 40% or the nominal speed.) Slow workers will thus be a waste on this one even if they will improve fast.

Also, as a first thought about it, I'd say that no more than 4 workers (one per accessable side) should be able to work on it.

The tile model should first be done.

**Comment by Danimal696** [comment]
Wouldnt an automatic structure be better? claim it and it spits gold from time to time...
Better than clashing with mining priorities

**Comment by hwoarangmy** [comment]
> Wouldnt an automatic structure be better? claim it and it spits gold from time to time...
> Better than clashing with mining priorities

It would be easier. But both can be done

**Comment by Bertram25** [comment]
@Danimal696 

The idea behind it was to undermine your ability to let worker do something else by forcing a given amount of them to work on that tile. I think it's a good strategical twist.
An automatic structure is a full feature without any drawbacks.

Now, it's about personal taste. What do you think of my reasoning?

**Comment by eugeneloza** [comment]
Automatic structure that requires 4 workers to operate :D like library/workshop mechanics.

**Comment by Bertram25** [comment]
> Automatic structure that requires 4 workers to operate :D like library/workshop mechanics.

lol. In any case, that can work, too. ;)

**Comment by Danimal696** [comment]
i can make any model when i have more free time, but it would be good to reach a consensus on it before doing it

**Comment by Bertram25** [comment]
> i can make any model when i have more free time, but it would be good to reach a consensus on it before doing it

Well, to avoid being forced to use new animations (while it is fun), I'd rather have a forever-diggable tile.
Is there at least someine about that part?

**Comment by hwoarangmy** [comment]
> Automatic structure that requires 4 workers to operate :D like library/workshop mechanics.

That's not the easiest way for us coders because atm, workers do not work in any room so it would be a completely new feature.

IMHO, the easiest would be:
- A structure that splits gold bags (easy for coding but need a new mesh)
- An infinite diggable gold tile (easy for artists since it only needs a new material and not too hard for coders since I was already planning on checking how many workers are digging a gold tile to avoid having too many on the same tile - be it infinite or not)

**Comment by Bertram25** [comment]
> An infinite diggable gold tile (easy for artists since it only needs a new material and not too hard for coders since I was already planning on checking how many workers are digging a gold tile to avoid having too many on the same tile - be it infinite or not)

Unless our Lead artist is against, I would be for that solution, then. It's easy to understand as for the player experience and easier for us to add. We can also later replace that tile with cooler looking textures/shapes.

**Comment by Danimal696** [comment]
yes, i like that, a gem tile with gems sticking from it would look nice
