### ISSUE TITLE
Should spells be castable on ally creatures?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#741]
@eugeneloza @oyvindln @Wout-van-Dongen @akien-mga @hwoarangmy @Danimal696 

Should defensive spells be castable on ally creatures or only on own creatures?
Other thoughts about this?
Let's have Heal in mind as an example.

**Comment by Bertram25** [comment]
Should they also be castable on ally claimed tiles but on own creatures?

**Comment by eugeneloza** [comment]
I think that every spell must be castable anywhere, except summoning/very powerful/etc. But it is possible to make them twice as expensive if cast on non-ally area (unclaimed or enemy's).
I don't think the spells hould be castable on AI controlled ally creature... however, that might be the way to go for multiplayer. So... maybe multiplayer test might answer the question?
I don't actually think it'll happen often. I.e. as I understand allying is just you don't fight each other :) But maybe, plan and attack together - then it might be usable. However the healing should be coordinated (i.e. "could you heal my troll, please.")? But again, the player will be buisy with managing his own creatures and I really doubt he'll have spare time to think about ally's creatures and risking double-healing of the same creature.
But that's only theoretic.

**Comment by Danimal696** [comment]
> I think that every spell must be castable anywhere, except summoning/very powerful/etc. But it is possible to make them twice as expensive if cast on non-ally area (unclaimed or enemy's).

+1
Also, yes, castable on allies

**Comment by akien-mga** [comment]
> I think that every spell must be castable anywhere, except summoning/very powerful/etc. But it is possible to make them twice as expensive if cast on non-ally area (unclaimed or enemy's).

I like the idea :)
IMO it does not make sense to restrict a spell like Heal to claimed tiles, as then it becomes strictly a defensive spell, and not a support spell when attacking. The price difference suggested by @eugeneloza makes for a nice way to differentiate the spell without creating two different spells for the two use cases.

As for casting on allies, I'd say why not, but the spell should prioritize your own creatures so that you don't heal an ally by mistake and see your creature die at the same time.

It would also be nice if the spell casting selector would show the skull flag of the selected creatures (and ideally also outline the creatures with a halo, but that's more for 0.7.0 IMO ;-)).

**Comment by Danimal696** [comment]
> outline the creatures with a halo

Pertty cool idea! i want it someday!

**Comment by Bertram25** [comment]
> I think that every spell must be castable anywhere, except summoning/very powerful/etc. But it is possible to make them twice as expensive if cast on non-ally area (unclaimed or enemy's).

I like the idea, too.

Overall, I agree with what @akien-mga said.

**Comment by hwoarangmy** [comment]
> IMO it does not make sense to restrict a spell like Heal to claimed tiles

Remember that the spells I've added so far are just for demonstration, that's why I didn't ask before implementing so, if everybody wants to change something, please feel free to do it. However, I was thinking that we could also add some research that would allow to cast spells outside claimed tiles. That would allow someone to goes fast for rooms (and for stronger creatures) to not overcome someone who researched spells and have weaker creatures (when defending as well as when attacking).

Concerning the explode spell, currently, claimed walls give vision behind them. Thus, allowing to cast it on dirt tiles would allow to hit creatures when turtling, which is not a good thing IMO.

> As for casting on allies, I'd say why not, but the spell should prioritize your own creatures so that you don't heal an ally by mistake and see your creature die at the same time.

Indeed, if we can heal allied units, we should prioritize owned ones. However, some may argue that during a fight, casting a mass heal spell will cost a lot and you are pretty sure to spend all your mana at once if you cast it...

> outline the creatures with a halo

as you can already see with skull flag, ogre is not very accurate with ray casting (improving speed decreasing accuracy) by checking only bounding boxes. That's why you always end up picking BigDragons in the editor when there is 1 around. Being more accurate is possible but is not easy and may hit performances.

**Comment by Bertram25** [comment]
> Remember that the spells I've added so far are just for demonstration, that's why I didn't ask before implementing so, if everybody wants to change something, please feel free to do it.

Sure, please don't take anything personally (well, you know us). :) The fact is, your example spells are good enough to be definitely included IMHO, with a few tweaks and that's what we're discussing atm.

> However, I was thinking that we could also add some research that would allow to cast spells outside claimed tiles. That would allow someone to goes fast for rooms (and for stronger creatures) to not overcome someone who researched spells and have weaker creatures (when defending as well as when attacking).

It's a good idea and it isn't incompatible with the twice cost rule, btw.
As a design pov, what you're proposing is our first keeper passive skill, right? (I mean not a new spell per se, and not an active one that can be triggered.)
Maybe we should discuss a bit how we see active/passive skills vs the research-to-be-renamed-to skill tree in a new topic, then.

> Concerning the explode spell, currently, claimed walls give vision behind them. Thus, allowing to cast it on dirt tiles would allow to hit creatures when turtling, which is not a good thing IMO.

Fair point, but unlocking casting spells on unclaimed tiles would end in the same potential behaviour, right?

> Indeed, if we can heal allied units, we should prioritize owned ones. However, some may argue that during a fight, casting a mass heal spell will cost a lot and you are pretty sure to spend all your mana at once if you cast it...

IMHO, that's fair. If we can't find a good agreement, this should become an option, or maybe permitted through a key, like shift-click? WDYT?

> as you can already see with skull flag, ogre is not very accurate with ray casting (improving speed decreasing accuracy) by checking only bounding boxes. That's why you always end up picking BigDragons in the editor when there is 1 around. Being more accurate is possible but is not easy and may hit performances. 

Hmm, I guess you mean this?  http://www.ogre3d.org/tikiwiki/Raycasting+to+the+polygon+level
I'd say no rush on that one, we're still very early in supporting lights, normals and particles and i'd rather have more game features than more visuals from us devs. ;)
No excuse to you artists. ;P

**Comment by hwoarangmy** [comment]
> Sure, please don't take anything personally (well, you know us). :) The fact is, your example spells are good enough to be definitely included IMHO, with a few tweaks and that's what we're discussing atm.

That was just to say that I do not consider the code to be mine and I won't feel offended if anyone changes it (for the best I hope ^^)

> Fair point, but unlocking casting spells on unclaimed tiles would end in the same potential behaviour, right?

Yes but a research would be needed, which is an important difference IMHO

> If we can't find a good agreement, this should become an option, or maybe permitted through a key, like shift-click? WDYT?

I think that it is a player choice. My feeling is that casting only on owned creatures is better. But if most of us think the opposite, I'm ok.

> Hmm, I guess you mean this? http://www.ogre3d.org/tikiwiki/Raycasting+to+the+polygon+level

Yep. It makes choosing the hovered creature pretty hard

**Comment by Bertram25** [comment]
> That was just to say that I do not consider the code to be mine and I won't feel offended if anyone changes it (for the best I hope ^^)

Don't worry, only @Danimal696 is afraid. (Must be some kind of world domination related paranoia.) ;)

> > Fair point, but unlocking casting spells on unclaimed tiles would end in the same potential behaviour, right?
> 
> Yes but a research would be needed, which is an important difference IMHO

True. Right, let's go that way and have people comment on it once it is ingame.

> > If we can't find a good agreement, this should become an option, or maybe permitted through a key, like shift-click? WDYT?
> 
> I think that it is a player choice. My feeling is that casting only on owned creatures is better. But if most of us think the opposite, I'm ok.

Well, I'm in favour of simple game mechanisms. So, let's add that behaviour first. If once it is ingame, a need arises, we'll add either the shift or twice cost feature.

**Comment by Bertram25** [comment]
If nobody else has got a strong argument against that, let's plan to, as a first row, at least:
- Keep the spells on claimed tiles and add a skill that permit to cast them on unclaimed tiles.
- Only target own creatures when casting defensive spells.

**Comment by hwoarangmy** [comment]
IMO, we should start settling a lan and try how it feels like that. Then, if I loose, that would mean that we need to change something

**Comment by Bertram25** [comment]
> IMO, we should start settling a lan and try how it feels like that. Then, if I loose, that would mean that we need to change something

You mean, in your _humble_ opinion, right? ;P

**Comment by hwoarangmy** [comment]
> You mean, in your humble opinion, right? ;P

^^

**Comment by Bertram25** [comment]
In any case, there are no changes planned so far after the discussion. I'll close this issue.

Let's reopen or open a new one if necessary.
