### ISSUE TITLE
Replace ingame/editor rooms, spells, creatures, ... tabs name with icons?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#742]
After working on modes handling, and before the settings addition, I'd like to do this.

The tabs names would then become tooltips.

Icons proposal:
- Rooms: http://game-icons.net/lorc/originals/white-tower.html http://game-icons.net/lorc/originals/stone-tower.html ~~http://game-icons.net/lorc/originals/anvil.html~~
- Traps: Reuse the Trap room icon so the link is visual.
- Spells: http://game-icons.net/lorc/originals/kindle.html
- Lights: Reuse the sole light icon we have (for now).
- Creatures: ~~http://game-icons.net/lorc/originals/skull-shield.html (Making a link with the skull flag)~~, 
  ~~http://game-icons.net/lorc/originals/pawn.html~~ http://game-icons.net/lorc/originals/blade-bite.html

We could even use this one for the Heroes creature tab: http://game-icons.net/lorc/originals/battle-gear.html

**Comment by hwoarangmy** [comment]
Rooms: I prefer the first one
Traps: Good
Spell: Good
Light: Good
Creatures: I don't like pawn but blade bite is nice (as well as the one for heroes)

**Comment by akien-mga** [comment]
Same comments as @hwoarangmy, apart for the room icon for which I'm not convinced yet. I guess I prefer the stone tower one, but it refers more to claimed walls than to placing rooms like the library or hatchery IMO. I don't find a better candidate anyway :)

**Comment by Bertram25** [comment]
Cool you agree about the change.
As for rooms, we'll see once I'm there. :)

**Comment by Bertram25** [comment]
Since I was on it: ;)
Spells:
![kindle](https://cloud.githubusercontent.com/assets/765917/7516664/1b11979e-f4d1-11e4-9bf1-c89bdc32e6d8.png)
Creatures:
![battle-gear](https://cloud.githubusercontent.com/assets/765917/7516788/bef2245a-f4d1-11e4-81e9-ca6028cf47fb.png)
![blade-bite](https://cloud.githubusercontent.com/assets/765917/7516831/f62e9b38-f4d1-11e4-93c4-4f7657cffb7b.png)
Rooms (I went for the stone tower for now, just because I like details. We'll replace it as soon as we find something better)
![stone-tower](https://cloud.githubusercontent.com/assets/765917/7516908/59d1c7f0-f4d2-11e4-8fde-031f2a6c345a.png)

**Comment by akien-mga** [comment]
The PR looks great.

An idea for future improvements of this part of the UI: how about making the main box textures like a parchment, and make the tabs look like bookmarks? Something like in:
- Arx Libertatis/Fatalis: http://www.geek.com/wp-content/uploads/2012/04/arx_lib_Character.jpg
- TESIV: Oblivion: http://images1.westword.com/imager/skyrim-and-oblivion-fantasy-role-playing/u/original/6566545/oblivion_1.jpg

**Comment by hwoarangmy** [comment]
That would mean to redo the look and feel. Why not for a future release ^^
