### ISSUE TITLE
Creatures becoming feral are keeping their former team color.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#745]
As discussed in #734 , a creature upset enough to be leaving your dungeon and which can't in due time becomes feral. (And that's normal).

The issue is that such creatures are keeping their former color (at least concerning their skull flags).
This should be fixed to make things clearer for the player.

**Comment by hwoarangmy** [comment]
I tried and confirm the issue ^^

**Comment by Danimal696** [comment]
i confirm the new pull fixes this

**Comment by hwoarangmy** [comment]
> i confirm the new pull fixes this

It is not a PR yet ;-)

**Comment by Bertram25** [comment]
Yeah, the latest binary comes from the future. ;)

**Comment by hwoarangmy** [comment]
almost ^^
