### ISSUE TITLE
Sleep animation is looped

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#748]
To see it, in the 2v2 skirmish test map, build a 1 tile dormitory and drop the bigknight. You will see his die animation... several times ^^

**Comment by hwoarangmy** [comment]
@Bertram25 Since I am currently on creature behaviour, do you want me to take this one ?

**Comment by Bertram25** [comment]
Sure, go avead. :) I'll be on gui stuff if possible.

**Comment by hwoarangmy** [comment]
ok
