### ISSUE TITLE
Implement KO state for creatures

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#751]
Note that we need to define the wanted behaviour:
- How do we choose to KO or kill creatures ?
- What happens to a KO unit (will it die after a while if not healed/taken by a kobold) ?
- How can a creature become KO (by enemy creatures/in the arena/by spell) ?
  
  Note that the KO state icon is temporary. The one that should be used is in #734 

@Bertram25 @akien-mga @Danimal696 @oyvindln @eugeneloza WDYT ?

**Comment by Bertram25** [comment]
IMHO:

> How do we choose to KO or kill creatures ?

I'd say if the killer's seat has got a Crypt, let's KO the opponent, if not, well, how to say that nicely?

> What happens to a KO unit (will it die after a while if not healed/taken by a kobold) ?

Yeah!!! Erm, I mean, yes. AFAIk, it's what happens to "corpse" atm, they disappear after some time. The same value should be used. corpse should disappear immediately.

> How can a creature become KO (by enemy creatures/in the arena/by spell) ?

By anything making its HP become 0. In the arena, the kobolds will have the duty to bring them back to their beds, though. But if you haven't got enough kobolds or they are too busy...

**Comment by Danimal696** [comment]
there will be the problem of having jail and cript, cript should only take dead ones. So i think we will need a button to imprison; if you have a prison and while checked, enemies monsters are ko´ed, when not checked (default state) they are killed. The button could appear only when jail/prison is researched

> What happens to a KO unit 

It dies after some time

Arena KO?: after a creature is KO´ed in the arena it could recover a single HP point so it can go to their bed by themselves

> corpse should disappear immediately 

Actually, they dissapear too fast, many of them dissapear before the battle ends, their corpse lives (KO as well) should be far longer on the field if we want to properly use KO and corpse system

**Comment by hwoarangmy** [comment]
> So i think we will need a button to imprison; if you have a prison and while checked, enemies monsters are ko´ed, when not checked (default state) they are killed.

Seems good. We should only think if there are other such options and decide if we go for a dedicated window or in the main guy.

> The button could appear only when jail/prison is researched

IMHO, it would be better to always display it. Even if we have no prison, I see no reason not to allow KOing creatures.

IIRC, in DK, when a creature was KO, a kobold had to bring it to its bed. Otherwise, I think it would die. That seems not a bad idea to me. Do you want to keep this behaviour ?

> Actually, they dissapear too fast, many of them dissapear before the battle ends, their corpse lives

It is configurable so feel free to increase it if you think it is better

**Comment by Bertram25** [comment]
> Seems good. We should only think if there are other such options and decide if we go for a dedicated window or in the main guy.

Could be a small checkbox in the corner of the GUI with a prison door icon next to it? :)

> The button could appear only when jail/prison is researched

IMHO, it would be better to always display it. Even if we have no prison, I see no reason not to allow KOing creatures.

True, but let's wait for the jail before that. I'll create an issue for later: #754 

> IIRC, in DK, when a creature was KO, a kobold had to bring it to its bed. Otherwise, I think it would die. That seems not a bad idea to me. Do you want to keep this behaviour ?

Well, I like this behaviour a lot, if it's possible I'd love to see it kept.
