### ISSUE TITLE
Regression in command completion in the console

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#757]
When I press tab in the console, the available commands are still displayed but the current command is cleared instead of being completed.

**Comment by Bertram25** [comment]
I can have a look this week if you want.

**Comment by Bertram25** [comment]
Just found why:
the console editbox is executing command when this event is happening: CEGUI::Editbox::EventTextAccepted
But this event is triggered when tab is pushed as well.
I'll be fixing that.
