### ISSUE TITLE
Missing model files on the main repository?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#76]
As stated by @tomluchowski here: http://forum.freegamedev.net/viewtopic.php?p=58772#p58772

The model file Shield_small.mesh is missing in the models/ folder and makes the game crash:
`*** ERROR: Internal Ogre3D exception: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource Shield_small.mesh in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /home/abuild/rpmbuild/BUILD/sinbad-ogre-dd30349ea667/OgreMain/src/OgreResourceGroupManager.cpp (line 756)`

It is declared for an Adventurer creature in the oldTest.level file atm:
https://github.com/OpenDungeons/OpenDungeons/blob/development/levels/singleplayer/oldTest.level#L6683

I've requested the model file to @tomluchowski . If he's got it, then we'll need to readd it, if he hasn't got it, then the mesh parameter in the level file will have to changed to 'none'.

**Comment by akien-mga** [comment]
Another missing model for oldTest.level:

> Mesh: Loading Shortsword.mesh.
> An internal Ogre3D error ocurred: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource Shortsword.mesh in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreResourceGroupManager.cpp (line 756)
> Internal Ogre3D exception: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource Shortsword.mesh in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreResourceGroupManager.cpp (line 756)
> **\* ERROR: Internal Ogre3D exception: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource Shortsword.mesh in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /home/iurt/rpmbuild/BUILD/ogre_src_v1-9-0/OgreMain/src/OgreResourceGroupManager.cpp (line 756)

@Bertram25 Not related, but could you give me rights to edit issues and add labels/milestones/assignees?

**Comment by Bertram25** [comment]
> @Bertram25 Not related, but could you give me rights to edit issues and add labels/milestones/assignees?

@Danimal696 @hwoarangmy ok with it? Akien has my vote to become a reviewer. What's yours?

**Comment by Bertram25** [comment]
> Another missing model for oldTest.level:

Ah ok. I'll reopen this issue after merging then.

**Comment by Bertram25** [comment]
@hwoarangmy @Danimal696 @akien-mageia Btw, this error now appears because it seems equipment meshes loading was fixed by one of @hwoarangmy 's patches. :)
I just saw an Orc with a blade in its right hand.

**Comment by Bertram25** [comment]
TODO: Make sure there is no other models missing by opening all the currently available maps and fix accordingly.

**Comment by akien-mga** [comment]
@Danimal696, @tomluchowski: We removed the references to the Shield_small.mesh and Shortsword.mesh models, but maybe the right fix would have been to import those models? The credits seem to indicate they were made by Danimal for the adventurer, but where are they?

**Comment by Danimal696** [comment]
actually they were split from my adventurer model by skorpio and used apart from it, ill reexport them, but arent they nowhere in our repos?; Its cools they are armed again :D i so want this new version

 I also vote for Akien to have the permits he wants

**Comment by Bertram25** [comment]
@akien-mageia Welcome to the reviewers team Akien :)
I just need your promise you won't push the merge button without making sure both the code and the game is fine, as I know it may be tempting. ;)
You can assign tags and milestones to issues.

**Comment by akien-mga** [comment]
> @akien-mageia Welcome to the reviewers team Akien :)
> I just need your promise you won't push the merge button without making sure both the code and the game is fine, as I know it may be tempting. ;)
> You can assign tags and milestones to issues.

Thanks! Well I don't intend to merge pull requests for now, except for really trivial ones for which even I can proofread the code :-)
I mostly wanted to be able to do some advanced bug triage. So I'll make sure I don't push "merge" before reviewing, even if it's a shiny button ;-)

**Comment by Bertram25** [comment]
Np, I trust you upon all that. :)

**Comment by hwoarangmy** [comment]
> ok with it? Akien has my vote to become a reviewer. What's yours?

Sorry to answer so late (and after it is done) but I also give my vote. There was so many discussions yesterday that I might have missed some (this one at least) :)

**Comment by Bertram25** [comment]
> Sorry to answer so late (and after it is done) but I also give my vote. There was so many discussions yesterday that I might have missed some (this one at least) :)

Yeah, yesterday was quite a crazy day. XD Anyway, it's good to have your vote.

**Comment by Bertram25** [comment]
@tomluchowski reported on forums:

> I also got , crash due to the missing "projectile_model.mesh" model .

**Comment by akien-mga** [comment]
> @tomluchowski reported on forums:
> 
> > I also got , crash due to the missing "projectile_model.mesh" model .

I can't find a reference to it in the development branch (searching with `ack -il "projectile"` that searches recursively for the given string in all files). Could it be something linked from inside a binary file, such as a model?

**Comment by Bertram25** [comment]
> I can't find a reference to it in the development branch (searching with ack -il "projectile" that searches recursively for the given string in all files). Could it be something linked from inside a binary file, such as a model?

Unlikely but still possible. He might also have misspelled it. Let's ask him the precise log, I guess.

**Comment by akien-mga** [comment]
Yes I checked the models and skeletons in models/, it's not there. At least not in clear text when opening the files in a text editor.

**Comment by Bertram25** [comment]
@akien-mga Ah, before I forget, could you push this commit to the main repo? (about the other shield reference removal.)
https://github.com/akien-mga/OpenDungeons/commit/839f466a637ed8b1ebefc5b0e7231711166dfea4

This one has my review. We can always put the models reference back whenever they are re-exported by @Danimal696 but in the meanwhile we must make sure the game can run.

Thanks! :)

**Comment by akien-mga** [comment]
> @akien-mga Ah, before I forget, could you push this commit to the main repo? (about the other shield reference removal.)
> akien-mga@839f466

It has been merged already: OpenDungeons@839f466 ;-)

**Comment by Bertram25** [comment]
> It has been merged already: OpenDungeons@839f466 ;-)

I'm an idiot. XD

**Comment by Bertram25** [comment]
As said on the forums, if nothing new happens within one week or two, I think we can close this issue. We'll reopen a new one whenever the new shiny models come back. :)

**Comment by Bertram25** [comment]
Let's readd the models when one export them again. Closing as the oldTest level file is working as for me.
