### ISSUE TITLE
Creatures cannot go through not activated closed doors

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#767]
Creatures should be able to cross closed doors if they are not activated

**Comment by akien-mga** [comment]
What do you mean by not activated? Should doors be crafted in the workshop and placed by kobolds too?

**Comment by hwoarangmy** [comment]
yep. And ATM, if you close them before they are crafted, creatures cannot go through

**Comment by Bertram25** [comment]
I just retested the model's fair. Isn't it fixed already?

**Comment by hwoarangmy** [comment]
yes it is. I forgot to close this
