### ISSUE TITLE
New wooden door open animation ends by closing the door

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#769]
@Danimal696 Could you please check the animation ? It should stop when the door is open.

**Comment by Danimal696** [comment]
it must have taken an extra frame. ill reupload tomorrow; but to make sure, is there a closing animation? or does it jump to closed from fully open?

**Comment by hwoarangmy** [comment]
The close animation seems good. FYI, I've downloaded a program "Ogre Meshy" that allows to open a mesh and see its materials, submeshes, animations. And you can even play them ^^

**Comment by Danimal696** [comment]
doesnt work on w7, i tried. Back to the question, the faulty animation opens and closes door?

**Comment by hwoarangmy** [comment]
> doesnt work on w7

I use W7 ^^

> Back to the question, the faulty animation opens and closes door?

Yep. "Open" animation opens and closes the door (at the end of the animation, the door is closed).
