### ISSUE TITLE
Do not use ogre for logging

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#772]
This is a requirement for #665 since the basic idea would be to not launch the rendering thread (only the server one). The main thread would have to wait for the server to be stopped somehow.

I guess the best would be to use boost instead. An example here:
http://stackoverflow.com/questions/16102128/how-to-redirect-boost-log-to-file

http://www.boost.org/doc/libs/1_55_0/libs/log/doc/html/log/tutorial/formatters.html

@Bertram25 @akien-mga @oyvindln WDYT ?

**Comment by hwoarangmy** [comment]
BTW, we could also use a macro like OD_LOG that would allow to easily change logging if required. Moreover, we could also implement a logging level to also remove most of OD_ASSERT(false, ...)

WDYT ?

**Comment by Bertram25** [comment]
> This is a requirement for #665 since the basic idea would be to not launch the rendering thread (only the server one). The main thread would have to wait for the server to be stopped somehow.
> I guess the best would be to use boost instead.

I've personally checked about the NullRenderer but overall, it looks more risky as it might make us use more workarounds and such, so yeah, the best solution so far is to use boost to log. Thus, I agree.

> BTW, we could also use a macro like OD_LOG that would allow to easily change logging if required. Moreover, we could also implement a logging level to also remove most of OD_ASSERT(false, ...)

Sounds good. What levels have you got in mind? Info, warning, error?

**Comment by hwoarangmy** [comment]
> I've personally checked about the NullRenderer

Well, we don't use Ogre so it seems better to me to not launch it at all...

> Sounds good. What levels have you got in mind? Info, warning, error?

Usually, I like to have error, info and debug (the later not being shown by default). But in this case, warning seems pretty interesting especially for unexpected client events (like trying to pickup a non existing creature or something that may look like an error but can be normal if we clic twice a creature).

**Comment by hwoarangmy** [comment]
BTW, after thinking a bit more and looking at @oyvindln test, this is not a requirement for #665 
I just have to create another log manager (that uses boost) and use it instead of Ogre one.

@Bertram25 Do you think using a macro is better ? IMHO, a macro is better only if we choose to use log level...

**Comment by Bertram25** [comment]
> @Bertram25 Do you think using a macro is better ? IMHO, a macro is better only if we choose to use log level...

Based on our previous discussions on this and on the fact that IMHO we'll need different log levels, I'd say yes to macros.
My two cents. :)
