### ISSUE TITLE
Comboboxes not refreshed properly for all clients multiplayer seat configuration

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#776]
Note that I noticed this when testing the new standalone server mode.
I connected three players to my server, in this order: Alice, Bob and Eve.

As expected, Alice is the "game master" and can manage the seat affectations. She gets added to seat 1 and this is shown in the combobox.

When I connect Bob, he gets added to seat 2 and this is shown in his client, on the other hand it's not shown in Alice's GUI. The combobox for seat 2 stays uninitialised (though Bob is now available to be selected). But the fact that Bob is shown in seat 2 in Bob's client makes me think that it's probably the case on server side, but this is not passed to seat 1.

When I connect Eve, same thing: Eve is shown in seat 3 in her client, but she is not shown in Alice nor Bob's GUIs.

See the screens for each player after all three players are connected:
- Alice
  ![od-alice](https://cloud.githubusercontent.com/assets/4701338/7783288/374aaed2-013d-11e5-9208-9049f881c3f1.jpg)
- Bob
  ![od-bob](https://cloud.githubusercontent.com/assets/4701338/7783289/3a778698-013d-11e5-9677-ff4f6fbe2ff5.jpg)
- Eve
  ![od-eve](https://cloud.githubusercontent.com/assets/4701338/7783290/40436380-013d-11e5-9704-6165decdf94f.jpg)

This is nit-picking, but it shows that our game is starting to be really nice if we can discuss about such cosmetic things :p

**Comment by akien-mga** [comment]
If Alice starts the game without touching the comboboxes, it works fine, so that confirms that it's just a refreshing issue. Bob and Eve _are_ affected to seat 2 and 3.

**Comment by hwoarangmy** [comment]
This is a regression from my current PR #775 . I will try to fix it ASAP. Thanks for testing

**Comment by akien-mga** [comment]
Fixed by 9ec35a2a.
