### ISSUE TITLE
Built door activates combat alert and is too small

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#778]
The size is my fault since i couldnt compare to anything, ill fix it soon.

**Comment by hwoarangmy** [comment]
what is the problem with combat alert ?

**Comment by Danimal696** [comment]
actually, do you resize door in code? i tried a 1:1 used as a creature mesh and the size was rigth

> what is the problem with combat alert ?

I craft a door, kobold mounts it and the combat music start playing, pressing space returns me to door like some figth is happening there, i only tested in "falling keeper" map thought

**Comment by hwoarangmy** [comment]
ATM, they are scaled (0.7,0.7,0.7) like nearly all entities (building objetcs, spike trap, cannon, boulder, ...). If you want, we can scale this one differently or adapt to the other objects size. Just tell.

> I craft a door, kobold mounts it and the combat music start playing, pressing space returns me to door like some figth is happening there, i only tested in "falling keeper" map thought

I've just tesed and I confirm the bug. I will fix it soon.

**Comment by akien-mga** [comment]
I wonder if this scaling by 0.7 won't become a bother as times goes on. Maybe it would be better to scale everything to 1.0 and just adapt the camera view accordingly to keep the same visuals? Then we could use scaling on a per-object basis for those objects that we really want to scale for a reason or another.

**Comment by hwoarangmy** [comment]
> Maybe it would be better to scale everything to 1.0 and just adapt the camera view accordingly to keep the same visuals?

No, we can't. That would mean to scale differently all the other meshes (tiles, creatures, ...). And play with the camera as you suggest to keep the same aspect ratio.

The other solution would be to resize the objects to have a 1.0 scale to be the correct size. But that would mean updating all building objects, traps, rooms...

**Comment by Danimal696** [comment]
so ill just upsize it by 0.3, no prob

**Comment by akien-mga** [comment]
> so ill just upsize it by 0.3, no prob

Technically, by 0.43 ;-)
`1.0/0.7 = 1.43`
