### ISSUE TITLE
Leave SourceForge definitively?

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#779]
On top of displaying ads everywhere, it seems that for a couple of years SourceForge has been bundling malwares in Windows installers of the projects they host (it does not affect us currently, but ethically... yuck!). Now I just read a report from a GIMP developer saying that SourceForge has taken over the control of the GIMP entry on SF, pretexting a "lack of inactivity", and they now distribute fake executable with malwares. The report is in French, so it might interest @Bertram25 and @hwoarangmy: https://linuxfr.org/news/sourceforge-de-pire-en-pire-usurpation-d-identite-du-projet-gimp

_Edit:_ More details and in English: http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/

I think we should stop supporting this disgusting business model, move our binaries somewhere else, and close the OpenDungeons account on SF.
The article I linked advises to use TuxFamily as a hosting platform, and since we've discussed using their services for a potential master server, maybe they could also handle file hosting?

If we all agree, I can get in touch with them to see what could be possible.

**Comment by hwoarangmy** [comment]
I don't really care about moving or not. I've never faced the problems described in your link. But I've been to the gimp website and they talk about it so it must be true.
Anyway, we almost have nothing in sourceforge ATM.
Do you know tuxfamily ? If we want to move there, I'm ok.

**Comment by akien-mga** [comment]
I don't fear that we could be affected by the same issue, since we don't propose Windows installers (only zip archives with a Windows executable, but I don't think they would bother with bundling something in our executable for such a small scale project). It's more about the ethics, I'm starting to think that SourceForge is no longer a place for free software made by people on their free site.

Of course they still provide us with virtually unlimited space to upload our binaries, and great download speed, so we shouldn't do anything too rash and shoot ourselves in the foot while we're trying to make OD better known :) I'll investigate alternatives, it won't hurt :)

**Comment by akien-mga** [comment]
Some more context, in English this time: http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/

**Comment by Bertram25** [comment]
I'll be thinking about this. I believe the main argument making me think about leaving is the fact that AFAIK downloads are limited to certain countries.

Any news from the tux family?

**Comment by akien-mga** [comment]
I've discussed with the TuxFamily guys, and the default formula is 1 GB of storage on their servers for any libre project that asks for it. Upon request, we can also have more (which would be good as currently we have ~2 GB on SF, and it would be sad to have to leave the old binaries behind).

We would have SSH access, so updating new files would be done via scp or similar. A bit less user-friendly that SF's upload button, but not too bad either for us IMO :)

They can also provide a web space with 100 MB of storage, we probably don't need this for the main website as we have the github.io domain, but maybe for the "masterserver" php/mysql stuff (cf. discussion in the lobby thread).

**Comment by Bertram25** [comment]
Hmm, IMHO you can definitely ask and start moving files there little by little if you agree to take care f this. :)
Once we have the files there and that we have updated the download links everywhere, we're good to go. :D

**Comment by akien-mga** [comment]
OK, so do we have a formal agreement to proceed this way? It's kinda political, so I want to be sure we all agree with the move :)

@hwoarangmy @oyvindln @Danimal696 @Wout-van-Dongen ?

**Comment by Bertram25** [comment]
You have my vote for it. (suspense for the others votes. ;])

**Comment by Danimal696** [comment]
does it have downloads tracker? its the only thing i like about sourceforge, anyways, yes, moving its not a bad idea

**Comment by hwoarangmy** [comment]
I'm also ok to move.

**Comment by akien-mga** [comment]
OK, I created an "opendungeons" project on TuxFamily: http://projects.tuxfamily.org/#%3Fdo%3Dgroup%3Bname%3Dopendungeons

Don't hesitate to create an account on TuxFamily and give me your username, so that I can add you as managers of the opendungeons project.

**Comment by akien-mga** [comment]
Our download space is live: http://download.tuxfamily.org/opendungeons/

**Comment by akien-mga** [comment]
> does it have downloads tracker? its the only thing i like about sourceforge,

Yeah I agree it's a very cool feature of SourceForge. According to the doc [1], TuxFamily also provides stats, e.g. http://stats.download.tuxfamily.org/vhffs4/
It doesn't work yet for the opendungeons project, but we'll sort it out in time :)

[1] http://faq.tuxfamily.org/Downloads/En#Stats

**Comment by akien-mga** [comment]
Our first files are online: http://download.tuxfamily.org/opendungeons/

For the stable releases, I've redone the Linux binaries to get the 32bit and 64bit versions in the same folder (thus saving a lot of space, though it means that Linux users get ~20 MB more of libraries that don't match their system architecture, but it's pretty common to see both 32bit and 64bit binaries in Linux tarballs).

**Comment by akien-mga** [comment]
BTW, some TuxFamily servers are down due to an air conditioning issue in their datacenter. Don't worry, I just found out that they are hosted by the same datacenter as Mageia, and it's usually a very good service, we usually get at most 2-3 days of downtime a year.

**Comment by Danimal696** [comment]
that page is pretty lackluster... having a look at their game section really put me off due to low looks.

**Comment by akien-mga** [comment]
> that page is pretty lackluster... having a look at their game section really put me off due to low looks.

Well it's a FTP, it's not meant to look fancy. It's our website's role to look good, normal users won't browse the FTP repo, they'll just click our download links.

**Comment by Bertram25** [comment]
@akien-mga Could you add a small page documenting the new links links on the wiki? :) nothing extraordinary, just so we don't forget.

**Comment by akien-mga** [comment]
The TF guys upgraded our repo to 2 GB when I requested it. For the time being it should be sufficient, and I'm sure we can have more if I ask again, I just did not want to be too greedy at first ;) (actually I've asked for "at least 1 GB more [...] but 2 GB would give us more air", and I guess the moderator just took the "2 GB" number and not "+ 2 GB" :)

I'll ask again for more space when it gets full (currently we use 800 MB of 2 GB).

@hwoarangmy @Bertram25 Can you create a TuxFamily account and give me your username, so that I can add you to the list of maintainers? You'll then be able to upload stuff to the download repo directly by connecting to ftp.tuxfamily.org with your favourite FTP client.

**Comment by hwoarangmy** [comment]
@akien-mga I've created my account. Username: hwoarangmy

**Comment by akien-mga** [comment]
@hwoarangmy Ok, I've added you to the "opendungeons" group.

**Comment by Bertram25** [comment]
@akien-mga It's done. Name: bertram :)

**Comment by akien-mga** [comment]
@Bertram25 I've added you too. All four of us (@alketii is also in the group) should be able to connect to ftp.tuxfamily.org to upload files to our download repo.

**Comment by Bertram25** [comment]
@akien-mga Cool, thanks. :)

**Comment by akien-mga** [comment]
Looks like uBlock Origin (a very nice open source ad blocker with great performance and, so far, better ethics than AdBlock*) decide to blacklist sourceforge.net :-D I guess moving away from there is not a bad idea :)

**Comment by Bertram25** [comment]
@akien-mga We're not far from done here, right? :)

**Comment by akien-mga** [comment]
Yep, what's left is basically cleaning the SF files, close the git and svn repos there, and put a notice saying that we moved to another location with links.

I'll need @Wout-van-Dongen to do this, or I can do this if he puts me admin on the SF page.

**Comment by Bertram25** [comment]
k, thanks for the update. :)

**Comment by akien-mga** [comment]
@Wout-van-Dongen @oyvindln Could one of you appoint me administrator on the SourceForge page, so that I can start closing down the repos, rework the description and do the necessary adjustments to effectively "leave SF"? I'll try to put a banner similar to that of megaglest: https://sourceforge.net/projects/megaglest/

**Comment by akien-mga** [comment]
Things left to do for this issue:
- [x] Retire the SourceForge page (needs admin rights)
- [x] Update links on the website
- [x] Update links in the documentation (wiki)
- [x] Announce it on the forum

**Comment by Bertram25** [comment]
Feel free to assign @Wout-van-Dongen and move this to later once you're done with other tasks in case he needs time for that.

**Comment by akien-mga** [comment]
I've updated the download link in the FAQ and created https://github.com/OpenDungeons/OpenDungeons/wiki/TuxFamily-hosting

**Comment by Bertram25** [comment]
Thanks. The info is indeed helpful. :)

**Comment by akien-mga** [comment]
It's now announced on the forum: http://forum.freegamedev.net/viewtopic.php?f=41&t=6419

**Comment by akien-mga** [comment]
And the SF project page is now retired too :)

**Comment by akien-mga** [comment]
BTW @Wout-van-Dongen also put @Bertram25 and I admins on the SF project page (we'll still keep it to redirect to our website and TF repo, since many people still browse SF when looking for free software, and the SF page is the second result for OD in Google).

**Comment by Bertram25** [comment]
@Wout-van-Dongen Thanks :)

@akien-mga And thanks a lot for handling that communication management part. :)
One good thing done.

**Comment by akien-mga** [comment]
@OpenDungeons/developers Just so you know, I asked for a quota upgrade for our disk space usage on TF from 2 GB to 4 GB, and it was granted. So we have some more room for future releases.
