### ISSUE TITLE
Refresh creature infos when stats window open

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#78]

**Comment by Danimal696** [comment]
it seems simple, but wont the stats window be discontinued once skull flags are integrated?

**Comment by Bertram25** [comment]
> it seems simple, but wont the stats window be discontinued once skull flags are integrated?

I'd like to reuse the stats window principle in the editor to edit the entities names, team color, ...
Also, indeed, in game, this will disappear for a normal player, but we migth want to keep it for debugging purpose.

**Comment by hwoarangmy** [comment]
Yes, I am currently re-adding it for debug purposes. Knowing what is a creature doing can help when it has strange behaviours. Moreover, I will send a string for that. When we will have the flags, we could send the creature data instead and the whole logic will already be there
