### ISSUE TITLE
Creature selection

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#785]
ATM, to know which creature is clicked on, we use Ogre to know which creature is hovered by mouse cursor. It makes very hard to select a specific creature because several can be in the same tile and, if there is a big one (like a Kreatur), you are pretty sure to pickit up and not the other ones.

IIRC, in DK, the selection was based on the tile selector. If it was over a tile with 2 creatures, you could move the mouse closer to the wanted creature and it would be selected.

Do you think this behaviour would be better than the current one ? Of course, picking a specific creature will still be difficult if on a tile with 10 other ones but at least, it would be possible.

@Bertram25 @akien-mga @Danimal696 @oyvindln @eugeneloza WDYT ?

**Comment by Danimal696** [comment]
if its easy to implement i say yes

**Comment by hwoarangmy** [comment]
I don't think it would be hard. We already have the cursor position to display the hand (at the tile top position). We just have to use it to ground position and that should be enough. I will have a look to see if it feels nice or not.

**Comment by hwoarangmy** [comment]
I've tried and it works. It feels a bit strange because I'm used to clic on a creature to pickit up but it allows to select more precisely (and it is also more "natural" for someone new to the game IMHO since we always show the square selector). I will upload a new version to test it.
Anyway, I won't add more commits to my current PR as it is already big enough like that (excepted if there are bugs). When it will be merged, I will open another one.

**Comment by Danimal696** [comment]
wait till i finish my exams and i start adding new things, then i foresee big pr´s again ;)

**Comment by hwoarangmy** [comment]
cool ^^

**Comment by hwoarangmy** [comment]
Closed by #790
