### ISSUE TITLE
When dropped in a dormitory, creatures should try to make a bed if they don't have any and they should sleep if not fully awake or fully healthy

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#79]

**Comment by Danimal696** [comment]
i would add, not fully awake or fully healty

**Comment by Bertram25** [comment]
> i would add, not fully awake or fully healty

+1

**Comment by hwoarangmy** [comment]
ok

**Comment by hwoarangmy** [comment]
I don't remember what was the behaviour in DK when a creature is dropped in a dormitory different from the one where its bed is.
And, more open question, what would we expect in OD ? I would say that if the keeper drops a creature in a dormitory, it is because he wants it to sleep there (even if it can be a mistake) so it should change the dormitory.

**Comment by akien-mga** [comment]
> And, more open question, what would we expect in OD ? I would say that if the keeper drops a creature in a dormitory, it is because he wants it to sleep there (even if it can be a mistake) so it should change the dormitory.

That's a tricky question: depending on how far the target dormitory and the creature's own dormitory are from each other, one could expect:
- The creature goes to its own bed in its dormitory if it's nearby
- The creature changes dormitory and creates a new bed in the target dormitory if the other one is unreachable or far away.

**Comment by Danimal696** [comment]
I remember in DK, the creature would create a new bed if you dropped it on a different dormitory, no matter how far or near his bed was.

**Comment by hwoarangmy** [comment]
Ok, let's do that then
