### ISSUE TITLE
Editor: Removing a room tile doesn't refresh the tile.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#792]
With latest master, when one removes a room tile (I tried with a portal), the tile is still looking as claimed while the portal is replaced as correctly.
Then, when one click on terrain tiles (like dirt) and place it, it actually refreshes the view.

**Comment by hwoarangmy** [comment]
I don't get what you mean. Portal tiles use the same mesh as claimed so it is normal that removing the portal tile do not change the tile. I've tried with another room (dormitory) and it works fine (not with latest master but with my PR).

**Comment by Bertram25** [comment]
Yes. I was confused and lacking sleep last night. As I added seat 0 portals, I got confused by them not changing when removing some tiles from the room.
I'll close. Sorry for wasting your time.
