### ISSUE TITLE
Cannot create fighters/workers in editor

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#795]
due to my last PR

**Comment by Danimal696** [comment]
i saw they are actually generated in 1-1 (?) corner (left down)

**Comment by hwoarangmy** [comment]
What is sure is that the bug happens because pickup fails. Thus, I don't know what happens to the creature as it is never put on map. However, because it is not in hand, it is possible it appears on the 0,0 tile since that's the default position.
