### ISSUE TITLE
Cannot change to D3D renderer

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#799]
By default, OpenGL renderer is selected (which is fine). But when we go to the settings and choose D3D renderer, nothing happens and after restarting, OpenGL renderer is selected again.

**Comment by Bertram25** [comment]
Note that it's normal. Atm, and afaik, it is not possible to change the renderer option in ogre config or change the renderer "for later".
We'll have to move the video + audio config into a custom made user file first.
