### ISSUE TITLE
Tag old releases (for the legacy)

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#805]
IMO it would be nice to tag older releases if we can find the commit that they were based upon. WDYT?

Here are the most recent ones:
- 0.4.8: 50404612
- 0.4.7: Around f0010044 (not sure if they used a version variable back then - @oyvindln might be able to point to the proper commit though).

**Comment by akien-mga** [comment]
Not sure if we want to go much further as it can be tedious, but at least 0.4.8 would be nice to show how much the game evolved between 0.4.8 and 0.4.9 :)

**Comment by Bertram25** [comment]
Ok, I'll tag 0.4.8 but let's first about the rest. :)

**Comment by akien-mga** [comment]
BTW I played 0.4.8 yesterday... wow, how did it change :-D

**Comment by Bertram25** [comment]
> BTW I played 0.4.8 yesterday... wow, how did it change :-D

:O Can you uploaed screenies into the website? It would be cool to see the evolution. :)

**Comment by akien-mga** [comment]
> :O Can you uploaed screenies into the website? It would be cool to see the evolution. :)

Yeah we should probably have a screenshot section on the website. I'd like to split the main page into several subpages instead of having everything in index.html.

BTW to try 0.4.8 is relatively easy, the Linux binaries we have on TuxFamily and SF work fine provided you symlink the missing 32bit deps.

**Comment by Bertram25** [comment]
I's done: https://github.com/OpenDungeons/OpenDungeons/releases/tag/0.4.8 :)

> Yeah we should probably have a screenshot section on the website. I'd like to split the main page into several subpages instead of having everything in index.html.

+1

> BTW to try 0.4.8 is relatively easy, the Linux binaries we have on TuxFamily and SF work fine provided you symlink the missing 32bit deps.

Noted. :)

**Comment by Bertram25** [comment]
Assigned @akien-mga as he did the actual job of searching the correct commits.

**Comment by akien-mga** [comment]
Thanks :)
