### ISSUE TITLE
Improve fighter creature behaviour

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#807]
Basically, when not forced, they should never be sleepy/hungry if they have a bed, the hatchery is big enough and they don't have to walk too much to go from one room to another.

ATM, they stop working when sleepy/hungry. But they go wandering instead of sleeping/eating.

**Comment by Danimal696** [comment]
it annoying when they are starving or very sleepy and they just decide to idle on the other side of the dungeon

**Comment by hwoarangmy** [comment]
Yep. That's why I wanted to change that ^^
