### ISSUE TITLE
Hovering mouse at gold makes it look like liquid (due to normal maps)

### ISSUE THREAD

**Issue by alketii** [OpenDungeons/OpenDungeons#813]
I don't know if its reported (I did a search).
Hovering mouse at gold makes it look like liquid.

**Comment by akien-mga** [comment]
It's a known issue, but indeed it doesn't seem that there is a ticket for it yet.
The "liquid" looks is due to the normal maps added in 0.5.0, it has been discussed in an issue or a pull request, but I don't remember which one :)

**Comment by akien-mga** [comment]
Actually superseded by #828.
