### ISSUE TITLE
Add an IRC service hook

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#814]
This one is for @Bertram25 (or anyone with management rights on the repo).

Could you add an IRC service hook that would point to #opendungeons on Freenode?
The purpose of this hook is that a bot will send a notice to the channel each time something is merged into the development branch, which is pretty cool to keep the lesser creatures aware of the workings of our evil dungeon.

To enable this, go to Settings > Webhooks & Services > Add service > IRC, and fill it in like that:
![od-bot](https://cloud.githubusercontent.com/assets/4701338/8193641/8ec95f72-1476-11e5-81f0-f210b1eedf05.jpg)

Note that for the "Message without join" option to work, @Wout-van-Dongen will have to allow external messages with `/msg ChanServ set #opendungeons mlock -n`

**Comment by alketii** [comment]
why not all branches :smile:

**Comment by akien-mga** [comment]
Because nothing happens on the other branches ;)

**Comment by Bertram25** [comment]
I'm on it. :)

**Comment by Bertram25** [comment]
Should be done now. Let's close once the first event has been witnessed. :)

**Comment by akien-mga** [comment]
Thanks! @Wout-van-Dongen is not sure about enabling external messages on the channel as it could lead to spam, so could you disable "Message without join" for the time being?
Then you can test the service by clicking the "Test service" button or something similar at the top.

**Comment by Bertram25** [comment]
@akien-mga Ok, I've disabled the message without join option.
I've also clicked on test service, just tell me how it turns out. :)

**Comment by akien-mga** [comment]
It works great, thanks!

```
* GithubJarvis (~GithubJar@192.30.252.41) vient de rentrer
-GithubJarvis/#opendungeons- [OpenDungeons] hwoarangmy pushed 2 new commits to development: http://git.io/vLW4H
-GithubJarvis/#opendungeons- OpenDungeons/development 16153d7 hwoarangmy: Fixed tileset tabs
-GithubJarvis/#opendungeons- OpenDungeons/development 067e391 hwoarangmy: Merge pull request #809 from hwoarangmy/development...
* GithubJarvis (~GithubJar@192.30.252.41) est parti
```
