### ISSUE TITLE
Character model requirements

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#816]
@Danimal696, what bones are used for animation purposes? Should the models stick to logic 'the less the better' or there is some OD standard or pattern to follow?
I.e. the model requires at least a specially defined weapon bone, right?

**Comment by hwoarangmy** [comment]
`Creatures with hands that should be able to hold a weapon should have two bones at their hands that have to be named Weapon_L and Weapon_R`

Taken from the wiki:
https://github.com/OpenDungeons/OpenDungeons/wiki/How-to-import-models-in-OD

**Comment by Danimal696** [comment]
less the better, for any model. With mocap using the existing bones from the mocap file is the best, remember to use the weapon bones, which are specific to OD.

Overall, having lots of bones can give really good animations, but the amount of work involved and the expertise are very high.

**Comment by eugeneloza** [comment]
Ok. I'll need to dig firstly into the mocap then and re-rig the naga to fit the mocap with IK tail.

**Comment by eugeneloza** [comment]
Do Weapon_L and Weapon_R support 'dual wield'? Or only a right-hand weapon and a shield?

**Comment by Danimal696** [comment]
dual wield as well

**Comment by eugeneloza** [comment]
Another relative question: How many quads/tris for the model are appliccable? Is 1.5k tris fine? Or should I lower the polycount?

**Comment by Danimal696** [comment]
up to 4k is fine, 3k is the ideal. Kudos to you if you can make it lower poli and good looking

**Comment by Bertram25** [comment]
> up to 4k is fine, 3k is the ideal. Kudos to you if you can make it lower poli and good looking

Could you modify the wiki page?

**Comment by Bertram25** [comment]
@eugeneloza  @Danimal696 Could you update the wiki page if needed?
https://github.com/OpenDungeons/OpenDungeons/wiki/How-to-import-models-in-OD

**Comment by Danimal696** [comment]
couldnt this be closed?

**Comment by akien-mga** [comment]
> couldnt this be closed?

After you've updated the above mentioned wiki page with the relevant info ;)

**Comment by Bertram25** [comment]
@Danimal696 If you have problems with the wiki syntax, feel free to give us the info you want there and a dev will handle it. Probably me, but @akien-mga usually does that real fast, too.

**Comment by Danimal696** [comment]
could you please link this: 
https://github.com/OpenDungeons/OpenDungeons/wiki/3D-Modelling-guidelines

inside Map creation/Modding and rename "How to create models" to "Exporting Blender models"; also it will need prettyfying, i cant put the code examples into place.

**Comment by Bertram25** [comment]
@Danimal696 Should be now done. :)

**Comment by Bertram25** [comment]
Assigning @Danimal696 (I assigned @hwoarangmy  by mistake.) and closing since the job is done. :)
