### ISSUE TITLE
Library logic

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#817]
This issue is a requirement for #577 
ATM, in the library, creatures go to work and, when they gather enough points, an entity is created representing the given research. When it is brought to the dungeon temple, the corresponding room/trap/spell is unlocked. Before the researches are taken by a worker, the research entity takes 1 active spot in the library (wall or center if no wall available). And if it occupies a center active spot, they will not allow any creature to work in the corresponding active spot.
That creates a need for big libraries (or at least well organized workers) to make sure too many researches are not laying in the library.

There are many weak points with this logic. The main ones, IMHO, being:
- When researching costly researches, no entity will be created for many time and, thus, the need for big libraries will decrease with time
- In an allied game, they would allow 1 player to rush for researches and, when he produces a powerfull one, to let his allies steal it while they were focusing on something else (like powerfull creatures).
- It creates a need to handle requirements as described in #577 

So, my proposition is that library should only produce research points. When enough are gathered (for example 50), a grimoire is created. To be used, it has to be brought to the dungeon temple. They can be seen as a resource (like gold) and to research something, a player will need X grimoires.

With this proposition:
- No need to handle research dependencies
- Allied players cannot reserach powerfull spells for other players (even if they still can produce grimoires for other players but if they do not represent too many points, it would require too many workers to bring them to the temple)
- To have a good research rate, big libraries are required from the start to the end (or at least good worker management)

@Bertram25 @akien-mga @Danimal696 @eugeneloza @alketii WDYT ?

**Comment by Bertram25** [comment]
@hwoarangmy IMHO, I think you can now do @OpenDungeons/developers This will be quicker with the growing team. ;)

I'll answer asap.

**Comment by Danimal696** [comment]
sounds good to me, different way and same result, but i wouldnt remove the spell in a book item, so it can be awarded/captured on the dungeon on certain levels

**Comment by Bertram25** [comment]
A bit like crafting points as seen in Dungeon II, I like the logic and it sounds simpler. You have my vote.

**Comment by hwoarangmy** [comment]
> i wouldnt remove the spell in a book item, so it can be awarded/captured on the dungeon on certain levels

I agree it would be a good thing to keep. However, I think we could group that with the "gift box" we are planning to do.

**Comment by akien-mga** [comment]
I think this is a sane proposal; we might also want to extend it to the workshop, so that the library produces grimoires, the workshop produces toolboxes, and both are resources that can be used for research and crafting.

**Comment by Bertram25** [comment]
> I think this is a sane proposal; we might also want to extend it to the workshop, so that the library produces grimoires, the workshop produces toolboxes, and both are resources that can be used for research and crafting.

Hmm, we already discussed about not using the crafting points. So, what is the team favourite concept for crafting here?
Do we want two separate logic for trap crafting and research (IMO, why not.) or do we want the same kind of system for both (IMO, why not, too but the logic has to be changed again...)

WDYT all?

**Comment by hwoarangmy** [comment]
Since this issue will be closed by my PR about library logic, I open a new one for the workshop: #835
