### ISSUE TITLE
Video renderer's options should be auto-added to the videosettings menu.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#822]
As discussed a bit earlier with @hwoarangmy , when choosing/changing a renderer, the settings should list all the renderer's options and added them with default values in the video settings + auto-create widgets on need there.

This way, one will be able to fully configure the video renderer based on its capabilities.

**Comment by hwoarangmy** [comment]
Just for the remind, the reason is that render options are render specific and may not be compatible (For example, video resolution string for OpenGL render is not compatible with D3D renderer).
