### ISSUE TITLE
Should we auto-claim borders?

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#824]
If you have a look at this picture;
![route1](https://cloud.githubusercontent.com/assets/765917/8269163/6892e49c-179e-11e5-9ff2-4fc1fbd7c4ba.png)
You can see that corners aren't claimed and are creating a visual glitch. The models being adapted or not.

I thus propose that corners get claimed if they can be at the moment the last tile next to it is claimed.
Feel free to discuss whatever is needed. :)

**Comment by hwoarangmy** [comment]
Note that fully linked claimed tiles currently are squares (you can see them by opening scream in the dark) and are not vey nice in this configuration.
@Danimal696 WDYT ?

**Comment by Danimal696** [comment]
try making a fully linked claimed wall, but surrounding it with dirt walls (four sides only), the result is a lot of empty corners with just the superior claimed tile, thats the reason i made it a full square

**Comment by hwoarangmy** [comment]
> the result is a lot of empty corners with just the superior claimed tile, thats the reason i made it a full square

Yes, I see perfectly what you mean and why you did it that way. But if we autoclaim corner walls, that's the result we will have

**Comment by Danimal696** [comment]
its not that bad imo

**Comment by hwoarangmy** [comment]
Well, you are the artist ^^
If you are ok with it, I agree.

**Comment by Bertram25** [comment]
So if I understand enough of it, there is no actual need to claim corners as it won't improve the current situation much?

**Comment by Danimal696** [comment]
it would be a nice touch nontheless, and if its easy to do, why not?

**Comment by Bertram25** [comment]
Well, to be completely honest, I'm completely in favour of it. And if we can upgrade the tileset to look cool with, it's even better.
So if you're ok about it, it has my vote. :)

**Comment by hwoarangmy** [comment]
I've had a look at @Danimal696 new full claimed tile but it looks like a dirt tile and do not fix the glitch. Is it worth auto claiming border tiles ?

**Comment by Bertram25** [comment]
> I've had a look at @Danimal696 new full claimed tile but it looks like a dirt tile and do not fix the glitch. Is it worth auto claiming border tiles ?

Hey @hwoarangmy :) I hope your few days away were fun: ;)
You will probably have to recall me something first. @Danimal696 said he fixed the claimed1111, so if I understand well, claimed corner walls are believing every direction is a wall of the same type? (I don't really remember and lazily didn't check but now we're speaking about it, I believe not.)
If I'm right, there would be several other "corner" cases, right?

**Comment by Danimal696** [comment]
yes, there are still empty corners, but i dont think this is something easy to fix

**Comment by hwoarangmy** [comment]
> I hope your few days away were fun: ;)

Yep, it was nice, thanks ^^

> claimed corner walls are believing every direction is a wall of the same type?

Yes. And there is no way ATM to allow them to link to claimed tiles only that will not break the link between full claimed tiles and full dirt tiles.

> yes, there are still empty corners, but i dont think this is something easy to fix

Yep, I also don't see an easy way to do it. And I would add that it might need to change the tileset logic so I'm not sure it is worth doing it for such a small glitch. However, I think the new full claimed tile is better than the previous one ^^

**Comment by Bertram25** [comment]
Hmm, then let's forget about that one for now. We have much more interesting to add and fix. ;)
