### ISSUE TITLE
Dropped minions handling improvement.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#833]
The dropped creatures are atm teleported on ground fresh and sound....
Hmm, this is not the OpenDungeons way of things. ;)

As discussed, they should drop or appear on ground ko (using the dead/ko animation) for 2 seconds before getting up and starting to move again.

They shouldn't lose HP as  we might end up by killing creatures when trying to save near dead ones.

**Comment by hwoarangmy** [comment]
Fixed by #936
