### ISSUE TITLE
Workshop logic

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#835]
In #817, we decided to change library logic so that library produces books that represents a fixed amount of points and that workers have to bring to the dungeon temple. Once enough points are gathered, the pending research is unlocked.

In the issue, @akien-mga proposed to use the same logic for workshop:

> we might also want to extend it to the workshop, so that the library produces grimoires, the workshop produces toolboxes, and both are resources that can be used for research and crafting.

ATM, workshop produces items that will activate a trap of the corresponding type. We can see that we have the same problem as we had for libraries; if you produce advanced traps (that require more points), you won't need as many workshops as if you build basic ones (because more crafted items will be generated). That being said, the problem is not as big as for library since it won't allow to unlock an advanced research for another player.

@OpenDungeons/developers WDYT ?

**Comment by Danimal696** [comment]
but then the toolboxes would be stored in the Hearth? limitless storage? i would make it so they can only be stored into the workshop until used, so they take working places and eventually leaves no place for working until used (or selling workshop and building elsewhere<-cheating rigth here?), and then the kobolds have to make several travels to build a complex trap

**Comment by Bertram25** [comment]
I agree being consistent in the way we make ressources available is the way to go so using grimoires to obtain crafting points? Ok for me. :)
Now, we need to make such resource limited and show it in the gui IMHO.
I don't mind if the resources are vanishing in the heart as many rts do that anyway.
As for the resource limit per type, maybe it can depends on skills?

**Comment by Danimal696** [comment]
i actually wouldnt change the current workshop logic, it feels more realistic and satisfactory than just some generic crafting point numbers. But i guess we have to agree in here to it.

**Comment by hwoarangmy** [comment]
> but then the toolboxes would be stored in the Hearth?

That's what would have to be decided. IMO, it would be better to bring them to the trap like is is done ATM (but it would be an craft item and you will need 1 or more to activate a trap). I don't see the point of bringing them to the dungeon heart.

> or selling workshop and building elsewhere<-cheating rigth here?

Well, you would loose half the workshop price. That's expensive enough IMHO to not need another penalty.

> i actually wouldnt change the current workshop logic, it feels more realistic and satisfactory than just some generic crafting point numbers

We have a working logic ATM that is IMHO, satisfying (it doesn't have the bad points from the old library logic and, thus, changing is not mandatory). If we don't have a strong agreement to change, I think we shouldn't.

**Comment by Bertram25** [comment]
> We have a working logic ATM that is IMHO, satisfying (it doesn't have the bad points from the old library logic and, thus, changing is not mandatory). If we don't have a strong agreement to change, I think we shouldn't.

Again, if the current logic is sufficient for everyone, let's not change. My overall point is that we should either change when it fails to satisfy you guys, and in that case, stay consistent, or do not change if we find it good as is.
I don't care if we take one or the other road.

**Comment by Bertram25** [comment]
> i actually wouldnt change the current workshop logic, it feels more realistic and satisfactory than just some generic crafting point numbers. But i guess we have to agree in here to it.
> 
> We have a working logic ATM that is IMHO, satisfying (it doesn't have the bad points from the old library logic and, thus, changing is not mandatory). If we don't have a strong agreement to change, I think we shouldn't.

I'd say: Let's not change it. Ok for you guys?

**Comment by hwoarangmy** [comment]
ok. I close the issue then
