### ISSUE TITLE
Update release notes for 0.6.0

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#845]
As usual, #540 can be used as a basis. The issues and pull request history might be useful too.

**Comment by Bertram25** [comment]
@akien-mga IMHO, you're done with that one. My turn I guess. :) Ok to close?

**Comment by akien-mga** [comment]
I'm just keeping it open to remember to add the latest changes before the release (incoming research buttons, etc.). But you can start on the announcement indeed :)

BTW I did not mention the cool new documentation that you wrote, nor the move to TF in the release notes (as they are more related to actual game features IMO), but we should probably mention both in the release announcement.

**Comment by hwoarangmy** [comment]
> as they are more related to actual game features IMO

Yep. IMHO, release notes should not mention TF or documentation progress.

**Comment by Bertram25** [comment]
Ok, I'll be on the announcement notes asap. :)
