### ISSUE TITLE
New multiplayer map with dungeon ruins

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#847]
At first I planned to make a skirmish map now that we are separating skirmish from "lan solo", and we have little skirmish-only maps. But without scripting skirmish maps are kind of limited anyway, so I'll just create another cool multiplayer map for the time being.

My idea would be a map with dungeon ruins in the middle, where there would be patches of rogue rooms, some rogue portals to claim, maybe gift boxes.

Note that if this issue is the last blocker for 0.6.0, I won't be bothered if we move it to the next milestone ;-) But I'll try working on it asap.

Feel free to throw in ideas for this map :-)

**Comment by Bertram25** [comment]
I wonder whether you could also add a wave portal with low level creatures getting out of it not too often, to create more a distraction than a threat to keepers. IMHO, that would outline the feature well and make it more dynamic even with several games.

**Comment by akien-mga** [comment]
> I wonder whether you could also add a wave portal with low level creatures getting out of it not too often, to create more a distraction than a threat to keepers. IMHO, that would outline the feature well and make it more dynamic even with several games.

Yeah great idea. I already planned to put rogue creeps in the ruins, but I could also had one or two low level wave portals so that those creeps get reinforcements :)

**Comment by hwoarangmy** [comment]
Note that portal wave always try to attack the closest dungeon. So, if you add 1 per player, they should attack only him (unless he turtles).
