### ISSUE TITLE
Add a button to grab fighters easily in the menu

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#85]
- Most leveled creatures first ?
- Better creatures first (creatures with best stats) ?

**Comment by hwoarangmy** [comment]
We should also kep in mind that this code will probably be shared with the AI

**Comment by Bertram25** [comment]
- Most leveled creatures first ?
  IMO, nope. :)
- Better creatures first (creatures with best stats) ?
  Not the "best stats" as it's hard to describe, but rather I'd say:
  The healthiest of the highest level not already fighting & not already taken.
  If no more not fighting left, take the rest in the level reverse order, IMO.

Later, next to that button, we'll probably want to add a button per creature type, for thiner needs, IMO.

**Comment by hwoarangmy** [comment]
I had not thought about health but I totally agree this is a key point here.

> highest level not already fighting & not already taken.

That's what I meant with "Most leveled creatures"

> Later, next to that button, we'll probably want to add a button per creature type, for thiner needs, IMO.

This feature will be usefull anyway to take units for AI players. But you are right we should keep in mind to give support to filter with creature types as the conditions will probably be the same.
BTW, that also means you will need to keep in mind that there will be changes in the UI according to your creatures definition file (adding an icon for each, ...)

**Comment by Bertram25** [comment]
> BTW, that also means you will need to keep in mind that there will be changes in the UI according to your creatures definition file (adding an icon for each, ...)

Yep, even more: In a perfect world, the creature/rooms buttons will be left aligned. So their positions may vary in time.
Maybe later we'll have to create buttons just like we create stats window, of find a good mix.

**Comment by Bertram25** [comment]
Assigning to @hwoarangmy and milestone 0.4.9 since he's done it. :)

**Comment by hwoarangmy** [comment]
I had forgotten this thread and the logic is slightly different. See #259 for more info. Anyway, this can be changed at will if we think it needs to.
