### ISSUE TITLE
Research queue handling by default

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#851]
ATM, the research queue is defined in the level by default.
That means that if we add a new spell and want it to be in the research queue in every level, we need to edit all of them.
That seems like a problem to me. IMHO, we should turn the ResearchPending level tag optional. If it is present, the queue is used as it is ATM. If it is not, we should decide what we want:
1 - No research per default. That means that if you build a library, nothing will be started by default
:+1: Same behaviour as workshop. We would also display a message when the research queue is empty BTW
:+1: If a player rushes for some tech, he would be noticed if the queue becomes empty as it would be the natural behaviour.
:-1:  New players might be surprised that creatures do not go to the library by themselves if they do not set the research queue
:-1: Might be annoying for players to have to define the research tree at every game start
:-1: We have to decide the order of the researches for AI by default and to code it

2 - We fill all researches by default. Best would be to fill it on a generic way so that when we add a new research, there is no need to worry about adding it to the queue.
:+1: At game start, you don't have to bother with researches. Once you build a library, you can go on
:-1: Players might not understand that they can change the research queue
:-1: We have to decide the order of the researches by default and to code it

Both solutions could work. For my part, I will be for solution 1 because it is a strategyc game (and researches are the most important strategy changer). Moreover, we would not influence players to go one way or the other.

@OpenDungeons/developers WDYT ?

**Comment by Danimal696** [comment]
both? we do by hand and we could also add a few butttons that resemble a path\specialization  (military, common, magic) with just the main skills of each, forgetting the branching ones (so we dont have to recode it each time the research topics are changed, just one at final release or big changes on trees)

**Comment by hwoarangmy** [comment]
Yes, a button to automatically fill paths may be nice once we have enough game content.
But we can always associate each researchs with a specialization and, if the player clicks a the button for the given path, select all researches flagged (including dependencies, being on the same path or not).

**Comment by Bertram25** [comment]
I agree with @hwoarangmy . It is dead easy to set a path to a research now. Just click on the research  if not set and everything will set up automatically.

I'm for a evil mix of 1 and 2:
- The research queue is empty at start.
- An auto-research button is added. It will choose a research completely at random each time a research is completed. The button can be activated/deactivated at will but is disabled or enabled based on user config at startup.
- The fact that the researches are chosen at random makes them not very relevant but ease the pain for new players and give them a chance...
- Once you have a library, periodically, you are reminded you have researches awaiting your command. (like other warnings) Let's say once the research queue is empty (when there are researches to do, of course), and every 3-5 minutes, if the auto-research is not enabled.
- Auto-research doesn't get in the way if you set researches by yourself, only if there are none.

**Comment by Danimal696** [comment]
+1 i like that

**Comment by akien-mga** [comment]
Strategically-speaking I'm more for 1 too. I like @Bertram25's 1 and 2 evil mix, it looks a bit like how it would work in other strategy games with a research tree like in the Civilization series: it's up to you to define your research strategy, but you can also make it automatic IIRC.

The auto-research button should only pick at random between researches that are directly available in the skill tree IMO (i.e. not pick at random a tier 3 research when starting the game, only tier 1).

**Comment by hwoarangmy** [comment]
> An auto-research button is added. It will choose a research completely at random each time a research is completed. The button can be activated/deactivated at will but is disabled or enabled based on user config at startup.

What about a button that would choose all not already selected available researchs randomly ? It would not add a new functionality while a button that would choose a research only when another 1 is finished will. Moreover, it will allow you to set some research you really want and then, to fill randomly the others.

I agree on all other points.

**Comment by akien-mga** [comment]
> What about a button that would choose all not already selected available researchs randomly ?

Yeah actually that sounds better. Choosing everything at random little by little makes for somewhat unpredictable games, and thus does not go in the way of advanced tactics.
On the other hand a "lazy fill" button sounds pretty good: you can see directly what the game plans for you, and if you don't like it, you can change it again.
