### ISSUE TITLE
Portal wave AI configuration

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#855]
Thinking about #847, I got an idea on how to make the portal wave more interesting in various scenarios. IIUC, the current AI will locate the nearest player, and send waves towards him at regular intervals.

That means that to get a fair multiplayer map using portal waves, we'd need one portal wave per player. So I thought about making the portal wave choose for each wave a random target among the players within range. I don't know if the range of the portal wave is currently limited, but that could also be a nice addition to control its behaviour.

So we could have several behaviours:
- Attack the nearest player (current behaviour)
  - If a range is defined, we only attack the nearest player if he has claimed tiles in range. If not, we send no waves and just spawn some idle creatures.
  - If no range is defined (unlimited range), we attack the nearest player regardless of how far he is on the map.
- Attack any player in range
  - If a range is defined, we attack only the players in range; the target is chosen randomly among the players in range at each wave.
  - If no range is defined, we attack any player on the map, chosen randomly for each wave.

So in the config, we would need to new parameters:
- Attack behaviour: "Nearest" or "Random"
- Range: A number of tiles or unlimited (-1 maybe?)

WDYT?

**Comment by Danimal696** [comment]
i love it, i want to see the undergroung become an ant farm crawling with coming and going ferals

**Comment by Bertram25** [comment]
> If a range is defined, we only attack the nearest player if he has claimed tiles in range. If not, we send no waves and just spawn some idle creatures.

For the record, this is not part of the currently implemented behaviour, at least AFAIK.

Adding a range is a fun option and random target is cool, too! :)
I would even be for a third option: A fixed Team ID target. All allies in team X.
