### ISSUE TITLE
GUI: Visually show the cooldown on spells buttons

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#858]
Let's try to achieve that before release.
This will be based on the solution used for research button as seen in: #857

**Comment by hwoarangmy** [comment]
It should not be too hard since cooldown is already handled on client side (through cooldown time display)

**Comment by Bertram25** [comment]
Cool, could be done rather quickly then. :)

**Comment by akien-mga** [comment]
That would be a really cool addition indeed :)

**Comment by Bertram25** [comment]
I'll still work on that part in my next PR. (Even if I know I'm slow at making things lately. :])

**Comment by Bertram25** [comment]
Created #882
