### ISSUE TITLE
Add room availability level parameter support (boolean)

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#86]
This is a level parameter, telling which rooms can be built in this map by the different players/AI.

Note that it says 'can be built', not 'already built' when starting the map.

It will be useful to later create a certain challenge on certain maps, will make possible to disable certain rooms at the beginning of the campaign for tutorial purpose, and will permit to disable unfinished/useless rooms when doing a release.

The corresponding room buttons will be hidden when the room isn't available.

**Comment by akien-mga** [comment]
I guess we want this to be player-specific too (or faction-specific?). Especially in campaigns, there might be cases where we want the player or some AI to have or not have special rooms. We might also want this so that different factions have different rooms (i.e. adventurers would likely not have a torture room, but maybe a tavern instead?).

**Comment by hwoarangmy** [comment]
> I guess we want this to be player-specific too (or faction-specific?).

Good point

**Comment by hwoarangmy** [comment]
We might also allow the level to redefine the creature def, for example to decrease the maximum level each creature can reach.
The logic would be to read the creature definition file and then, if the level overwrites a part of it, to use theses instead.

**Comment by Bertram25** [comment]
> I guess we want this to be player-specific too (or faction-specific?).

indeed, player specific, for tutorial purpose.

> We might also allow the level to redefine the creature def, for example to decrease the maximum level each creature can reach.
> The logic would be to read the creature definition file and then, if the level overwrites a part of it, to use theses instead.

True and fine as well.

**Comment by hwoarangmy** [comment]
> indeed, player specific, for tutorial purpose.

Or for campaign purposes. We could allow the AI to use more advanced units than the player...

**Comment by Bertram25** [comment]
> Or for campaign purposes. We could allow the AI to use more advanced units than the player...

Ah, indeed. To me, campaigns are big and fun tutorials functionally speaking. ;)

**Comment by Bertram25** [comment]
As discussed in #9, we'll do that later.
