### ISSUE TITLE
Output info in the log/stderr when having problems parsing levels

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#862]
Currently, when a level file is badly formatted and can't be parsed (in my case I had a tag written `Waves]` instead of `[Waves]`), the log/stderr does not give really useful information:

```
Couldn't start server. The level file can't be loaded: /home/akien/Projects/opendungeons/OpenDungeons-akien/levels/multiplayer/RuinsOfTheConfluent.level
ERROR: /home/akien/Projects/opendungeons/OpenDungeons-akien/source/modes/MenuModeEditor.cpp line 193 Could not start server for editor !!!
```

If it would be possible to give a hint about the parsing error in the log, it would be great. I don't expect something as well defined as what a compiler would do, but maybe we could tell which line could not be parsed, or what was the last well-formatted information that could be parsed.

**Comment by hwoarangmy** [comment]
If the error is with waves, you should have had an error log:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/rooms/RoomPortalWave.cpp#L374
However, when something fails, the level continues to be read and usually, other errors are printed.

The problem with displaying line number is that the first thing done within map loading is to remove the empty lines and the comments. Thus, line number are lost in the process. Changing that may not be that straightforward...

**Comment by akien-mga** [comment]
Ah indeed I overlooked the error message which was earlier in the log:

```
ERROR: /home/akien/Projects/opendungeons/OpenDungeons-akien/source/rooms/RoomPortalWave.cpp line 374 RoomPortalWave=PortalWave1, str=Waves]
```

If there are similar mechanisms when encountering other parsing issues, I get this bug report can be closed.

**Comment by akien-mga** [comment]
> If there are similar mechanisms when encountering other parsing issues, I get this bug report can be closed.

Looks like there are, e.g.:

```
WARNING: expected [ResearchPending] and read [/Seat]
```

This one should maybe be changed to an error btw, as it prevents loading the level altogether (at least in the editor).
