### ISSUE TITLE
Show human readable spell name next to the tile selector instead of code name

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#863]
Currently when casting a spell like "Summon worker", the tooltip next to the tile selector shows "summonWorker" (same for other spells). It would be nice to display "Summon worker" instead.

I'll assign to myself as it seems a relatively easy task. We'll see ;-)

**Comment by akien-mga** [comment]
Looks like the fix was simpler than I thought.
@hwoarangmy @Bertram25 Could you confirm that the above change is harmless, or will it break something in the spell manager logic?

From what I could see the spell name is only used in SpellManager::getSpellTypeFromSpellName, which itself is never used. And it's argument is a const std::string&, so I guess using "human-readable" names (e.g. with spaces) won't be an issue when using it either.

**Comment by akien-mga** [comment]
I've looked a bit more, and though it does work for spells, if I do the same change for the TrainingHall room (by changing its name to "Training Hall"), it breaks the logic for e.g. config/spawnconditions.cfg where "TrainingHall" is used to retrieve the room type.

What are your thoughts about this issue? Should we keep "engine" names like "summonWorker" and "TrainingHall", and also declare a (sometimes redundant) "print name" to display in the UI (and later in scripts, etc.)?

I guess the topic is wider than I thought initially, as it probably also concerns creatures (e.g. PitDemon).

**Comment by akien-mga** [comment]
Note that I removed 34b5b93 from my fork to prevent pushing it in my current PR, as I believe my proposed change is not as good as I thought it first.

**Comment by hwoarangmy** [comment]
As you already noticed, the registred name is also used to retrieve the spell type from the name (as in the RoomManager and in the SpellManager) in SpellManager::getSpellTypeFromSpellName.
However, for spells, it is not used. But for handling it in a more generic way, the simpler would be to add a new string parameter in the register function and save for each a "readable name". Then, we just have to use this parameter instead of the name.
And that can also be done for rooms/traps if we want.

**Comment by akien-mga** [comment]
Yes I agree, that seems to be the cleaner solution if we want to keep "shortnames" like TrainingHall or PitDemon for the config files, while displaying a different name in game.

**Comment by hwoarangmy** [comment]
@akien-mga If I'm not mistaken, that's the last code release blocker for 0.6.0. If you want, I can take it so you can focus on the last other tasks for the release and we can build a RC1 ^^

**Comment by akien-mga** [comment]
Sounds good to me; I'll get started on the release announcement to help @Bertram25 :)
