### ISSUE TITLE
Save the open/closed status of doors in the level file

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#864]
Unless I'm mistaken, we can't save the open/closed status of door currently. All doors will open themselves when you start a saved game or a map with doors already placed.

For the map I'm making, it would be cooler that the doors are closed when the game starts.
The feature is needed both for saved games (keep state as it was when the game was saved) and for the editor (allow to define the status of a door with a slap).

**Comment by hwoarangmy** [comment]
I confirm the door state is not saved in file ATM

**Comment by hwoarangmy** [comment]
I've had a look and I've seen an architecture problem with traps. Traps are expected to be defined 1 line per tile with optional data following. That means that the door state should be expected to be at the end of the trap definition. But when we read a trap, we call the tile activate method just after loading it (before loading trap specific data). For the record, the real fix would be to load all the trap data and do specific stuff after. A good way to do that would be to use a trap static function to load a trap from stream and let export/import to stream function be protected (actually, that would be good to do that for all game entities as it is the best way I've found so far from the tries I've done).

Of course, we can easily work around that for this specific door problem. But I will see if I can do the real fix soon and, if not, I will do a workaround.
