### ISSUE TITLE
Notify player when the research queue is empty

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#869]
As discussed previously, a notification should be sent to the player when the research queue is empty, in a similar way as done for the lack of treasury tiles.

It sounds relatively easy to do, so I'll take it.

**Comment by akien-mga** [comment]
For the reference, the fix should probably be similar to #435.

**Comment by Bertram25** [comment]
@akien-mga Thanks for getting more in the dirt for the project. :)

**Comment by akien-mga** [comment]
> Thanks for getting more in the dirt for the project. :)

Thanks for letting me use our project as a learning material, and mentoring me on the way ;)

**Comment by Bertram25** [comment]
I guess this is done.! Congrats. :)

What's left is to check whether the player has got a library before complaining.
Should we also disabled the library panel until the player has got a library (in the menus and on the UI)?

**Comment by hwoarangmy** [comment]
> Should we also disabled the library panel until the player has got a library

I would say no as it allows to choose researches at the beginning of the game, when there might be not much to do.

**Comment by Bertram25** [comment]
> I would say no as it allows to choose researches at the beginning of the game, when there might be not much to do.

Good point.

**Comment by akien-mga** [comment]
> What's left is to check whether the player has got a library before complaining.

The problem with this is that the current logic triggers the warning only when defining the next research; so if we don't trigger the warning when the player defines an empty research queue without a library, the warning won't get triggered after the library is built.
We could of course also add a check in the function called when creating the library, or find a better logic altogether.

**Comment by Bertram25** [comment]
> The problem with this is that the current logic triggers the warning only when defining the next research; so if we don't trigger the warning when the player defines an empty research queue without a library, the warning won't get triggered after the library is built.
> We could of course also add a check in the function called when creating the library, or find a better logic altogether.

IMHO, as the warning is periodically triggered whatever the library state is, I guess adding a check to silence the warning whenever there is no library before triggering it may be the way to go.
(I mean maybe you can disable the visual warning in that case without disabling the whole periodical check?)

**Comment by akien-mga** [comment]
> IMHO, as the warning is periodically triggered whatever the library state is, I guess adding a check to silence the warning whenever there is no library before triggering it may be the way to go.
> (I mean maybe you can disable the visual warning in that case without disabling the whole periodical check?)

That's a good point yes, I'll have a look.

**Comment by hwoarangmy** [comment]
@akien-mga If you want, there is something similar with treasuries (even if in your case, since the message is sent on server side, the client do not need to know if there are libraries or not).
The idea would be to compute the library number in the seat (like it is done for treasuries) and to not check the research tree if the number of libraries is 0.
See Seat::mNbTreasuries

**Comment by hwoarangmy** [comment]
@akien-mga Do you want me to handle the message when no library ?

**Comment by akien-mga** [comment]
> Do you want me to handle the message when no library ?

Feel free to do it, I won't have much time to code before Thursday I think.

**Comment by hwoarangmy** [comment]
ok. I will then
