### ISSUE TITLE
Makes the first treasury tile cost 0, so players/AI can't get stuck without means to store their gold.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#87]
The temple room (the one that makes you lose when destroyed and that is spawning workers atm) should permit to store the equivalent of one Treasury tile.

This is prevent a player from being stuck if all its treasury tiles are destroyed or when starting without a treasury. (as in DK)

An much simpler solution would be to make the first treasury tile cost 0 gold.
What is your favourite solution?

**Comment by akien-mga** [comment]
Integrate it in the temple room would be great if it's coherent with the model (i.e. the temple room should have a dedicated space to hold a bag o' loot :-)

**Comment by hwoarangmy** [comment]
It could be nice to use the dungeon temple but I think it much work for a small use (and do not change the fact of what happens if this particular tile is destroyed but not the whole dungeon temple) ?). A cost of 0 to the first tile will be much simpler...

**Comment by Bertram25** [comment]
At the moment, we haven't got some shiny model yet, even if I know @Danimal696 is on it.

I'd propose this, let's do the simple solution now, and add support for the shiny stuff once we have a good model in place and done more urgent things.

Ok with it?

**Comment by hwoarangmy** [comment]
The more I think, the more I believe the 0 cost first treasury room is the best solution. Otherwise, the dungeon temple handling will be really tricky as we can expect some tiles to be destroyed so we cannot even choose one of them. And the room size may change between games. Moreover, that would also change the gold digging logic as in addition to seraching treasury tiles to drop gold, it will have to check the dungeon's one.

**Comment by Bertram25** [comment]
Ok, let's go for the simple solution, then.

**Comment by Bertram25** [comment]
N.B.: AI will have to be aware of it.

**Comment by Danimal696** [comment]
Hard question, in DK1 the hearth coulndt hold gold, in DK2 it holded over 7 squares surrounding it. 
As i understand we need at least one treasure tile or the kobolds go nuts and do nothing; there is a middle way, and that is adding support on the level file for starting gold per seat, that gold wont have physical presence to speak of, and should be used to set up the treasure room first thing. I say that could work thanks to the workers ai patch, it could even add to the game mechanics making money devoid maps you have to pass with only the initial allowance.

**Comment by akien-mga** [comment]
> As i understand we need at least one treasure tile or the kobolds go nuts and do nothing; there is a middle way, and that is adding support on the level file for starting gold per seat, that gold wont have physical presence to speak of, and should be used to set up the treasure room first thing. I say that could work thanks to the workers ai patch, it could even add to the game mechanics making money devoid maps you have to pass with only the initial allowance.

I understood it more as: if for any reason all your treasury tiles get destroyed, but not your temple room, then you should be able to restart a base (and collect gold) even if you were down to 0 gold.

**Comment by hwoarangmy** [comment]
Well, there is a huge difference between DK and OD : in DK, the rooms were not destroyed, they were stolen.

> adding support on the level file for starting gold per seat

I definitely agree with that. And it would help for debug purposes. But that do not change the fact that if you loose your treasury, you cannot do anything. And since dungeon temple tiles are destroyed like any other, I don't see how we can avoid that.

**Comment by Bertram25** [comment]
> I understood it more as: if for any reason all your treasury tiles get destroyed, but not your temple room, then you should be able to restart a base (and collect gold) even if you were down to 0 gold.

^ What Akien said.

> adding support on the level file for starting gold per seat

This also can be added, but it is not incompatible with the current issue that remains to be done using the first-treasury-tile-0-gold-cost exception.

**Comment by hwoarangmy** [comment]
> This also can be added, but it is not incompatible with the current issue that remains to be done using the first-treasury-tile-0-gold-cost exception.

Starting with gold would help for debugging but it is true that it's tricky since you may have no treasury room at start...

**Comment by Bertram25** [comment]
@Danimal696 Just to make it clear on why we believe more in the 0 gold solution:
First of all, to reserve some gold for the treasury or permitting to cost 0 as first tile is in the end the same thing if the rule is valid for All Keeper seats.
Secondly, we never know what may happen after some time in game, and thirdly, this solution is very simple to add. ;)
I wanted to say that since I wouldn't want you to think we're not listening.

**Comment by akien-mga** [comment]
Nota: We should make sure this is properly documented, so that players know that they can create a first treasury tile even with 0 gold. The question is how? Adapt the tooltip (see issue #89) of the treasury icon when there are no treasury tiles built?

**Comment by hwoarangmy** [comment]
Well, it will be part of the tutorials... once they are done :)

**Comment by Bertram25** [comment]
True, we can also add a quick play guide, later in the wiki.

**Comment by Danimal696** [comment]
Yes, the 0 gold treasury sounds sensible

**Comment by Bertram25** [comment]
I'll add something like that (whenever I'll have the time to.):

``` c++
        case ClientNotification::askBuildRoom:
        {
            int x1, y1, x2, y2;
            int intType;

            OD_ASSERT_TRUE(packetReceived >> x1 >> y1 >> x2 >> y2 >> intType);
            Player* player = clientSocket->getPlayer();
            std::vector<Tile*> tiles = gameMap->getBuildableTilesForPlayerInArea(x1,
                y1, x2, y2, player);

            if(tiles.empty())
                break;

            Room::RoomType type = static_cast<Room::RoomType>(intType);
            int costPerTile = Room::costPerTile(type);
            int goldRequired = tiles.size() * costPerTile;

            // The first treasury tile doesn't cost anything to prevent a player from being stuck
            // without any means to get gold.
            // Thus, we check whether it is the current attempt and we remove the cost of one tile.
            if (type == Room::treasury
                    && gameMap->numRoomsByTypeAndSeat(Room::treasury, player->getSeat()) == 0)
                goldRequired -= costPerTile;

            if(gameMap->withdrawFromTreasuries(goldRequired, player->getSeat()) == false)
                break;

            Room* room = gameMap->buildRoomForPlayer(tiles, type, player);
            // We build the message for the new room creation here with the original room size because
            // it may change if a room is absorbed
            ODPacket packet;
            packet << ServerNotification::buildRoom;
            int nbTiles = tiles.size();
            int seatId = player->getSeat()->getId();
            const std::string& name = room->getName();
            packet << name << intType << seatId << nbTiles;
            for(std::vector<Tile*>::iterator it = tiles.begin(); it != tiles.end(); ++it)
            {
                Tile* tile = *it;
                packet << tile;
            }
            sendToAllClients(packet);

            break;
        }
```

**Comment by hwoarangmy** [comment]
Sounds ok. The server paradigm is nice in cases like that :)

**Comment by Bertram25** [comment]
Ok, I'll test it and will create a pull request asap.
