### ISSUE TITLE
Veteran Scarab is not used in the new map "Ruins of the confluent"

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#878]
A level specific class "VeteranScarab" is defined but the scarabs on the map are simple Scarab, not VeteranScarab. Is it wanted ?

@akien-mga BTW, when you create a level, when it is done, please do not hesitate to open it in the editor and to save it (even without changing anything) to test if map saving is correct. Moreover, it would ensure that everything is sorted as the editor does which is better because if someone changes the map in the editor, he will see his changes only.

**Comment by akien-mga** [comment]
Ah right I forgot to adapt the names of the scarabs, I'll fix that.
When I create levels I often go back and forth from the text editor to the OD editor, but I might have not saved it after my last edits indeed, I'll see if it creates a diff before pushing the rest of the changes.

**Comment by hwoarangmy** [comment]
Note that you should wait for #873 to be fixed or you will need to add the mood modifier manually if you want to keep it.

**Comment by hwoarangmy** [comment]
@akien-mga I confirm the bug about the pick selector sound. In reality the cause is that my fix makes the game load every sound as spacial. And interface sounds are played at position 0,0. That's why it worked on the 2v2 skirmish small test map (because the dungeon is near 0,0 and not in the maps lwhere the dungeon is far.
I've fixed it but I will wait for your PR about your map because it will conflict with my next one.
