### ISSUE TITLE
Hero AI support

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#88]
Add support for an Hero AI that get support of wave of allies and track evil Keeper to kill them.

To beat an Hero AI, you have to kill its portal. (Hero AI have no temple and build nothing.)

Will be useful in campaigns but still fun in coop lan and such. ;)

**Comment by Bertram25** [comment]
Also depends on #12 for enemy heroes waves.

**Comment by hwoarangmy** [comment]
Should we use AS for that (would be a good occasion to test) or define something specific in the level file ?

**Comment by oyvindln** [comment]
The AS part of the code needs to be reworked first if you want to use that, seeing as the server runs in a different thread.

**Comment by Bertram25** [comment]
@hwoarangmy The fact that this AI is scripted or hardcoded depends on how much we can count on the scripting language. I'd say that ultimately the AI should be scripted, but if you don't want to lose time testing both AS and the new AI, it can be hardcoded at first, IMHO.

**Comment by hwoarangmy** [comment]
I'm not talking about scripting the AI (this would require testing performances) but only to use that to spawn hero waves (asI don't see how we can do that currently).
@oyvindln Yes, it shall be done on server side or it would have no effect.

**Comment by Bertram25** [comment]
@hwoarangmy I guess we have to start somewhere. :)
What would be really cool is to give them a destination upon spawn (A keeper temple ;>) and make them dig their way the closest possible, but this can be done in a second step, of course.

**Comment by hwoarangmy** [comment]
yes, I understand that as it is the behaviour in DK. But I think we should decide if we want to define hero portal spawning in code or in AS. If we choose to hardcode, we might also use a different portal than the current one (even if it can use same mesh) and have different behaviour (spawning by wave - and make it configurable).

**Comment by Bertram25** [comment]
> If we choose to hardcode, we might also use a different portal than the current one (even if it can use same mesh) and have different behaviour (spawning by wave - and make it configurable).

I'd be for hardcoding a new portal (and personally I don't care if it's the same mesh, I'd rather have another one to show it's not a keeper's portal.)
This way, adding levels with hero waves would be brain dead easy. Smarter events and AI could come later.

**Comment by Danimal696** [comment]
i have a few new portal models located but they need textures and the like, so dont expect them soon; but anywyas the models are there.

**Comment by Bertram25** [comment]
IMHO, this issue us done with portal wave support.
Ok to close it ?

**Comment by hwoarangmy** [comment]
yep. For the record, it is closed by #594
