### ISSUE TITLE
Spell button refinements

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#882]
Use the seconds per turn member to compute a smooth update of button cooldown progress value.

**Comment by hwoarangmy** [comment]
That's a good idea. I will also take it and see if I can do that before 0.6.0

**Comment by Bertram25** [comment]
Thanks a lot (bis)

**Comment by hwoarangmy** [comment]
Note that smooth cooldown can be done only for spells as it is not linear for researches (since it depends on bringing grimoires)

**Comment by Bertram25** [comment]
> Note that smooth cooldown can be done only for spells as it is not linear for researches (since it depends on bringing grimoires)

Hmm, I guess it depends on how you see the implementation. As for me, a spell button would start from 0 and try to reach the current progress value set when a grimoire has triggered it. Is there something else I didn't see?

**Comment by hwoarangmy** [comment]
ok. So, you want to increase smoothly the research button ?
For example if a research needs 2 grimoires, when the first one is brought, it would fill half smoothly (instead of filling half at once) ?
Note that if it is the case, I don't think it is worth doing that as it will only be visible if you have the research tree open while a grimoire is brought, which is not very likely. So, IMHO, it is too much work for something that most players won't see.

**Comment by Bertram25** [comment]
> For example if a research needs 2 grimoires, when the first one is brought, it would fill half smoothly (instead of filling half at once) ?
> Note that if it is the case, I don't think it is worth doing that as it will only be visible if you have the research tree open while a grimoire is brought, which is not very likely. So, IMHO, it is too much work for something that most players won't see.

Well, I won't push too hard on a feature that is only a small visual and also because you are the one doing the job so far. And this small stuff can be sorted out in 0.7.
(I guess someone should tell me: If you want to see it done, just do it you little mor... ;])

Anyway, here is what is bothering me so far:
When a grimoire is brought to the temple, the research progress is set to, let's say, a 0.6 progress value. The thing is, when you open the research tree, you don't really know whether the progress is heading up or down.
To mitigate that confusing visual, I wondered whether it would be possible to update the progress of the current research from 0 to the current value in a smooth way when the player opens the research window.
This means the progress visual effect will be "played" every time the player opens the window.
Also, the progress update could be made smooth when the progress value has changed, of course.

Nothing urgent, release blocking or whatsoever, but WDYT guys?

**Comment by akien-mga** [comment]
That sounds like a cool idea, if we do that we are really starting to go past the beta stage :-P

**Comment by hwoarangmy** [comment]
ok, that sounds good to me too

**Comment by hwoarangmy** [comment]
I've separated the 2 issues are they are pretty different after all and the spell one is already fixed #894

**Comment by Bertram25** [comment]
> I've separated the 2 issues are they are pretty different after all and the spell one is already fixed #894

Perfect. :) Thanks!
