### ISSUE TITLE
[Technical] - Use a lambda function to list every spells in a more automated way when updating the spell cooldown.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#883]
To be applied on spell buttons cooldown:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/modes/GameMode.cpp#L1399

As it is done here for researches:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/modes/GameMode.cpp#L1392

Also, the new function listing every spells will have to move to the ResearchManager.

**Comment by hwoarangmy** [comment]
I can take this one if you want

**Comment by Bertram25** [comment]
Thanks!

**Comment by akien-mga** [comment]
/me needs to do some reading on lambda functions :-)

**Comment by hwoarangmy** [comment]
> /me needs to do some reading on lambda functions :-)

The concept is pretty simple. Usually, when you use a callback, you need to expose a function with the correct signature and pass it to the API that needs the callback.
When something happens, the callback will be called. The problem with this approach is that you need 1 class (or at least function) for each different behaviour. And that's pretty annoying especially when the behaviour is simple. Moreover, if you need some information that doesn't come from the API when the callback is needed, you need to declare member variables that will be exposed to the whole file (if you have used a function) or at least to the class.

That's where lambda function come. They allow to define a function like if it was a variable. And you can let it have access to the local variables accessible from where it is defined. That allows to have a very short scope. However, the definition is not very easy to understand. But by googling a bit, it is not too hard to find how to use them ^^

**Comment by Bertram25** [comment]
Lambdas are cool to emulate higher level languages calls, do easy callbacks, avoid function pointers, ... But, yeah, it's really not that straight.
