### ISSUE TITLE
Rename the Research* to Skill*

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#884]
The research manager, UI and so on, is in fact a skill thing.

This is a more generic name, fitting more a RPG-ish game and will make it clearer other skills obtained through magic and maybe gold, too? can go there.

**Comment by hwoarangmy** [comment]
> The research manager, UI and so on, is in fact a skill thing.

Seems like a better name, yes.

> other skills obtained through magic and maybe gold, too?

Why not ? But as a second step or if someone really wants to bite this as it is not something required for a first release

**Comment by Bertram25** [comment]
> Why not ? But as a second step or if someone really wants to bite this as it is not something required for a first release

Yep, I agree. :)

**Comment by akien-mga** [comment]
Sounds good to me.
