### ISSUE TITLE
Sounds - Normalize, monoify the new sounds, use ogg, and maybe a few other tricks

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#885]
This is a blocker for 0.6, after: https://github.com/OpenDungeons/OpenDungeons/pull/876

Related to #126

**Comment by akien-mga** [comment]
I wonder, should we not use WAV instead of OGG for short sound effects?

**Comment by hwoarangmy** [comment]
wav are much bigger than ogg and the repo will grow much if we do that...

**Comment by akien-mga** [comment]
> wav are much bigger than ogg and the repo will grow much if we do that...

That's true, I just did a quick test converting all ogg files in sounds/ to wav, and the way files are about 10 times bigger, so the folder goes from 1.6 MB to ~15 MB. I haven't had a look at the wav quality setting though, maybe it can be brought down; but anyway if ogg is good enough, no need to use wav indeed :)
