### ISSUE TITLE
Keyboard not working 

### ISSUE THREAD

**Issue by tomluchowski** [OpenDungeons/OpenDungeons#887]
After a few minutes of gameplay the keyboard stops working, and I cannot do any action via keyboard (camera hoovering , rotate, etc. )

**Comment by Bertram25** [comment]
Cannot reproduce here, and I do use keyboard a lot while playing.
Is it systematic?

**Comment by akien-mga** [comment]
I'd suspect a conflict with the window manager regarding keyboard grab. Maybe you hit a key combination like Alt+Tab or the Windows/Desktop key that would make the window lose focus, and thus lose keyboard grab?

**Comment by tomluchowski** [comment]
> Is it systematic? 

You mean does it always happens ? Well on that system sometimes  works a few seconds than it stops.
The game is compiled without the OD_NO_LINUX_KEYBOARD grab.

**Comment by tomluchowski** [comment]
How do I close issue liike this one ? 
Now it works again after setting to grab mouse and keyboard.

**Comment by Bertram25** [comment]
> How do I close issue liike this one ?

You can click on the 'Close Issue' or 'Close and comment' button.

> Now it works again after setting to grab mouse and keyboard. 

Did something change in your setup for this to work?
