### ISSUE TITLE
Segfault when when calling CEGUI::Window::getProperty

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#889]
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/modes/GameEditorModeBase.cpp#L259

We call the templated version of getProperty that returns a PropertyHelper<T>::return_type:
http://static.cegui.org.uk/docs/0.8.3/classCEGUI_1_1PropertySet.html#ad5f30fae4570428877a3ba832cb93586

 In reality, we want a CEGUI::String so we could call:
http://static.cegui.org.uk/docs/0.8.3/classCEGUI_1_1PropertySet.html#af7cfc649d1dbe40b42e7d4dea87888aa

I've setup a new environment with a MinGW-64 compiler. And I get a segfault when calling the function as said. Is there a reason to not call the second function ? I guess the reason why it segfaults now and not before is that for some reason, there is an automatic cast or something similar that goes wrong here.

@Bertram25 Do you know why we use the first version and not the second ? Do you think there would be a downside if we change ? My guess is that we had luck and the compilers we use could hide the problem but I'm not sure using the first version is correct.

**Comment by Bertram25** [comment]
> @Bertram25 Do you know why we use the first version and not the second ? Do you think there would be a downside if we change ?

It must be my past self doing weird stuff. There is IMHO no downside in using the CEGUI::String getProperty() function, and you're right, this have to be changed as proposed.
My apologies for that small mistake leading to build failures... :S

**Comment by hwoarangmy** [comment]
> My apologies for that small mistake leading to build failures... :S

No problem. It is common for us all to do such things when using a library we are not used to ^^
Moreover, cegui is not the best documented library I've ever seen (functions are pretty well documented but not how they should be used).

I will fix that then as I'm already on it ^^

**Comment by Bertram25** [comment]
Done with https://github.com/OpenDungeons/OpenDungeons/commit/3f6ab7caf06a9baea706951a4be10aafea840bea
