### ISSUE TITLE
Add a tooltip showing the price of a room tile/trap when hovering its icon

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#89]
As the topic says. For now it's by trial and error that you know whether you can place a room tile.

**Comment by hwoarangmy** [comment]
Yes, we could add in the text showing the room name the total price of the room.

**Comment by akien-mga** [comment]
> Yes, we could add in the text showing the room name the total price of the room.

Ah indeed it could be done like that too. Or both :-)

**Comment by Bertram25** [comment]
IMHO, both.

When selecting the room, its price should be indicated next to the name.
When in the process of adding a room (mouse dragging), the total price should be shown.
Later, we'll probably want to color the stuff depending on whether it's possible.

**Comment by Bertram25** [comment]
0.4.9 or later? (Might be trickier than it sounds... or not.)

**Comment by hwoarangmy** [comment]
doesn't sound that tricky. If it reveals to be, we could just forget for now :)

**Comment by Bertram25** [comment]
Doc for default CEGUI tooltip implementation:
http://cegui.org.uk/wiki/Tooltips
http://static.cegui.org.uk/docs/0.8.4/classCEGUI_1_1Tooltip.html

I'll deal with improving the skin once we have it in-game.

**Comment by Bertram25** [comment]
As discussed with @hwoarangmy , the CEGUI button icon tooltip part is moved to 'Later' for now.
As he said, all the necessary code is here to show cegui system tooltips, yet they won't show for an unknown reason. This will have to be investigated.
And if we can't display them that way, we will have to add a custom text overlay and use it as tooltip.

**Comment by Bertram25** [comment]
Reopening as the hover tooltip part isn't done yet.

**Comment by Bertram25** [comment]
Note to self or anyone, for later use when fixing this:
I've looked at that by pure fanciness:
First problem I have seen is that in Gui.cpp, we're using:

``` c++
CEGUI::System::getSingleton().getDefaultGUIContext().setDefaultTooltipObject(new CEGUI::Tooltip("OD","Tooltip"));
```

Which creates a memleak and isn't the preferred way to do that. We should instead use AFAIK:

``` c++
CEGUI::System::getSingleton().getDefaultGUIContext().setDefaultTooltipType((CEGUI::utf8*)"OD/Tooltip");
```

As it will handle the tooltip internally, and log if there is an error when creating a valid tooltip object.

Secondly, in ODFrameListener, the injectTimePulse() method should also be called on the default gui context. This line is missing next to the existing one:

``` c++
CEGUI::System::getSingleton().getDefaultGUIContext().injectTimePulse(evt.timeSinceLastFrame);
```

This may or may not fix the problem but at least can't hurt.
