### ISSUE TITLE
Code snippet which does not work

### ISSUE THREAD

**Issue by tomluchowski** [OpenDungeons/OpenDungeons#891]
How one is supposed to move the camera ?
putting that snippet onto end of  :  bool GameMode::mouseMoved(const OIS::MouseEvent &arg):

```
if (!inputManager.mDirectionKeyPressed)
{
if (arg.state.X.abs == 0)
    frameListener.moveCamera(CameraManager::moveLeft);
else
    frameListener.moveCamera(CameraManager::stopLeft);
if (arg.state.X.abs == arg.state.width)
    frameListener.moveCamera(CameraManager::moveRight);
else
    frameListener.moveCamera(CameraManager::stopRight);
if (arg.state.Y.abs == 0)
    frameListener.moveCamera(CameraManager::moveForward);
else
    frameListener.moveCamera(CameraManager::stopForward);
if (arg.state.Y.abs == arg.state.height)
    frameListener.moveCamera(CameraManager::moveBackward);
else
    frameListener.moveCamera(CameraManager::stopBackward);
} 
```

From what I understand many commmits ago the function moveCamera(CameraManager::Direction) has been heavily changed , so now this snippet does not work, any ideas how that could be merged into ?This would require some smart debugging , for what I found so far is moveCamera is really called when putting mouse cursor on the edge ....

**Comment by akien-mga** [comment]
Maybe check the CameraManager? https://github.com/OpenDungeons/OpenDungeons/blob/development/source/camera/CameraManager.cpp#L437

**Comment by Bertram25** [comment]
Is this question still valid or was ruled out as per discussion in #892 ?

**Comment by akien-mga** [comment]
Judging by @tomluchowski's PR, it looks like he found out that the moveCamera function needs to pass two arguments now.
