### ISSUE TITLE
Make workers flee only when receiving first enemy blow.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#90]
It has been discussed on the forum that the workers should continue to work until they get damage (or at least until an enemy actually attacks it).

In the small map, it is quite obvious that there is something weird with the current behaviour as it is really hard to get workers claim tiles when they are not far from the enemy base.

**Comment by Danimal696** [comment]
maybe its related to the treath system you once described?

**Comment by Bertram25** [comment]
> maybe its related to the treath system you once described?

Can you elaborate?

**Comment by Danimal696** [comment]
i remember you saying creatures calculate threat levels on each tile depending on enemy proximity, so are they constantly running away because of how small the map is?

**Comment by Bertram25** [comment]
> i remember you saying creatures calculate threat levels on each tile depending on enemy proximity, so are they constantly running away because of how small the map is?

Ah yes. In battleField.cpp. Indeed, a threat value is computed according to enemies / allies proximity ratio. Indeed, it surely is.
EDIT: And that's what we try to work around, through this feature.
