### ISSUE TITLE
Heal spell can be cast on full health creatures

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#903]
I've tested the heal spell and seen it can be cast on full health creatures. At is a regression (maybe from the SpellManager). Since during battle, creatures tend to be all on the same tiles, it will be pretty hard (and costly) to cast heal spell if it targets every creature including healthy ones...

If everybody agrees, I will make a patch tonight

**Comment by Bertram25** [comment]
I fully agree.
