### ISSUE TITLE
Bugs seen on 0.6.0 RC1

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#905]
For the record, we can gather here the bugs we see in the 0.6.0 RC1 and decide if we fix them or not

**Comment by hwoarangmy** [comment]
The video renderer cannot be changed. If you set it to D3D, the game will ask to restart and exit as expected. But when the game is launched again, OpenGL renderer is still selected
(_Edit:_ Fixed in hwo's local git)

**Comment by hwoarangmy** [comment]
The settings window is too small. When D3D renderer is selected (I've fixed the video renderer that couldn't be saved), it seems there are more settings and they don't fit in the window

![settings](https://cloud.githubusercontent.com/assets/7493706/9015180/838f3b9e-37c7-11e5-8ef0-c9eb74da214b.png)

**Comment by hwoarangmy** [comment]
ERROR: Assert failed file C:\devMSVS2013\od-gh-src\source\network\ODServer.cpp line 228
seems like we send chat messages to computer player

**Comment by hwoarangmy** [comment]
AI should try to take hungry/tired creatures back to dungeon when it helps an allied player and there is no threat anymore (_Edit:_ Moved to #909)

**Comment by akien-mga** [comment]
Default start view for seats != 1 is wrong in Ruins of the Confluent (_Edit:_ Fixed in #906)

**Comment by akien-mga** [comment]
Ruins of the Confluent needs dirt bridges until we have support for actual bridges (_Edit:_ Fixed in #906)

**Comment by hwoarangmy** [comment]
Crash in Ruins of the confluent due to PortalWave:
- L781 we fill a vector with central tiles of the dungeon temple assuming the dungeon is there
- L817 we use the tiles but if the room is not on the central tile, we use a nullptr tile and segfault

This won't be hard to fix ^^

**Comment by Bertram25** [comment]
@hwoarangmy As for parameters, I'll have a look at making the area scrollable.

**Comment by hwoarangmy** [comment]
ok. In the mean time, I can make it bigger so the D3D menu fits

**Comment by Bertram25** [comment]
> ok. In the mean time, I can make it bigger so the D3D menu fits

Sure!

**Comment by akien-mga** [comment]
Inactive doors are hard to notice IMO, they should be made more transparent. (_Edit:_ Fixed in #911)

**Comment by eugeneloza** [comment]
Creature misplaced when sleeping: https://github.com/OpenDungeons/OpenDungeons/issues/916
Minimap lag: https://github.com/OpenDungeons/OpenDungeons/issues/917
Grabbed object blink: https://github.com/OpenDungeons/OpenDungeons/issues/918

**Comment by eugeneloza** [comment]
Actually 0.6.0 RC1 is really fantastic. The progress is outstanding!

**Comment by hwoarangmy** [comment]
> Actually 0.6.0 RC1 is really fantastic. The progress is outstanding!

RC2 will come soon as we have fixed the bugs we have seen in RC1 ^^

**Comment by hwoarangmy** [comment]
We have fixed or opened a dedicated issue for everything here. I close this one and we will see if we need another one for RC2 ^^
