### ISSUE TITLE
Do not show mood of enemy creatures

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#907]
Actually, mood is displayed for every creature. It should be displayed for allied creatures only

**Comment by akien-mga** [comment]
The mood overlay should also be removed when picking up a creature. Currently it stays displayed on the screen where the creature was.

**Comment by hwoarangmy** [comment]
> The mood overlay should also be removed when picking up a creature. Currently it stays displayed on the screen where the creature was.

Fixed in #913

**Comment by hwoarangmy** [comment]
Note that I've had a look at this issue but fixing it requires a change in the architecture. It will have to wait for the 0.7.0 ^^

**Comment by Bertram25** [comment]
Np at all. :)

**Comment by eugeneloza** [comment]
Maybe, also relative: Do not show enemy 'call to war' spell cast on player's Dungeon Heart.

**Comment by hwoarangmy** [comment]
> Maybe, also relative: Do not show enemy 'call to war' spell cast on player's Dungeon Heart.

This one is displayed to enemy players on purpose. However, if most people here want to not show it, we can open an issue.

@OpenDungeons/developers WDYT ?

**Comment by Danimal696** [comment]
Show it, let them feel the fear

**Comment by Bertram25** [comment]
No strong opinion. Just that I think it's giving information to enemy players.

**Comment by hwoarangmy** [comment]
> Show it, let them feel the fear

That's my line ^^

**Comment by akien-mga** [comment]
Wow, what is the chance to have a commit hash starting with 1111111? You should start playing lotto @hwoarangmy :-D
