### ISSUE TITLE
AI should take hungry/tired creatures back to dungeon when they cannot reach their dungeon heart

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#909]
This happens pretty often especially when AI helps an ally. But after, creatures cannot get home and get angry/sleepy/hungry

**Comment by hwoarangmy** [comment]
@akien-mga I don't think we should add this to 0.6.0. IMHO, we should only add bug fixes, no new functionality (even if in this case, we could consider the behaviour is buggy)

**Comment by akien-mga** [comment]
Fine by me; better release 0.6.0 asap than adding further behavioural changes that might come with their own bugs.

**Comment by hwoarangmy** [comment]
That's my line ;-)
