### ISSUE TITLE
Review the code for the main conventions

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#91]
The code should have copyright headers, and follow the main style conventions:
...

More severe problems than formatting (like putting variable in the private space will have to dealt with another issue.)

Culprits found so far:
1- Misses header copyright (check pragma once practice): (Needed for release)
- [x] CullingQuad.cpp/h
- [x] DummyArrayClass.cpp/h
- [x] PrefixTree.h/cpp
- [x] SlopeWalk.cpp/h
- [x] SoundEffectsHelper.cpp/h

2- Needs variables renaming. (can be done afterwards.)
- [x] AIManager.cpp.h
- [x] CullingQuad.cpp/h (To be removed along with the culling manager)
- [x] DummyArrayClass.cpp/h
- [x] FastPODAllocator.h (To be removed along with the culling manager)
- [x] GameEntity.cpp/h
- [x] GameMap.ccp/h
- [x] LogManager.cpp/h: sem_t logLockSemaphore;
- [x] MenuModeSkirmish.cpp/h
- [x] MenuModeMultiplayer.cpp/h
- [x] NullAI.h: static AIFactoryRegister<NullAI> reg;
- [x] ODPacket.h/cpp: sf::Packet packet;
- [x] PrefixTree.h/cpp
- [x] RenderRequest.cpp/h
- [x] SlopeWalk.cpp/h (To be removed along with the culling manager)
- [x] SoundEffectsHelper.cpp/h
- [x] StackTracePrint.cpp/h
- [x] Tile.h
- [x] Vector3i.cpp/h (Now useless, will be removed along with the culling manager.)

Used? (Has problem 1. and 2.)
- [x] SocketException.h (was removed.)

**Comment by hwoarangmy** [comment]
> SocketException.h

This one can be safely removed

**Comment by hwoarangmy** [comment]
And I would add that MapLight, Weapon and Battlefield are not game entities. Looking at their code shows that they share almost all the needed to be. Is there a reason why ? To be honest, I have not looked enough to be sure there is no tricky reason but from what I've seen, it seems possible...

**Comment by Bertram25** [comment]
> And I would add that MapLight, Weapon and Battlefield are not game entities. Looking at their code shows that they share almost all the needed to be. Is there a reason why ? 

I'm not certain but I know map lights are shown in the editor mode. Weapon also have meshes to represent them, and battleField values can be represented using visuals if some debug code is uncommented. This may explain it.

**Comment by hwoarangmy** [comment]
I'm not asking why they are close to GameEntity but why they do not extend GameEntity ?

**Comment by Bertram25** [comment]
> I'm not asking why they are close to GameEntity but why they do not extend GameEntity ?

Depends on what it permits as for simplifications and code/member factoring, I guess. I can't answer without fiddling with that, though.

**Comment by hwoarangmy** [comment]
> I can't answer without fiddling with that

That's why it's not already done ;)
But it's good to have your version as you could have been aware of something about that as it seems to me too obvious that they look like GameEntity as I don't think the coder who made them may have missed that. That's why I can see 2 reasons :
- technical : something I've not seen
- historical : they did not look so much like entities when created and they came closer to entities with time

**Comment by Bertram25** [comment]
Yeah, true. :)

**Comment by Bertram25** [comment]
I'm setting the milestone to Later as it is less urgent for release now, strictly speaking. But I plan to work on kiiling this one little by little from time to time. :)

**Comment by hwoarangmy** [comment]
ODPacket is already done and will be part of my next pull request.
