### ISSUE TITLE
Ambient lighting configuration in the settings

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#912]
On my intel IGP the game is pretty dark, and at times I find it uncomfortable. _Edit:_ It's also dark with nvidia GPU btw, now the two drivers seem to give me a similar display, which is good.

It would be nice to have the possibility to configure the gamma correction (_Edit: ambiant lighting_), if OGRE allows such things. I see mentions of "hardware gamma" on the OGRE forum and in the source code, so I guess there's something similar to what I'm looking for :)

**Comment by Bertram25** [comment]
Gamma or simply make the ambient lighting modifiable?

**Comment by akien-mga** [comment]
Ambient lighting might be enough, I'm not sure how this stuff is handled or named actually :P

**Comment by Bertram25** [comment]
> Ambient lighting might be enough, I'm not sure how this stuff is handled or named actually :P

I must say I'm saying this because changing the ambient lighting is usually better looking than gamma correction which can lead to weird colors or artefacts in the worst cases for the same desired result. Plus, AFAIK, it's really easy to set.
WDYT?

**Comment by akien-mga** [comment]
I trust you on that one, IIUC ambient lighting would be plenty enough for what I described above,

**Comment by Bertram25** [comment]
Was added in #1253

**Comment by akien-mga** [comment]
Closing as fixed.

**Comment by Bertram25** [comment]
At least, I did something for 0.7.1 XD

**Comment by Loobinex** [comment]
@Bertram25: It's sunny outside today, so I had a look, and the game is totally playable now when I adjust this setting. It wasn't before.

Only strange thing is you put this setting in the 'game' tab instead of the 'video' tab of the settings menu.

**Comment by Bertram25** [comment]
@Loobinex Thanks for the test and the feedback on it. I could indeed move the setting back into video, and if everyone is ok about it, I'll do it. WDYT guys?
