### ISSUE TITLE
Make each settings tabs potentially scrollable.

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#915]
Maybe using a scrollablePane?
http://static.cegui.org.uk/docs/0.8/classCEGUI_1_1ScrollablePane.html

**Comment by Bertram25** [comment]
Since I cannot compile the beast for now, this will have to wait for 0.7.0 of #922 to be fixed.

**Comment by akien-mga** [comment]
So, #922 was fixed. _hums innocently_

**Comment by Bertram25** [comment]
Eh eh. Not on Debian unfortunately. ;) But I'm on it.

**Comment by Bertram25** [comment]
I finally made od compilation feasible again (and on gcc-5!). I'll be on this one. :)

**Comment by Bertram25** [comment]
@akien-mga @hwoarangmy It should be much nicer to use now. :) See PR.

**Comment by Bertram25** [comment]
@akien-mga To test it, you can for instance reduce the area property of a scrollable pane in the settings windows, or reduce the window size. :)
