### ISSUE TITLE
Creature is misplaced when sleeping

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#916]
Creatures are not sleeping in their beds (sometimes looks very funny :D) 0.6.0 RC1 Win7 64
![odscreenshot_2015-08-04_072510_0](https://cloud.githubusercontent.com/assets/10726162/9054328/9a7d9986-3a88-11e5-83db-4079cfb2f85d.png)
![odscreenshot_2015-08-04_072703_1](https://cloud.githubusercontent.com/assets/10726162/9054330/9aa2dd04-3a88-11e5-94d4-1a9e4a52a521.png)
Maybe the cause is in 'displacement' or sleeping in wrong angle / relative to bed head, not median.

**Comment by hwoarangmy** [comment]
The problem is that we play the sleep animation (or die if a creature do not have sleep) when they reach their bed. To make it better, we should define the tile of the bed where they should sleep as well as the direction they should face.

**Comment by Danimal696** [comment]
having proper sleep animations will also help, but those will come with the new characters
