### ISSUE TITLE
Grabbed object blink

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#918]
Had a few graphical bugs after grabbing objects. For a moment a huge copy of the object blinks almost full screen. Noted at grabbing gold (at least once), creature (I don't remember the creature blinking, but the mood icon blinked fullscreen at least once)

**Comment by akien-mga** [comment]
The blinking is a known issue (#868), but you refer to a copy of the object taking up the full screen, and that I haven't experienced yet. Would you be able to take a screenshot or make a screencast?

**Comment by eugeneloza** [comment]
I'll try screencast, but I'm not sure I'll have time to this week. And not sure it'll works, as printscreen doesn't (maybe I'll try windowed mode).

**Comment by eugeneloza** [comment]
Couldn't reproduce the bug today. Maybe it was something wrong with my videocard (it's very hot now and it overheats frequently and starts glitching around). However, it usually glitches a few 3d mesh points, never before scale.
I'll test it better as soon as I have time (no earlier than August 11th).

**Comment by Bertram25** [comment]
I think I have a way to reproduce this. Try grabbing a worker with gold on its head.

**Comment by akien-mga** [comment]
Confirmed, I tried grabbing a worker with a gold stack on its head, and I saw a huge gold sack for a second or so. I'm leaving it assigned to 0.6, but as a non-critical issue; if the release is ready and we haven't found the bug, we can release.

**Comment by hwoarangmy** [comment]
I confirm the issue. It also happens if you grab a creature affected by a spell
