### ISSUE TITLE
Add support to start with a definite amount of gold

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#92]
This is a Seat specific parameter set level files.

As discussed in #87

**Comment by hwoarangmy** [comment]
To start somewhere, I would say that this gold amount should be set in the treasury available from the start. If no treasury, it is dropped.

**Comment by Bertram25** [comment]
> To start somewhere, I would say that this gold amount should be set in the treasury available from the start. If no treasury, it is dropped.

Good point. This is indeed the only way to truly respect the game logic. I think we will have to document this in the "Good OD map maker" future wiki topic. ;)

**Comment by Bertram25** [comment]
Fixed in https://github.com/OpenDungeons/OpenDungeons/commit/5b274cfa612d8c50f9744c7a839ede11d5869457
