### ISSUE TITLE
Linking failure when using gcc 5

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#922]
I'm opening this issue to start the investigation:

ld linking using c++ version 5.2.1-15 is failing because of OIS:

``` shell
/opendungeons/source/modes/InputManager.cpp:81: undefined reference to « OIS::InputManager::createInputObject(OIS::Type, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) »
/opendungeons/source/modes/InputManager.cpp:84: undefined reference to « OIS::InputManager::createInputObject(OIS::Type, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) »
collect2: error: ld returned 1 exit status
```

`libois-dev` is installed, along with `libois` and this was working when using gcc 4.9. When checking the linking command, `-lOIS` is there. Note that ld doesn't complain about the `destroy*` corresponding functions, which are also used in the `InputManager`

**Comment by akien-mga** [comment]
Were libOIS and OGRE compiled against gcc 5.2.1 too?

**Comment by Bertram25** [comment]
> Were libOIS and OGRE compiled against gcc 5.2.1 too?

Indeed. That's what I'll check next. (Whenever I get some time to).
Note that I'm just speaking about a debian-specific problem here for self-memory purpose. :)
I should have assigned this issue to me, btw.

**Comment by akien-mga** [comment]
Well we don't know yet if it's Debian-specific or if it would affect any system with gcc 5.2.1.
I'm still using 4.9.2 here, so I haven't tested 5.x yet.

**Comment by Bertram25** [comment]
> Well we don't know yet if it's Debian-specific or if it would affect any system with gcc 5.2.1.
> I'm still using 4.9.2 here, so I haven't tested 5.x yet.

IMHO, it is, because Debian is currently in a half-baked state between 4.9 and 5.2. But of course, it can be about any project in such a state. 
And you're right. It seems libois is still depending on gcc >=4.7. I'll use gcc 4.9 and close this issue. It is too early to try and compile od with gcc 5.2 on Debian form what I can see.

**Comment by akien-mga** [comment]
Just FYI, we've just pushed gcc 5.2.1 in Mageia Cauldron (future Mageia 6), and I have the same kind of issues to rebuild OD there :) I'm now fighting my way through the OGRE dependencies to get them all rebuilt with C++11 which is the new default implementation.

**Comment by akien-mga** [comment]
After rebuilding OGRE, CEGUI, OIS, SFML and most of their dependencies against gcc 5.2.1, OD 0.5.0 rebuilt just fine: http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20150822103922.akien.valstar.11279/opendungeons-0.5.0-3.mga6/build.0.20150822104005.log

There are some new warnings in there that might be relevant for us, but I shall try to compile 0.6.0 RC2 with gcc 5.2.1 first before we try to fix them.

**Comment by Bertram25** [comment]
Yep :) Nice things to have you as a maintainer of mageia. :D 
Btw, for the record, the command used to build od using a specific compiler:
`CC=gcc-4.9 CXX=g++-4.9 cmake .`
(But on my side, it failed at link time because of the use of gcc 5 in certain debian packages.)

Btw, I confirm I can see the same deprecated warnings from Ogre source when using gcc-5.2. IMHO, this is Ogre fault and may need fixing there.

I guess I'll build libois using gcc5 to be able to build OD again on Debian for now.

**Comment by akien-mga** [comment]
> I guess I'll build libois using gcc5 to be able to build OD again on Debian for now.

Note that from my experience, you might also have to rebuild OGRE, CEGUI and SFML and their dependencies if the Debian maintainers haven't done it yet. Else you will also get linking issues related to whatever changed in C++11 for basic stuff, e.g.: std::__cxx11::basic_string

**Comment by Bertram25** [comment]
Yep, but fortunately, only libois was left out the gcc 5 transition. Plus, I already built cegui myself.
Btw, I reported a bug for the exact same reason you on the debian bts, yesterday.
