### ISSUE TITLE
Rework Stonekeep Siege once bridges are implemented

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#929]
The north dungeon (I guess the "Stonekeep") in Stonekeep Siege is a pre-built based for seat 4 (light blue), but all the claimed tiles and traps seem to belong to seat 0. So the traps actually attack the creatures of seat 4 :)

The rooms seem to belong to seat 4 though.

**Comment by akien-mga** [comment]
Maybe it's not a bug and it was intended to be so though? IIRC the map was designed by @Danimal696.

**Comment by Danimal696** [comment]
That level is in need of heavy reworking, once we have things like bridges i want to fix it. Meanwhile, by pure chance the traps act as a limiter to the blue seat having too much power from start.

**Comment by akien-mga** [comment]
Hehe okay, let's move this to 0.7.0 then as a general "Stonekeep Siege" needs love.

**Comment by hwoarangmy** [comment]
ATM, OD games are pretty slow. I guess the lack of bridges is one of the main reasons. If nobody else does it before, I might have a go soon.

**Comment by akien-mga** [comment]
I agree that games are pretty slow currently, that was especially clear when we last played with only the two of us on Greed or Might, since the map is quite big for two. (though arguably, you were doing the dishes and I was coding some stuff while playing :P)
For 0.7 we need to find how to make the game a bit faster IMO, first with bridges, and then maybe by doing some balancing or improving default creature behaviours, etc. We can also design some more smaller arcade-ish maps for fast paced games (like the 2v2 test map).

**Comment by hwoarangmy** [comment]
> and I was coding some stuff while playing

No excuse !!! You lost and that's all the world needs to know ^^

> some more smaller arcade-ish maps for fast paced games

The problem is that such games will not allow to make researches and will not allow to have a little bit advanced buildings. Note that I also don't have any solution, yet.

**Comment by Danimal696** [comment]
Implementing the gem tile would be a pretty good addition as well besides bridges, and i suspect its even easier

**Comment by akien-mga** [comment]
IMO to make the game funnier, we need incentives to get early encounters between players while they are still building up their base. We currently have rogue portals and huge gold reserves as incentives, and we could probably use those more when creating maps. Then we'll add the gem tile to those.

There should still be more things IMO; the aim would be that after 8-10 min. player would already be fighting one another (but not in their respective dungeons) for the control of some territory or resource.

Some ideas: collectible grimoires, mana pools, pre-crafted traps or weapons, unique creatures to rally, rogue creatures to fight for XP.

**Comment by akien-mga** [comment]
Basically, we need to encourage players to explore the map and have early fights instead of simply securing gold and turtling until their creatures are from high tiers and high levels :)

**Comment by akien-mga** [comment]
Note to self: I still need to play DK more to have a better understanding of what its gameplay entails, I guess the suggestions I'm making right now sound more Wacraft-ish ;)

**Comment by Danimal696** [comment]
no, they are pretty fine. A new creature for cript and the prison and torture room are very needed to use the rogues as resources. We will get there on time

**Comment by hwoarangmy** [comment]
Note that prison will come soon (when my current PR is in ;) )

**Comment by Danimal696** [comment]
nice, ill have to ready a few iron bars and nasty rats

**Comment by akien-mga** [comment]
Bridges are implemented now, do you want to have a go at improving Stonekeep Siege @Danimal696?

**Comment by Danimal696** [comment]
Yes, i think of doing a total rework of it
