### ISSUE TITLE
Complete the CREDITS file

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#93]
The following file is incomplete and not very easy to read.

Let's complete it and improve its readability:
https://github.com/OpenDungeons/OpenDungeons/blob/development/CREDITS

It will also be necessary if we want to be certain about the file licenses we're using.

EDIT: Adding the latest TODO list to close this issue:
Font file to change for an open-licensed one:
- [x] bluehigh.ttf (Proposed replacement: http://openfontlibrary.org/en/font/medievalsharp)

To add missing licenses: (The models were done either andrewbuck or skorpio and are thus  CC BY SA 3.0 according to Danimal and oln)
- [x] Light.mesh
- [x] Field_indicator.mesh
- [x] SquareSelector.mesh
- [x] Split gui/OpenDungeons.png into separate parts per license + according changes.

Add missing license files:
- [x] CC BY 3.0
- [x] OFL license (if an OFL licensed font is chosen.)
- [x] CC0

**Comment by akien-mga** [comment]
I hadn't seen this issue, but it's partly fixed by #96 :-)

**Comment by Bertram25** [comment]
Note to self: 
- [x] Get missing model author % licenses.
- [x] Get authors & licenses of gui files, both falagard & custom made.
- [x] Add missing MIT License text in licenses
- [x] Convert Axe.tga -> png to prevent having multiple formats uselessly.

**Comment by Bertram25** [comment]
What's left:
- Files to remove:
  - [x] golem.*
  - [x] LavaGolem.mesh
  - [x] WoodWatchTower.mesh
- Font file to change for an open-licensed one:
  - [x] bluehigh.ttf
- To redo with clear licenses:
  - [x] Light.mesh
  - [x] Field_indicator.mesh
  - [x] SquareSelector.mesh

@Danimal696 : 
The cavehornet mesh is actually still using the Insect_low.003.skeleton file.
Could you re-export it using a same-named skeleton?
Also, is the Scarab the same creature as the cavehornet?? The two creatures are listed as separate in level files. This seems weird to me. O.o`
Could you also redo the given unclear models? not urgent as they are very specific to this game, thus have probably been made by someone around.

> GoldstackLv*.mesh Me!!! im going to get angry at you! :x 

Huh, please, no!!! :O

**Comment by Danimal696** [comment]
hi, have you tried looking for it into the old svn repository? many of the old blends had licenses texts incorporated

**Comment by Bertram25** [comment]
> hi, have you tried looking for it into the old svn repository? many of the old blends had licenses texts incorporated

Ok, I'll have a look.

**Comment by Danimal696** [comment]
i already did, there is no blend of those models and i couldnt find more information, redoing them seems difficult in that case since i have no idea how they were done.

They were made specifically for OD, so the safest is to say skorpio was the author, or maybe Svend, but the chances are lower of being him

**Comment by Bertram25** [comment]
> They were made specifically for OD, so the safest is to say skorpio was the author, or maybe Svend, but the chances are lower of being him

Yeah, that's what I thought, too. The square selector is the thing you're using to select tiles, the light can seen in the editor mode. It's a flat panel with a flame animation.
I don't know about the third, yet.

**Comment by Bertram25** [comment]
@Danimal696 I added pictures of the models to redo, if possible, here:
http://forum.freegamedev.net/viewtopic.php?f=35&t=5757&p=59064#p59064

**Comment by Bertram25** [comment]
Ah, btw, I'll have to split the gui/OpenDungeons.png file into two, as parts of it are MIT licensed and the other one is CC BY SA 3.0 which can't reside on the same image.
I'll thus propose to move TaharezLook bits in a OpenDungeonsOldSkin.png
and the new bits in OpenDungeonsSkin.png file and do the corresponding cegui files changes.

Are you ok with it, guys? We're almost free of licensing dirt! :D

**Comment by Bertram25** [comment]
And what do you think of this font to replace the closed source highway one?
http://openfontlibrary.org/en/font/medievalsharp

**Comment by Danimal696** [comment]
That fonts look goods and is clear to read
