### ISSUE TITLE
Settings for AI

### ISSUE THREAD

**Issue by eugeneloza** [OpenDungeons/OpenDungeons#933]
I've thought it'd be a good idea to have difficulty settings for enemy AIs. Not very needed for single maps, but that'd be good for campaign. I.e. of course the maps difficulty might be set by enemy lack of dungeon heart or portal, or access to gold, but the player should gain (a learning) experience of defeating a full-scale enemy base, however, this should still be easy to do so.

**Comment by Bertram25** [comment]
@eugeneloza This will be true once we start with the campaign. :)
As a general note:
@akien-mga @hwoarangmy Seems some of us want a campaign ;)

**Comment by hwoarangmy** [comment]
@eugeneloza AI is designed to be able to have different difficulty levels. However, we need to decide the levels we want and the differences between each.

**Comment by Danimal696** [comment]
I agree, things like:
Digging and room construction speed
Attack intensity and frequency
Creature retrieval speed (or lack of retrieval)

Name more yourself...
