### ISSUE TITLE
Prison room improvements

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#937]
see http://forum.freegamedev.net/viewtopic.php?f=45&t=4765&start=575#p65809
- Dropped creature needs an icon different to KO creatures
- Time to get up needs to be fine-tuned, the heavier and powerful the creature the longer, kobolds should only have 0.5 seconds or so time
- healing spell should work into imprisioned creatures
- we should be able to slap imprisioned creatures

**Comment by Danimal696** [comment]
Stunned by dropping creature icon
![stunned](https://cloud.githubusercontent.com/assets/8299756/9819496/a74923d0-58ae-11e5-9185-2b179b3bcc09.png)
![stunned2](https://cloud.githubusercontent.com/assets/8299756/9819498/a9341ef2-58ae-11e5-9a1c-7a4903876e81.png)

Which one do you like the most? none of them? any suggestion?

**Comment by akien-mga** [comment]
I think the first one is quite good :)

**Comment by hwoarangmy** [comment]
I also like the first one. @Danimal696 do you have a 32x32 version ? Can you post the link to the original website?

**Comment by Bertram25** [comment]
First one, too. :)

**Comment by Danimal696** [comment]
Ok, ill upload shortly, its a remix from the usual site, so only i have the source

**Comment by Bertram25** [comment]
@Danimal696 Use the media repo, Luke!

**Comment by Bertram25** [comment]
I'd add the stunned creature stun time shouldn't go over 5 seconds. It's already quite long and we'll be able to fine tune this if there are case where it is "too short", IMHO.

**Comment by hwoarangmy** [comment]
> I'd add the stunned creature stun time shouldn't go over 5 seconds

I will release a PR tonight with creature tunable stun time and some more related candies ^^
Note that I've not used @Danimal696 icon because I couldn't get anything worth it by changing its resolution. But it will be easy to change if he can do something nice on 32x32
