### ISSUE TITLE
Wooden bridges are completely coloured and stone bridges have no colour

### ISSUE THREAD

**Issue by akien-mga** [OpenDungeons/OpenDungeons#944]
As shown here:
![colour](https://cloud.githubusercontent.com/assets/4701338/9836209/f14ff4c8-5a10-11e5-961f-bd7dcb832f01.png)

Also, the stone bridge does not seem coloured, but I guess it's because there is no reference to its mask in the material definition. @Danimal696, could you have a look at it using the snapshot @hwoarangmy recently uploaded? I guess StoneBridge.material should be more similar to WoodBridge.material.

**Comment by Danimal696** [comment]
![bridges](https://cloud.githubusercontent.com/assets/8299756/9848664/7df92b1a-5ae3-11e5-9468-bd620743a6be.jpg)

**Comment by akien-mga** [comment]
Fixed by efc2b01.
