### ISSUE TITLE
Game works utterly slow

### ISSUE THREAD

**Issue by tomluchowski** [OpenDungeons/OpenDungeons#951]
Since sevaral commits ago , the development version works with 19 frames per second , which is circa about HALF THE SPEED of usual gameplay. Does anyone experienced similar issue ?

**Comment by akien-mga** [comment]
I did not experience this as far as I can tell when testing recent pull requests. Since when did it become slow? Is it working fine with 0.6.0?

**Comment by tomluchowski** [comment]
Sorry, it was due to high antialiasing settings -- issue closed .
