### ISSUE TITLE
Creature weapons

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#953]
I've been thinking a bit about creature weapons and how do they fit in the global fighting system (especially how the weapon damages interacts with creature damages).
The proposition is to add to weapons (the modifiers apply to melee or range depending on weapon range):
- Physical damage: The physical damages the weapon deals
- Magical damage: The magical damages the weapon deals
- Max range

Note that this is linked to #376 

@OpenDungeons/developers WDYT ?

**Comment by akien-mga** [comment]
This looks like a good plan to me, it allows to create some interesting weapons (e.g. magic swords which deal both physical and magical damage, etc.).

A related question though is how will all this be micro-managed? Will creatures equip themselves automatically with fitting weapons from the armoury, or will there be a kind of equipment UI where you'll be able to assign a weapon to a given creature?

Actually writing about it, I think there could be a kind of UI listing all creatures, their health, mood modifiers, what they are doing, etc., and where you could also assign them a weapon from the armoury's inventory. Upon validation, they would probably have to go to the armoury to drop their weapon and/or take a new one. For a bullfrog inspired game that would be fitting IMO, a bit like the staff management screen in Theme Hospital.

**Comment by Danimal696** [comment]
Awhile ago, cant remember where, we more or less agreed that creatures dropped on forge would "work" there and upgrade their weapon one level if the research was completed (3 research were decided masterful-magical-legendary);
Another option was forge creating weapon points that are stored into an armory, and creatures would go there and grab a weapon upgrade.

**Comment by hwoarangmy** [comment]
In any case, weapon creation do not dependent on weapon use. We can discuss that when the forge will be in (we might have better ideas when we will want to implement it). Concerning the weapon use as defined in the issue, WDYT ?

**Comment by Danimal696** [comment]
Are the modifiers really needed? or the other way around, i dont see the point of having the two at the same time, since just one acomplishes what we want.

**Comment by hwoarangmy** [comment]
> Are the modifiers really needed?

Nothing is really needed, we just have to make a choice ;)
The basic idea of the modifiers is to allow to turn off physical or magical attack when using a weapon. For example, if we assign a bow to a wizard, is it normal to deal magic damage when the same bow would not when used by an adventurer ?
Of course, we can always say that we will somehow find a way to not let wizards use bows. But, after all, why couldn't they use it if the player wants ?
Moreover, it would also allow to have some weapons like an axe that can increase physical damage proportionally to the user's power.

**Comment by akien-mga** [comment]
I think modifiers are a cool idea :)

**Comment by Danimal696** [comment]
i think we should refrain from too much micro-management, having to specify by hand what weapon wears each creature is a bit too much, and could create situations like squishy mages swordfighthing. Its a cool idea, but somewhat flawed, also take in account that the heroes will be the more benefited by weapons, since the keeper will have lots of non-weapon wearing beasts.

On the technical side, its pretty doable, once a skeleton-rig is put together with all those animations all humanoids can effectively use diferent weapons.

**Comment by hwoarangmy** [comment]
> i think we should refrain from too much micro-management, having to specify by hand what weapon wears each creature is a bit too much

I agree and that's why I propose to use modifiers. That would allow to let any creature (that can use weapons) to use any weapon. Even if it becomes less powerfull with it.

> could create situations like squishy mages swordfighthing

Well, if someone wants to equip his mages with swords, why not ? In any case, since creatures are not hardcoded, if we want to specialize creatures so that a mage cannot equip a sword, that will lead to the "too much micro management" you are talking about. In fact, that's why I propose the modifier.

**Comment by akien-mga** [comment]
I guess what @Danimal696 means is that we don't need management at all: creatures would have a "weapons path" that determines which weapon upgrade they can get, and stick to it. It would not allow to create more fine-tuned combinations by choosing which weapon a creature can get.

**Comment by Danimal696** [comment]
that way is the easiest but its not like im not open to others options, it just needs to be easy to use

**Comment by Danimal696** [comment]
Also bear in mind that having an universal rig means that all models animation will look the same, making them all kind of generic, having creatures specialized in certain weapon makes possible to give the barbarian some brutish walking step or the ranger a sneaky one.

So the choice is a generic rig or a per model one, a workaround to have both would be to define a kind of animation depending on weapon equiped, so everyone wearing axes or claymore walk brutish, and the likes for bow.

**Comment by hwoarangmy** [comment]
> I guess what @Danimal696 means is that we don't need management at all

Well, after thinking a bit more about that, it may be a good (and simple) solution. I will stick to adding physical/magical damages, then, as it is done ATM. I will change the original message so that it is clear

**Comment by Danimal696** [comment]
I would like to add poison damages as well as i said before, i think that damage trinity is a good one (thinking on traps and spell and our very own vile demon-esque creature).

**Comment by hwoarangmy** [comment]
As we said, I've implemented the most simple way weapons: I've removed range and missile mesh. Now, they just have physica and magical damages that are added to the used attack. It will be the modder responsability to make things logic (bow for ranged units, for example, and not swords)
