### ISSUE TITLE
Use appVeyor and Travis for CI

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#960]
That would allow to check that OD always compiles. I gave a try for another open source project (UFOAI if you want to know) and using appVeyor is pretty easy (I guess Travis is the same).

@OpenDungeons/developers WDYT ?

**Comment by tomluchowski** [comment]
Maybe a little intro of what those two are ?

**Comment by hwoarangmy** [comment]
They are more or less the same with appVeyor being for windows and Travis for Linux. Basically, they are tools that build the sources each time a new PR is merged automatically. It allows to ensure the master branch can always be compiled.
Moreover, I think we can also use them to build and deploy binaries. That means that each time a PR is merged, we can use them to upload to our repos new binaries automatically.

They can be easily integrated into github with an icon that shows if the sources compiles with both tools.

**Comment by hwoarangmy** [comment]
I've just seen in UFOAI that even when a PR is proposed, it checks if the sources still compiles. Note that if there are unit tests, they can also be run automatically, which makes much more usefull to have some.

**Comment by Bertram25** [comment]
As for me, I'm using Travis CI for VT and I've been using AppVeyor for a few other projects. It's a must IMHO. Running unit tests could be an fine extra point.

**Comment by hwoarangmy** [comment]
appVeyor part is handled in #992 
It builds the game with MSVS2013 and MinGW32.

**Comment by Bertram25** [comment]
I just activated Travis CI for OpenDungeons from my personal account.

I'll have a go with appveyor now.

**Comment by hwoarangmy** [comment]
ok. I'm done with travis. I will release the PR tonight. Just testing after rebase

**Comment by Bertram25** [comment]
Done for appveyor activation. :)
https://ci.appveyor.com/project/Bertram25/opendungeons

**Comment by Bertram25** [comment]
The MinGW32 appveyor build is a success :) The MSVC one is doing well so far.

**Comment by Bertram25** [comment]
Interesting warnings:

``` shell
c:\projects\opendungeons\source\modes\gameeditormodebase.cpp(237): warning C4101: 'e' : unreferenced local variable [C:\projects\opendungeons\OpenDungeons.vcxproj]
c:\projects\opendungeons\source\modes\gameeditormodebase.cpp(253): warning C4101: 'e' : unreferenced local variable [C:\projects\opendungeons\OpenDungeons.vcxproj]
c:\projects\opendungeons\source\modes\abstractapplicationmode.cpp(76): warning C4065: switch statement contains 'default' but no 'case' labels [C:\projects\opendungeons\OpenDungeons.vcxproj]
```

**Comment by hwoarangmy** [comment]
> Interesting warnings:

Yes. I guess logging the exception would be the less we can do. In any case, doing nothing (even a log) when such an exception occurs looks like a bad practice

**Comment by hwoarangmy** [comment]
I've release the PR for travis
