### ISSUE TITLE
cmake falsely identifies libsfml-dev 2.1+dfsg2-1+b2 as sfml 1.x.x

### ISSUE THREAD

**Issue by t4im** [OpenDungeons/OpenDungeons#966]
Compiling ee92d44 with libsfml-dev 2.1+dfsg2-1+b2 (current version in Debian Jessie) is falsely identified by cmake:

```
CMake Error at cmake/modules/FindSFML.cmake:356 (message):
   SFML found but version too low (requested: 2, found: 1.x.x)
```

Skipping the version test results in a good compilation with working sound.

**Comment by hwoarangmy** [comment]
Interesting. I got the same version on a Ubuntu 14 that I just installed. But I didn't check and thought the sfml version was really 1.x.
For my part, I just downloaded, compiled and installed sfml 2.3.2 and the error just went away. Note that our SFML cmake module is the one included with SFML. It might be good to have a look if there is a new one. Are you sure you don't have an older SFML installed ?

**Comment by Bertram25** [comment]
I had the same symptoms on a machine at home. I'll do more tests and return my findings here asap. Thanks for the feedback!

**Comment by t4im** [comment]
https://github.com/SFML/SFML/pull/903 seems to have addressed this upstream as well. A simple update to the more recent SFML cmake module might be already enough.

**Comment by Bertram25** [comment]
Yep, just tested the same this morning. Patch incoming. Thanks for the help.

**Comment by t4im** [comment]
Patch works, thank you. :)
