### ISSUE TITLE
0.6.0 Win 32 binary not a valid win32 application

### ISSUE THREAD

**Issue by EntropicPariah** [OpenDungeons/OpenDungeons#967]
I was told win xp isn't supported on this version when I asked about it on the IRC. 0.5.0 starts fine, if I try to run the 0.6.0 exe it tells me that it's not a valid win32 application. No load, no crash, it just flat out won't start.
The windows 32bit binary is also gone from the link on that page. Not sure if that was a different file but the one I got from the "older binaries" link doesn't run at all.
https://opendungeons.github.io/#downloads

**Comment by hwoarangmy** [comment]
If I'm not mistaken, we started to build from 0.6.0 with MSVC2013 instead of MinGW for windows releases.
Unfortunately, I have no win xp to test. But I guess that it may work if compiled with MinGW. Do you know how to compile from sources ?

**Comment by Bertram25** [comment]
@hwoarangmy When compiling with MSVC 2013, are you still able to select e.g. v120_xp as a platform compilation target?
https://msdn.microsoft.com/en-us//library/jj851139.aspx

**Comment by hwoarangmy** [comment]
No, I had not tried to change the platform compilation target. I will build a new dev snapshot to try.

**Comment by Bertram25** [comment]
Setting to 0.7 but just to point out from when the XP platform was considered.

**Comment by hwoarangmy** [comment]
I've tried to build after setting the toolset to v120_xp but it doesn't launch on win xp. I will try to build it with MinGW and see if it works on win xp (I guess it does).

**Comment by hwoarangmy** [comment]
@EntropicPariah Could you please try this release:
http://download.tuxfamily.org/opendungeons/WIP/OpenDungeons-git20151011-Win32-MinGW64.zip

and tell us if it works with win xp ?

**Comment by EntropicPariah** [comment]
Sorry it took so long, I just now tried the version from the link you posted and it worked fine. Thanks for the update!

**Comment by hwoarangmy** [comment]
> Sorry it took so long, I just now tried the version from the link you posted and it worked fine. Thanks for the update!

Cool. Then, I will try to build MinGW versions if I can.
