### ISSUE TITLE
Bug "stuck creatures on wall corners" and some suggestions

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#971]
While playing the last snapshot i came across a bug, creatures get stuck in corners, it happens inside and outside of battle

![stuck](https://cloud.githubusercontent.com/assets/8299756/10270276/e6816102-6aec-11e5-967b-6cc4cf7f690c.png)

Also some suggestions:
-Spells only work on owned land, it sucks and renders them useless except for defense
-Spell cooldown counter numbers went back to jumpy; didnt it get some nice counter before?
-Offset for Spiders/chicken on Cript and Farm, can it also be applied like on normal creatures?

**Comment by Bertram25** [comment]
> -Spells only work on owned land, it sucks and renders them useless except for defense

This is configurable AFAIR (and if it's not, it's not hard to change), but I think only certain of them should be. Could you tell us which ones should or shouldn't be castable everywhere in your opinion?

> -Spell cooldown counter numbers went back to jumpy; didnt it get some nice counter before?

I'll test.

> -Offset for Spiders/chicken on Cript and Farm, can it also be applied like on normal creatures?

Good idea.

**Comment by Bertram25** [comment]
@Danimal696 All those secondary ideas should become issues IMHO. Could you create them?

**Comment by Danimal696** [comment]
This topic spawned this new issues:
#973 
#974 
#975 
#976

**Comment by hwoarangmy** [comment]
I've never seen this bug but I was expecting it ^^
IIUC, the creatures are in the wall and cannot walk, right ?
When that happens, do they continue to have an animation (and does the animation changes ?)
If you can reproduce it, could you try a middle clic on the creature and see if the displayed position changes ?

I just want to check if that happens on the client side only (what I suspect) or if it is also on server side. The workaround is pretty easy but it would be better to really understand what is going on.

**Comment by Danimal696** [comment]
I was able to reproduce; yes, you got it rigth, they change animations, positions value and even win XP (by attacking) all when stuck into a corner.

**Comment by hwoarangmy** [comment]
ok. Then, it's the bug I was expecting. It comes from a de-synchronization between server and client. Basically, time goes quicker on server side so, sometimes, when it sends a move command, the entity is not exactly on the same tile and it can cross a not expected tile.
If it happens on server side, that would be a problem. But on client side, that's not a big deal.
