### ISSUE TITLE
Spell cooldown counter numbers went back to jumpy

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#974]
Maybe just my impression, but i think we had a softer counter?

**Comment by hwoarangmy** [comment]
Note that if you are not happy with cooldowns, you can change them
https://github.com/OpenDungeons/OpenDungeons/blob/development/config/spells.cfg

If you find better values, do not hesitate to create a PR ^^

**Comment by akien-mga** [comment]
By "jumpy" you mean that they display e.g.: 5.0 / 4.6 / 4.2 / 3.8 / etc., instead of 5.0 / 4.9 / 4.8 / 4.7 / etc.?

**Comment by Danimal696** [comment]
Yes

**Comment by hwoarangmy** [comment]
ok. I had not undestood what you meant. I was planning on doing it so let's go ^^
