### ISSUE TITLE
Sneak peek at new unit: Dark elf

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#981]
Im becoming a master of remixing; i think crossbow will really suit her

![untitled2](https://cloud.githubusercontent.com/assets/8299756/10292491/cf3a810e-6baf-11e5-8c60-b5facee5ebec.jpg)
![untitled](https://cloud.githubusercontent.com/assets/8299756/10292492/cf7767a4-6baf-11e5-9d34-2e01e44b3123.jpg)

**Comment by hwoarangmy** [comment]
It looks really nice. Where did you get it from ?

**Comment by Danimal696** [comment]
its a rework of a model from blendswap:
http://www.blendswap.com/blends/view/66691

**Comment by hwoarangmy** [comment]
Cool. Is it near from ready ?

**Comment by Danimal696** [comment]
retexturing and lowering polis is done, now i need to rig with motion capture skeleton and fine tune it all, could take a week or two depending on my free time

**Comment by hwoarangmy** [comment]
ok. Cool. It would also be nice to have a few more rooms (and I guess it is easier and less time consuming) to allow to associate creatures with rooms. IMHO, we have enough creatures for a 1.0. And if we need to, we can always play with the textures and size to create a creature from another one. For example, this dark elf can easily become a hero creature by changing its color.

**Comment by akien-mga** [comment]
What are the rooms on our todo list for 1.0?

**Comment by hwoarangmy** [comment]
> What are the rooms on our todo list for 1.0?

Good question. I don't think we have a list. But it might be a a good thing to do if we haven't. I guess @Danimal696 may have something in mind

**Comment by Danimal696** [comment]
Maybe guard post, arena and temple?

**Comment by Bertram25** [comment]
The model is cool! :)

About the rooms, we have in fact several lists AFAIR:
Models in need of update:
- prison, crypt, temple (for heroes and keepers), portal (for heroes),
  Rooms that needs to be created:
- Forge, Guard Post + upgrade to bunker, different traps such as the poison one, the scarecrow one, ..., the sacrifice room, the arena, the torture room, a casino equivalent.

Let's discuss what rooms we really want for core gameplay and once we have them, maybe officially start about the campaign.

**Comment by akien-mga** [comment]
Sound we move the rooms discussion to its own issue?

**Comment by hwoarangmy** [comment]
> Sound we move the rooms discussion to its own issue?

Good idea. Let's not hack this issue

**Comment by Bertram25** [comment]
Done: #982 :)

**Comment by Danimal696** [comment]
almost ready, wait for it next week ;)

**Comment by Danimal696** [comment]
just one step away from game release ;)

http://opengameart.org/content/elf-game-ready-and-animated
http://opengameart.org/content/dark-elf-game-ready-and-animated

**Comment by hwoarangmy** [comment]
Looks cool ^^
Is it a replacement for other creatures ? Or a special creature ?

**Comment by Danimal696** [comment]
i dont know... they wont replace anything for sure, but, i would like them to be "skill user-archers", a kind of super archers, suppose the common archer creature would only use its ranged physical attack and a few support skills on itself (maybe a granade skill at high level?(exploson skill)); and these ladies could cast fireballs, poison bolts or the like to dish out different kinds of damage plus their physical arrows.
Since you have a better idea of the new blancing ill let the stats to you this time.

**Comment by hwoarangmy** [comment]
> Since you have a better idea of the new blancing ill let the stats to you this time.

No pb ^^

> they wont replace anything for sure

We already have 3 creatures per tier for both factions. However, some creatures are currently not final (AFAIK, knight and big knight share the same mesh, cavehornet is used for both factions, tentacle looks more like tier 1 than tier 2...). IMHO, we should decide, for each new creature we want to introduce:
- If it replaces another one (in this case, I think it is the most appropriate since this model is for both factions)
- If it is a special creature like lich or skeleton that do not need to replace anything.

**Comment by hwoarangmy** [comment]
the dark elf is in #1016 
@OpenDungeons/developers WDYT about replacing a creature (if so, which) or adding it as a new one ?

**Comment by Bertram25** [comment]
IMHO, whatever it is replacing or not, it is some kind of tier 2 Wizard equivalent for keepers. :>

**Comment by hwoarangmy** [comment]
> IMHO, whatever it is replacing or not, it is some kind of tier 2 Wizard equivalent for keepers

The thing is that IIUC, @Danimal696 also have a hero faction equivalent for the dark elf.
IMHO, currently, we have
- cavehornet used twice
- knight, bigknight using same mesh
- Some not as nice models as the others: wyvern, gnome, pitdemon, dragon, lich (acceptable but some more triangles won't hurt)

My proposition is to use the elf as a tier2 creature replacing adventurer/wyvern. adventurer would become tier3 and kight/wyvern would be removed.
WDYT ?

**Comment by hwoarangmy** [comment]
The Elf + DarkElf are in the main repository. What is left it their weapons + integrate them ingame. If nobody goes against, I will do what I said in my proposition when they can be integrated.

**Comment by Danimal696** [comment]
oh,  the weapons... sure ill get them ready
