### ISSUE TITLE
Rooms global issue

### ISSUE THREAD

**Issue by Bertram25** [OpenDungeons/OpenDungeons#982]
Taken from: #981

About the rooms, we have in fact several lists AFAIR:
Models in need of update:

```
prison, crypt, temple (for heroes and keepers), portal (for heroes), Rooms that needs to be created:
Forge, Guard Post + upgrade to bunker, different traps such as the poison one, the scarecrow one, ..., the sacrifice room, the arena, the torture room, a casino equivalent.
```

Let's discuss what rooms we really want for core gameplay and once we have them, maybe officially start about the campaign.

**Comment by hwoarangmy** [comment]
IMHO, we should check for rooms which have a model more or less ready in one of @Danimal696 favorite blender sites and use them in priority.

Apart from that, the best would be a torture room ^^

**Comment by Danimal696** [comment]
Sadly, almost everything on the net is garbage, and im not even that exigent, but finding decent models is difficult and if they need to be open source it gets even worse.

**Comment by Bertram25** [comment]
I think this issue is more a forum thing and has been discussed on other issues more specifically. Closing.

**Comment by hwoarangmy** [comment]
> I think this issue is more a forum thing and has been discussed on other issues more specifically. Closing.

I was also thinking that it would be nice to group (in the forum or in an issue) the prioritary things we all agree on. For example, for rooms, the blacksmith, stuff like that. Ideally, we should let in the first message the 2-3 ones we want the most. Same for spells/traps.

**Comment by akien-mga** [comment]
I guess we should have extensive discussions on the forum, but try to keep GitHub issues as a summary of what was decided on each topic. We are not all moderators on the forum so we can't edit the OP as we can do on GH, so that's an advantage of GH issues for such "roadmap" topics.

**Comment by Bertram25** [comment]
> I was also thinking that it would be nice to group (in the forum or in an issue) the prioritary things we all agree on. For example, for rooms, the blacksmith, stuff like that. Ideally, we should let in the first message the 2-3 ones we want the most. Same for spells/traps.

I'm all for creating some 'old' sub-sections on the forums for the development, and place everything that has more than 1 year in it, for a start. WDYT? Who is admin on the OD forums, btw?
