### ISSUE TITLE
Creature balancing

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#985]
Just like skills, elemental damages have been implemented. But ATM, no creature or spell use it.

Following #877 we said that we would like to have something like 3 creatures per tier specialized in one of the type and with a triangle. For example, if the 3 creatures are A, B an C, at same level, A > B, B > C and C > A.

**Comment by Danimal696** [comment]
elemental as in fire, water, earth and air? or as in the previously used in OD physical, magic, acid?

**Comment by hwoarangmy** [comment]
elemental is the "generic" name for what we called "acid"

**Comment by hwoarangmy** [comment]
As for the triangle, I would propose as a first step to try for 1 creature of each tier:
- Good damage on its natural attack
- Medium defense against its natural attack
- Good defense vs another attack.
- Bad defense against the last attack

For example, if we consider 3 tier 1 creatures:
- Spider
- Tentacle
- Slime

Spider would have Attack: 5 phy, 0 mag, 0 ele. Def: 2 phy, 4 mag, 0 ele.
Tentacle would have Attack: 0 phy, 5 mag, 0 ele. Def: 0 phy, 2 mag, 4 ele.
Slime would have Attack: 0 phy, 0 mag, 5 ele. Def: 4 phy, 0 mag, 2 ele.

I guess that with this stats, Spider > Tentacle, Tentacle > Slime and Slime > Spider.

@OpenDungeons/developers WDYT ?

**Comment by Danimal696** [comment]
I would switch stats for spider to tentacle since spiders can poison a bit as well, otherwise its good

**Comment by eugeneloza** [comment]
Looks good!

**Comment by hwoarangmy** [comment]
> I would switch stats for spider to tentacle since spiders

No problem, it was only an example. I'm not even sure that these creatures are the tier 1 keeper (since there are more like roach, cavehornet or the other tentacle). BTW, since we have many creatures on keeper side and not enough for heroes, it could be a good idea to switch some. Any idea ?

Since we are talking about creature balancing, at which level do we except a creature to become better than its same tier better unit ? In my example, at which level does the slime become better than a level 1 tentacle ?

**Comment by Danimal696** [comment]
thats pretty tricky, i tried to use a golden rule when i balanced last time, and that was, even the weakest creature should be able to hurt a bit the strongest one when both are at LV1.
Apart from that we have other values to play with now, like HP and skills to make one creature better than other

**Comment by hwoarangmy** [comment]
> even the weakest creature should be able to hurt a bit the strongest one when both are at LV1

Seems good.

For my part, I would say that level 7 to 10 creatures should begin to win vs their same tier better unit.

**Comment by eugeneloza** [comment]
```
 it could be a good idea to switch some. Any idea ?
```

Maybe not 'switch' but 'add' for heroes? Like
MLEE: peasants > adventurers > soldiers > knights > crusaders > paladins > heroes
MAGIC: commoner > initiate > scholar > mage > warlock > archwizard
ELEMENTAL: scout > robber > rogue > murder > assasin
RANGED: slinger > archer > crossbowman > sniper > ballista

```
 As for the triangle
```

Maybe, there's a point in adding a 'balanced' creature? Which has equals on all. It'll be weaker than the same rank creatures, but will be more universal.

```
 creatures should begin to win vs their same tier better unit.
```

Maybe, there's a point to try this logic in the same tier: (rank 2 unit) equals 2 (rank 1 units of the same level) (50% kill depending on the 'first blow'). (rank 2 unit lvl.1) equals (rank 1 unit lvl.7)

**Comment by hwoarangmy** [comment]
> Maybe not 'switch' but 'add' for heroes? Like

My idea was to not put too much burden on our artists shoulders and to go fast (as we have many creatures on keeper side but not enough on hero's). But if you want to add some new creatures, you are welcome. However, I think we need rooms more than creatures ATM.

> Maybe, there's a point in adding a 'balanced' creature? Which has equal on all. It'll be weaker than the same rank creatures, but will be more universal.

Yes. Maybe for "special" creatures that do not spawn through the portal like skeleton / lich. I think we should try to avoid what was, IMHO, the biggest problem of DK: balancing. Basically, the idea was always to train one of the best creatures (for me, the vampire) and unleash it in an enemy dungeon where it would kill everybody. That's why we should try to add some more strategy and the triangle is IMHO, one of the best ways to achieve that.

> Maybe, there's a point to try this logic in the same tier: (rank 2 unit) equals 2 (rank 1 units of the same level) (50% kill depending on the 'first blow'). (rank 2 unit lvl.1) equals (rank 1 unit lvl.7)

Yes, we should try to balance creatures of different tiers as well.

**Comment by hwoarangmy** [comment]
I've had a look at the creature list. As we can see in the wiki, we have 6 keeper tier 2 creatures (wyvern, lizardman, orc, goblin, tentacle, kreatur) + roach
At the same time, we only have 2 tier 3 creatures for hero (bigknight and dwarf runelord).

To have at least 3 creatures per tier for both sides, I would propose to change some creatures teams. Moreover, we could have 3 tier 4 creatures (allowing more interesting strategies than rushing blindly to tier 4 ASAP)

That will leave:
Keeper:
- Tier 1: cavehornet, slime, spider
- Tier 2: wyvern, goblin, roach
- Tier 3: kreatur, lizardman, orc
- Tier 4: pitdemon, dragon, troll

Hero:
- Tier 1: gnome, dwarf, cavehornet
- Tier 2: dwarf chief, tentacle, adventurer
- Tier 3: wizard, knight, dwarf runelord
- Tier 4: defender, bigknight, scarab

For balancing purposes, I would propose to try to:
- have 1 specialized in attack type creature per tier (for our triangle).
- At same level, even tier 1 creatures should be able to hurt tier 4 creatures
- At level 7, a creature should be more or less equivalent to its same tier stronger unit (according to the triangle)
- A tier N creature should be equivalent to its tier N + 1 level 1 creature at level 10

Then, we will have to give some skills (but it will be for after ^^)

@OpenDungeons/developers WDYT ?

**Comment by Danimal696** [comment]
not bad, in absence of enought creatures for everyone, its a good plan.

**Comment by Bertram25** [comment]
Looks perfect on paper :D 
I guess this will require some stat spreadsheet or something?

**Comment by hwoarangmy** [comment]
well, I will try with some basic stats, each creature being perfect opposite to an hero. Then, we will see what we want ^^
