### ISSUE TITLE
Implement a "defense" spell

### ISSUE THREAD

**Issue by hwoarangmy** [OpenDungeons/OpenDungeons#986]
So that we have a little bit more choices when giving skills to creatures

**Comment by Danimal696** [comment]
ill hijack this, i think it would be better to just create an issue with posible skills to be added

**Comment by hwoarangmy** [comment]
This issue is for creating the defense spell (I will do it soon). But if you want to create one issue that gathers all spells we want to discuss, please feel free. When we will have a list, we can open an issue for each.
Also do not hesitate to post links to icons if you have something in mind

**Comment by Danimal696** [comment]
i like these two:
http://game-icons.net/lorc/originals/barbute.html
http://game-icons.net/lorc/originals/visored-helm.html

they are pretty close to the original DK, http://dungeonkeeper.wikia.com/wiki/Armour_%28Creature_Spell%29

**Comment by hwoarangmy** [comment]
ok. I will use http://game-icons.net/lorc/originals/barbute.html
