### ISSUE TITLE
CMake error when trying to open /usr/local/cegui-0.8.3/cegui/include/Version.h for reading

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#987]
Feel free to close this issue once you have a look at forum:
http://forum.freegamedev.net/viewtopic.php?f=54&t=6589&p=66193#p66193

**Comment by akien-mga** [comment]
I believe the error is due to a bogus CEGUI installation by the user, so I'll close as invalid for now. I may reopen depending on the answers given to my questions on the forum.
