### ISSUE TITLE
Digging selection sound only played on left side

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#989]
If you use headphones like me you can tell it very easily, only one of them plays the sound no matter where you click

**Comment by akien-mga** [comment]
IIRC it should be a "spatial" sound, i.e. it should play on the left if you click on the left of your focus/camera view, and it should play on the right if clicking on the right.

**Comment by Danimal696** [comment]
it doenst, only plays on left no matter where you click

**Comment by hwoarangmy** [comment]
I think @Bertram25 might know something about it. I will also try

**Comment by Bertram25** [comment]
From soundEffectManager.cpp line 62, sounds not spacial have no attenuation at all, so they should be at the same level whatever the position used.
Yet, their default position is 0;0 when played without coords arguments, like in:
`void playSpatialSound(SpatialSoundType soundType, const std::string& family)`

Thus, explaining IMHO the bug. A test that could be done is to set the sound position to the one of the listener just before playing it when the sound is not spatial.
