### ISSUE TITLE
Wave portals and how they work?

### ISSUE THREAD

**Issue by Danimal696** [OpenDungeons/OpenDungeons#990]
i want to build several on the same level but cant put to work even one of them. Could you explain all values?

```
[Room]
10  PortalWave1 5   9
28  28
28  29
28  30
29  28
29  29
29  30
30  28
30  29
30  30
9   250 1   0   -
[Waves]
[Wave]
SpawnTurnMin    0
SpawnTurnMax    1000
[Creatures]
DwarfWorker 7
Adventurer  4
Adventurer  3
Wizard  4
Knight  3
[/Creatures]
[/Wave]
[/Waves]
[/Room]
```

**Comment by akien-mga** [comment]
We should indeed better document this kind of stuff in the wiki.

For now, here is the description:

```
[Room]
10 PortalWave1 5 9   # RoomType RoomName SeatID NbOfTiles
28 28    # TileX TileY
28 29
28 30
29 28
29 29
29 30
30 28
30 29
30 30
9 250 1 0 -    # ClaimedValue TurnsBetweenWaves Strategy RangeInTiles TeamIDs
[Waves]
[Wave]    # Define a specific wave, several types of waves can be defined
SpawnTurnMin 0     # When should this wave start
SpawnTurnMax 1000    # When should this wave stop
[Creatures]     # Creatures spawned at each wave
DwarfWorker 7    # CreatureType Level
Adventurer 4
Adventurer 3
Wizard 4
Knight 3
[/Creatures]
[/Wave]
[/Waves]
[/Room]
```

Regarding the "Strategy", it can be:
- 0: attack closest dungeon in range
- 1: attack a random player in range at each wave
- 2: attack only the teams listed in TeamIDs

For "TeamIDs", values can be "-" (any team) or one of more team IDs (separated by a slash when there are more than one, e.g. "2" or "1/3").

**Comment by Danimal696** [comment]
Thanks, ill try again

**Comment by hwoarangmy** [comment]
Couldn't explain better than @akien-mga did ^^

**Comment by akien-mga** [comment]
Reopening and assigning to myself as this should figure in the wiki IMO.

**Comment by akien-mga** [comment]
Finally done: https://github.com/OpenDungeons/OpenDungeons/wiki/Making-wave-portals :)

@hwoarangmy @Bertram25 While documenting this, I wondered if we should not move the `TurnsBetweenWaves` global parameter within each `[Wave]` definition? This way modders could define a portal that e.g. spawns weak waves quite often during the first 1000 turns, and then switches to another mode with low frequency but powerful waves.

**Comment by Bertram25** [comment]
> @hwoarangmy @Bertram25 While documenting this, I wondered if we should not move the TurnsBetweenWaves global parameter within each [Wave] definition? This way modders could define a portal that e.g. spawns weak waves quite often during the first 1000 turns, and then switches to another mode with low frequency but powerful waves.

Hey :) Here I must say I don't know what's best. Is it simple enough to adapt the logic for this? (Probably, it is) or is it worth waiting for some scripting support?
In any case, I would open a new issue.

**Comment by hwoarangmy** [comment]
@akien-mga Sorry I had not seen the question. It should not be hard to move the parameter if you want to give a try ^^
